### ISSUE TITLE
[Dúvida] no [DICT] - Subfluxo de portabilidade para o PSP reivindicador com acesso direto ao DICT:

### ISSUE THREAD

**Issue by farito** [bacen/pix-perguntas-e-respostas#10]
**Descreva sua dúvida ou problema**
Em subfluxo de portabilidade para o PSP reivindicador com acesso direto ao DICT paso 6, disse o siguente:
_PSP reivindicador solicita atualização da chave no DICT._
neste caso temos que fazer um PUT para chave e logo concluir portabilidad?, o com fazer um concluir portabilidade, DICT internamente atualiza sua base de chaves y o PSP faz o memo?

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
Respondido em https://github.com/bacen/pix-perguntas-e-respostas/issues/6
