### ISSUE TITLE
[Dúvida] no [SPI] - Erro ao validar a assinatura na validação do XML utilizando o XSD

### ISSUE THREAD

**Issue by douglasrs89** [bacen/pix-perguntas-e-respostas#100]
**Descreva sua dúvida ou problema**
O XML que geramos, hoje é aceito pelo SPI. Porém, ao tentar validar o XML com o XSD, está retornando erro na parte da assinatura.

`Cvc-complex-type.2.4.c: The Matching Wildcard Is Strict, But No Declaration Can Be Found For Element 'Signature'., Line '1', Column '414'.`

Estamos utilizando uma biblioteca de validação, porém, ao tentar validar em alguns sites como o https://www.freeformatter.com/xml-validator-xsd.html e o https://www.liquid-technologies.com/online-xsd-validator, retorna o mesmo problema.

Quando adiciono no XSD o _import_ abaixo, eu consigo validar o XML.

`<xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd"/>`

A dúvida é, o XSD que vocês fornecem, precisa ter esse _import_? Ou estou fazendo algo errado na validação?

**Sistema ou Área**
SPI

**Comment by jbrasileiro** [comment]
Podemos usar como exemplo o [XSD da NF-e](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=CoNA9VIgZ3E=).
Nele é disponibilizado um XSD do leiaute (ex: leiauteNFe_v4.00.xsd) que inclui XSD adicionais:

```

<xs:schema attributeFormDefault="unqualified" 
 elementFormDefault="qualified" 
 targetNamespace="http://www.portalfiscal.inf.br/nfe" 
 xmlns="http://www.portalfiscal.inf.br/nfe" 
 xmlns:ds="http://www.w3.org/2000/09/xmldsig#" 
 xmlns:editix="http://www.portalfiscal.inf.br/nfe" 
 xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema_v1.01.xsd"/>
	<xs:include schemaLocation="tiposBasico_v4.00.xsd"/>
... 
```

Não está faltando ser disponibilizado um XSD completo para usarmos para validação ?

**Comment by cristianokbc** [comment]
Normalmente as bibliotecas de validação de schema admitem a inclusão de uma lista de XSDs para validação.

[Vejam um exemplo em Java](https://stackoverflow.com/questions/7009285/xml-validation-using-multiple-xsds).

Dessa forma é possível guardar todos os XSDs onde for mais conveniente sem a necessidade de estabelecer previamente a localização e sem a necessidade de imports.
