### ISSUE TITLE
[Problema] no [Dict] - Erros 500 e timeouts na Consulta de Vínculos

### ISSUE THREAD

**Issue by thulio** [bacen/pix-perguntas-e-respostas#101]
**Descreva sua dúvida ou problema**
Desde ontem à tarde estamos recebendo timeouts e/ou erros 500 no endpoint de Consulta de Vínnculo no DICT

**Sistema ou Área**
DICT

**Identificador do Problema**
CorrelationId: 97CF3CDF4442458A97198F1F4EA168DB

**Mensagens Enviadas / Recebidas**
XML recebido:

```xml
<problem xmlns="urn:ietf:rfc:7807">
    <type>https://dict.pi.rsfn.net.br/api/v1/error/InternalServerError</type>
    <title>Internal Server Error</title>
    <status>500</status>
    <detail>Internal server error. Please contact support for details.</detail>
    <correlationId>97CF3CDF4442458A97198F1F4EA168DB</correlationId>
</problem>
```

**URL de conexão**
htts://dict-h.pi.rsfn.net.br/api/v1-rc5/

**Dados adicionais**
Os erros 500 e timeouts estão acontecendo tanto no RC4 quanto no RC5

**Comment by luizlaydner** [comment]
Para essa requisição específica, você mandou o parâmetro [PI-EndToEndId](https://github.com/bacen/pix-dict-api/blob/b7710e5856014e5a4ac93eff110b7102cae6c411/openapi/openapi.yaml#L497) num formato incorreto.
Como habilitamos ontem o mecanismo de _rate-limiting_, tal erro passou a acontecer para suas requisições.
Temos do nosso lado uma correção a fazer, retornando mensagem de erro de que o parâmetro é inválido.

**Comment by HenriqueSimoes82** [comment]
@thulio 
Problema corrigido. Obrigado pelo reporte detalhado.
