### ISSUE TITLE
[Dúvida] no [DICT] - Cache-Control em consulta da chave

### ISSUE THREAD

**Issue by farito** [bacen/pix-perguntas-e-respostas#103]
**Descreva sua dúvida ou problema**
Cual vai ser o valor retornado em header Cache-Control e que unidade de medida vai ter?

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
Na consulta a vínculos, está sendo retornado `Cache-Control: private, max-age=60` , isto é: cache não compartilhado com validade de 60 segundos. Essas diretivas de cache poderão mudar futuramente.
[Veja aqui](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Headers/Cache-Control) mais informações sobre caching HTTP.
