### ISSUE TITLE
[Dúvida] no [SPI] - Assinatura Inválida 

### ISSUE THREAD

**Issue by simonevirgilio** [bacen/pix-perguntas-e-respostas#104]
As mensagens PACS008 que recebemos hoje a tarde estão apresentando erro de assinatura inválida e não conseguimos validar a assinatura.
As demais mensagens estamos validando a assinatura com sucesso.
Quando detectamos este erro temos que responder com ADMI.002?

**Sistema ou Área**
SPI

**Identificador do Problema**
 ResourceId (SPI/ICOM). 
ISPB 71027866
Data 23/07/20
Hora:17:32

**Mensagens Enviadas / Recebidas**
XML das mensagem recebida

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Envelope xmlns="https://www.bcb.gov.br/pi/pacs.008/1.4">
   <AppHdr>
      <Fr>
         <FIId>
            <FinInstnId>
               <Othr>
                  <Id>00038166</Id>
               </Othr>
            </FinInstnId>
         </FIId>
      </Fr>
      <To>
         <FIId>
            <FinInstnId>
               <Othr>
                  <Id>71027866</Id>
               </Othr>
            </FinInstnId>
         </FIId>
      </To>
      <BizMsgIdr>M000381660KCZ95GWZ10JQLUWVHMWSFA</BizMsgIdr>
      <MsgDefIdr>pacs.008.spi.1.4</MsgDefIdr>
      <CreDt>2020-07-23T20:32:37.859Z</CreDt>
      
   </AppHdr>
   <Document>
      <FIToFICstmrCdtTrf>
         <GrpHdr>

**Comment by LeoGonCha** [comment]
> As mensagens PACS008 que recebemos hoje a tarde estão apresentando erro de assinatura inválida e não conseguimos validar a assinatura.
> As demais mensagens estamos validando a assinatura com sucesso.
> Quando detectamos este erro temos que responder com ADMI.002?
> 
> **Sistema ou Área**
> SPI
> 
> **Identificador do Problema**
> ResourceId (SPI/ICOM).
> ISPB 71027866
> Data 23/07/20
> Hora:17:32
> 
> **Mensagens Enviadas / Recebidas**
> XML das mensagem recebida
> 
> 00038166 71027866 M000381660KCZ95GWZ10JQLUWVHMWSFA pacs.008.spi.1.4 2020-07-23T20:32:37.859Z

@simonevirgilio caso o problema ainda exista pedimos que verifique se a validação de assinatura esta sendo realizada com o certificado correto disponível em http://www.bcb.rsfn.net.br/seguranca/seguranca.shtm. Caso ainda persista nos envie mais informações sobre o erro.

**Comment by simonevirgilio** [comment]
Bom dia! 
A falha na autenticação continua e só é observada em pacs.008, quando a origem da transação é o BB. Por exemplo a mensagem M000381660KDAGUEZT10V7XUIE775PRS,
na qual a assinatura não pode ser verificada, e o BS2 não pode responder a essa mensagem. 
Após alguns instantes  recebemos uma pacs.002 
(M000381660KDAH7AIO10V7XUIEEF98XR) informando"Pagamento expirado por timeout". A assinatura da 
Pacs.002 foi conferida sem problemas. Também,
estamos testando o pix com muitas instituições, 
nenhuma delas apresenta tal comportamento. As pacs.008 provenientes de outras instituições estão tendo suas assinaturas conferidas sem maiores problemas.

Dados técnicos.
(Utilizado Library do Framework .net Core)
1. A conferência do serial number do certificado. ok
2. Signature format. ok
3. Signature info. ok
4. Check Digested References
   1. Primeira referência "keyInfo". ok
   2. Segunda referência "AppHdr". ok   
   3. Terceira referencia "Document". Falha 
       (Hash diferente de ds:DigestValue)


<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Envelope xmlns="https://www.bcb.gov.br/pi/pacs.008/1.4">
   <AppHdr>
      <Fr>
         <FIId>
            <FinInstnId>
               <Othr>
                  <Id>00038166</Id>
               </Othr>
            </FinInstnId>
         </FIId>
      </Fr>
      <To>
         <FIId>
            <FinInstnId>
               <Othr>
                  <Id>71027866</Id>
               </Othr>
            </FinInstnId>
         </FIId>
      </To>
      <BizMsgIdr>M000381660KDAGUEZT10V7XUIE775PRS</BizMsgIdr>
      <MsgDefIdr>pacs.008.spi.1.4</MsgDefIdr>
      <CreDt>2020-07-31T16:53:27.017Z</CreDt>
      <Sgntr>
      </Sgntr>
   </AppHdr>
   <Document>
      <FIToFICstmrCdtTrf>
         <GrpHdr>
            <MsgId>M000381660KDAGUEZT10V7XUIE775PRS</MsgId>
            <CreDtTm>2020-07-31T16:53:27.017Z</CreDtTm>
            <NbOfTxs>1</NbOfTxs>
            <SttlmInf>
               <SttlmMtd>CLRG</SttlmMtd>
            </SttlmInf>
            <PmtTpInf>
               <InstrPrty>HIGH</InstrPrty>
            </PmtTpInf>
         </GrpHdr>
         <CdtTrfTxInf>
            <PmtId>
               <EndToEndId>E00000000202007311634CDQb1iYzgiB</EndToEndId>
            </PmtId>
            <IntrBkSttlmAmt Ccy="BRL">30.02
            </IntrBkSttlmAmt>
            <AccptncDtTm>2020-07-31T16:34:34.315Z</AccptncDtTm>
            <ChrgBr>SLEV</ChrgBr>
            <Dbtr>
               <Nm>CLEBER CARVALHO MARQUES</Nm>
               <Id>
                  <PrvtId>
                     <Othr>
                        <Id>00098262017315</Id>
                     </Othr>
                  </PrvtId>
               </Id>
            </Dbtr>
            <DbtrAcct>
               <Id>
                  <Othr>
                     <Id>00000000000000753920</Id>
                     <Issr>0551</Issr>
                  </Othr>
               </Id>
               <Tp>
                  <Cd>CACC</Cd>
               </Tp>
            </DbtrAcct>
            <DbtrAgt>
               <FinInstnId>
                  <ClrSysMmbId>
                     <MmbId>00000000</MmbId>
                  </ClrSysMmbId>
               </FinInstnId>
            </DbtrAgt>
            <CdtrAgt>
               <FinInstnId>
                  <ClrSysMmbId>
                     <MmbId>71027866</MmbId>
                  </ClrSysMmbId>
               </FinInstnId>
            </CdtrAgt>
            <Cdtr>
               <Id>
                  <PrvtId>
                     <Othr>
                        <Id>01434145697</Id>
                     </Othr>
                  </PrvtId>
               </Id>
            </Cdtr>
            <CdtrAcct>
               <Id>
                  <Othr>
                     <Id>260002</Id>
                     <Issr>0001</Issr>
                  </Othr>
               </Id>
               <Tp>
                  <Cd>CACC</Cd>
               </Tp>
            </CdtrAcct>
            <RmtInf>
               <Ustrd></Ustrd>
            </RmtInf>
         </CdtTrfTxInf>
      </FIToFICstmrCdtTrf>
   </Document>
</Envelope>

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Envelope xmlns="https://www.bcb.gov.br/pi/pacs.002/1.3">
   <AppHdr>
      <Fr>
         <FIId>
            <FinInstnId>
               <Othr>
                  <Id>00038166</Id>
               </Othr>
            </FinInstnId>
         </FIId>
      </Fr>
      <To>
         <FIId>
            <FinInstnId>
               <Othr>
                  <Id>71027866</Id>
               </Othr>
            </FinInstnId>
         </FIId>
      </To>
      <BizMsgIdr>M000381660KDAH7AIO10V7XUIEEF98XR</BizMsgIdr>
      <MsgDefIdr>pacs.002.spi.1.3</MsgDefIdr>
      <CreDt>2020-07-31T17:03:27.744Z</CreDt>
      <Sgntr>
      </Sgntr>
   </AppHdr>
   <Document>
      <FIToFIPmtStsRpt>
         <GrpHdr>
            <MsgId>M000381660KDAH7AIO10V7XUIEEF98XR</MsgId>
            <CreDtTm>2020-07-31T17:03:27.744Z</CreDtTm>
         </GrpHdr>
         <TxInfAndSts>
            <OrgnlInstrId>E00000000202007311634CDQb1iYzgiB</OrgnlInstrId>
            <OrgnlEndToEndId>E00000000202007311634CDQb1iYzgiB</OrgnlEndToEndId>
            <TxSts>RJCT</TxSts>
            <StsRsnInf>
               <Rsn>
                  <Cd>AB03</Cd>
               </Rsn>
               <AddtlInf>Pagamento expirado por timeout</AddtlInf>
            </StsRsnInf>
         </TxInfAndSts>
      </FIToFIPmtStsRpt>
   </Document>
</Envelope>

**Comment by simonevirgilio** [comment]
Problema corrigido pelo BB
