### ISSUE TITLE
Problema no DICT - Listar Eventos de CIDs

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#106]
**Descreva sua dúvida ou problema**
Estamos criando fluxo para analise de inconsistências dos CIDs, e detectamos que a chamada de Listar Eventos de CIDs não esta gravando as interações de ADDED ou REMOVED quando a operação da Key ocorre pelas chamadas de Portabilidade/Reivindicação, gostaria de saber se é um Bug ou se realmente o log das operações no Dict serão somente realizadas as operações básicas do Dict (Criar/Atualizar/Remover).
Fico no aguardo. 
Obrigado!

**Sistema ou Área**
DICT

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc5/cids/events

**Comment by judahreis** [comment]
@evertongodoi, mudanças em entries decorrentes de operações de claims devem aparecer nos eventos. Vamos verificar...

**Comment by judahreis** [comment]
@evertongodoi, pode nos passar algumas informações: (i) chave reivindicada; (ii) ISPB consultou o evento.
