### ISSUE TITLE
Problema no DICT - Listar Reivindicações (Erro Limit Vazio)

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#107]
**Descreva sua dúvida ou problema**
Estamos realizando testes na chamada Dict Listar Reivindicações, quando enviamos o Limit vazio a API retorna erro status: 500, detail: Internal server error. Please contact support for details. Porem se enviarmos a informação no input Limit o retorno ocorre com sucesso, mas na documentação v1-rc5 o campo limit não é obrigatório, único campo obrigatório é Participant.
Fico no aguardo.
Obrigado.

**Sistema ou Área**
DICT

**Identificador do Problema**
correlationId: 5EFB83CB7AD84EED89C7C30E2DB7A3F2

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc5/claims?Participant=02318507&IsDonor=&IsClaimer=&Status=&Type=&ModifiedAfter=&ModifiedBefore=&Limit=

**Comment by HenriqueSimoes82** [comment]
@evertongodoi 
Problema corrigido. Pode testar novamente. Obrigado pelo reporte detalhado.
