### ISSUE TITLE
DICT RC5 - Polling - periodicidade 

### ISSUE THREAD

**Issue by JoaoPereiraBB** [bacen/pix-perguntas-e-respostas#108]
DICT RC5 explica que existe um pooling periodico e que periodiocidade dependera de cada servico. 

Onde nos podemos encontrar mais detalhes da periodicidade na documentação e pagina onde podemos achar um exemplo ? 

Obrigado
Joao

**Comment by judahreis** [comment]
@JoaoPereiraBB, será publicado, em breve, na página do fórum de pagamentos instantâneos um novo anexo: Manual de Tempos. Fique de olho...
