### ISSUE TITLE
[Dúvida] no [DICT] - Status contas cliente no registro chave DICT

### ISSUE THREAD

**Issue by simonevirgilio** [bacen/pix-perguntas-e-respostas#109]
**Descreva sua dúvida ou problema**

No registro de chave no DICT, o Bacen determina que essa funcionalidade deve estar liberada para todos os status de conta ( status interno na IF - Ex: Conta inativa ou Conta bloqueada por fraude)
ou fica a critério da instituição?

**Sistema**
DICT

**Comment by carloschioquetta** [comment]
Essa questão fica a critério da instituição.

**Comment by carloschioquetta** [comment]
Essa questão fica a critério da instituição.
