### ISSUE TITLE
[Problema] no [INFRA] - Get e Post na icom

### ISSUE THREAD

**Issue by rsabin** [bacen/pix-perguntas-e-respostas#11]
**Descreva sua dúvida ou problema**
Bom dia, hoje por volta das 11h30 os comandos _get_ e _post_ na interface _icom_ do Bacen estão retornando exceção: `HTTP/1.1 header parser received no bytes`

**Sistema ou Área**
SPI, INFRA

**Identificador do Problema**
ISPB: 92702067
Data-hora: 23/06/2020 11:30 

**URL de conexão**
`https://icom-h.pi.rsfn.net.br/api/v1/out/92702067/stream/start`

**Dados adicionais**
Esta exceção já ocorreu outras vezes e sempre começa e se resolve "sozinho", o que me leva a crer que é alguma situação no lado do Bacen.
Não sei se mais alguém está utilizando Java e tem recebido essa mesma exceção. 
Qual a sugestão para tratamento de erros neste caso onde aparentemente o problema é do outro lado? 
Neste caso, por exemplo, o programa não tem como saber se foi corrigido sem ficar tentando e recebendo erros até que se resolva. Poderá acabar gerando muitos alertas para as áreas de monitoração.

**Comment by judahreis** [comment]
Ronaldo,

Para problemas de instabilidade no ambiente que não estejam diretamente ligado a funcionalidades, pedimos que registre através dos canais de atendimento do 61 3414-2156 ou suporte.ti@bcb.gov.br. 

Obrigado pelo report.
