### ISSUE TITLE
[Dúvida] no [SPI] - Sincronizacion de horario

### ISSUE THREAD

**Issue by farito** [bacen/pix-perguntas-e-respostas#110]
**Descreva sua dúvida ou problema**
E necesario a sincronização de data e hora nas instances que vamos a usar para SPI (dict e transactional) com BACEN?

**Sistema ou Área**
SPI

**Comment by rafael-omello** [comment]
Conforme consta no Manual de Redes do SFN, seção 6.2:
"Está disponível um servidor de tempo no BCB que poderá ser utilizado pelos participantes da
RSFN para o sincronismo de horário dos servidores MQ e demais servidores da RSFN através do
protocolo NTP."
O manual pode ser acessado através do link:
https://www.bcb.gov.br/content/estabilidadefinanceira/cedsfn/Manual_de_Redes_do_SFN_Ver_9.pdf
