### ISSUE TITLE
APIs de Recebimento x APIs proprietárias

### ISSUE THREAD

**Issue by dncosta** [bacen/pix-perguntas-e-respostas#111]
O Bacen divulgou recentemente o schema das APIs de recebimento que deverão ser oferecidas pelas instituições no modelo de participantes diretos.
Essas instituições, poderão, além de oferecer as APIs de recebimento nos padrões determinados pelo Bacen, permitir a geração desses QRCode através de outras APIs próprias, que não seguem esse padrão?
É possível oferecer a criação desse QRCode atrávés de duas APIs distintas ou a única API capaz de gerar um QRCode do PIX deverá ser a API de recebimento?

**Comment by gabrielmcv** [comment]
Aproveitando o tópico: será possível criar solicitações de recebimento e receber o status da transação através da API?

**Comment by guilhermedecampo** [comment]
@gabrielmcv a mensageria SPI vai ser responsável por esses avisos e precisa ser criada uma abstração pelo participante direto pelo que estou vendo. 

https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/AnexoII%E2%80%93CatalogodeMensagensdoSPI-versao1.9.pdf

**Comment by ninrod** [comment]
@gabrielmcv , sim. Inclusive [estão especificados](https://github.com/bacen/pix-api-recebimentos/releases/download/1.2.0/spec.html) os endpoints para realizar essas operações.

@dncosta , estou colhendo uma resposta oficial e vou deixar em aberto essa issue até que eu possa repassar pra vocês aqui.

**Comment by ninrod** [comment]
@dncosta colhi a informação a respeito de suas perguntas: 

> Essas instituições, poderão, além de oferecer as APIs de recebimento nos padrões determinados pelo Bacen, permitir a geração desses QRCode através de outras APIs próprias, que não seguem esse padrão?

R: não é permitido. 

> É possível oferecer a criação desse QRCode atrávés de duas APIs distintas ou a única API capaz de gerar um QRCode do PIX deverá ser a API de recebimento?

R: não é permitido.
