### ISSUE TITLE
Dúvida no PIX - A especificação 1.10 foi cancelada?

### ISSUE THREAD

**Issue by alexandredsimoes** [bacen/pix-perguntas-e-respostas#112]
**Descreva sua dúvida ou problema**
Na sexta-feira (24/07) a especificação 1.10 das mensagens estava no site e hoje segunda (27/07) não encontra-se mais listado.
Foi abortado? 

**Sistema ou Área**
SPI - Mensagens

**Dados adicionais**
https://www.bcb.gov.br/estabilidadefinanceira/forumpagamentosinstantaneos

**Comment by rafael-omello** [comment]
Dúvidas de negócio devem ser enviadas para spi@bcb.gov.br
