### ISSUE TITLE
[Problema] no [DICT] - Resposta HasMoreElements do Listar Reivindicações sempre é false

### ISSUE THREAD

**Issue by lucasjmatias** [bacen/pix-perguntas-e-respostas#113]
**HasMoreElements  deveria retornar true caso haja mais itens em que o limite não tenha trazido**. Mas após uns testes, temos 15 reivindicações na listagem, filtrei por 5, já é estranho, pois retorna 6 itens( apesar do limite ter sido 5), e o HasMoreElements retorna false, quando deveria retornar true.

**Sistema ou Área**
DICT

**Identificador do Problema**
**HasMoreElements** sempre retorna false.
`<HasMoreItems>false</HasMoreItems>`

A primeira URL de conexão retorna 6 itens(apesar do limit ser 5) e HasMoreItems false, utilizando 01/01/2020 como modifiedAfter como ponto inicial de iteração;
A segunda URL, usando o ModifiedAfter como o LastModified adicionado de 1 milissegundo do último claim da primeira url como parâmetro **retorna mais 6 itens**. **Logo existia mais itens a iterar**. 

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc5/claims/?Participant=00000208&IsDonor=false&IsClaimer=true&ModifiedAfter=2020-01-01T00:00:00.000Z&Limit=5
e
 https://dict-h.pi.rsfn.net.br/api/v1-rc5/claims/?Participant=00000208&IsDonor=false&IsClaimer=true&ModifiedAfter=2020-07-22T13:41:02.728Z&Limit=5

**Comment by HenriqueSimoes82** [comment]
@lucasjmatias 
Problema corrigido. Pode testar novamente. Obrigado pelo reporte detalhado.
