### ISSUE TITLE
[Problema] no [DICT] - Download de arquivo de CIDs

### ISSUE THREAD

**Issue by thulio** [bacen/pix-perguntas-e-respostas#115]
**Descreva sua dúvida ou problema**
Estou tentando fazer o download de um arquivo de CIDs e mas sempre recebo 404 como resposta

**Sistema ou Área**
DICT

**Identificador do Problema**
ISPB: 16501555

**Mensagens Enviadas / Recebidas**
XML Recebido no endpoint /cids/files/{Id}:
```xml
<GetCidSetFileResponse>
    <CidSetFile>
        <Id>1199</Id>
        <Status>AVAILABLE</Status>
        <Participant>16501555</Participant>
        <KeyType>CPF</KeyType>
        <RequestTime>2020-07-27T18:50:52.145Z</RequestTime>
        <CreationTime>2020-07-27T18:50:52.230Z</CreationTime>
        <Url>https://arq-h.pi.rsfn.net.br/api/v1/download/16501555/cidsetfile/16501555_CPF_1199_2020-07-27T18:50:52.176Z.txt</Url>
        <Bytes>65975</Bytes>
        <Sha256>db07558b8d66298a5da494e20e0d15a459acc7eda57ed004d13c3666144f0eed</Sha256>
    </CidSetFile>
</GetCidSetFileResponse>
```

Quado tento fazer o download da URL https://arq-h.pi.rsfn.net.br/api/v1/download/16501555/cidsetfile/16501555_CPF_1199_2020-07-27T18:50:52.176Z.txt, recebo:

```xml
<?xml version="1.0" encoding="UTF-8"?><problem xmlns="urn:ietf:rfc:7807"><type>https://icom.pi.rsfn.net.br/api/v1/error/notFound</type><title>Não encontrado</title></problem>
```

**URL de conexão**
https://arq-h.pi.rsfn.net.br/api/v1/download/16501555/cidsetfile/16501555_CPF_1199_2020-07-27T18:50:52.176Z.txt

**Comment by HenriqueSimoes82** [comment]
@thulio 
Problema corrigido. Favor solicitar novamente o arquivo de CIDs e fazer o download do arquivo. Obrigado pelo reporte.
