### ISSUE TITLE
[Problema] no [DICT] - Reivindicação de Posse na fase de encerramento

### ISSUE THREAD

**Issue by simonevirgilio** [bacen/pix-perguntas-e-respostas#116]
**Descreva sua dúvida ou problema*
Recebemos a reivindicação de posse do ID A99586B4-6E78-4CAB-B5BB-5590E3EABEB5 E aguardamos o período de 7 dias e estamos na fase de encerramento (status WAITING_RESOLUTION) e ela ainda está sendo consultada por outros PSP, como se a chave estivesse conosco. 

O manual des especificações diz que no período de encerramento, que vai do sétimo ao décimo quarto dia, a chave não estará vinculada a nenhuma conta, logo a consulta não deveria retornar nenhum SPB.

Nos temos que tomar alguma ação ou o esperado seria a chave está vinculado ao nosso ispb.

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
@simonevirgilio, é obrigação do PSP confirmar a doação no 7o. dia com a <Reason>DEFAULT_OPERATION</Reason>. Faz parte do ANS do participante, descrito no Manunal de Tempos na [página do Pix](https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos). O DICT nunca inicia uma ação... é sempre o participante quem faz o estímulo, para garantir sincronismo das bases DICT-PSP.

**Comment by simonevirgilio** [comment]
Mas a partir do momento que confirmo a posse (enviando DEFAULT_OPERATION), o PSP reivindicador atualiza a base dele e já consegue concluir a revindicação no estado CONFIRMED, não?
Não vejo como chegará no fim do 14o dia para enviar de novo um CONFIRMED (razao USER_REQUEST).
Na no fluxo de reivindicação (https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/X_ManualOperacionaldoDICT-versao1-1.pdf, pag 29), o fluxo 5 diz:
"Caso não haja mudança na solicitação de reivindicação de posse até o 14º dia, o PSP reivindicador deve ele mesmo alterar o status da solicitação para “Confirmado”". Isso entra em conflito com doador, não?

**Comment by judahreis** [comment]
@simonevirgilio, a documentação será corrigida. Tanto o Reivindicador quando o DICT precisam de uma ação do Doador. A claim ficará parada enquanto não houver essa ação. O BACEN vai monitorar os doadores que não tomarem ação até o 7o. dia.

**Comment by vtlino** [comment]
Mas em relação a confirmação após o 7o dia, quando o doador enviar a confirmação (com a razão DEFAULT_OPERATION), o reivindicador poderá concluir, sem passar o período de encerramento. Ou entendi errado?

**Comment by fbjhon** [comment]
Boa noite, também necessito dessa definição.

**Comment by judahreis** [comment]
@vtlino, se o doador confirmar por falta de confirmação do usuário (DEFAULT_OPERATION), o reivindicador deve esperar os 14 dias (7 dias após a confirmação), e realizar uma nova validação ativa antes de completar a reivindicação. 

A janela de 14 dias só é revogada caso a confirmação do doador aconteça a pedido do usuário (USER_REQUESTED).

**Comment by carloschioquetta** [comment]
Caso o usuário que registrou originalmente a chave não se manifeste até o 7º dia, o PSP doador deverá confirmar a reivindicação. Contudo, o PSP reivindicador não vai conseguir confirmar a posse, pois o usuário ainda terá 7 dias adicionais para cancelar a reivindicação. Após o 14º dia, o PSP reivindicador vai conseguir confirmar a posse com o seu cliente, caso o usuário original não cancele o processo. Para isso, de fato, ele não precisa confirmar o processo no DICT. O processo já estará confirmado após o 7º dia pelo PSP doador. Vamos corrigir esse passo em uma nova versão do Manual Operacional do DICT, que será publicado em breve.

**Comment by vtlino** [comment]
@judahreis, abri uma reivindicação, id = 357588f6-708b-4bdf-a164-06e5415b8b77. No no papel de doador, com DEFAULT_OPERATION, confirmei a doação (de fato não esperei os 7 dias, mas lembro desse comportamento ter ocorrido outrora (se não pudesse com essa razão, deveria ser bloqueado pelo DICT, não?)), e a data CompletionPeriodEnd, que antes estava para duas semanas, passou para o dia de hoje. Não respeitando a documentação da API do DICT:

"_Para reivindicação de posse, caso razão seja DEFAULT_OPERATION, o prazo de resolução (ResolutionPeriodEnd) deve ter passado. Se a razão informada for USER_REQUESTED, o prazo de encerramento (CompletionPeriodEnd) será adiantado para permitir o encerramento imediato pelo reivindicador._"

Uma que aceitou o DEFAULT_OPERATION sem ter passado o prazo, e outra que adiantou o CompletionPeriodEnd sem ser por USER_REQUESTED.

e @carloschioquetta, o reivindicador deverá confiar cegamente na data de CompletionPeriodEnd?

**Comment by judahreis** [comment]
@vtlino, atualizei o comentário do @carloschioquetta. O que temos é:   "Após o 14º dia, o PSP reivindicador vai conseguir confirmar a posse com o seu cliente, caso o usuário original não cancele o processo. Depois disso, ele (o psp reivindicador) pode encerrar o processo no DICT. ".

Ou seja, o reivindicador não precisa confiar cegamente na data, pois ele mesmo deve tomar a ação de encerrar a reivindicação (claim / completeClaim)

Quanto ao que vc reportou da claim 357588f6-708b-4bdf-a164-06e5415b8b77, o comportamento não é o esperado. Vou verificar e retorno.

**Comment by vtlino** [comment]
@judahreis , obrigado. 
Se a chamada de confirmar com DEFAULT_OPERATION não atualizar o ResolutionPeriodEnd, resolverá o problema. Porque se atualizar (igual ao USER_REQUESTED), o reivindicador vai se confundir com a confirmação de usuário, podendo concluir, uma vez que já passou do CompletionPeriodEnd
