### ISSUE TITLE
Problema no DICT - Erro 400 piPayerId (Consultar Vínculo)

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#117]
**Descreva sua dúvida ou problema**
Na data de hoje a chamada Consultar Vínculo, começou a retornar o erro: 400, payerId, reason: must match "[0-9a-f]{64}", segue dados encaminhados.

piPayerId: 1BDA016399003E7BF6219427F46B9A15FDD303BAA8FBEC1D116E20E6E610B257
piPayerId-size: 64

**Sistema ou Área**
DICT

**Identificador do Problema**
Correlation-Id: F26CDC18036543248DF7382A0F7CD2E1

**Mensagens Enviadas / Recebidas**
<type>https://dict.pi.rsfn.net.br/api/v1/error/EntryInvalid</type><title>Bad Request</title><status>400</status><detail>Invalid parameters</detail><correlationId>F26CDC18036543248DF7382A0F7CD2E1</correlationId><violations><violation><reason>must match "[0-9a-f]{64}"</reason><value>1BDA016399003E7BF6219427F46B9A15FDD303BAA8FBEC1D116E20E6E610B257</value><property>payerId</property>

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc5/entries/everton6@gmail.com

**Comment by judahreis** [comment]
@evertongodoi, o padrão atual é hexadecimal minúsculo [0-9a-f]{64}. Para evitar problemas futuros, vamos modificar o padrão para hexadecimal case-insensitive [0-9a-fA-F]{64}. Até lá, só fazer um lowercase no seu PayerId que vai funcionar.
