### ISSUE TITLE
[Problema] no DICT - Erro ao consultar arquivo de CIDS

### ISSUE THREAD

**Issue by jorgebaruchi** [bacen/pix-perguntas-e-respostas#118]
**Descreva sua dúvida ou problema**
Estamos solicitando a criação do arquivo de CIDs, mas não conseguimos recebê-lo.

**Sistema ou Área**
DICT

**Identificador do Problema**
Sempre que consultamos sua disponibilidade no endpoint GET /cids/files/{Id}, obtemos o response como ERROR e nenhuma informação adicional, conforme abaixo:

**Mensagens Enviadas / Recebidas**
```xml
<GetCidSetFileResponse>
  <Signature></Signature> 
  <CidSetFile>
    <Id>{ID}</Id>
    <Status>ERROR</Status>
    <Participant>{ISPB}</Participant>
    <KeyType>CPF</KeyType>
    <RequestTime>2020-07-28T18:45:50.906Z</RequestTime>
    <Bytes>0</Bytes>
  </CidSetFile>
</GetCidSetFileResponse>
```

**URL de conexão**
API RC4

**Comment by judahreis** [comment]
Resolvido

**Comment by jorgebaruchi** [comment]
Bom doa @judahreis 

Conseguimos baixar o arquivo, mas os CIDs estão vindo em UPPERCASE. Segundo a documentação, iremos considerar o CIDs em LOWERCASE. Poderia confirmar nosso entendimento ?

Texto retirado da API RC5:

cid é a representação hexadecimal, em lowercase, do resultado da função hmacSha256.
