### ISSUE TITLE
[Problema] no [DICT] - Download de arquivo de CIDs

### ISSUE THREAD

**Issue by thulio** [bacen/pix-perguntas-e-respostas#119]
**Descreva sua dúvida ou problema**
Depois do problema descrito na issue https://github.com/bacen/pix-perguntas-e-respostas/issues/115 , todos
os arquivos que eu requisito ficam com status **ERROR**

**Sistema ou Área**
DICT

**Identificador do Problema**
 ISPB: 16501555

**Mensagens Enviadas / Recebidas**
 XML Recebido no endpoint **/cids/files/{Id}**:

```xml
<GetCidSetFileResponse>
    <CidSetFile>
        <Id>1214</Id>
        <Status>ERROR</Status>
        <Participant>16501555</Participant>
        <KeyType>CPF</KeyType>
        <RequestTime>2020-07-28T19:17:12.799Z</RequestTime>
        <Bytes>0</Bytes>
    </CidSetFile>
</GetCidSetFileResponse>
```

**URL de conexão**
Tanto **/api/v1-rc4/cid/files/{Id}** quanto **/api/v1-rc5/cid/files/{Id}**

**Comment by judahreis** [comment]
@thulio, identificamos um bug na geração do arquivo, introduzido por uma manutenção. A correção deve acontecer em breve.

**Comment by thulio** [comment]
Fiz mais testes agora e funcionou normalmente. Obrigado @judahreis !

**Comment by judahreis** [comment]
Atualizamos o ambiente, e está resolvido. Obrigado pelo relato @thulio .
