### ISSUE TITLE
[Dúvida] no [DICT] - Reconciliação - Verificar Sincronismo

### ISSUE THREAD

**Issue by farito** [bacen/pix-perguntas-e-respostas#12]
**Descreva sua dúvida ou problema**
Na API DICT versao1.0.0rc3, para a operacao de "Verificar Sincronismo", agora no tem o valor SyncVerifierLastModified para pasar ao endpoint. No cenario onde o PSP sempre tem disponible o registro das chaves e reivindicacoes (7x24), pode pasar que sempre o Verificar Sincronismo da diferente de nosso valor calculado pelo VSync? ou nos obliga primeiro a calcular VSync do DICT y depois con el valor SyncVerifierLastModified obtido calcular nosso VSync ate da data de campo SyncVerifierLastModified?

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
Farito,

Verificar Sincronismo sempre retornará o estado atual da base, no momento que foi solicitado. A ideia seria suspender por alguns instantes sua operação (fora da janela obrigatória) a fim de checar o sincronismo, e retornar em seguida. Estamos falando da ordem de alguns segundos. Lembrando que, idealmente, o participante acompanha cada alteração de chave pelo endpoint GET /cids/events, mantendo-se síncrono evento a evento.
