### ISSUE TITLE
[Dúvida] no [DICT] - Finalização do processo de reivindicação de chave

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#120]
**Descreva sua dúvida ou problema**

Olá! Gostaria de tirar duas dúvidas sobre o fluxo de reivindicação posse de chave.

1 - Após os 14 dias, se o PSP doador não der nenhum retorno (nem confirmando ou cancelando o pedido), o DICT automaticamente mudará a situação do pedido para confirmado?

2 -  Seguindo o cenário acima, enquanto o PSP reivindicador, não der um complete, a chave pode ser cadastrada por outro usuário?

Obrigada

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
@monise,

1 - Não. O DICT é sempre passivo, ou seja, a mudança sempre tem que partir do PSP. Isso garante que não haverá inconsistência no ecossistema nas transferências entre PSPs e booktransfers. O PSP estará sujeito a sanções caso não realize a mudança no prazo regulamentar. O Banco Central fará o monitoramento constante de PSPs em atraso.

2 - Não. A chave fica reservada para o usuário que iniciou a reivindicação. Essa liberação só é feita ao término do processo (seja por conclusão, seja por cancelamento).
