### ISSUE TITLE
Consulta de Vínculo por CID

### ISSUE THREAD

**Issue by morellibmv** [bacen/pix-perguntas-e-respostas#121]
Pessoal, qual o tempo médio previsto para retorno de uma consulta de vínculo por CID? Nos nossos testes, até o momento, estão levando mais de 120 segundos.

**Comment by luizlaydner** [comment]
Vamos investigar. Tempo esperado seria pra menos de 1s.

**Comment by morellibmv** [comment]
Boa tarde, Luiz. Sim é o endpoint getEntryByCid. 

Alguns dos CIDs que consultei:
50B47F8380E652FC112FA6F71C22E5EAFFC447AFD7E40EF453D3C0B6DB74AD5A
5C93A6938E5D1F756134389607A58CDE3D3E6F11A790181509DE7B6507F84243
5E9E46E5796E479B78337D34FC36A6EACCB9090E915E299AB6AE5FE97C551213
5C93A6938E5D1F756134389607A58CDE3D3E6F11A790181509DE7B6507F84243 
5E9E46E5796E479B78337D34FC36A6EACCB9090E915E299AB6AE5FE97C551213 
5C93A6938E5D1F756134389607A58CDE3D3E6F11A790181509DE7B6507F84243 
5E9E46E5796E479B78337D34FC36A6EACCB9090E915E299AB6AE5FE97C551213 
5C93A6938E5D1F756134389607A58CDE3D3E6F11A790181509DE7B6507F84243 
5E9E46E5796E479B78337D34FC36A6EACCB9090E915E299AB6AE5FE97C551213 
5C93A6938E5D1F756134389607A58CDE3D3E6F11A790181509DE7B6507F84243

**Comment by luizlaydner** [comment]
@morellibmv Não conseguimos identificar a situação relatada. Se você voltar a observá-la, agradeceria se pudesse coletar mais informações sobre a requisição.
O tempo de 120s que você relatou me parece incoerente com configurações que temos no serviço. 
Requisições mais longas que poucos segundos (5s) são abortadas automaticamente. Geraria um erro 500.
