### ISSUE TITLE
[Dúvida] no [SPI] - Tamanho e Domínio Campo tipoModificacao na REDA.022

### ISSUE THREAD

**Issue by adrianbp** [bacen/pix-perguntas-e-respostas#122]
**Descreva sua dúvida ou problema**
Boa Tarde!

Na versão 1.11 do catálogo de mensagens detalhadas do SPI, temos o xls da REDA.022 onde há 3 campos tipoModificacao de 4 caracteres, porém ao olhar a coluna "Regra para o Brasil" temos as seguintes orientações:
   1-)  Deve ser preenchido com a opção: CONTATOPSP.
   2-) Deve ser preenchido com a opção: DIRETORPSP.
   3-) Deve ser preenchido com a opção estabelecida na tabela de domínio - Mod. 

Os 2 primeiros itens ultrapassam 4 caracteres e o último item ao olhar à tabela de domínios temos o código "INSE". Com 4 caracteres. Qual será o tamanho e o domínio destes campos da mensagem REDA.022 ?

**Sistema ou Área**
SPI

**Comment by rodalvarenga** [comment]
Para dúvidas sobre o negócio, favor encaminhar um email para spi@bcb.gov.br
