### ISSUE TITLE
Dúvida/Erro no DICT - Idempotência não funcionando no fluxo de COMPLETE de uma reivindicação

### ISSUE THREAD

**Issue by bernardeslucas** [bacen/pix-perguntas-e-respostas#123]
**Descreva sua dúvida ou problema**
Ao testar os cenários de idempotência nas Reivindicações, o COMPLETE, retorna como operação inválida, e a mensagem abaixo:
```
 Current claim status('COMPLETED') does not allow an operation to be made
```

Já o CONFIRM e CANCEL, funcionam como descrito conforme a documentação, onde retorna a Reivindicação como se fosse a primeira requisição, seguindo a idempotência.

**Sistema ou Área**
DICT

**Identificador do Problema**
Correlation-Id: 2C6F040943D14387AB3E2DFC629AF918

**Mensagens Enviadas / Recebidas**

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?><CompleteClaimRequest 
    xmlns:ns2="http://www.w3.org/2000/09/xmldsig#"><ClaimId>0cb5a40e-552e-4ad6-bd23-48caf5c70c59</ClaimId>
    <RequestId>8d151ea6-2033-4746-9f49-7d7b39225092</RequestId><Participant>59588111</Participant></CompleteClaimRequest>'
# 
    <ds:X509SerialNumber>66906355272994040667436154809</ds:X509SerialNumber></ds:X509IssuerSerial></ds:X509Data> 
    </ds:KeyInfo></ds:Signature><type>https://dict.pi.rsfn.net.br/api/v1/error/ClaimOperationInvalid</type><title>Bad  
    Request</title><status>400</status><detail>Current claim status('COMPLETED') does not allow an operation to be 
    made</detail>

**Comment by luizlaydner** [comment]
Para que a operação de completeClaim seja considerada "a mesma" deve usar o mesmo `RequestId` e `ClaimId`.
Seria possível que você tenha feita a 2a requisição com um `RequestId` diferente ?

**Comment by bernardeslucas** [comment]
Olá, Luiz!
Realmente, estávamos testando com `RequestId` variável nos testes, como não estava totalmente explicíto essa questão na documentação e os outros fluxos estavam funcionando a idempotência, acabou passando, obrigado pelo esclarecimento.
