### ISSUE TITLE
DICT - Reconciliação - Listar Eventos de CIDs

### ISSUE THREAD

**Issue by leandrofrancisquete** [bacen/pix-perguntas-e-respostas#124]
Boa tarde! 

Conforme especificado, enviamos uma requisição sem o Content-type.

https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/AnexoV-APIdoDiretoriodeIdentificadoresdeContasTransacionais-versao1.0.0-RC5.html#operation/listCidSetEvents

![image](https://user-images.githubusercontent.com/50705181/89049487-bad61900-d327-11ea-9d06-bc24a8b3059b.png)

Porém recebemos o retorno:

    <type>https://dict.pi.rsfn.net.br/api/v1/error/BadRequest</type>
    <title>Unsupported Media Type</title>
    <status>415</status>
    <detail>Acceptable Media Types: application/xml</detail>

Existe uma nova versão a caminho, a documentação está defasada, estamos fazendo algo errado?

Obrigado!!

**Comment by luizlaydner** [comment]
@leandrofrancisquete Estamos incorretamente exigindo para essa requisição GET o cabeçalho `Content-Type: application/xml` . No entanto, tal cabeçalho só faz sentido quando há corpo na requisição (PUT/POST).

Para que você consiga fazer o teste, inclua o header `Content-Type: application/xml`. 

Vamos corrigir esse problema.

**Comment by judahreis** [comment]
@leandrofrancisquete, sua sugestão foi atendida na RC6, já disponível no ambiente de homologação.
