### ISSUE TITLE
Dúvida/erro - Atualização REDA.022 (catálogo de mensagens versão 1.10) - campo tipoModificacao

### ISSUE THREAD

**Issue by fescariot** [bacen/pix-perguntas-e-respostas#125]
Boa tarde,
Foi atualizada a mensagem REDA.022 no catálogo de mensagens da versão 1.10 e talvez alguns campos alterados precisem de atualização pois o arquivo “reda.022_msg.xml” diverge do arquivo “REDA022.xlsx”.
1.	Os campos “ScopeIndication <ScpIndctn>” (tipoModificacao) devem ser preenchidos com as informações “DIRETORPSP” e “CONTATOPSP” ou devem ser preenchidos com o valor “INSE” (tal como era na versão 1.9)?
2.	Se os campos forem preenchidos com as informações “DIRETORPSP” e “CONTATOPSP”, então o tamanho dos campos deve ser alterado para um valor maior que 4 caracteres alfanuméricos.

**Comment by rodalvarenga** [comment]
Para dúvidas referentes ao negócio, favor enviar um email para spi@bcb.gov.br
