### ISSUE TITLE
[Dúvida] no [SPI] - Timeout Estimulo Reenvio Mensagens PACS008 e PACS002

### ISSUE THREAD

**Issue by adrianbp** [bacen/pix-perguntas-e-respostas#126]
Boa Tarde!

No documento de especificações técnicas e de negõcio, na sessão 3.4.6.1 e 3.4.6.2 fala sobre o processo de reenvio de mensagem PACS008 ou PACS002 quando o PSP Direto não teve resposta do SPI até o tempo máximo definido para caracterização de timeout. Já temos este timeout definido para as liquidações prioritarias ?

**Sistema ou Área**
SPI

**Comment by rafael-omello** [comment]
No dia 17 de julho de 2020 foi enviada consulta sobre o Manual de Tempos do Pix para o GT Padronização e Requisitos Técnicos e o GT Segurança. Nesse manual podem ser encontradas as definições do BC sobre esse tema, inclusive o tempo máximo para as transações de pagamento no âmbito do Pix.
