### ISSUE TITLE
[Problema] no [DICT] - Arquivo de CID retorna chave que foi doada/confirmada pelo PSP doador

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#127]
**Descreva sua dúvida ou problema**

Olá! Fizemos um teste onde uma chave estava no processo de reivindicação de posse e o PSP doador **confirmou o pedido**, ou seja, a chave foi **excluída do PSP doador** (PSP que estamos testando o sincronismo de chaves). 
O PSP reivindicador ainda não concluiu o processo. Quando consultamos a chave, ela não é retornada (o que é o esperado).

Porém, quando solicitamos o **arquivo de CID** do PSP (que está sendo o PSP doador), essa chave **está sendo retornada**. Isso está correto? 
No nosso entendimento, a chave neste momento não pertence mais ao PSP doador, portanto não deveria vir no arquivo de CIDs.

No nosso processo de sincronismo, tentamos excluir a chave do DICT para corrigir as bases e é retornado que ela está no processo de reivindicação.

**Sistema ou Área**
DICT

**Identificador do Problema**

CID em estado de reinvidicação já aceita pelo PSP doador: 55471318c3fb4c406aad4d7cb798f0e10f761acec2fc7c428d6a94834ef69d63

Linha do CIDfile que o CID foi apresentado pelo BACEN: linha 23  

Chave: ios@matera.com

Chamada de consulta ao BACEN
` GET /api/v1-rc4/cids/entries/55471318c3fb4c406aad4d7cb798f0e10f761acec2fc7c428d6a94834ef69d63 HTTP/1.1`

Resposta: 
`<GetEntryByCidResponse> <Signature/> <Cid>55471318c3fb4c406aad4d7cb798f0e10f761acec2fc7c428d6a94834ef69d63</Cid> <Entry> <Key>ios@matera.com</Key> <KeyType>EMAIL</KeyType> ... ... <CreationDate>2020-07-21</CreationDate> <KeyOwnershipDate>2020-07-21</KeyOwnershipDate> </Entry> </GetEntryByCidResponse>  `

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc4/

**Comment by HenriqueSimoes82** [comment]
@monise 
Chave excluída não deveria estar no arquivo de CID. Iremos realizar a correção. Obrigado pelo reporte.

**Comment by jorgebaruchi** [comment]
Boa tarde ! Alguma novidade sobre este bug ?

**Comment by monise** [comment]
@HenriqueSimoes82 Olá!! Você tem uma previsão de quando estará disponível essa correção?

**Comment by judahreis** [comment]
@monise, @jorgebaruchi, a correção foi aplicada. Favor realizar o teste novamente.
