### ISSUE TITLE
[Sugestão] - API de Recebimento - Consulta de situação de pagamento 

### ISSUE THREAD

**Issue by fernandogodoy** [bacen/pix-perguntas-e-respostas#128]
**Descreva sua dúvida ou problema**
Olá,
Analisando a documentação da api, fiquei com uma duvida.

O usuário teria que fazer pooling pra capturar o status de um pagamento?

Se sim, poderia ser considerado uma url de callback para envio de notificação, dessa forma, evitando o pooling?

**Sistema ou Área**
Api de Recebimento

**Comment by ninrod** [comment]
@fernandogodoy , sim, esse seria o funcionamento. A princípio estamos seguindo a linha de deixar a API enxuta e só adicionar o que for estritamente necessário. 

Mas sim, a questão de uma url de callback ainda está na mesa.

**Comment by hmaesta** [comment]
Sou favorável a URL de callback. Penso que é melhor o serviço fazendo 1 request de POST do que recebendo indeterminados GET.

Os impedimentos que consigo pensar são:

- Definir um mecanismo pra validar que o remetente de fato é o BCB
   - Faixa de IPs
   - Hash no cabeçalho
- Determinar o que é uma resposta de sucesso
  - Status HTTP `200`
  - Retorno em formato padronizado `{ "response": { "status": "success" } }`
- Em caso de falha no callback, o que fazer?
  - Invalidar a transação
  - A transação não muda, mas tenta enviar novo POST mais X vezes
    - Aumenta consideravelmente a dificuldade (e responsabilidade) do serviço

**Comment by rubenskuhl** [comment]
> Sou favorável a URL de callback. Penso que é melhor o serviço fazendo 1 request de POST do que recebendo indeterminados GET.

+1 para URL de callback. Usamos isso para recebimento de cartão de crédito e funciona bem. 

> 
> Os impedimentos que consigo pensar são:
> 
> * Definir um mecanismo pra validar que o remetente de fato é o BCB

Na verdade a API de Recebimento não é do BCB, é do PSP que o EC escolheu. 
Então cada IF/IP precisaria informar seus clientes de IPs de origem, mudanças nele etc. 

>   
>   * Faixa de IPs
>   * Hash no cabeçalho

A conexão sendo TLS pode-se usar muitas alternativas diferentes de mútua autenticação. 

> * Determinar o que é uma resposta de sucesso
>   
>   * Status HTTP `200`
>   * Retorno em formato padronizado `{ "response": { "status": "success" } }`

Talvez por idempotência informar que a transação TXID teve sua nova situação conhecida. 

> * Em caso de falha no callback, o que fazer?
>   
>   * Invalidar a transação

Não, a transação já foi confirmada no PIX. 

>   * A transação não muda, mas tenta enviar novo POST mais X vezes

Acho que é mais por aí mesmo. 
     
>     * Aumenta consideravelmente a dificuldade (e responsabilidade) do serviço

Em o retorno não acontecendo sempre dá para fazer novo GET de situação, então a dependência não é absoluta.

**Comment by Sphinxs** [comment]
@ninrod Onde consigo acesso a API / documentação?

**Comment by ninrod** [comment]
@Sphinxs , [aqui](https://github.com/bacen/pix-api-recebimentos)

**Comment by rubenskuhl** [comment]
> @ninrod Onde consigo acesso a API / documentação?

https://github.com/bacen/pix-api-recebimentos/releases/download/1.2.0/spec.html

**Comment by ninrod** [comment]
Caros, teremos `webhook`. Versão `2.0.0` provavelmente será liberada amanhã. Obrigado pelas contribuições.

**Comment by xpsnetworks** [comment]
Quem tem acesso a esta API?

**Comment by renatofrota** [comment]
> Quem tem acesso a esta API?

Veja [aqui](https://github.com/bacen/pix-api/issues/76#issuecomment-708554577).

**Comment by rubenskuhl** [comment]
> Quem tem acesso a esta API?

Para ter acesso você precisa ter uma conta transacional em um dos PSPs que oferecem a API Pix. O @renatofrota já comentou o issue onde tento manter uma lista de quais são eles, mas eu não sei se a sua dúvida era mais conceitual ou mais prática. 

Notar que a https://github.com/bacen/pix-api/ substituiu a API de recebimento, e ela engloba tanto o lado público (onde os PSPs recebedores expõe cobranças para os PSPs pagadores) quanto o lado autenticado da relação entre um PSP recebedor e seus correntistas.
