### ISSUE TITLE
Dúvida no DICT - Dúvida quanto ao cadastro de chave já existente

### ISSUE THREAD

**Issue by Leonardo34** [bacen/pix-perguntas-e-respostas#129]
**Descreva sua dúvida ou problema**
Quando cadastramos uma chave já existente no Bacen, não seria interessante ser retornado os dados da chave já existente para que possamos dar o devido direcionamento ao usuário, no sentido de indicar se ele necessita cadastrar uma reivindicação de posse ou portabilidade para que ele possa fazer uso da chave ? Dado que antes do cadastro ser realizado de fato no DICT ele já comprovou a devida posse da chave.

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
Leonardo, acredito que o tipo de erro retornado na situação de já existir chave cadastrada (`EntryKeyOwnedByDifferentPerson`, `EntryKeyInCustodyOfDifferentParticipant`) já serve ao propósito de indicar qual fluxo seguir.

`EntryKeyOwnedByDifferentPerson` ->  reivindicação de posse.
`EntryKeyInCustodyOfDifferentParticipant` ->  portabilidade.
