### ISSUE TITLE
[Dúvida] no [DICT] - Reconciliação - Verificar Sincronismo

### ISSUE THREAD

**Issue by slheckler** [bacen/pix-perguntas-e-respostas#13]
**Descreva sua dúvida ou problema**
Durante os testes para o endpoint `/sync-verifications/` enviamos o payload abaixo com o SyncVerifier calculado em nosso lado, porém o payload de retorno indica Result NOK, apesar de trazer o mesmo exato SyncVerifier. O payload de resposta devolve o SyncVerifier enviado?

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
Slhecklet, faltou o payload...

**Comment by judahreis** [comment]
De qualquer maneira, o SyncVerifier do DICT nunca é retornado. Na mensagem de retorno, o SyncVerifier sempre é o mesmo informado na requisição com o resultado: OK ou NOK. Para identificar as divergências, é preciso solicitar o arquivo de CIDS (POST /cids/files/), ou acompanhar o LOG de eventos de chaves (GET /cids/events).

**Comment by slheckler** [comment]
Obrigado!
