### ISSUE TITLE
DICT - Indisponível

### ISSUE THREAD

**Issue by rafaelpkcortes** [bacen/pix-perguntas-e-respostas#130]
**Descreva sua dúvida ou problema**
DICT  - indisponível após alteração do ambiente

**Sistema ou Área**
DICT

**Identificador do Problema**
Inclusão de chave celular, retornando timeout.

**Mensagens Enviadas / Recebidas**
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<CreateEntryRequest>
	<Entry>
		<Key>+5557933245333</Key>
		<KeyType>PHONE</KeyType>
		<Account>
			<Participant>36586946</Participant>
			<Branch>1</Branch>
			<AccountNumber>295406</AccountNumber>
			<AccountType>CACC</AccountType>
		</Account>
		<Owner>
			<Type>NATURAL_PERSON</Type>
			<TaxIdNumber>50478353081</TaxIdNumber>
			<Name>Roberto gomes</Name>
		</Owner>
	</Entry>
	<Reason>USER_REQUESTED</Reason>
	<RequestId>2f9126a5-ee51-45a0-9784-d9cf3bb593ba</RequestId>
</CreateEntryRequest>

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc4/entries

**Dados adicionais**
após alteração do IP 56 para 36 não conseguimos testar com o DICT.

**Comment by judahreis** [comment]
@rafaelpkcortes , não identificamos nenhum problema do nosso lado. Vários PSPs estão realizando operações hoje. Na verdade, não identificamos indisponibilidade há alguns dias... você tem algum dado adicional? Qual IP está resolvendo dict-h.pi.rsfn.net.br do lado de vcs?

**Comment by rafaelpkcortes** [comment]
DICT esta resolvendo 200;218;66;36

**Comment by rafaelpkcortes** [comment]
> @rafaelpkcortes , não identificamos nenhum problema do nosso lado. Vários PSPs estão realizando operações hoje. Na verdade, não identificamos indisponibilidade há alguns dias... você tem algum dado adicional? Qual IP está resolvendo dict-h.pi.rsfn.net.br do lado de vcs?

200.218.66.36
