### ISSUE TITLE
[DICT] - Testes de carga - disponibilização das chaves para consulta

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#131]
**Descreva sua dúvida ou problema**

Olá! Sobre os testes de carga para consulta de chaves, será disponibilizado de alguma forma as chaves de outros PSP para consulta?

![image](https://user-images.githubusercontent.com/5355541/89205092-882d5a00-d58d-11ea-980c-8d5b305ee04a.png)

**Sistema ou Área**
DICT

**Comment by fescariot** [comment]
Estamos procurando instituições parceiras para realizar os testes de consultas de chaves. Você teria interesse @monise ?

**Comment by luizlaydner** [comment]
Para facilitar o teste de carga, cadastramos no DICT chaves de telefone no intervalo:

+5561988000000 a +5561988999999
