### ISSUE TITLE
[Dúvida] no [QRCODE-EMV] - Caracteres permitidos no EMV

### ISSUE THREAD

**Issue by gpneto** [bacen/pix-perguntas-e-respostas#132]
Na versão 2.0.0 do BR CODE( https://www.bcb.gov.br/content/estabilidadefinanceira/spb_docs/ManualBRCode.pdf) consta no Histórico de versões a seguinte descrição: "Removida a restrição que determinava uso somente de caracteres alfanuméricos".

Não localizei na documentação quais os caracteres que serão aceito na geração do EMV.

Neste caso será possível adicionar qualquer caracter no QR CODE? 

Dúvidas:
na TAG 59(Merchant Name) pode ter? João da Silva ou Carlos D'avila
na TAG 60(Merchant City) pode ter? São Paulo

**Sistema ou Área**
QR Code - EMV

**Comment by ninrod** [comment]
@gpneto, o BR Code segue o EMV e nesse sentido, qualquer caracter UTF8 é aceito.
