### ISSUE TITLE
[Problema] no DICT - Concluir reivindicação

### ISSUE THREAD

**Issue by gabrielmendesbb** [bacen/pix-perguntas-e-respostas#133]
Quando chamo a API concluir reivindicação não vem os campos CreationDate e KeyOwnershipDate. Como acontece no incluir chave. 

Não deveria ter esses campos?? Como vou saber esses dados se a chave for vinculada via processo de reivindicação ?

**Comment by luizlaydner** [comment]
Me parece que seria mais coerente mesmo retornar a Entry criada como consequência da conclusão da reivindicação. Vamos adicionar isso na API, provavelmente na próxima RC.

**Comment by judahreis** [comment]
@gabrielmendesbb, sua sugestão foi atendida na RC6, já disponível no ambiente de homologação. Os campos foram incluidos no CompleteClaimResponse.
