### ISSUE TITLE
Fluxo de Disputa

### ISSUE THREAD

**Issue by rafaelpkcortes** [bacen/pix-perguntas-e-respostas#134]
**Descreva sua dúvida ou problema**
Quando será disponibilizado o Fluxo Disputa

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
@rafaelpkcortes, a previsão de publicação para testes é 21/08/2020, homologação a partir de 01/09/2020. A API já está pronta na [versão rc5](https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/AnexoV-APIdoDiretoriodeIdentificadoresdeContasTransacionais-versao1.0.0-RC5.html).
