### ISSUE TITLE
[Dúvida| no [DICT] - Requisitos para gerar chave EVP

### ISSUE THREAD

**Issue by jaquelinejardim** [bacen/pix-perguntas-e-respostas#136]
Gostaria de saber quais requisitos/informações teremos que solicitar do usuário para geração da chave EVP (Endereço Virtual de Pagamento). Sendo uma chave gerada pelo DICT, na hora de selecionar o tipo de chave, o usuário deverá escolher alguma informação que será vinculada ao EVP? (Por exemplo: escolher um telefone) Ou será necessário apenas solicitar  a geração, e esta será automática?

**Comment by luizlaydner** [comment]
@jaquelinejardim Uma chave do tipo EVP é número aleatório gerado pelo DICT no momento em que o participante comanda a operação, a pedido do usuário. O usuário poderá escolher vincular sua conta transacional a uma chave desse tipo. As informações que estarão vinculadas ao EVP no DICT são as mesmas exigidas para o registro de qualquer tipo de chave (dados de identificação do titular e da conta transacional). Uma diferença importante do EVP é que ele não pode ser sofrer portabilidade ou reivindicação de posse.
