### ISSUE TITLE
[Dúvida|Problema] no [SISTEMA] - Título

### ISSUE THREAD

**Issue by mlardone** [bacen/pix-perguntas-e-respostas#137]
**Descreva sua dúvida ou problema**
Na DICT API (1.0.0-RC5) diz

_Limitação de requisições
A política de limitação (rate-limiting) funciona com base em cabeçalhos enviados na requisição.
O parâmetro PI-PayerId é o identificador pseudonimizado do usuário final, vinculado a um participante. Requisições vindas de um mesmo usuário, para um mesmo participante, devem usar o mesmo identificador. Como sugestão de implementação, pode ser utilizado o valor hexadecimal da aplicação de HMAC-SHA-256 a um identificador do usuário, com chave de conhecimento restrito ao participante._

Se a mesma pessoa tem 2 contas, o hash é sobre o CPF ou sobre o numero da conta?

Por essemplo:
CPF: 123
Conta 1: 111
Conta 2: 222
A consulta é desde a conta 1

hash(CPF) ou hash(111)

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
@mlardone, a ideia é essa mesma: diferentes contas de um mesmo CPF tem o mesmo PayerId. Ou seja, tanto a conta 1 quanto a conta 2 teriam o mesmo PayerId.
