### ISSUE TITLE
[Dúvida] no [DICT] - Dúvidas serviços de abertura e fechamento de uma disputa

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#138]
**Descreva sua dúvida ou problema**

Olá! Gostaria de tirar algumas dúvidas sobre os serviços de abertura e fechamento de uma disputa.

1 - É permitido abrir mais de uma disputa (com valor parcial) para o **mesmo pagamento** enquanto uma disputa não for fechada? Se não for permitido, o serviço de abertura retornará o erro **DisputeAlreadyBeingProcessedForTransaction**?

2 - O erro **DisputePeriodExpired** será retornado no serviço de fechamento de uma disputa caso ela tenha ultrapassado os 21 dias? 

3 - Se um pedido de disputa passar dos 21 dias **sem** que o PSP recebedor feche a disputa (aceite ou rejeite), a disputa será fechada automaticamente pelo DICT? Se sim, seria com o status de rejeitada?

4 - No serviço de fechamento, o campo **Participant** do request body, é opcional mesmo? 

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
@monise,
1a. Se houver disputa OPEN ou ACKNOWLEDGED para a transação, uma nova disputa sobre a mesma transação retornará DisputeAlreadyBeingProcessedForTransaction.
1b. Se houver disputa  "CLOSED" para a transação, novas disputas sobre a mesma transação retornarão DisputeAlreadyProcessedForTransaction.
1c. Se houver disputa "CANCELED" para a transação, novas disputas sobre a mesma transação podem ser criadas, sem problemas. 

2. Não. O DisputePeriodExpired é exclusivo para a abertura. O participante poderá fechar a qualquer momento, mas poderá sofrer sanções se demorar mais que 21 dias.

3. O DICT é sempre passivo. O participante deve obrigatoriamente fechar a disputa, sob pena de sanções.

4.  É obrigatório. Vamos modificar. Obrigado pela revisão. :)
