### ISSUE TITLE
Dúvida no DICT - Dúvida quanto os dados de frade na consulta de chave

### ISSUE THREAD

**Issue by Leonardo34** [bacen/pix-perguntas-e-respostas#139]
**Descreva sua dúvida ou problema**
Dúvida quanto aos dados de frade que são retornados na consulta de uma chave. Esses dados foram adicionados na RC5 da API do PIX, e tem como objetivo possibilitar que ações anti-fraude sejam tomadas na realização do pagamento, após consulta da chave. A dúvida é a seguinte, quando um participante indireto consulta uma chave de um direto (que está na nossa base) não temos essas informações para listar, teríamos então que consultar ela diretamente no DICT mesmo sendo nossa ? Esse comportamento não é aderente ao que existe hoje, que não possibilita a consulta de uma chave que me pertence. 

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
> teríamos então que consultar ela diretamente no DICT mesmo sendo nossa ?

Sim. No cenário de um PSP indireto consultar a chave um PSP direto, a requisição poderá ser encaminhado para o DICT.
Na requisição, o header `PI-RequestingParticipant` será o do PSP indireto. O DICT nesse caso aceitará a consulta.

O que o DICT rejeita é consulta de chave em que o `PI-RequestingParticipant` é o mesmo do que consta no vínculo. A consulta do PSP direto para vínculo dele mesmo retorna o erro `EntryCannotBeQueriedForBookTransfer`.
