### ISSUE TITLE
Problema no Dict - Problema ao confirmar reivindicação de posse para participante indireto

### ISSUE THREAD

**Issue by Leonardo34** [bacen/pix-perguntas-e-respostas#14]
### **Descreva sua dúvida ou problema**
Cadastrei uma solicitação de portabilidade `00b4c525-b635-4498-9784-e6cd48cd7d68`.
O donorParticipant dela é meu ISPB Virtual indireto (59588112), e o claimer é meu participant direto (59588111). Consegui realizar o cadastro da claim e o acknowledge dela com sucesso, porém ao solicitar a confirmação dela, estou recebendo o seguinte retorno de erro: 

```
<type>https://dict.pi.rsfn.net.br/api/v1/error/InvalidReason</type>
<title>Bad  Request</title>
<status>400</status>
<detail>Invalid reason</detail>
<correlationId>079189C1401F465081836F244E8215D3</correlationId>
```

Minha requisição foi a seguinte: 

```
<?xml version="1.0" encoding="UTF-8"?>
<ConfirmClaimRequest xmlns:ns2="http://www.w3.org/2000/09/xmldsig#">
   <ClaimId>00b4c525-b635-4498-9784-e6cd48cd7d68</ClaimId>
   <Reason>USER_REQUESTED</Reason>
</ConfirmClaimRequest>
```

Conforme documentado aqui, acredito que estou seguindo as regras de negócio e estou informando a REASON correta.

![image](https://user-images.githubusercontent.com/14354193/85479366-660aea00-b594-11ea-803b-7b6ce0068c2e.png)

### **Sistema ou Área**
DICT

### **Identificador do Problema**
CorrelationId -> **_079189C1401F465081836F244E8215D3_**

### **Mensagens Enviadas / Recebidas**
**Payload da request:** 
```
<?xml version="1.0" encoding="UTF-8"?>
<ConfirmClaimRequest xmlns:ns2="http://www.w3.org/2000/09/xmldsig#">
   <ClaimId>00b4c525-b635-4498-9784-e6cd48cd7d68</ClaimId>
   <Reason>USER_REQUESTED</Reason>
</ConfirmClaimRequest>
```
**Response:**
```
<type>https://dict.pi.rsfn.net.br/api/v1/error/InvalidReason</type>
<title>Bad  Request</title>
<status>400</status>
<detail>Invalid reason</detail>
<correlationId>079189C1401F465081836F244E8215D3</correlationId>
```

### **URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1/claims/00b4c525-b635-4498-9784-e6cd48cd7d68/confirm

### **Dados adicionais**
Um detalhe, é que realizei o mesmo fluxo apenas invertendo os papeis (solicitante como meu ISPB indireto virtual, e doador meu ISPB direto) e obtive sucesso, me parece que talvez o erro tenha relação com o participante indireto ser o donor da chave.
Essa claim mencionada é a de ID _12c5937f-5afb-4ec2-9741-6ee2fe42bfad_

**Comment by judahreis** [comment]
Vamos investigar

**Comment by judahreis** [comment]
Leonardo,

Identificamos o problema, e haverá um ajuste na mensagem de permitirá a solução do problema. Será lançado na próxima versão da API (v1.0.0-RC4).

Obrigado pelo report detalhado!
