### ISSUE TITLE
[Problema] no [SPI] - Erro versão xsd

### ISSUE THREAD

**Issue by GabrielSouzasbl** [bacen/pix-perguntas-e-respostas#140]
**Descreva sua dúvida ou problema**
Estamos recebendo a pacs.002 com namespace:
"https://www.bcb.gov.br/pi/pacs.002/1.3"

porém na versão SPI 1.11 o xsd do mesmo vem com namespace:
"https://www.bcb.gov.br/pi/pacs.002/1.4"

**Comment by adilson-silva** [comment]
Segundo o Informe SPI - 024/2020, a versão 1.3 da pacs.002 será desabilitada definitivamente somente a partir de 10/08. 

Na prática, em algum momento após o fechamento da janela do dia útil anterior (07/08).

**Comment by GabrielSouzasbl** [comment]
Entendi, obrigado!
