### ISSUE TITLE
[Problema] no [DICT - PIX] - Canal inseguro de Reporte a bugs.

### ISSUE THREAD

**Issue by GraoMelo** [bacen/pix-perguntas-e-respostas#141]
**Descreva sua dúvida ou problema**
as mensagens de bugs confidenciais não estão seguras tanto pelo envio quanto pelo armazenamento.
as mesmas podem ser forjadas e não existe nada que possa garantir o "não repudio" e o envio de bugs a: suporte.ti@bcb.gov.br 

**Sistema ou Área**
DICT, INFRA 

**Identificador do Problema**
para internalização correta será necessário a implementação de encriptação por meio de chave assimetrica.
pode usar as especificações do iti.gov.br por exemplo ( até entao tao sendo ignoradas ) 

**Mensagens Enviadas / Recebidas**
podem usar o exemplo de outra autoridade. o cert.br

Informações de Contato do CERT.br
Para entrar em contato com o CERT.br envie um email para:

CERT.br <ALGO@cert.br>
Para comunicação através de um canal seguro, por favor utilize a seguinte chave PGP:

Chave PGP 2020
PGP Key ID: 111C10AD
Fingerprint: XXXX 390F 767D 77A7 5271 4B89 DE8E 3FC8 041C XXX
PGP Public Key
Para reportar incidentes por favor envie um email de notificação diretamente para os contatos da rede de onde parte a atividade, colocando e email <ALGO@cert.br> no campo "Cc:" da mensagem.

Mais informações sobre como reportar os incidentes e como encontrar os emails de contato das redes podem ser encontradas nos seguintes documentos: 

**Dados adicionais**
https://cert.br/docs/whitepapers/notificacoes/
http://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11419.htm
http://www.planalto.gov.br/ccivil_03/MPV/Antigas_2001/2200-2.htm

**Comment by judahreis** [comment]
@GraoMelo, agradecemos a sugestão. Vamos analisar a alternativa.

**Comment by GraoMelo** [comment]
@judahreis grato por deixar claro que críticas não são bem  vindas.
