### ISSUE TITLE
Dúvida no SPI - Mensagem REDA016 não está sendo retornada

### ISSUE THREAD

**Issue by alexandredsimoes** [bacen/pix-perguntas-e-respostas#142]
**Descreva sua dúvida ou problema**
Estou efetuando testes de mensagens REDA014 e REDA031 (Inclusão e exclusão de participante indireto) e o retorno REDA016 ramente vem. Existe alguma grade de horário pra testes dessas mensagens?

**Sistema ou Área**
SPI

**Comment by rodalvarenga** [comment]
Prezado, consegue informar algum identificador de mensagem REDA.014 ou REDA.031 para o qual não recebeu mensagem de retorno?

**Comment by alexandredsimoes** [comment]
Reda014
M0471568520200806181317362256920

**Comment by rodalvarenga** [comment]
Consta no SPI que a mensagem de retorno REDA.016 foi enviada em **2020-08-06T18:17:25.873Z** com identificador **M000381660KDJ4HJ0110V6PLVRMVCN64** e recibo de leitura **UEkBc8T9+nEJgSWpRfdC25k+2lbOOoqp**

**Comment by alexandredsimoes** [comment]
Mandei uma reda031
M0471568520200806194428436426051

**Comment by rodalvarenga** [comment]
M0471568520200806194428436426051
Retorno REDA.016
Identificador: M000381660KDJ7QQO310V70OBLFRPPUO
Recibo de leitura: UEkBc8VRbIOYCiRFiRlP2a0Mvw2NN1CW

M0463285620200806223444008423932
Retorno REDA.016
Identificador: M000381660KDJDOFKG10V70OBL3Z6LP0
Recibo de leitura: UEkBc8XpjdDQgGp5OlFKJIYrsk+CC7nm

M0463285620200806220055658664973
Retorno REDA.016
Identificador: M000381660KDJCH11310V6PLVRGCCAE0
Recibo de leitura: UEkBc8XKp3cCfThdWsBJ06GnC0b7wOA2

Conforme pode ser observado, para todas as mensagens de entrada citadas foi gerada a mensagem de retorno correspondente, inclusive com recibo de leitura.
