### ISSUE TITLE
[Dúvida] no [DICT] - Restrição de Horário lista de CIDs - DICT

### ISSUE THREAD

**Issue by ale517** [bacen/pix-perguntas-e-respostas#143]
Descreva sua dúvida ou problema

Olá! Conforme a documentação Geração de arquivo com lista de CIDs está classificado como categoria D: de 20 horas às 8 horas, todos os dias (incluindo sábados, domingos e feriados).

Esta restrição de horário aplicada para “Criar Arquivo de CIDs” (POST) e “Consultar Arquivo de CIDs” (GET) ou apenas para geração do arquivo ?

Existe   alguma recomendação em tempo para consulta periódica do consultar arquivos de CIDS? 

Sistema ou Área
DICT

**Comment by judahreis** [comment]
@ale517 , estamos removendo a restrição de janela para a geração de arquivos de CIDs. Ele poderá ser gerado a qualquer momento (pelo menos no início da operação do DICT). Essa modificação está disponível no manual de tempos do pix e no manual operacional (a ser publicado).

Quanto ao polling, o ideal é uma consulta por minuto, para verificar o status de geração do arquivo.
