### ISSUE TITLE
Problema no DICT - Consultar Vínculo por CID

### ISSUE THREAD

**Issue by leandrofrancisquete** [bacen/pix-perguntas-e-respostas#144]
Bom dia!

Segundo especificação, o serviço "Consultar Vínculo por CID" não solicita informação do header "PI-RequestingParticipant", porém recebemos 400 - Bad Request.

![image](https://user-images.githubusercontent.com/50705181/89543613-86ef6d80-d7d7-11ea-8409-ad74f8837ba7.png)

400 Bad Request
null:  HTTP/1.1 400 Bad Request
Content-Language:  en-US
Transfer-Encoding:  chunked
Date:  Wed, 05 Aug 2020 18:42:54 BRT
Connection:  Close
Content-Type:  application/xml
X-Powered-By:  Servlet/3.1

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<a:problem xmlns:a="urn:ietf:rfc:7807">
    <a:Signature></a:Signature>
    <a:type>https://dict.pi.rsfn.net.br/api/v1/error/BadRequest</a:type>
    <a:title>Bad Request</a:title>
    <a:status>400</a:status>
    <a:detail>Missing request header 'PI-RequestingParticipant'</a:detail>
</a:problem>

Poderiam verificar, por favor?

Obrigado!!

**Comment by luizlaydner** [comment]
Está faltando na especificação a definição de que o header `PI-RequestingParticipant` é obrigatório para a operação getEntryByCid.
Vamos corrigir na próxima release da spec. Obrigado por reportar.
