### ISSUE TITLE
Dúvida no DICT - Campo de razão na reivindicação

### ISSUE THREAD

**Issue by mpostemsky** [bacen/pix-perguntas-e-respostas#145]
Bom Dia,

Existe a possibilidade de adicionar o campo de razão na reivindicação? Esta informação seria útil para nós conhecer os cenários de cancelamento/confirmação do doador.

**Comment by luizlaydner** [comment]
Sua sugestão seria adicionar o campo `Reason` que já existe nas requisições nas respostas também?
Poderia elaborar um pouco mais a sugestão ? De que forma a informação seria útil ?

**Comment by mpostemsky** [comment]
Obrigado pela sua resposta. Sim, seria adicionar o campo Reason que já existe nas requisições nas respostas também.

Em princípio, seria muito útil para cenários em que uma reivindicação é cancelada devido a fraude. No momento, no caso de ser um PSP reivindicado, não podemos informar ao usuário qual foi o motivo desse cancelamento. Além disso, nos permite ter um histórico de reivindicações fraudulentas (por chaves ou proprietários).

No caso de uma reivindicação de posse ser cancelada, podemos ter revisões manuais, dependendo se o motivo foi DEFAULT_OPERATION ou USER_REQUESTED. Em outras palavras, se o usuário doador cancelou a reinvidicação porque ele poderia fazer uma validação ativa, deveríamos descobrir como nosso usuário solicitante conseguiu validar essa chave do nosso lado.

**Comment by judahreis** [comment]
@mpostemsky, já disponível para testes no ambiente de homologação.
