### ISSUE TITLE
[Dúvida/Problema] no [SPI] - Timeout Manual de Tempos PIX - Homologação

### ISSUE THREAD

**Issue by adrianbp** [bacen/pix-perguntas-e-respostas#146]
**Descreva sua dúvida ou problema**

Boa Tarde!

Conforme orientação dada na issue 126, utilizei o Manual Tempos PIX encaminhado no dia 17/07 para tirar a dúvida referente ao timeout máximo de tempo do PIX de 40 segundos. No entanto, fiquei com dúvida referente ao cancelamento das transações. Os PSPs devem aguardar a mensagem PACS002 de retorno com o código AB03 ou eles podem realizar o cancelamento sem o retorno do SPI após o período de 40 segundos ?

Realizei um teste abaixo no ambiente de homologação e tive o retorno da PACS002 com o timeout após um período de 8 minutos. Inclusive reenviando a PACS.008 com o mesmo conteúdo. Abaixo temos o detalhamento das informações:

**Sistema ou Área**
SPI

**Identificador do Problema**

EndToEndId: E595881112020080616061905902NEXB

PI-ResourceId gerado no envio das PACS.008 
     UEkBc8SHlbqa1VUfHRBEFKczf6ftGqED"
     UEkBc8SIVHEvf8CSgWBILb9vMT6ZYtzi"
     UEkBc8SHFzh90GYvNnZF5J/zkRVwccPN"

**Mensagens Enviadas / Recebidas**
<Envelope xmlns="https://www.bcb.gov.br/pi/pacs.008/1.4"> 
    <AppHdr>
        <Fr>
            <FIId>
                <FinInstnId>
                    <Othr>
                        <Id>59588111</Id>
                    </Othr>
                </FinInstnId>
            </FIId>
        </Fr>
        <To>
            <FIId>
                <FinInstnId>
                    <Othr>
                        <Id>00038166</Id>
                    </Othr>
                </FinInstnId>
            </FIId>
        </To>
        <BizMsgIdr>M595881118202008062X57190592245B</BizMsgIdr>
        <MsgDefIdr>pacs.008.spi.1.4</MsgDefIdr>
        <CreDt>2020-08-06T16:07:21.021Z</CreDt>
        <Sgntr></Sgntr>
    </AppHdr>
    <Document>
        <FIToFICstmrCdtTrf>
            <GrpHdr>
                <MsgId>M595881118202008062X57190592245B</MsgId>
                <CreDtTm>2020-08-06T16:07:21.021Z</CreDtTm>
                <NbOfTxs>1</NbOfTxs>
                <SttlmInf>
                    <SttlmMtd>CLRG</SttlmMtd>
                </SttlmInf>
                <PmtTpInf>
                    <InstrPrty>HIGH</InstrPrty>
                </PmtTpInf>
            </GrpHdr>
            <CdtTrfTxInf>
                <PmtId>
                    <EndToEndId>E595881112020080616061905902NEXB</EndToEndId>
                    <TxId>12555487</TxId>
                </PmtId>
                <IntrBkSttlmAmt Ccy="BRL">10.50</IntrBkSttlmAmt>
                <AccptncDtTm>2020-08-06T16:05:00.510Z</AccptncDtTm>
                <ChrgBr>SLEV</ChrgBr>
                <Dbtr>
                    <Nm>Pagamento PIX BV</Nm>
                    <Id>
                        <PrvtId>
                            <Othr>
                                <Id>72264462000</Id>
                            </Othr>
                        </PrvtId>
                    </Id>
                </Dbtr>
                <DbtrAcct>
                    <Id>
                        <Othr>
                            <Id>15218503</Id>
                            <Issr>1</Issr>
                        </Othr>
                    </Id>
                    <Tp>
                        <Cd>CACC</Cd>
                    </Tp>
                </DbtrAcct>
                <DbtrAgt>
                    <FinInstnId>
                        <ClrSysMmbId>
                            <MmbId>59588111</MmbId>
                        </ClrSysMmbId>
                    </FinInstnId>
                </DbtrAgt>
                <CdtrAgt>
                    <FinInstnId>
                        <ClrSysMmbId>
                            <MmbId>68900810</MmbId>
                        </ClrSysMmbId>
                    </FinInstnId>
                </CdtrAgt>
                <Cdtr>
                    <Id>
                        <PrvtId>
                            <Othr>
                                <Id>00710270844</Id>
                            </Othr>
                        </PrvtId>
                    </Id>
                </Cdtr>
                <CdtrAcct>
                    <Id>
                        <Othr>
                            <Id>0431330007</Id>
                            <Issr>0001</Issr>
                        </Othr>
                    </Id>
                    <Tp>
                        <Cd>CACC</Cd>
                    </Tp>
                    <Prxy>
                        <Id>00710270844</Id>
                    </Prxy>
                </CdtrAcct>
                <RmtInf>
                    <Ustrd>Envio de Pagamento BV</Ustrd>
                </RmtInf>
            </CdtTrfTxInf>
        </FIToFICstmrCdtTrf>
    </Document>
</Envelope>

**URL de conexão**
https://icom-h.pi.rsfn.net.br/api/v1/in/59588111/msgs

**Dados adicionais**

**Comment by rsabin** [comment]
O que precisa ser respondido aqui é:
Após o PSP enviar uma pacs.008 ao SPI com sucesso (entenda-se, o PSP recebeu o resource-id), qual é o processo caso o PSI não responda com a pacs.002?

Sabemos que devemos aguardar o retorno do Bacen, mas e se não vier?
O consenso comum é re-enviar a pacs.008. Mas e se mesmo assim continuar não vindo resposta, como foi o caso acima?

**Comment by rafael-omello** [comment]
Dúvidas de negócio devem ser enviadas para spi@bcb.gov.br.
