### ISSUE TITLE
Problema no DICT - Tempo resposta Consultar Vínculo (teste de capacidade)

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#147]
**Descreva sua dúvida ou problema**
Estamos realizando o teste de capacidade, "consultar mil chaves diferentes em um intervalo de 60 segundos e receber resposta DICT com sucesso", porem o tempo de resposta do DICT esta com uma variação muito grande onde chegamos a detectar até 1.5s de tempo para a consulta: key: +5561988000005, envio: 2020-08-06 14:10:43.726443 resposta: 2020-08-06 14:10:45.235368 EndToEndId: E02318507202008061410uAfeC2qhheo, e para conseguirmos realizar o teste precisaríamos realizar aproximadamente 17 consultas por segundo, gostaria de saber se o sistema DICT esta pronto para iniciarmos os testes de capacidade. 
Obrigado!

**Sistema ou Área**
DICT

**Mensagens Enviadas / Recebidas**
Segue abaixo log dos testes de consultas realizados, para o ISPB: 02318507.
============================
+5561988000002 2020-08-06 14:10:43.073181 2020-08-06 14:10:43.644234 E02318507202008061410UZq3yndH8SU
0.5710523128509521
============================
+5561988000000 2020-08-06 14:10:43.070857 2020-08-06 14:10:43.689515 E02318507202008061410OeMNa8vlWcp
0.6186604499816895
============================
+5561988000001 2020-08-06 14:10:43.072190 2020-08-06 14:10:43.723157 E02318507202008061410nRNDpJy4ZTQ
0.6509678363800049
============================
+5561988000003 2020-08-06 14:10:43.647556 2020-08-06 14:10:45.027542 E02318507202008061410fOLdSitedaI
1.3799841403961182
============================
+5561988000004 2020-08-06 14:10:43.692985 2020-08-06 14:10:45.158545 E02318507202008061410Uecaz7gZdq4
1.4655590057373047
============================
+5561988000005 2020-08-06 14:10:43.726443 2020-08-06 14:10:45.235368 E02318507202008061410uAfeC2qhheo
1.508922815322876
============================
+5561988000006 2020-08-06 14:10:45.032079 2020-08-06 14:10:46.159457 E02318507202008061410z1MnxofUYm8
1.127375602722168
============================
+5561988000007 2020-08-06 14:10:45.162022 2020-08-06 14:10:46.219973 E02318507202008061410iNWaHbm5y2F
1.0579497814178467
============================
+5561988000008 2020-08-06 14:10:45.238775 2020-08-06 14:10:46.274291 E02318507202008061410TiTsWodwaMa
1.0355150699615479
============================
+5561988000009 2020-08-06 14:10:46.162757 2020-08-06 14:10:46.760169 E02318507202008061410WnDi4ZI3Uom
0.5974106788635254
============================
+5561988000011 2020-08-06 14:10:46.277509 2020-08-06 14:10:46.892099 E02318507202008061410M4UyNvVW6GN
0.614588737487793
============================
+5561988000010 2020-08-06 14:10:46.223329 2020-08-06 14:10:46.939309 E02318507202008061410QVedW3q3CWd
0.7159793376922607
============================

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc5/entries/{Key}

**Comment by judahreis** [comment]
@evertongodoi, o DICT está pronto. Para agendar o teste, favor enviar e-mail para dict@bcb.gov.br.

**Comment by luizlaydner** [comment]
@evertongodoi , só complementando... Como é possível fazer requisições concorrentes, o _throughput_ não é determinado pelo inverso da latência. Se a latência for 500ms, por exemplo, não significa que só dá pra fazer 2 req/s, pois é possível fazer várias requisições paralelas.
Sobre a latência observada na sua ponta, alguns valores parecem altos realmente. Uma hipótese a investigar: está reutilizando conexões http? Como é feita autenticação TLS mútua, o overhead de latência para estabelecer uma conexão é grande. É fundamental usar conexões HTTP persistentes. Caso esteja usando java, veja por exemplo [PoolingClientConnectionManager](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/PoolingClientConnectionManager.html).

**Comment by evertongodoi** [comment]
@luizlaydner obrigado pelo retorno!
