### ISSUE TITLE
[Problema] no [DICT] - Erro interno do Servidor ou Timeout

### ISSUE THREAD

**Issue by rsabin** [bacen/pix-perguntas-e-respostas#148]
**Descreva sua dúvida ou problema**
Ao tentar listar os eventos de um CID do meu participante indireto, às vezes dá erro **500** e às vezes dá **timeout** na conexão.

**Sistema ou Área**
DICT

**Identificador do Problema**
CorrelationId 4880541DCF494A9BBF1191DF536E0CA4
Quando tem timeout não retorna nada.
PSP 92702067 - indireto 92934215

**Mensagens Enviadas / Recebidas**
```
<problem xmlns="urn:ietf:rfc:7807">
  <type>https://dict.pi.rsfn.net.br/api/v1/error/InternalServerError</type>
  <title>Internal Server Error</title>
  <status>500</status>
  <detail>Internal server error. Please contact support for details.</detail>
  <correlationId>4880541DCF494A9BBF1191DF536E0CA4</correlationId>
</problem>
```

**URL de conexão**
EndPoint: https://dict-h.pi.rsfn.net.br/api/v1-rc5/cids/events/?Participant=92934215&KeyType=EVP&Limit=200

**Dados adicionais**
A documentação está meio confusa, não sei se está exigindo o PI-RequestingParticipant ou não (tentei dos dois jeitos). Alguns comandos get pedem que seja passado, mesmo com o participante sendo informado também na url. Esse comando específico não exige na documentação, mas tentei igual só pra ver.

**Comment by rsabin** [comment]
Complementando, se eu consultar os eventos de do próprio PSP (participante direto), acontece os mesmos erros.

**Comment by luizlaydner** [comment]
Colocamos um volume de dados maior para teste e essa consulta se revelou problemática. Fizemos e estamos fazendo uns ajustes e otimizações nos índices. Se puder testar novamente, deve estar funcionando adequadamente agora.

**Comment by basmoura** [comment]
Desde sexta-feira está bem lento e instável. Alguma atualização?
