### ISSUE TITLE
[Dúvida] no [SPI] - Retorno múltiplas transações nas PACS (teste de capacidade)

### ISSUE THREAD

**Issue by gstabel** [bacen/pix-perguntas-e-respostas#149]
Prezados.
Estamos realizando testes internos de dimensionamentos de carga da nossa integração com o ICOM. Em especial focando no teste que capacidade que temos agendado.

Em homologação vimos _sempre_ o retorno de mensagens PACS.002 com uma (1) transação por mensagem, mesmo quando enviamos alguns sequencias de pacotes PACS.008 com várias transações.
Dúvida: teremos esse mesmo comportamento no teste de capacidade? Ou a tendência com volume é termos pacotes maiores?

Nossa preocupação, em produção especialmente, é como melhor dimensionar a quantidade de instâncias da nossa aplicação realizando polling (HTTP/GET no /stream), e por consequência sockets que serão abertos com o BACEN.

Estamos querendo definir a melhor estratégia de escalar a aplicação no runtime.

Grato,
Gabriel C. Stabel

**Sistema ou Área**
SPI

**Identificador do Problema**
ISPB: 01181521 (Sicredi)

**Mensagens Enviadas / Recebidas**
Exemplo PACS008 em 06/08/2020 19:08:17
M0118152120200806220817nnz3BTw95
E0118152120200806220805owohASK56,E0118152120200806220808So8HDKuCA,E0118152120200806220809x7kZ8bLwA,E0118152120200806220814Cw9WkkIKl,E0118152120200806220815Q6xszCLLC

**Comment by adilson-silva** [comment]
Este cenário de 1 transação apenas nas mensagens de saída da ICOM deve mudar muito em breve, então o código de leitura das mensagens deve estar preparado para tratar “n” transações em cada PACS conforme XSD das mesmas.

Essa multiplicidade vai estar limitada (conforme comunicado, atualmente são 10 transações) então o tamanho da mensagem não vai ser muito maior, ainda mais estando compactada.

Vale salientar que não existe relação entre a multiplicidade das mensagens que chegam a ICOM com as que saem. Por exemplo, varias pacs008 para um mesmo participante (vindas de participantes diferentes) podem resultar em apenas uma mensagem na saída. 

Vou aproveitar sua pergunta para resumir algumas dicas “gerais” que podem ajudar na otimização: 

- E extremamente importante separar o recebimento das mensagens com seu processamento, que deveria ser sempre assíncrono. 
- Faça uso de múltiplas threads de consumo (atualmente limitadas a 4 por participante). 
- Por outro lado, se o limite de theads for ultrapassado, o participante começa a receber erro 429, o que representa desperdício de recursos nas duas pontas. Se isso estiver acontecendo de forma frequente, diminua o número de threads.
- Certifique-se que esteja aceitando compactação (Accept-Encoding: gzip).
- Habilite o uso de multipart (Accept: multipart/mixed). Em conjunto com a compactação isso traz um bom ganho (a requisição inteira é compactada). Mesmo sem considerar essa compactação, em cenário de alta latência o uso de multipart ajuda muito.
- Procure fechar corretamente cada stream com DELETE (após um tempo x aberto), para evitar receber e ter de tratar mensagens duplicadas.

**Comment by gstabel** [comment]
Obrigado pelo resposta ágil @adilson-silva e as dicas gerais. Vamos avaliar a questão do Accept: multipart/mixed na nossa implementação.

Aproveitando a sua lista de, vou adicionar outras dúvidas.

- Quantos conexões/sockets serão permitidos no envio ao ICOM (POST /msgs) antes de receber um 429? Hoje na maneira que construímos a aplicação chegamos a 10 sockets com alto volume.
- Quanto tempo seria recomendável manter o stream aberto (tempo do GET /start até o DELETE)? Temos esse tempo configurado para 1s hoje, e cogitamos aumentar até 5s (cinco).

Acho que seria interessante esses valores limites do ICOM (número de sockets, tempo de long polling, etc) estarem definidos na documentação (apesar de ser algo mais "vivo") para evitar que os PSPs ultrapassem apenas por suposições incorretas.

Att.
Gabriel

**Comment by adilson-silva** [comment]
- Até 10 sockets (em caso de maior volume) no envio para a ICOM parece ser um bom número. Avalie usar multipart também para enviar, se julgar necessário.

- Sobre o tempo do stream na saída da ICOM, estamos trabalhando atualmente com o cenário de 5 **minutos** até o DELETE. A ideia do long pooling e mesmo manter a conexão aberta por um tempo maior.

Vamos avaliar colocar mais sobre esses limites no manual de interface, mas o problema e que o ciclo de atualização dela é bem diferente.

**Comment by gstabel** [comment]
Obrigado @adilson-silva!

Realmente a parte do tempo do abrir-fechar do stream estávamos supondo algo bem diferente. Consumiríamos "meia dúzia" de mensagens em poucos segundos e já fecharíamos (apenas um parâmetro do nosso lado).
Esse tempo maior de minutos vai economizar muitas requisições de DELETE.

Grato.
Gabriel

**Comment by jgslima** [comment]
Caro Adilson,

> * Sobre o tempo do stream na saída da ICOM, estamos trabalhando atualmente com o cenário de 5 **minutos** até o DELETE. A ideia do long pooling e mesmo manter a conexão aberta por um tempo maior.
> 

Isto não ficou claro. Pelo nosso entendimento da especificação, não haveria este limite de tempo para ter que encerrar o stream. No design do nosso sistema, a aplicação usa os mesmos streams até o encerramento da instância da aplicação.

É obrigatório que o PSP encerre os streams com DELETE após determinado tempo? Qual seria a consequência de não fazer isso?

Obrigado

**Comment by jgslima** [comment]
Marcando @adilson-silva

**Comment by adilson-silva** [comment]
N

> 
> 
> Caro Adilson,
> 
> > * Sobre o tempo do stream na saída da ICOM, estamos trabalhando atualmente com o cenário de 5 **minutos** até o DELETE. A ideia do long pooling e mesmo manter a conexão aberta por um tempo maior.
> 
> Isto não ficou claro. Pelo nosso entendimento da especificação, não haveria este limite de tempo para ter que encerrar o stream. No design do nosso sistema, a aplicação usa os mesmos streams até o encerramento da instância da aplicação.
> 
> É obrigatório que o PSP encerre os streams com DELETE após determinado tempo? Qual seria a consequência de não fazer isso?
> 
> Obrigado

Não é obrigatório e não existe atualmente um tempo limite “hard” para fechamento do stream com DELETE. Mas após um longo período o stream pode ser finalizado pela ICOM.

O tempo de 5 minutos é apenas uma sugestão. De qualquer forma, a aplicação deve estar preparada para iniciar outro stream (com /stream/start) ao tomar algum erro durante um pull-next.

**Comment by adilson-silva** [comment]
Conforme comentado em https://github.com/bacen/pix-perguntas-e-respostas/issues/156, o limite maximo de streams foi aumentado para 6.

**Comment by gstabel** [comment]
Obrigado pela atualização.
