### ISSUE TITLE
Duvida com reivindicação

### ISSUE THREAD

**Issue by mlardone** [bacen/pix-perguntas-e-respostas#150]
**Descreva sua dúvida ou problema**
Quero conhecer se o seguinte entendimento e certo. No escenario de reivindicação onde o cliente que tem que seder a chave não atua:

Dia 1: PSP claimer faz a claim.
Dia 7: PSP donor elimina a chave.
Dia 7: DICT também elimina a chave.
Dia 14: PSP donor confirma a claim com reason DEFAULT_OPERATION.
Dia 14: Com a leitura da confirmação fecha a claim e crea a chave ao claimer.

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
@mlardone, só para deixar mais claro:

Dia 1: PSP claimer faz a claim fazendo push em /claims/
Dia 7: Donor elimina a chave da base local, e invoca push /claims/{id}/confirm, com <Reason>DEFAULT_OPERATION</Reason>. Com isso, o DICT irá remover a chave do Donor, e consultas param de retornar a chave.

Entre o dia 7 e o dia 14 não é necessário o Donor fazer mais nada (exceto se identificar que houve fraude, situação na qual deve invocar /claims/{id}/cancel com <Reason>FRAUD</Reason>). O DONOR nunca completa o claim... quem completa é o CLAIMER. O DONOR somente confirma.
