### ISSUE TITLE
Dúvida no BRCode - Divergência entre tamanhos PACs.0008 e BRCode no Campo TxID

### ISSUE THREAD

**Issue by oximer** [bacen/pix-perguntas-e-respostas#151]
**Descreva sua dúvida ou problema**
Qual é tamanho real do campo TxID no BRCode?

Segundo manual de Iniciação de pagamento [https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/AnexoI-PadroesParaIniciacaodoPix.pdf](url)

QRCode Estático

> 1.4.6. Identificador de transação: txid no QR Code Estático
> O objeto primitivo EMV 62-05 Reference Label, conforme especificado no manual do BR
> Code, é limitado a 25 caracteres e quando em efeito30
> , deve ser utilizado para conciliar pagamentos. Trata-se de um identificador de transação que deve ser
> retransmitido intacto pelo PSP do pagador ao gerar a ordem de pagamento. Esta
> informação permitirá ao recebedor identificar e correlacionar a transferência, quando
> recebida, com a apresentação das instruções ao pagador.

QRCode Dinâmico

> O preenchimento do campo txid é limitado a 35 caracteres, na PACS008. Quanto ao
> seu conteúdo, a maneira específica que será empregada pelo PSP recebedor para
> implementar a funcionalidade de conciliação de pagamentos por meio da utilização
> do txid transcende o escopo da presente especificação. De outra maneira, estando
> habilitado o recebedor a conciliar pagamentos conforme especificados no âmbito do
> PIX, o preenchimento do txid fica a cargo do PSP Recebedor. 

Segundo o Manual do BRCode [https://www.bcb.gov.br/content/estabilidadefinanceira/SiteAssets/Manual%20do%20BR%20Code.pdf](url)

<img width="609" alt="Captura de Tela 2020-08-07 às 10 12 35" src="https://user-images.githubusercontent.com/2430694/89649179-ba450180-d896-11ea-8420-d1d554e029f7.png">

Segundo a PACs.0008 [https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/DefinicoesdetalhadasdasmensagensdoCatalogodeMensagensdoSistemadePagamentosInstantaneos(SPI)-versao1.11.zip](url)

<img width="1396" alt="Captura de Tela 2020-08-07 às 10 15 01" src="https://user-images.githubusercontent.com/2430694/89649290-e3659200-d896-11ea-8721-8c6ff4033746.png">

Assim existe essa disparidade entre o TxID disponíveis via Payload URL (até 35 dígitos) e os embutidos no BRCode (até 25 posições). Correto? 

Se o TxID for estar no QRCode seja dinâmico (fora da URL/chapado no BRCode) e/ou estático ele tem q ter até 25 posições dado a limitação do modelo EMV escolhido.

**Sistema ou Área**
QR Code

**Identificador do Problema**
Documentação

**Mensagens Enviadas / Recebidas**
PACS.008

**URL de conexão**
Não se aplica

**Comment by ninrod** [comment]
@oximer 

O QR Estático contém toda a informação dentro de si, então está 100% preso ao BR Code, que por sua vez é aderente ao padrão EMV que determina que esse campo específico tenha no máximo 25 caracteres. 

O QR Dinâmico, por outro lado, não está preso ao padrão EMV nesse contexto, porque as informações sobre a transação se encontram em um endpoint, ou seja, encontram-se fora do QR Dinâmico. Tudo o que o QR Dinâmico faz é apontar para esse endpoint. Contudo, a PACS008 apresenta uma restrição de 35 caracteres para o campo txid, determinação vinda da ISO 20.022. 

Diante disso, você tem um cenário em que realmente o QR Dinâmico tem acesso a esse limite de 35 (via ISO 20.022) caracteres enquanto o QR Estático está preso a esse limite inferior, de no máximo 25 caracteres (limite imposto pelo EMV para QR Codes).
