### ISSUE TITLE
Dúvida no DICT - Operação padrão na reivindicação

### ISSUE THREAD

**Issue by mpostemsky** [bacen/pix-perguntas-e-respostas#153]
Bom Dia,
qual seria a operação padrão do reinvidicador PSP se o usuário, após o PSP doador confirmar uma reinvidicação de posse, não executar a validação ativa para concluir a reinvidicação?

Em seguida, defino o estágio em que vemos essa possível inação:

1. PSP_reiv cria a reivindicação
2. PSP_donor confirma a reivindicação (DEFAULT_OPERATION ou USER_REQUESTED)
3. PSP_reiv recebe confirmação e, uma vez concluído o CompletionPeriodEnd, notifica o usuário de que ele deve executar a validação ativa para concluir a reivindicação.
4. O usuário reinvindicador não executa a validação ativa e o CompletionPeriodEnd já foi cumprido.

**Questões:**

* No caso de o usuário reivindicador não executar a validação ativa depois que o tempo X passar. Qual deve ser a ação a seguir do PSP reivindicador? Devemos continuar esperando? Devemos cancelar a reivindicação?

* No caso de uma resposta de DEFAULT_OPERATION do PSP doador, em que o CompletionPeriodEnd não é modificado. O PSP reivindicador pode solicitar ao usuário que valide ativamente a chave sem que o CompletionPeriodEnd não passe?

**Comment by gizelysc** [comment]
Boa tarde, 
Há uma previsão de retorno desses questionamentos?  Estou com essa mesma dúvida, sobre como atuar nesses casos.

**Comment by CharlesMendes** [comment]
O CompletionPeriodEnd leva em consideração o horário? Ou seja, reivindicador fez Open às 15h30 do dia 1, ao iniciar contagem dos 14 dias, no 14° dia é considerado término até 15h30 ou até final da janela Dict 20h?

**Comment by luizlaydner** [comment]
@mpostemsky @gizelysc Favor verificar a última versão do [manual operacional do DICT](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/X_ManualOperacionaldoDICT-versao1-1.pdf). Houve alterações na seção 6.

> previsão de que o PSP reivindicador deve cancelar o processo de reivindicação no DICT caso seu usuário não faça a validação ativa da chave até o trigésimo dia após o início do processo de reivindicação.

@CharlesMendes  `CompletionPeriodEnd` é uma data-hora, não é apenas data.
