### ISSUE TITLE
[Dúvida] no [DICT] - ANS do fluxo de disputa

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#154]
**Descreva sua dúvida ou problema**

Olá! Vocês já possuem os ANS para as operações do fluxo de disputa?

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
@monise, já está definido no Manual de Tempos na  [página do Pix](https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos) (lembrando que Disputa virou Infração)
