### ISSUE TITLE
[Problema] no [DICT / ARQ] - PKIX path building failed

### ISSUE THREAD

**Issue by rsabin** [bacen/pix-perguntas-e-respostas#155]
**Descreva sua dúvida ou problema**
Hoje estávamos recebendo o seguinte erro: PKIX path building failed: unable to find valid certification path to requested target.
O erro acontecia mais no endpoint do dict e de arquivos. A icom de mensagens estava sempre ok.

**Sistema ou Área**
DICT e ARQUIVOS

**Identificador do Problema**
Quando tentávamos um acesso na interface do dict (https://dict-h.pi.rsfn.net.br) ou de arquivos (https://arq-h.pi.rsfn.net.br) volta e meia recebíamos o erro descrito acima, como se não fosse possível concluir o handshake tls.
A interface da icom funcionava normal. O certificado e a cadeia é o mesmo utilizado nos três endpoints.

**URL de conexão**
https://arq-h.pi.rsfn.net.br/api/v1/download/92702067/extrato/F9DBF66F61AFB9BF5833CB7CF6ACB4CA8D3A18625B92C81ADCDB137F4BCD5FF4.zip

**Dados adicionais**
Data e hora que aconteceu: 07/08/2020 15:40:35.333
Segundo nossa infra, poderia ser algum balanceamento de carga nos servidores do PSI onde um dos certificados estava faltando ou corrompido. 
Como o erro acontece uma vez sim e outra vez não, a suposição é válida.
Teriam alguma pista?

**Comment by luizlaydner** [comment]
Seria possível que em alguns servidores seus vocês não tenham certificados da AC do ICP-Brasil instalados ?
O LB dos serviços não envia no handshake TLS o certificado raiz. Ele precisa estar instalado na máquina que faz a conexão.
Não recebemos relato similar de nenhum outro PSP.
