### ISSUE TITLE
[Dúvida] no [ICOM] - Teste de Capacidade

### ISSUE THREAD

**Issue by guimapalmeira** [bacen/pix-perguntas-e-respostas#156]
**Descreva sua dúvida ou problema**
Olá,
Gostaria de esclarecer algumas dúvidas em relação ao teste de capacidadade.

**Sistema ou Área**
SPI

**Identificador do Problema**
1. Qual o máximo de conexões/threads simultâneas estão liberadas para realizar o long polling(Leitura da das msgs GET /api/v1/out/{ispb}/stream)?

2. As transações dentro das mensagens de recepção chegarão em lote(máx 10) ou de 1 em 1? Isso faz total diferença em relação ao _throughput_ total. (No primeiro teste que fizemos, recebemos tudo 1..1) 
Ex. Vazão de recebimento cai de 2000 por min, pra 200 por min. (no caso, isso x2, já que cada recebimento 008 devolvemos 002 e depois recebemos mais um 002 de ACCC.)

3. O uso do endpoint de DELETE stream, só evita duplicidade se no proximo pull, enviarmos o mesmo hash de stream, correto? Se for sequencial e seguir o fluxo correto as mensagens não duplicam!?

4. O objetivo do teste é, X **mensagens** por minuto ou X **pagamentos/transferências** por minuto, porque precisamos levar isso em consideração também para o throughtput de liquidação, devido ao lote.

Obrigado.
Att,
Guilherme Palmeira.

**Comment by adilson-silva** [comment]
> 
> 
> **Descreva sua dúvida ou problema**
> Olá,
> Gostaria de esclarecer algumas dúvidas em relação ao teste de capacidadade.
> 
> **Sistema ou Área**
> SPI
> 
> **Identificador do Problema**
> 
>     1. Qual o máximo de conexões/threads simultâneas estão liberadas para realizar o long polling(Leitura da das msgs GET /api/v1/out/{ispb}/stream)?
> 

Atualmente 4.

>     2. As transações dentro das mensagens de recepção chegarão em lote(máx 10) ou de 1 em 1? Isso faz total diferença em relação ao _throughput_ total. (No primeiro teste que fizemos, recebemos tudo 1..1)
>        Ex. Vazão de recebimento cai de 2000 por min, pra 200 por min. (no caso, isso x2, já que cada recebimento 008 devolvemos 002 e depois recebemos mais um 002 de ACCC.)
> 

Por enquanto apenas 1 por mensagem, mas isso deve mudar em breve. Reforçando que todos participantes devem estar preparados para receber várias operações em cada mensagem.

Sobre otimizacao do throughput, ver também a resposta em  https://github.com/bacen/pix-perguntas-e-respostas/issues/149 


>     3. O uso do endpoint de DELETE stream, só evita duplicidade se no proximo pull, enviarmos o mesmo hash de stream, correto? Se for sequencial e seguir o fluxo correto as mensagens não duplicam!?
> 

Ao usar o DELETE o stream e finalizado na ICOM. Você deve iniciar outro com /stream/start

>     4. O objetivo do teste é, X **mensagens** por minuto ou X **pagamentos/transferências** por minuto, porque precisamos levar isso em consideração também para o throughtput de liquidação, devido ao lote.
> 

**pagamentos/transferências** (operações) por minuto 

> 
> Obrigado.
> Att,
> Guilherme Palmeira.

**Comment by guimapalmeira** [comment]
> > **Descreva sua dúvida ou problema**
> > Olá,
> > Gostaria de esclarecer algumas dúvidas em relação ao teste de capacidadade.
> > **Sistema ou Área**
> > SPI
> > **Identificador do Problema**
> > ```
> > 1. Qual o máximo de conexões/threads simultâneas estão liberadas para realizar o long polling(Leitura da das msgs GET /api/v1/out/{ispb}/stream)?
> > ```
> 

**> Atualmente 4.**

_Pensam em aumentar esse número ainda pro teste de carga?_
> 
> > ```
> > 2. As transações dentro das mensagens de recepção chegarão em lote(máx 10) ou de 1 em 1? Isso faz total diferença em relação ao _throughput_ total. (No primeiro teste que fizemos, recebemos tudo 1..1)
> >    Ex. Vazão de recebimento cai de 2000 por min, pra 200 por min. (no caso, isso x2, já que cada recebimento 008 devolvemos 002 e depois recebemos mais um 002 de ACCC.)
> > ```

**> Por enquanto apenas 1 por mensagem, mas isso deve mudar em breve. Reforçando que todos participantes devem estar preparados para receber várias operações em cada mensagem.**
_Essa nova versão ainda será disponibilizada durante o teste de capacidade? 
Vale a pena aguardar? 
Vão comunicar? 
Porque recebendo em lote pode dimunuir a vazao de recebimento em até 10x._
> 

**> Sobre otimizacao do throughput, ver também a resposta em #149**
_Ah sim, eu já havia visto, mas ainda me ficou  algumas dúvidas, obrigado._
> 
> > ```
> > 3. O uso do endpoint de DELETE stream, só evita duplicidade se no proximo pull, enviarmos o mesmo hash de stream, correto? Se for sequencial e seguir o fluxo correto as mensagens não duplicam!?
> > ```
> 
**> Ao usar o DELETE o stream e finalizado na ICOM. Você deve iniciar outro com /stream/start**
_Entendi, mas você enxerga algum ganho, em relação a duplicidade mesmo garantindo a ordem correta dos pollings?_
_Vi em outro posto também a sugestão de fechar a carda 5minutos, correto?_
> 
> > ```
> > ```
> > 4. O objetivo do teste é, X **mensagens** por minuto ou X **pagamentos/transferências** por minuto, porque precisamos levar isso em consideração também para o throughtput de liquidação, devido ao lote.
> > ```
> 
**> pagamentos/transferências** (operações) por minuto
_Ok, muito bom saber disso._


Muito Obrigado pelos esclarecimentos,
Att,
Guilherme Palmeira.

**Comment by adilson-silva** [comment]
> 
> _Pensam em aumentar esse número ainda pro teste de carga?_
> 

Vamos aumentar para 6 em breve.

> _Essa nova versão ainda será disponibilizada durante o teste de capacidade? Vale a pena aguardar? Vão comunicar? Porque recebendo em lote pode dimunuir a vazao de recebimento em até 10x._
>

No momento não temos como dar um prazo essa questão da multiplicidade de pagamentos por mensagem.  Mas iremos comunicar sim.  Independente disso, como disse no outra issue, avalie usar também o recurso de “multipart”. 

> _Entendi, mas você enxerga algum ganho, em relação a duplicidade mesmo garantindo a ordem correta dos pollings?_
> _Vi em outro posto também a sugestão de fechar a carda 5minutos, correto?_
>

Sobre o DELETE, o tempo de 5 minutos é como estamos trabalhando em nossos testes internos.  Desde que se siga corretamente os "pulll-next" e não esteja tomando erro, o stream poderia ficar aberto por um tempo maior (ou mesmo “indefinidamente”).

**Comment by adilson-silva** [comment]
O limite máximo de streams na saída da ICOM foi aumentado para 6 nesta manha.

**Comment by guimapalmeira** [comment]
Opa, 
boa notícia @adilson-silva, muito obrigado pelo feedback.

**Comment by jgslima** [comment]
> O limite máximo de streams na saída da ICOM foi aumentado para 6 nesta manha.

Prezado @adilson-silva 

Não estava claro para nós que havia este limite. Você poderia explicar um pouco melhor como ele funciona?

Os PSPs realmente não podem abrir mais de 6 streams? Há alguma consequência em se fazer isso?

Inclusive, temos nossas dúvidas da real viabilidade de atender os 200ms para retirar mensagens disponíveis durante os testes de carga com a limitação de 6 streams.

Obrigado

**Comment by adilson-silva** [comment]
Se o número de streams fosse ilimitado, ao abrir um número excessivo de threads um PSP poderia interferir (ou mesmo impedir) o consumo de outros PSPs.

Ao tentar abrir mais streams simultâneos do que o máximo o PSP começa a tomar 429, conforme descrito no manual de interface (e em comunicado recente, além dos comentários em https://github.com/bacen/pix-perguntas-e-respostas/issues/149)

Com o uso dos recursos disponíveis (por exemplo, multipart e tratamento assíncrono das mensagens) é viável o atendimento ao SLA proposto.
