### ISSUE TITLE
[Problema] no [SPI] - BookingDate do arquivo de lançamentos / extrato (camt.052)

### ISSUE THREAD

**Issue by rsabin** [bacen/pix-perguntas-e-respostas#157]
**Descreva sua dúvida ou problema**
No arquivo de lançamentos (solicitado pela camt.060 e respondido na camt.052) a coluna BookingDate está vindo em formato ISO8601, com fuso horário "Z" (-00:00). É aquele velho problema, do jeito que está informado dá-se a entender que devemos aplicar a fórmula para obter a data/hora local fazendo com que retroceda um dia.

**Sistema ou Área**
SPI, Arquivo de Estrato

**Identificador do Problema**
BookingDate = "2020-08-07T00:00:00.000Z" que convertido para hora local é "06/08/2020 21:00:00".

**Dados adicionais**
O campo deve vir com formato apenas de data ("2020-08-07") ou então deve ser aplicada a fórmula correta para gerar a data em formato ISO8601 ("2020-08-07T03:00:00.000Z").
Outra opção obviamente é estabelecer que para este campo específico não se deve aplicar conversão de fuso horário, embora fique despadronizado.

**Comment by rafael-omello** [comment]
Dúvidas de negócio devem ser enviadas para spi@bcb.gov.br.
