### ISSUE TITLE
[Problema] no [DICT] - InternalServerError ao  Criar Vínculo e Criar Reivindicação

### ISSUE THREAD

**Issue by fbjhon** [bacen/pix-perguntas-e-respostas#158]
**Descreva sua dúvida ou problema:**
A partir de hoje passou a retornar erro 500 InternalServerError ao incluir Vínculo ou reivindicação na versão rc5

**Sistema ou Área:**
DICT

**Identificador do Problema:**
Correlation-Id 629475D485B24658BD62E0151BBBF811 executado às 16:54

**Mensagens Enviadas / Recebidas**
<problem xmlns="urn:ietf:rfc:7807">
  <type>https://dict.pi.rsfn.net.br/api/v1/error/InternalServerError</type>
  <title>Internal Server Error</title>
  <status>500</status>
  <detail>Internal server error. Please contact support for details.</detail>
  <correlationId>629475D485B24658BD62E0151BBBF811</correlationId>
</problem>

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc5/claims/

**Comment by HenriqueSimoes82** [comment]
@fbjhon existe algum caractere UTF-8 inválido no request. Revise e reenvie a requisição.
