### ISSUE TITLE
[Dúvida] no [SPI] - Data utilizada para geração do arquivo de extrato

### ISSUE THREAD

**Issue by rsabin** [bacen/pix-perguntas-e-respostas#159]
**Descreva sua dúvida ou problema**
Recebi um pagamento no SPI no dia **10/08/2020** perto das **23h** da noite.
No outro dia, solicitei um extrato completo do dia anterior (de 00:00 - 23:59) e esse movimento não foi listado no arquivo.
Ele só é listado no arquivo do dia **11/08/2020**.

**Sistema ou Área**
 SPI

**Identificador do Problema**
EndToEndId: `E7102786620200810230237867344686`
BookingDate: `2020-08-10`
ValueDate: `2020-08-11T02:02:44.653Z`  (10/08 as 23:44)
AcceptanceDateTime: `2020-08-11T02:02:34.703Z` (10/08 as 23:34)

**Dados adicionais**
Esse movimento deveria ser listado no arquivo de extrato do dia 10/08/2020, pois foi quando ele aconteceu. Todos os campos de data da mensagem apontam para o dia 10 (após conversão de fuso).

**Comment by rafael-omello** [comment]
Dúvidas de negócio devem ser enviadas para spi@bcb.gov.br.
