### ISSUE TITLE
Dúvida no DICT - Dúvida quanto ao momento de cadastro de uma chave vinculada a uma reivindicação de posse/portabilidade

### ISSUE THREAD

**Issue by Leonardo34** [bacen/pix-perguntas-e-respostas#16]
## **Descreva sua dúvida ou problema**
Gostaria de saber o exato momento onde a chave vinculada a uma reivindicação de posse ou portabilidade deve ser cadastrada na base do participante. Estou em dúvida se isto deve ser persistido no momento que recebo a confirmação por parte do doador (via endpoint de listagem de claims -> https://dict-h.pi.rsfn.net.br/api/v1/claims/), ou apenas após ter efetuado a conclusão. 

Meu entendimento do fluxo é o seguinte, gostaria apenas de validar pois a documentação me deixou algumas dúvidas.

1. Cadastro uma reivindicação
2. Doador recebe reivindicação, efetua o acknowledge e em seguida confirma a reivindicação.
3. Recebo via API de listagem de claims (https://dict-h.pi.rsfn.net.br/api/v1/claims/) a atualização da claim com status CONFIRMED, e cadastro então a partir dos dados da claim a chave na minha base interna. Neste ponto já temos a chave cadastrada para posso do reivindicador no bacen ?
4. Após a chave devidamente cadastrada na minha base de dados e na do BCB devo efetuar o complete da reivindicação (https://dict-h.pi.rsfn.net.br/api/v1/claims/{ClaimId}/complete).

Meu entendimento está correto ? Saliento a dúvida do item 3, onde após o doador efetuar a confirmação de uma chave, a mesma já é cadastrada sob posse do reivindicador no base do BCB ?

**Comment by judahreis** [comment]
Leonardo,

A partir do status CONFIRMED da claim, o vínculo antigo da chave deixa de existir no PSP doador e no DICT, mas ainda não está associada ao reivindicador. Nesse momento, sugerimos que o PSP reivindicador coloque a chave em situação intermediária nos seus sistemas, algo como "ATIVAÇÃO_PENDENTE_DICT", e envie o a mensagem de "complete" para o DICT. Na resposta com sucesso do DICT, o reivindicador pode colocar a chave como "ATIVA" em sua base. Não é necessário fazer mais nada no DICT. O próprio "complete" que fecha a reivindicação também realiza a ativação da chave no DICT.

**Comment by Leonardo34** [comment]
Perfeito @judahreis, fiquei apenas como uma dúvida quanto ao flow. Quando uma chave está com o status como você comentou "ATIVAÇÃO_PENDENTE_DICT", ela é considerada no fluxo de reconciliação ? Devo considerá-la para o calculo do v_sync ?

**Comment by judahreis** [comment]
Não. Entre o Confirmada e o Completada (quando ela estará PENDENTE_DICT) a chave não está ativa no DICT e portanto não fará parte do arquivo de reconciliação. Tampouco o participante deve devolver a chave nas consultas internas. A chave só deve ser ativada de fato após o retorno com sucesso do COMPLETE pelo DICT. A partir desse ponto também estará presente o seu CID no arquivo de reconciliação.
