### ISSUE TITLE
Problema no DICT - Erro 400 Listar Disputas

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#160]
**Descreva sua dúvida ou problema**
Estamos realizando a chamada Dict Listar Disputas v1-rc5, porem estamos recebendo o erro status: 400 - detail: No message available.

**Sistema ou Área**
DICT

**Identificador do Problema**
Correlation-Id: 9C78F12B5C394F02964FA4C687ED7B9A

**Mensagens Enviadas / Recebidas**
<problem xmlns="urn:ietf:rfc:7807"><type>https://dict.pi.rsfn.net.br/api/v1/error/BadRequest</type><title>Bad Request</title><status>400</status><detail>No message available</detail><correlationId>9C78F12B5C394F02964FA4C687ED7B9A</correlationId></problem>

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc5/disputes/?Participant=02318507&IsPayer=&IsDisputed=&Status=&IncludeDetails=&ModifiedAfter=&ModifiedBefore=&Limit=200

**Comment by luizlaydner** [comment]
Prezado @evertongodoi, o serviço da API de disputas não foi liberado para teste ainda.
