### ISSUE TITLE
[Dúvida] no [DICT] - Request Id no processo de reconciliacão

### ISSUE THREAD

**Issue by alexandrepkill** [bacen/pix-perguntas-e-respostas#163]
**Descreva sua dúvida ou problema**
No processo de reconciliação eu devo criar chaves que por ventura não tenham sido criados no DICT local. Para isso eu baixo minha lista de CIDs de acordo com o arquivo no endpoint /cids/files/{Id}. Para cada um deles, caso não exista no meu banco, eu devo chamar o endpoint /cids/entries/{Cid}. No processo de inclusão eu devo calcular o cid para inserir no banco e nessa inclusão o cálculo do que veio do Bacen com o local deve coincidir. Daí vem a pergunta: como eu vou conseguir calcular o cid local e checar se eles batem se na resposta do endpoint /cids/entries/{Cid} não vem o requestId que é utilizado no cálculo do cid ?

**Comment by luizlaydner** [comment]
Nesse cenário, você deve excluir o vínculo (deleteEntry) com campo `Reason` igual a `RECONCILIATION` e em seguida criar novamente o vínculo (createEntry) com campo `Reason` também com `RECONCILIATION`. 
Na criação do vínculo, você passará um novo `RequestId`, podendo então calcular o CID .

**Comment by alexandrepkill** [comment]
Tudo bem. Mas podem existir casos que existam reivindicações criadas. O que favor nesse cenário?
