### ISSUE TITLE
[Dúvida] no [DICT] - Fluxo notificação de infração

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#164]
**Descreva sua dúvida ou problema**

Olá! Gostaria de tirar algumas dúvidas sobre o fluxo de disputa.

1 - Conforme foi divulgado no regulamento do PIX, o fluxo de disputa (iniciado pelo pagador) foi removido, correto? 

2 - Foi incluído a funcionalidade de notificação de infração, que pela documentação do DICT "X_ManualOperacionaldoDICT-versao1-1.pdf", fará uso das APIs de disputa do DICT, é isso mesmo?
 
3 - As APIs de disputa atualmente disponibilizadas no DICT serão alteradas? Por exemplo, para um fluxo de notificação de infração, é necessário passar o valor da transação?
 
4 - A data de homologação da funcionalidade de disputa era de 01/09 a 30/09. Qual será a data de homologação do fluxo de notificação de infração?
 
**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
@monise, 

1. Sim, Disputas foram removidas. Agora o nome do resource será InfractionReport. 

2. O fluxo de InfractionReport será semelhante ao de Disputes, ou seja, um psp cria, outro dá ack e, posteriormente, completa concordando ou discordando do relato.

3. Não haverá valor da transação. O resource ficou mais simples. Vamos enviar as alterações amanhã, junto com algumas adaptações e correções de bug em uma prévia da API v1.0-RC6.

4. Inicialmente, vamos manter as datas, visto que a abertura do DICT está prevista para 05/10, e será necessário concluir todas as etapas de homologação antes disso.

Qualquer dúvida adicional, estamos à disposição. Grato pelas revisões e questionamentos, sempre relevantes.

**Comment by monise** [comment]
@judahreis Boa tarde!! Vocês tem a data de quando será liberada a RC6 com as novas assinaturas para o fluxo notificação de infração?

**Comment by judahreis** [comment]
Vamos lançar a prévia da API amanhã, e a publicação no ambiente no dia 25.

**Comment by judahreis** [comment]
@monise, já disponível no ambiente de homologa.
