### ISSUE TITLE
[Dúvida] no [DICT] - Request Id no processo de reconciliacão (caso tenha reivindicação)

### ISSUE THREAD

**Issue by alexandrepkill** [bacen/pix-perguntas-e-respostas#165]
**Descreva sua dúvida ou problema**
Eu tinha aberto uma dúvida que dizia isso abaixo (https://github.com/bacen/pix-perguntas-e-respostas/issues/163)
"No processo de reconciliação eu devo criar chaves que por ventura não tenham sido criados no DICT local. Para isso eu baixo minha lista de CIDs de acordo com o arquivo no endpoint /cids/files/{Id}. Para cada um deles, caso não exista no meu banco, eu devo chamar o endpoint /cids/entries/{Cid}. No processo de inclusão eu devo calcular o cid para inserir no banco e nessa inclusão o cálculo do que veio do Bacen com o local deve coincidir. Daí vem a pergunta: como eu vou conseguir calcular o cid local e checar se eles batem se na resposta do endpoint /cids/entries/{Cid} não vem o requestId que é utilizado no cálculo do cid ?"

Resposta:
"Nesse cenário, você pode excluir o vínculo (deleteEntry) com campo Reason igual a RECONCILIATION e em seguida criar novamente o vínculo (createEntry) com campo Reason também com RECONCILIATION.
Na criação do vínculo, você passará um novo RequestId, podendo então calcular o CID ."

No que eu ainda tenho uma dúvida: No caso de existirem reivindicações, eu não vou conseguir conseguir excluir a chave. O que fazer nesse caso ?

**Comment by luizlaydner** [comment]
@alexandrepkill Vamos avaliar adicionar na API o `RequestId` na resposta da operação getEntryByCid .
Me parece que isso resolveria a situação que você descreveu, correto?

**Comment by alexandrepkill** [comment]
Sim.. Resolveria.

**Comment by kertony** [comment]
Entendo que a recomendação e solução acima não resolvem o caso:
1 - O RequestId está retornando null do DICT. 
2 - A solução de excluir e incluir novamente a chave não me parece sustentável, pois, no caso da chave Aleatória (EVP), vai trocar o código da chave?
3 - A reconciliação acontece fora da janela do DICT, logo, não conseguirei excluir e incluir a chave quando estiver no definitivo.
4 - Após confirmar a disponibilização, em alguns casos o download do arquivo de CIDs retorna erro notfound, logo em seguida conseguimos baixar.
5 - A data para conclusão do teste homologatório está bem em cima: 31/08.

**Comment by luizlaydner** [comment]
Antes de tudo, é importante entender que o processo de reconciliação como desenhado visa a correção de diferenças pontuais nos dados. Não se deve considerar o DICT como um "backup" dos dados. O cenário descrito originalmente na issue, a meu ver, poderia também ser corrigido mantendo-se um log no banco de dados do PSP de todas as operações feitas, incluindo-se aí o RequestId usado.

> Entendo que a recomendação e solução acima não resolvem o caso:
> 1 - O RequestId está retornando null do DICT.

Falha nossa aqui, vamos corrigir.

> 2 - A solução de excluir e incluir novamente a chave não me parece sustentável, pois, no caso da chave Aleatória (EVP), vai trocar o código da chave?

Sim, é verdade... por isso adicionamos o `RequestId` no getEntryByCid. 

> 3 - A reconciliação acontece fora da janela do DICT, logo, não conseguirei excluir e incluir a chave quando estiver no definitivo.

A janela de reconciliação estava prevista inicialmente, nas primeiras iterações do desenho. Não existe mais janela para fazer a reconciliação. Atendendo ao que está definido na SLA, o participante tem autonomia para fazer operações de reconciliação quando bem entender.

> 4 - Após confirmar a disponibilização, em alguns casos o download do arquivo de CIDs retorna erro notfound, logo em seguida conseguimos baixar.

Vamos investigar. O DICT não deveria retornar que o arquivo está disponível se ele não está de fato. Pode ser relacionado ao tempo que leva para replicar uma cópia do arquivo. 

> 5 - A data para conclusão do teste homologatório está bem em cima: 31/08.

Essa data é apenas uma referência que o BC usa para acompanhar os participantes que tem obrigação de implementar o DICT. Não é um prazo rígido para o processo de homologação. Sabemos que os prazos estão comprimidos. Está sendo para nós aqui um desafio bem grande também!

**Comment by judahreis** [comment]
Reabrindo para acompanhar a publicação do bug (não retorna requestId)

**Comment by kertony** [comment]
Boa tarde,

Obrigado pelo retorno.

Estamos no aguardo da correção. Estamos mantendo nosso objetivo de concluir este teste no prazo.

**Comment by luizlaydner** [comment]
> Reabrindo para acompanhar a publicação do bug (não retorna requestId)

Corrigido faz algum tempo.
