### ISSUE TITLE
[Dúvida] no [DICT] - Teste de Capacidade/Consulta Chaves DICT

### ISSUE THREAD

**Issue by guimapalmeira** [bacen/pix-perguntas-e-respostas#166]
**Descreva sua dúvida ou problema**
Olá, tenho uma dúvida em relação ao teste de consulta do DICT.
Na circular descreve, 
**"Consultar 2000 chaves diferentes por minuto durante 10 minutos"**

_Considerando o cenário que pode fazer cache de chaves consultadas, teremos que consultar 20.000 chaves diferentes durante os 10 minutos ou podemos consultar as mesmas 2000 nesse intervalo, repetindo-as._

Obrigado,
Guilherme Palmeira.

**Comment by luizlaydner** [comment]
Para o teste de capacidade, ideal é não ter hits no cache. 
Cache foi definido principalmente para lidar com cenários de pico (ex: evento na TV pedindo doações via QR-Code).
Portanto, sua proposta de consultar de 20k chaves diferentes no intervalo de 10minutos atende melhor ao propósito do teste de capacidade.
