### ISSUE TITLE
Dúvida no DICT - Tipos de contas transacionais para portabilidade

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#167]
**Descreva sua dúvida ou problema**
Os mecanismos de portabilidade criados e existentes no DICT são aplicáveis também para as contas transacionais do tipo Conta Salario ?

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
Pro DICT, não há diferença entre os tipos de conta. É guardado no DICT pois é informação necessária para a criação da mensagem pacs008, enviada pro SPI.
Você enxerga alguma preocupação específica que acha que devíamos ter com relação a esse tipo de conta?

**Comment by evertongodoi** [comment]
@luizlaydner obrigado pelo retorno, estávamos analisando o caso da portabilidade de conta salário, mas creio que não haverá problemas no DICT, mas sempre será um procedimento duplo, o cliente vai ter que requerer a portabilidade da conta salario seguindo o regulatório atual com o modelo e janela de processamento, para só depois fazer o processo de migração do DICT.
