### ISSUE TITLE
[Dúvida] no [BRCode] - Validador

### ISSUE THREAD

**Issue by oximer** [bacen/pix-perguntas-e-respostas#168]
**Descreva sua dúvida ou problema**

O Bacen vê na criação de um projeto open-source para validar os BRCode utilizados no SPB e consequentemente no PIX?

Acredito que como comunidade poderíamos criar um projeto que o qualquer empresa pudesse submeter seus QRCode ao programa e validar se ele é valido.

Antes de iniciar esse desenvolvimento, gostaria de pegar informação se o BACEN entende isso valido e/ou já tem tratado em algo nesse sentido?

Importante entender que o BRCode suporte múltiplos arranjos assim esse validar deveria ser capaz de validar isso.

**Sistema ou Área**
QR Code

**Identificador do Problema**
BRCode não válido e/ou não interoperáveis entre bancos.

**Comment by ninrod** [comment]
@oximer , é uma ideia interessante, obrigado. Vou levar para o time.

**Comment by ninrod** [comment]
@oximer , 

Nada impede a comunidade de desenvolver esse tipo de programa, no caso, um app que valide um BR Code. 

Não consta, no momento, nos planos do BACEN, disponibilizar para o mercado um app que apresente tal função. 

Acho interessante sua iniciativa e realmente tem um potencial de valor.

**Comment by fbbergamo** [comment]
Fiz um gerador de BRCODE e tb gostaria de conseguir validar, segui a documentação 2.0.0 

https://github.com/fbbergamo/gerador-pix -- https://www.gerarpix.com.br/
