### ISSUE TITLE
[Dúvida] no [DICT] - Listar Eventos de CIDs

### ISSUE THREAD

**Issue by idutra** [bacen/pix-perguntas-e-respostas#169]
**Descreva sua dúvida ou problema**
Na documentação da API para Listar Eventos de CIDs, temos os seguintes Query Parameters:
- Participant (obrigatório)
- KeyType (obrigatório)
- StartTime (opcional)
- EndTime (opcional)
- Limit (opcional)

Levando em condieração que os campos `StartTime`, `EndTime` e `Limit` são opcionais, caso não sejam informados, como a DICT irá tratar essa informação? qual o valor default caso eles não sejam informados?

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
`Limit` tem valor padrão de 20. Caso `StartTime` ou `EndTime` não sejam informados, eventos serão retornados ordenados por `LastModified`
