### ISSUE TITLE
Dúvida no DICT - Listar Reivindicações

### ISSUE THREAD

**Issue by fCamargosRibeiro** [bacen/pix-perguntas-e-respostas#17]
As dúvidas sobre o uso das apis de reivindicação são as seguintes:
**No serviço de Listar Reivindicações existe um campo dentre os QUERY PARAMETERS Limit, na documentação não está especificado qual o Limit máximo que pode ser passado nesse parâmetro e se ele é obrigatório, também no retorno não está especificado se ao estabelecer um Limit e tiver mais dados que o Limit, como vou saber se consultei todos os dados, essa preocupação se refere principalmente nas reivindicações oriundas de outras IFs. 
**Também existe a dúvida sobre o rate limiting dessa API.
**Também vimos que na documentação é passado para algumas consultas serem realizadas a cada minuto, mas isso está de forma segregada por status, seria um problema fazer uma consulta mais global a cada minuto? Isso está a cargado da nossa equipe de desenvolvimento decidir, ou no caso seria melhor fazer várias consultas segregadas pro tipo e status.

**Comment by luizlaydner** [comment]
Para a operação listClaims, o parâmetro `Limit` não é obrigatório. Caso não seja passado, seu valor padrão é 20. O valor máximo é 200. Vamos refletir isso na documentação da API.
Sobre o indicador de que existem mais reivindicações para consultar, ele atualmente não existe. Mas é uma boa sugestão!

Quando não houvesse mais reivindicações para iterar, ficaria algo como:
```xml
<ListClaimsResponse>
    <Signature></Signature>
    <IsLast>true</IsLast>
    <Claims>...</Claims>
</ListClaimsResponse>
```

Vamos avaliar e ver se incluímos ele na próxima release da API, ok ?

Sobre _rate-limiting_ , haverá limite, mas ainda não temos os parâmetros definidos. O intuito da limitação será manter a estabilidade do sistema, permitindo que os níveis de serviço dos PSPs sejam cumpridos. Assim que tivermos esses limites definidos, os divulgaremos.

Sobre a forma de realizar as consultas, não é problema fazer consulta mais global. Única ressalva é que vamos ainda colocar uma restrição adicional, exigindo que se escolha o papel do participante (doador ou reivindicado), por razões de desempenho.

**Comment by luizlaydner** [comment]
@fCamargosRibeiro Foi adicionado campo [HasMoreElements](https://github.com/bacen/pix-dict-api/blob/b7710e5856014e5a4ac93eff110b7102cae6c411/openapi/schemas.yaml#L817) na versão v1.0.0-RC5. Deverá estar disponível em homologação ao final do dia.
