### ISSUE TITLE
[Dúvida] no [DICT] - Previsão do enhancement (issue #165)

### ISSUE THREAD

**Issue by alexandrepkill** [bacen/pix-perguntas-e-respostas#170]
**Descreva sua dúvida ou problema**
Tem alguma previsão para o enhancement https://github.com/bacen/pix-perguntas-e-respostas/issues/165 relativo ao sincronismo? Estou preocupado com isso pois o marco homologatório é em 31/08/2020. Isso impacta diretamente o planejamento da próxima sprint.

**Comment by judahreis** [comment]
@alexandrepkill, estamos prevendo a publicação da RC6 para o dia  21/08. Essa modificação estará contemplada lá.
