### ISSUE TITLE
[Dúvida] no [DICT] - Elementos são ordenados?

### ISSUE THREAD

**Issue by pedrolamarao** [bacen/pix-perguntas-e-respostas#171]
**Descreva sua dúvida ou problema**
O XML do DICT tem seus elementos em ordem (i.e. exatamente na sequência especificada) ou sem ordem (i.e. podendo aparecer em qualquer ordem)?
Entendemos que a especificação do DICT é uma aplicação de OpenAPI.
Procuramos na documentação do OpenAPI por este esclarecimento e não encontramos.
Abaixo exemplificamos a questão.
Ambos os exemplos são legítimos?

**Sistema ou Área**
DICT.

**Dados adicionais**
Exemplo na mesma ordem da especificação:

```
<Owner>
	<Type>NATURAL_PERSON</Type>
	<TaxIdNumber>11122233300</TaxIdNumber>
	<Name>João Silva</Name>
</Owner>
```

Exemplo em ordem diferente da especificação:

```
<Owner>
	<Name>João Silva</Name>
	<TaxIdNumber>11122233300</TaxIdNumber>
	<Type>NATURAL_PERSON</Type>
</Owner>
```

**Comment by judahreis** [comment]
@pedrolamarao, a ordem dos elementos não é garantida, e pode mudar mesmo na mesma versão.
