### ISSUE TITLE
[Dúvida] no [DICT] - Teste Reivindicação do tipo Portabilidade

### ISSUE THREAD

**Issue by celobento** [bacen/pix-perguntas-e-respostas#172]
Segundo o item **2.6.5** do Documento de Especificação versão 6.2:

"_A **portabilidade** tem como objetivo facilitar o processo de vinculação de chaves nos casos em que o usuário **muda o PSP** em que ele possui conta transacional._"

Visto que para conclusão dos testes homologatórios precisamos nos envolver com outra PSP, o Bacen disponibiliza alguma PSP de teste para realização deste teste homologatório ?

Qual a recomendação para conclusão deste teste envolvendo a portabilidade?

**Comment by luizlaydner** [comment]
No ambiente de homologação, existe um participante indireto virtual vinculado a cada participante direto. 
O ISPB do virtual é ISPB-direto + 1 (se ISPB do direto é 12345678 , o virtual é 12345679)

**Comment by celobento** [comment]
@luizlaydner boa tarde! em testes enviados, quando procedo com orientação que você passou (ISPB do virtual é ISPB-direto + 1 (se ISPB do direto é 12345678 , o virtual é 12345679)) recebo 

<Cd>RC10</Cd></Rsn><AddtlInf>ISPB do participante recebedor inexistente</AddtlInf>

Como proceder para os testes de pagamento e recebimento?
