### ISSUE TITLE
Dúvida no QR CODE Dinâmico - Padrão de retorno em caso de leitura da URL com erro

### ISSUE THREAD

**Issue by gpneto** [bacen/pix-perguntas-e-respostas#173]
**Descreva sua dúvida ou problema**
Na documentação não localizei um padrão de erro a ser seguido em caso de algum erro de negócio/sistema na chamada da URL do QR Code Dinânico.

Por exemplo, quando o app do PSP Pagador chamar a URL do QR Code para detalhar os dados de pagamento, caso o documento de cobrança esteja vencido e não aceite o pagamento vencido, mesmo assim deverá retornar o payload com os dados? 

Neste caso o próprio APP do PSP Pagador tem que fazer a validação da data de vencimento(o app terá que verificar se é dia útil e se documento de cobrança venceu em um dia não útil...), neste caso o PSP Recebedor já sabe que esse pagamento não pode ser efetivado e mesmo assim transfere a responsabilidade da validação para o app do PSP do Pagador.

Ou essas validações podem ser verificadas no Serviço do PSP Recebedor quando é chamada a URL e caso não permita realizar o pagamento, não detalha os dados e retorna o erro da validação realizada pelo PSP Recebedor do motivo de não aceitar esse pagamento. Neste caso deverá ter um padrão de payload de retorno, para saber em qual campo deverá ser buscado a mensagem a ser apresentada.

**Sistema ou Área**
QR Code

**Comment by ninrod** [comment]
@gpneto , no exemplo levantado, o PSP recebedor deve utilizar a semântica padrão HTTP response codes da família 4xx. 

Por exemplo, retornar o código [410](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410), nesse caso, seria uma boa escolha. O status 410 apresenta uma semântica que indica que um recurso existia, realmente, nesse endpoint, mas já não existe mais. 

O PSP recebedor está livre para usar os "response status codes" que julgar mais apropriados para cada caso.

**Comment by gpneto** [comment]
@ninrod, obrigado pelo retorno.

Minha dúvida seria mais na mensagem apresentada ao usuário que está tentando realizar o pagamento. 

No aplicativo ele irá tentar realizar o pagamento do título vencido e será apresentado uma mensagem genérica de erro. Como não está padronizado onde a mensagem de erro deve estar entre os PSPs não tem como saber qual erro que realmente ocorreu. O usuário final não saberá que o erro que ocorreu foi por causa do título vencido igual ocorre hoje em um pagamento de boleto.

O PSP 1 pode retornar o erro no body: {**erro**: "Pagamento de cobrança vencido"} e o PSP 2 pode enviar como o body: {**mensagem**: "Pagamento de cobrança vencido"}, neste caso como não tem um padrão da mensagem do erro o aplicativo simplesmente irá considerar que ocorreu um erro 4xx e apresentar uma mensagem que o PSP Pagador entende ser adequada, mas não é a mensagem que o PSP Recebedor enviou por exemplo no body.

**Comment by ninrod** [comment]
@gpneto , seu argumento é interessante.  Vou levar para o time e retorno aqui pra você com uma posição. 

Enquanto isso, vou deixar a issue aberta.

**Comment by rturk** [comment]
Caros pode ajudar OpenPix disponibilizou em beta um leitor de QRCode EMV
https://openpix.com.br/qrcode/scanner/

**Comment by ninrod** [comment]
@gpneto a API de Recebimentos passará a se chamar API PIX e ocorrerá uma entrega, versão `2.0.0`, provalmente amanhã. 

Essa questão de vencimento do título não será aplicada porque a API PIX versão `2.0.0` tratará somente da "Função recebimento". Não haverá "títulos vencidos". Então a situação não se aplica. A questão de data de vencimento, por exemplo, não será abordada nesse momento. 

Ficará mais claro com o lançamento da versão `2.0.0`. Tomo a liberdade de fechar esse issue em decorrência desse desenvolvimento. 

Liberada a versão `2.0.0` juntamente com os documentos que acompanharão essa versão, sinta-se à vontade para contribuir com eventuais questões.
