### ISSUE TITLE
[Dúvida] no [DICT] - Validar notificação de infração recebida

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#174]
**Descreva sua dúvida ou problema**

Olá!! Gostaria de tirar algumas dúvidas sobre as regras de abertura e aceite de uma notificação de infração.

1 - Sobre o fluxo de infração, o **PSP remetente** (que pode ser o pagador ou o recebedor) antes de **abrir** a notificação, deve verificar se a transação foi feita nos **últimos 6 meses**, se ela foi realizada fora desse prazo, a solicitação não pode ser aberta, correto?

2 - Agora, no caso do **PSP destinatário** (PSP que **recebe** a notificação), ele **deve validar** se a transação que está sendo reportada está dentro do prazo de 6 meses?  Ou o DICT não permitirá que seja enviado uma notificação fora do prazo?

Obrigada

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
@monise, o DICT fará o controle do prazo. Se o destinatário for notificado, deve considerar o prazo válido.
