### ISSUE TITLE
Dúvida no DICT - Verificar Sincronismo ParticipantSyncVerifier 

### ISSUE THREAD

**Issue by fCamargosRibeiro** [bacen/pix-perguntas-e-respostas#175]
**Descreva sua dúvida ou problema**
É mais uma sugestão, hoje no processo de Verificar Sincronismo passamos o ParticipantSyncVerifier e recebemos ele no retorno com o OK ou NOK. A gente já conseguiu fazer o processo funcionar, mas foi difícil sem conseguir enxergar o vsync que o Bacen calculou, porque a gente só tem a visão do nosso lado, então não temos visão onde estamos cometendo o erro se não temos a visão do que estamos comparando. 

Então gostaria de saber se é possível adicionar o campo do vsync que o Bacen calculou no response?

**Sistema ou Área**
DICT.

**Comment by judahreis** [comment]
@fCamargosRibeiro, a ideia por trás da decisão de não deixar o campo na resposta é, justamente, garantir que o cálculo foi feito do lado do participante. Caso contrário, um participante poderia simplesmente enviar o campo que o DICT informasse em seguida. Para verificar o "ponto de discordância", recomendamos acompanhar passo a passo os [eventos de CID](https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/AnexoV-APIdoDiretoriodeIdentificadoresdeContasTransacionais-versao1.0.0-RC5.html#operation/listCidSetEvents).
