### ISSUE TITLE
[Dúvida] no [API Recebimento / DICT] - Utilização

### ISSUE THREAD

**Issue by ehamerski** [bacen/pix-perguntas-e-respostas#176]
**Descreva sua dúvida ou problema**

Em geral, PSPs já possuem APIs de integração padronizadas para seus clientes, que expõem, por exemplo, o serviço de geração de cobrança: Clientes <--> API Integração do PSP <--> PSP.
 
No meu entendimento, a API de Recebimento e a API do DICT são interfaces que o backend do PSP utiliza para se integrar aos serviços SPI & DICT: PSP <--> API Recebimento/DICT <--> SPI/DICT.

Ou no caso da utilização dos serviços de um PSTI, a utilização das APIs de Recebimento e DICT ficam transparentes por serem integradas do lado do PSTI: PSP <--> PSTI <--> API Recebimento/DICT <--> SPI/DICT

Nesse contexto, a API de integração do PSP deverá expor novos endpoints para oferecer os serviços PIX para seus clientes, de acordo com a padronização já existente na sua própria API de integração:
- Cenário 1: Clientes <--> API Integração do PSP <--> PSP <--> API Recebimento/DICT <--> SPI/DICT
- Cenário 2: Clientes <--> API Integração do PSP <--> PSP <--> PSTI <--> API Recebimento/DICT <--> SPI/DICT

Faz sentido?

**Sistema ou Área**
DICT, SPI

**Comment by judahreis** [comment]
@ehamerski, não entendemos a pergunta, especialmente o que as setinhas "<-->" querem dizer. Pode esclarecer qual a dúvida?

**Comment by ehamerski** [comment]
Tudo bem, @judahreis?

As setas indicam o sentido das interações (requests e responses).

Neste exemplo, 

Clientes <--> API Integração do PSP <--> PSP <--> API Recebimento/DICT <--> SPI/DICT

Backend do cliente integrado utiliza a API de Integração/SDK do PSP para chamar o backend do PSP.
Backend do PSP utiliza a API Recebimento/DICT (SDK) para chamar o SPI/DICT.

**Comment by rubenskuhl** [comment]
> Tudo bem, @judahreis?
> 
> As setas indicam o sentido das interações (requests e responses).
> 
> Neste exemplo,
> 
> Clientes <--> API Integração do PSP <--> PSP <--> API Recebimento/DICT <--> SPI/DICT
> 
> Backend do cliente integrado utiliza a API de Integração/SDK do PSP para chamar o backend do PSP.
> Backend do PSP utiliza a API Recebimento/DICT (SDK) para chamar o SPI/DICT.
> 
> A dúvida é se as APIs de Recebimento e DICT são as interfaces de comunicação entre o backend do PSP e os sistemas SPI e DICT (ou entre o backend do PSTI e os sistemas SPI e DICT).
> 
> E portando não são interfaces que serão ofertadas diretamente para os clientes do PSP por estarem num padrão diferente daquele já mapeado e utilizado pelos clientes dos PSPs (no caso das APIs de integração proprietárias).

A API de Recebimento é justamente entre o PSP e seus clientes. 
Já as do DICT, ICOM e ARQ são entre o BACEN e os PSPs.

**Comment by ehamerski** [comment]
> A API de Recebimento é justamente entre o PSP e seus clientes.
Então ela pode ser a API de Integração já publicada da IP / IF com a adição dos novos endpoints para geração de qrcode?

**Comment by ninrod** [comment]
@ehamerski 

> Então ela pode ser a API de Integração já publicada da IP / IF com a adição dos novos endpoints para geração de qrcode?

Não sei se entendi a sua pergunta. 

A princípio, para que o PSP esteja aderente, não há o que se falar em termos de outros endpoints possíveis de serem implementados que não estejam na API. 

Lembrando que a API na versão 1.2.0 ainda sofrerá algumas alterações em virtude de feedbacks do mercado.

**Comment by rubenskuhl** [comment]
> > A API de Recebimento é justamente entre o PSP e seus clientes.
> 
> Então ela pode ser a API de Integração já publicada da IP / IF com a adição dos novos endpoints para geração de qrcode?

A geração do QR-Code é mais uma questão de biblioteca do que end-point, não ? Pq fazer uma chamada transitar via rede se uma função pode receber um conjunto de dados e devolver uma imagem ?

**Comment by ehamerski** [comment]
Pois é, isso significa que a PSP deve jogar fora a sua API de integração / SDK, padronização e investimento e expor essa nova API de Recebimento. Mantendo ambas. É isso?

**Comment by rubenskuhl** [comment]
Me parece que aí entra numa discussão mais de negócio do que o escopo deste fórum... mas o @bacen é que precisa dizer. 

De qualquer forma, a API de Recebimento não é versátil o suficiente para outros recebimentos (boleto, cartão), então eu não vejo como ficar só com ela.

**Comment by ninrod** [comment]
> Pois é, isso significa que a PSP deve jogar fora a sua API de integração / SDK, padronização e investimento e expor essa nova API de Recebimento. Ou manter ambas. É isso? Não sei se estamos falando da mesma coisa.

@ehamerski , a API de recebimento diz respeito apenas ao arranjo Pix. 

Os outros arranjos, por exemplo, boleto, cartão, TED, possuem outros regramentos estabelecidos pelos seus respectivos instituidores.
