### ISSUE TITLE
[Dúvida] no [DICT] - Grade de disponibilidade em 05/10

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#177]
**Descreva sua dúvida ou problema**

Olá!! Gostaria de tirar algumas dúvidas sobre a grade de disponibilidade do DICT.

1 - No novo manual "_X_ManualOperacionaldoDICT-versao1-1.pdf_" não existe mais informações sobre a grade de disponibilidade das funcionalidades. Esse item foi removido mesmo ou está contido em outro manual?

2 - Se não foi removido, continua valendo as disponibilidades divulgadas anteriormente no manual "_EspecificaçõesPI_versão6-2.pdf_"?

3 - Para a entrada em produção em **05/10**, já estará valendo a grade de disponibilidade de cada uma das funcionalidades do DICT (Categoria A, B, C e D)? 

**Sistema ou Área**
DICT

**Comment by fbjhon** [comment]
Boa tarde, também temos essa dúvida, alguma posição?

**Comment by gizelysc** [comment]
Boa tarde! Eu tb estou com dúvida a respeito de período de cadastro antecipado.
A IN-9 fala que :
Art. 1º A fase de operação restrita do DICT, de que trata a Seção IV do Capítulo XXII da Resolução BCB nº 1, de 12 de agosto de 2020, ocorrerá de 5 de outubro de 2020 a 15 de novembro de 2020, sendo que:

I - durante o período de 5 de outubro de 2020 a 2 de novembro de 2020, o acesso ao DICT poderá ser realizado das 9h às 18h, excetuados os finais de semana e feriado

Diante dessa grade horária, o próprio Bacen ficará com o serviço indisponível nesse horário, negando caso seja realizada alguma requisição fora da janela definida pelo Bacen?

**Comment by CharlesMendes** [comment]
Pessoal, fiz essa pergunta nessa issue, deem uma olhada

https://github.com/bacen/pix-perguntas-e-respostas/issues/197
