### ISSUE TITLE
[Dúvida] no [DICT] - Dúvida sobre Compactação no DICT

### ISSUE THREAD

**Issue by fCamargosRibeiro** [bacen/pix-perguntas-e-respostas#178]
No Manual de Interface de Comunicação na seção 2.1.5 fala da parte de compactação e fala:

"O PSP e a API devem aceitar conteúdo no formato gzip. Para isso, devem aceitar o
cabeçalho “Content-Encoding” com valor “gzip”."

Mas essa parte não está explicita que é só para a parte do ICOM ou se também é valido para DICT? Porque nos documentos específicos do DICT eu não vi nada sobre esse assunto.

**Comment by jorgebaruchi** [comment]
Bom dia, também temos esta dúvida. Existe algum tipo de compactação na comunicação do DICT que aumente a performance de consultas a base? Este informação é de extrema importância, pois poderia performar diretamente o TPS das aplicações...

**Comment by luizlaydner** [comment]
**Habilitamos em homologação o uso de compressão com gzip!**

Como XML contém muita redundância, compactação é bastante efetiva.

Para que o DICT _responda_ com compactação, deve-se incluir o header `Accept-Encoding: gzip` nas requisições.
Respostas compactadas do DICT terão o header `Content-Encoding: gzip`.

Para _enviar_ uma requisição com corpo compactado ao DICT, deve-se incluir o header `Content-Encoding: gzip` na requisição.

Vamos atualizar a especificação do DICT para incluir a possibilidade de se usar compactação.
