### ISSUE TITLE
[Dúvida] Implementação para aplicativos que não são fintechs/bancos

### ISSUE THREAD

**Issue by gabrielmcv** [bacen/pix-perguntas-e-respostas#179]
Bom dia a todos, 

Tenho uma aplicação de chat que utilizo para diversos segmentos na área médica, não sendo fintech ou banco registrado, será possível checar o status de uma transação entre dois pares através do ID de Transação? Existirá alguma URL de consulta?

Desde já, agradeço a atenção.

**Comment by ninrod** [comment]
> será possível checar o status de uma transação entre dois pares através do ID de Transação? Existirá alguma URL de consulta?

@gabrielmcv , entre dois pares, em que vc não seja a ponta receptora, não, no momento. 


No futuro, com a implementação da figura de iniciação de pagamento e também com o estabelecimento das APIs no âmbito de Open Banking, pode ser que esse cenário que você coloca seja possível de ser implementado.
