### ISSUE TITLE
Problema no DICT - Erro 404 Download Arquivo de CIDs 

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#18]
**Descreva sua dúvida ou problema**
Estamos com problemas ao tentar fazer o download do arquivo de CIDs, o Bacen esta sempre retornando 404.

**Sistema ou Área**
DICT

**Mensagens Enviadas / Recebidas**
`<GetCidSetFileResponse><CidSetFile><Id>1030</Id><Status>AVAILABLE</Status><Participant>07853842</Participant><KeyType>EMAIL</KeyType><RequestTime>2020-06-25T13:48:32.592Z</RequestTime><CreationTime>2020-06-25T13:48:32.679Z</CreationTime><Url>https://arq-h.pi.rsfn.net.br/api/v1/download/07853842/cidsetfile/07853842_EMAIL_1030_2020-06-25T13:48:32.620Z.txt</Url><Bytes>0</Bytes><Sha256>e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</Sha256></CidSetFile></GetCidSetFileResponse>`

`<?xml version="1.0" encoding="UTF-8"?><problem xmlns="urn:ietf:rfc:7807"><type>https://icom.pi.rsfn.net.br/api/v1/error/notFound</type><title>Não encontrado</title></problem>`

**Dados adicionais**
Já realizamos abertura de chamado anterior e nos foi retornado que o serviço estaria disponível em 22/06, porem até o momento o erro continua.

**Comment by judahreis** [comment]
Everton,

De fato, existe um problema na solução atual de download de arquivos do DICT. Vamos resolver, e avisamos quando já estiver disponível.

**Comment by guimapalmeira** [comment]
Olá, o problema já foi resolvido?
Continuo recebendo 404 pra Participante **Direto** e 403 para Participante **Indireto**.
Engraçado que ontem, dia 02/07, estava tomando Timeout e hoje retornou para 404.

Obrigado.

**Comment by judahreis** [comment]
Infelizmente ainda não. Temos a expectativa de estar resolvido até 07/07. Assim que resolvermos, fechamos o issue.

**Comment by judahreis** [comment]
Caros, uma nova versão foi publicada que corrige o problema. Podem testar o download do arquivo.
