### ISSUE TITLE
[Dúvida] no [SPI] - Documentação Idempotência

### ISSUE THREAD

**Issue by mfabioe** [bacen/pix-perguntas-e-respostas#180]
Após a última atualização da documentação, fomos verificar se havia alguma mudança na idempotência, mas não conseguimos achar nada sobre idempotência.
Onde está definido o comportamento de idempotência agora?
Anteriormente, estava no Documento de Especificações 6.2

**Comment by rafael-omello** [comment]
Já estamos providenciando a inclusão e informaremos em breve a localização da documentação desse item.

**Comment by mfabioe** [comment]
Verifiquei que foi publicada algumas informações sobre Idempotência no Catálogo de Serviços: https://www.bcb.gov.br/content/estabilidadefinanceira/cedsfn/Catalogos/Catalogo_de_Servicos_do_SFN_Volume_VI_Versao_501.pdf
No entanto, ainda não está definida a janela em que a idempotência deve ser garantida. Consta apenas como exemplo uma janela de 24h.

**Comment by rafael-omello** [comment]
A definição da janela encontra-se no "Catálogo de Serviços do SFN" (disponível no link que você passou acima), na seção "Mensagens trocadas com o SPI nos cenários de transferências de recursos".
