### ISSUE TITLE
[Problema] no [SPI] - Possível defeito na API do SPI - ICOM

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#181]
**Descreva sua dúvida ou problema**

Olá! De acordo com o **Manual de Interface de Comunicação versão 1.4.0**, ao habilitarmos a opção para **aceitar múltiplas mensagens** (Accept: multipart/mixed) o SPI deveria retornar os Pi-ResourceIds separados por vírgula.

Porém, ao enviar uma requisição com o cabeçalho "Accept: multipart/mixed" o SPI **não está retornando o cabeçalho PI-ResourceId**, conforme descrito no manual (vide logs em anexo).

Gostaríamos de saber se isso se trata de uma falha na API do SPI ou se houve alguma alteração com que faça que o tratamento para esse cenário seja diferente.

> Manual de Interface de Comunicação - 2.2.1.3. PI-RESOURCEID
> Quando a requisição tratar de várias mensagens (multipart), esse cabeçalho carregará as identificações de cada mensagem separadas por vírgula (“,”)

**Sistema ou Área**
SPI

**Identificador do Problema**
`GET /api/v1/out/13370835/stream/703ba5c3-2137-4242-8432-71e34dd4439b `

**Mensagens Enviadas / Recebidas**

![image](https://user-images.githubusercontent.com/5355541/90522642-56e28b80-e142-11ea-976e-6a789d049676.png)

**Comment by cristianokbc** [comment]
@monise, trata-se de um erro na documentação. No caso de multipart no endpoint de saída, o ResourceId vem como cabeçalho de cada parte, após o "boundary".

**Comment by cristianokbc** [comment]
Acabamos de publicar a versão 1.5 do Manual das Interfaces de Comunicação com a correção.
