### ISSUE TITLE
Dúvida no DICT - Fluxo de consulta ao DICT

### ISSUE THREAD

**Issue by gpneto** [bacen/pix-perguntas-e-respostas#182]
**Descreva sua dúvida ou problema**

No [Manual de Fluxos](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/III_ManualdeFluxosdoProcessodeEfetivacaodoPix-versao1.pdf) página 9 é apresentado no fluxo que deve ser chamado o DICT após a confirmação dos dados pelo usuário em tela.

Neste caso deverá ser chamado duas vezes a consulta ao DICT?
    1 - Para apresentar em tela os dados do Beneficiário(Nome, CPF/CNPJ e PSP)
    2 - Após a confirmação dos dados conforme o fluxo mencionado acima

Gostaria de confirmar se o fluxo está correto, pois neste caso terá duas chamadas ao DICT.   

**Sistema ou Área**
DICT

**Dados adicionais**
Consulta no DICT após a confirmação dos dados pelo Usuário 
<div style="text-align: center">
<table border="1">
    <tr>
        <td>Imagem do Fluxo</td>
    </tr>
    <tr>
        <td><img src="https://github.com/gpneto/pix/raw/master/fluxo_1.png" width="800" /></td>
    </tr>
</table>

**Comment by pFerreiraBlupay** [comment]
Eu acredito que é realizada apenas uma consulta. No primeiro momento, a consulta é realizada em um endpoint do Recebedor (uma URL vinda no QR Code), nesse caso ele retorna um json com os dados retornados da API do PSP. A consulta ao DICT na minha visão acontece apenas quando PSP pagador encaminha a chave para consulta (etapa 7 do fluxo descrito) , que no caso vai solicitar a consulta aos dados da chave enviada.

**Comment by carloschioquetta** [comment]
Para registro: A última versão do documento em questão foi alterado para esclarecer esse ponto.
https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/III.ManualdeFluxosdoProcessodeEfetivacaodoPix-versao1.1.pdf
