### ISSUE TITLE
[Dúvida] no [DICT] - Teste de capacidade consulta de chaves

### ISSUE THREAD

**Issue by guimapalmeira** [bacen/pix-perguntas-e-respostas#183]
**Descreva sua dúvida ou problema**
Para o teste de capacidade, devemos consultar 20.000 chaves em 10 minutos.
Minha dúvida é, 
1. Teremos 10 minutos para consultar essas chaves, correto?
2. Podemos tentar consulta-las o mais rápido que conseguirmos? Ex. Finalizar as vinte mil(diferentes) em 5 minutos.
3. Para isso o RateLimit teria que estar preparado, correto?

**Sistema ou Área**
DICT

obrigado,
Guilherme Palmeira.

**Comment by judahreis** [comment]
1. O participante deve manter as consultas por 10 minutos. 20.000 é o mínimo que deve alcançar nesse período, sem picos de consultas.
2. Se conseguir mais rápido, deve manter o testes por 10 minutos.
3. O RateLimit estará desabilitado durante os testes de capacidade.

**Comment by andred5678** [comment]
Srs. Estamos recebendo erros intermitentes hoje 04/09/2020 nas chamadas do DICT, algum problema?
