### ISSUE TITLE
[Dúvida] no [DICT] - Homologação funcionalidade de verificação de sincronismo

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#185]
**Descreva sua dúvida ou problema**

Olá! Gostaria de tirar algumas dúvidas sobre o teste de homologação da funcionalidade de sincronismo:
 
![image](https://user-images.githubusercontent.com/5355541/90635584-b81c6480-e1ff-11ea-9e56-dd0ee6c19414.png)

1 - É necessário cadastrar mil chaves **apenas** de um tipo de chave ou o teste tem que ser para **cada** um dos 5 tipos de chaves?

2 - Mesmo em homologação, só será possível solicitar o **arquivo de CIDs** das 16h às 18h?

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
1 - apenas um tipo de chave.
2 - não haverá mais janela para solicitação de arquivo de CIDs. Poderá ser solicitado a qualquer momento.
