### ISSUE TITLE
[Dúvida] sobre a URL do site de [QR code dinâmicos] - Emissão de certificado

### ISSUE THREAD

**Issue by jocimarcan** [bacen/pix-perguntas-e-respostas#187]
Referente à URL dos sites/domínios de QR code dinâmicos, e considerando:
a) O prazo do processo de contratação e de emissão de certificado do tipo EV, dada a natureza jurídica do banco Banestes;
b) A recente exigência do formato da URL para ambiente de homologação. Exemplo: “qrcode-h.bancoxyz.com.br”; 
c) O óbice na edição do campo CN de certificado quando já emitido; e
d) O investimento, pelo Banestes, em plataforma de gerenciamento de APIs com padrões pré-definidos de nomes de URLs expostas para internet, de acordo com o modelo de segurança necessário à URL em questão;

Necessitamos dos seguintes esclarecimentos:
1)Haverá alguma exigência de formatação da URL ainda a ser divulgada?
2)Podemos proceder ao processo de demanda de contratação dos certificados do tipo EV para as URLs abaixo? 

Homologação:
https://pix-api-h.api.apps.banestes.b.br
Produção:
https://pix-api-prd.api.apps.banestes.b.br

**Comment by ninrod** [comment]
Prezado @jocimarcan, encaminhei a questão internamente. Responderemos em breve.

**Comment by gpneto** [comment]
@jocimarcan, legal esses pontos que você levantou. Também estamos realizando a contratação dos certificados o quanto antes. 

Só fiquei com uma dúvida na tua colocação, referente ao item b) "A recente exigência do formato da URL para ambiente de homologação.": não localizei na documentação essa exigência para homologação da URL do QR Code, poderia sinalizar para mim em qual documento está descrito essa exigência. 

Muito Obrigado.

**Comment by ninrod** [comment]
@jocimarcan , as respostas:

> Necessitamos dos seguintes esclarecimentos:
1)Haverá alguma exigência de formatação da URL ainda a ser divulgada?
2)Podemos proceder ao processo de demanda de contratação dos certificados do tipo EV para as URLs abaixo?

1) não haverá exigência de formatação da URL ainda a ser divulgada.
2) Não vemos impedimentos.

**Comment by jocimarcan** [comment]
@gpneto essa especificação está presente no manual de segurança, página 22.
https://www.bcb.gov.br/content/estabilidadefinanceira/cedsfn/Manual%20de%20Seguranca%20do%20PIX%20v3.0.pdf
