### ISSUE TITLE
Dúvida no SPI - Pooling Participantes Indiretos

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#188]
**Descreva sua dúvida ou problema**
Referente ao pooling dos indiretos no caso devemos utilizar na URL do stream o ISPB do participante direto ou indireto? 

https://icom-h.pi.rsfn.net.br/api/v1/out/ISPB_Partitipante_**Direto**/stream/start
Ou
https://icom-h.pi.rsfn.net.br/api/v1/out/ISPB_Partitipante_**Indireto**/stream/start

Se for do participante a URL de stream o ISPB do Participante Direto, tenho algumas duvidas (considere somente a duvida para esse caso):
-  Como identificaremos se o recebimento da mensagem foi do participante direto ou do indireto?
-  No caso de termos certificados diferentes para direto e indireto, como será a validação das assinaturas? Pois a mensagem pode sair pelo ISPB Direto (certificado 1), e receber o stream pelo ISPB Indireto (certificado 2).

Obrigado.

**Sistema ou Área**
SPI

**Comment by cristianokbc** [comment]
Apenas o participante direto tem acesso de envio ou recebimento de mensagens. Portanto, tanto a URL de envio quanto a de recebimento será usada apenas por esse participante.

A assinatura também é feita pelo participante direto.

A identificação é feita pelos dados da mensagem. No caso da pacs.008, verificar DbtrAgt e CdtrAgt.

**Comment by evertongodoi** [comment]
@cristianokbc Obrigado pelo retorno!

**Comment by evertongodoi** [comment]
@cristianokbc em complemento a pergunta, atualmente uma instituição pode ter mais de 1 certificado SPI ativo certo? 
A pergunta é se temos 2 certificados (A e B), e enviamos uma mensagem com o B. A resposta vai vir coma o A ou com B?
