### ISSUE TITLE
[Dúvida] no [QR Code] - JWS

### ISSUE THREAD

**Issue by jhmjesus** [bacen/pix-perguntas-e-respostas#189]
Gostaria de confirmar a utilização do Media Type **application/jose** para identificar o conteúdo no padrão JWS retornado ao acessar um link de um QR Code Dinâmico? 

Considerando que será utilizado o método [JWS Compact Serialization](https://tools.ietf.org/html/rfc7515#section-9.2.1) o Mime Type **application/jose** parece ser o correto, mas no manual de segurança mais recente (3.0) não traz nenhuma referência a esse assunto.

**Comment by ninrod** [comment]
Prezado, @jhmjesus 

Sim, conforme consta na RFC 7515, o MIME Type correto neste caso é o "application/jose".
