### ISSUE TITLE
[Dúvida] no [DICT] - Formato arquivo de CIDs

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#19]
**Descreva sua dúvida ou problema**
Qual é o formato do arquivo de CIDs? Um arquivo .zip?

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
@monise  O formato do arquivo é um CID por linha. Linhas são separadas por [LF](https://www.fileformat.info/info/unicode/char/000a/index.htm). Arquivo não é compactado.

**Comment by jorgebaruchi** [comment]
Pessoal, existe algum meio de baixar o arquivo em formato gzip / zip ? Otimizando o tempo e uso banda?

**Comment by luizlaydner** [comment]
@jorgebaruchi : Atualmente não tem como baixar o arquivo de CIDs compactado. 
Vale lembrar que como o CID é um número aleatório, representado em hexadecimal no arquivo, a compactação tem efetividade limitada. Compacta perto de 50%. Ajuda, mas não muito.
Podemos colocar essa possibilidade no futuro, mas não é prioridade no momento.
