### ISSUE TITLE
[Dúvida] na [API de Recebimento] - Devolução

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-perguntas-e-respostas#191]
Com a remoção da funcionalidade de devolução do Pix, a API de Recebimento será alterada para remover esse método ? Ou o PSP deverá iniciar um Pix reverso ao receber do EC um pedido de devolução ?

**Comment by ninrod** [comment]
@rubenskuhl, não tenho essa informação. A informação que eu tenho é que essa funcionalidade continua existindo.

**Comment by rubenskuhl** [comment]
Descobri o que foi. O BACEN tirou a transação de devolução do teste de homologação, e colocou a denúncia de fraude no DICT no lugar. Mas a transação de devolução continua prevista, mas recebedores vão ter que se certificar de que aquele PSP suporte a transação de devolução.
