### ISSUE TITLE
[Problema] no [SPI] - [ICOM] Recebimento de Mensagem com Caractere  "&#13 ;" 

### ISSUE THREAD

**Issue by birouska** [bacen/pix-perguntas-e-respostas#192]
Estamos recebendo na assinatura das mensagens o Caractere "&#13 ;" na tag <ds:SignatureValue> observamos esse comportamento desde a última sexta-feira. Desse modo não estamos mais conseguindo transforma a string xml recebida em Document (Usamos Java). 

Houve alguma alteração? 
Caso sim, será definitiva e constará no manual?

**Identificador do Problema**
Data e Hora da mensagem = 22-08-2020 18:33:08.729
RESOURCE_ID=UEkBdBgW6KbSMm1M4ZFBwqbt8pzaH6xH
Tag = 
<ds:SignatureValue>qUqQHXOhRRWEVQvtaHgZfN4oIqNfDWyVG1Q16/rfPiEfzEN7+P0AXM8O7RhdDgznXTu1v42gL7Vv & # 1 3  ;
56mNbykqaQl+IS9Iqz5UWGUnSVayl5ge10KS5LnmTsWuZAbX62JIh1Z7Ahs4Ek17siZoGBNAuINI & # 1 3  ;
qe68UGK2PCNXbVXWld5xvzNFV0K+Fr+jMGPEOYG8tKWtuitv/qMXyJwM5cnZC9m4MUQRN81VZZ7y & # 1 3 ; 
FzGbYC96XiLhT00rZVGlrzHmDXhSB1SgpVxbA17z0u64v6XL/vhPCfFczYg+JNiDr0nSzrQZn4nL & # 1 3 ; 
MTLdw2YLxHMkmUXim+xFS8Ff29z8m+EE7gp9ow==</ds:SignatureValue>

**** Inclui os espaços nos carateres para pode demonstrar o problema ****

**URL de conexão**
https://icom-h.pi.rsfn.net.br/api/v1/out/{isbp}/stream/start

**Comment by cristianokbc** [comment]
O uso de "&#13;" é válido no XML. Na decodificação XML, se traduz em quebra de linha, que é aceito na codificação base64 usada na assinatura. Portanto, é uma construção válida.

Nossa implementação em Java aceita a assinatura nos formatos com ou sem quebras de linha.
