### ISSUE TITLE
Dúvida no SPI - Certificados simultâneos 

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#193]
**Descreva sua dúvida ou problema**
Atualmente formos informados que, uma instituição pode ter mais de 1 certificado SPI ativo certo?
A pergunta é, se temos 2 certificados (A e B), e enviamos uma mensagem com o B. A resposta vai vir coma o A ou com B?
Obrigado.

**Sistema ou Área**
SPI

**Comment by cristianokbc** [comment]
A resposta não utiliza o certificado do participante. Ela sempre sempre virá assinada com o certificado do Bacen. Dessa forma, nesse caso não importa qual o certificado usado pelo PSP.

**Comment by evertongodoi** [comment]
@cristianokbc Obrigado!
