### ISSUE TITLE
[Problema] no [ICOM] - CAMT052 não é retornada.

### ISSUE THREAD

**Issue by dcardosotree** [bacen/pix-perguntas-e-respostas#196]
Prezados, 

Estou enviando uma CAMT060 solicitando uma CAMT052, porém retorna que as datas estão erradas, validei o xsd e aparentemente não tem erro.

Segue trecho da CAMT060 com a data e hora.

<FrToDt>
	<FrDt>2020-08-21</FrDt>
	<ToDt>2020-08-21</ToDt>
</FrToDt>
<FrToTm>
	<FrTm>08:00:00.150Z</FrTm>
	<ToTm>10:00:00.250Z</ToTm>
</FrToTm>

Segue informação da CAMT060 enviada.
BizMsgId = M2812760318d285ca244c4854a648169

Segue retorno do ICOM com ADMI002
BizMsgId  = M000381660KE90MB6611GU4TP4ZBCTHH

<RsnDesc>Data/hora inicial de resultado e/ou data/hora final de resultado inválida(s)</RsnDesc>

Poderia me indicar se é realmente um erro na minha mensagem ou algum problema na validação do XSD?

**Comment by rafael-omello** [comment]
Conforme xls da CAMT.060, na coluna "Regra para o Brasil" do campo ToDate: "Este campo é usado para indicar a data final do período da relação de lançamentos  (conforme calendário do horário UTC informado nos lançamentos), caso não seja a mesma data inicial. O período máximo a ser consultado será de 24 horas. Data no formato padrão YYYY-MM-DD."
Ou seja, o ToDate não deve ser preenchido se for o mesmo do FromDate.
