### ISSUE TITLE
[Dúvida] no [DICT] horário da jornada Reivindicação de posse e portabilidade

### ISSUE THREAD

**Issue by CharlesMendes** [bacen/pix-perguntas-e-respostas#197]
**Descreva sua dúvida ou problema** 
O CompletionPeriodEnd leva em consideração o horário? 

Ou seja, reivindicador fez Open às 15h30 do dia 1, ao iniciar contagem dos 14 dias, no 14° dia é considerado término até 15h30 desse dia ou até final da janela Dict 20h? 

**Sistema ou Área** 
DICT

**Identificador do Problema** 
N/A

**Mensagens Enviadas / Recebidas** 
N/A

**URL de conexão** 
N/A

**Dados adicionais** 
N/A

**Comment by judahreis** [comment]
@CharlesMendes, o horário está sendo considerado, desde que dentro da janela obrigatória - ver categoria C no manual.

**Comment by CharlesMendes** [comment]
@judahreis  "ver categoria C no manual." desculpe, mas não encontrei no Manual Operacional DICT, onde encontro a categoria C?

**Comment by judahreis** [comment]
@CharlesMendes, falha minha. As janelas de funcionamento saíram da documentação, e foram listadas no (regulamento)[https://www.bcb.gov.br/estabilidadefinanceira/exibenormativo?tipo=Resolu%C3%A7%C3%A3o%20BCB&numero=1], Sessão IV. A janela obrigatória está listada no art. 80.

**Comment by CharlesMendes** [comment]
@judahreis obrigado, o art. 79 e 80 não estão conflitantes?
![image](https://user-images.githubusercontent.com/1323305/91461030-e8e34600-e85e-11ea-8e4c-430640a76bc6.png)

**Comment by judahreis** [comment]
Isso significa que o DICT é 24x7, mas os participantes só são obrigados a fazer registros/exclusão/portabilidade/reivindicações de 8h as 20h. Opcionalmente podem oferecer essas operações tb 24x7.

**Comment by CharlesMendes** [comment]
@judahreis Essa grade de 05/out a 15/nov, está mantida? ou já em 05/outubro passa a valer o que está no Regulamento? (anulando esse informe abaixo) 

![image](https://user-images.githubusercontent.com/1323305/91496473-8e63dd00-e892-11ea-93c6-a4c4351a1ba6.png)

**Comment by judahreis** [comment]
No período de 05/10 a 15/11 vale a janela de 9h às 18h, excetuados os finais de semana e feriados, e a participação é completamente facultativa. A partir do dia 03/11 passam a valer as operações de consulta e relato de infração (substitui a solicitação de devolução),e a participação é obrigatória.

**Comment by gizelysc** [comment]
Olá, boa tarde!
Mas fora dessa janela, caso algum haja tentativa de cadastro ,o próprio Dict vai responder que o serviço encontra-se indisponível?
