### ISSUE TITLE
Dúvida no DICT - Dúvida quanto ao update de chave do tipo EVP

### ISSUE THREAD

**Issue by Leonardo34** [bacen/pix-perguntas-e-respostas#20]
### **Descreva sua dúvida ou problema**
O update de chaves do tipo EVP é permitido ? Estou tentando realizar o PUT de uma chave do tipo EVP e estou obtendo apenas o seguinte retorno: "Bad Request - Invalid reason", informando a reason USER_REQUESTED.
Na documentação não ficou clara a viabilidade desse fluxo. 

### **Sistema ou Área**
DICT

**Comment by judahreis** [comment]
Chaves do tipo EVP não podem ser modificadas a pedido do usuário (USER_REQUESTED). Somente se houver restruturação de agências por parte do participante (BRANCH_TRANSFER).
