### ISSUE TITLE
[Problema] no [DICT] - Instabilidades no DICT - processo de portabilidade

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#200]
**Descreva sua dúvida ou problema**

Olá! Hoje (25/08/2020) estamos notando instabilidades no DICT e mais especificamente nos processos envolvendo portabilidade de chave PIX, onde a notificação de iniciação do processo não está chegando ao PSP Doador.
Segue abaixo a lista de ID dos processos de portabilidade que estão em aberto no PSP Reivindicador e que não chegaram no lado do PSP Doador:
- e141fb02-3305-442f-8f49-bb09596541e7
- 321bde14-9a79-45e9-9d63-21d868c22f78
- e143b1d4-2339-4973-a81b-6542f6dc292a

Há de fato alguma instabilidade no processo de portabilidade de chave PIX?

Observação: estamos usando a RC5 das APIs do DICT.

**Sistema ou Área**
DICT

**Comment by monise** [comment]
No nosso log aparece que o retorno está vindo da RC6, isso está correto?

![118240409_972517699933726_7169240805927275862_n](https://user-images.githubusercontent.com/5355541/91214413-68e79f80-e6e9-11ea-8a8f-2b60701b04be.png)

**Comment by luizlaydner** [comment]
@monise Tivemos uma situação pela manhã que gerou instabilidade.
Sobre o header Location ser v1-rc6 na resposta que você mostrou, é um bug. Vamos corrigir.
Obrigado pelo relato!
