### ISSUE TITLE
Confirmação da reivindicação pelo PSP reivindicador ao fim do período de encerramento.

### ISSUE THREAD

**Issue by gizelysc** [bacen/pix-perguntas-e-respostas#201]
Boa noite,
No manual operacional do DICT diz que :
Caso o usuário doador não valide a posse da chave nem confirme a reivindicação de posse durante o período de encerramento, o PSP reivindicador deve necessariamente confirmar o pedido. A confirmação do pedido por ausência de confirmação deve ser feita ao término do período de encerramento.

Mas na definição da Api  não há razão possível na qual o reivindicador possa efetuar uma confirmação.
Qual a melhor forma de proceder nesse caso?

**Comment by CharlesMendes** [comment]
Seguindo essa dúvida, após 14 dias, o Reivindicador irá no 15º dia realizar a validação de posse para encerrar o processo, nesse caso, ele tem quanto tempo para realizar esse processo? se virar 16 dias, 17 dias em diante... até quando temos que manter a "vez" com o reivindicador, ou apenas no 15º dia e no 16ºdia o PSP reivindicador encerra, liberando a chave?

**Comment by monise** [comment]
No passado levantamos esse ponto (https://github.com/bacen/pix-perguntas-e-respostas/issues/29) e a resposta foi que esse fluxo do lado do reivindicador não existe e que a documentação seria alterada. Mas no manual atual o requisito permanece. 
É um fluxo que deve ser implementado pelo PSP na visão reivindicador? ou realmente falta alteração na documentação?

**Comment by judahreis** [comment]
A documentação será atualizada. Não é possível o Reivindicador realizar a confirmação unilateralmente, pois tal procedimento causaria inconsistência entre a base do doador e as bases do DICT/Reivindicador. As ação do doador no 7o. dia é obrigatória, sob pena de sanção regulamentar. Já solicitamos a atualização do manual. Vou até deixar esse issue aberto, enqto ela não for atualizada (só para lembrar a gente... )

**Comment by CharlesMendes** [comment]
@judahreis não ficou claro, ou se poderiam reforçar na nova versão da documentação, a ação do usuário Reivindicador após passado 14 dias. Ou seja, quanto tempo ele tem para atuar no 15º dia em diante, ou apenas no 15º se ele não se manifestar, o PSP Reivindicador deve cancelar o processo encerrando a reivindicação e a chave ficando livre (pois ela já foi excluída após o 7º dia, e está bloqueada até conclusão desse processo)

**Comment by luizlaydner** [comment]
Para deixar registrado: [Manual Operacional do DICT v1.1](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/X_ManualOperacionaldoDICT-versao1-1.pdf) foi atualizado quanto aos pontos aqui levantados.

> - caso o usuário doador não se manifeste dentro do período de resolução, o PSP doador deve necessariamente confirmar a reivindicação no DICT;
> - no período de encerramento, o usuário doador pode somente validar a posse da chave, cancelando o processo. A confirmação não é possível durante esse período;
> - previsão de que o PSP reivindicador deve cancelar o processo de reivindicação no DICT caso seu usuário não faça a validação ativa da chave até o trigésimo dia após o início do processo de reivindicação.
