### ISSUE TITLE
[Dúvida] na [API de Recebimentos] - Listar Documentos/Txid

### ISSUE THREAD

**Issue by fescariot** [bacen/pix-perguntas-e-respostas#202]
Prezados, 

1. Na API de Recebimentos, na funcionalidade de "Listar Documentos" serão retornados apenas QR Codes dinâmicos?

2. Como o QR Code estático pode ser gerado pelo usuário recebedor, é possível que os valores de Txid sejam repetidos, já que o PSP não tem controle sobre este valor. Como poderá ser realizada a conciliação em caso de txid repetido?

3. Há previsão de nova versão da API de Recebimentos e previsão de nova documentação, com mais detalhes?

Sistema ou Área: API de Recebimentos

Grata.

**Comment by ninrod** [comment]
Olá @fescariot 

1. Estáticos também. 

2. A API na versão 2.0.0 será idempotente: será o usuário recebedor o responsável por gerar seus txids.  Os casos de colisão ficam sob a responsabilidade do usuário recebedor. 

3. Sim, a versão 2.0.0 está sendo implementada e será disponibilizada "em breve". Não consigo informar uma data precisa nesse momento.

**Comment by fescariot** [comment]
Muito obrigada @ninrod!
