### ISSUE TITLE
[Problema] no [SPI] - Bacen não está respondendo

### ISSUE THREAD

**Issue by rsabin** [bacen/pix-perguntas-e-respostas#203]
**Descreva sua dúvida ou problema**
Bacen não está respondendo a mensageria.

**Sistema ou Área**
SPI, INFRA. ICOM

**Identificador do Problema**
ResourceId enviado: `UEkBdCqeESWcUQ1Lkv5ECqBcQj7GM13l`
ISPB: `92702067`
Data-hora: `26/08/2020 08:53:55`

**Mensagens Enviadas / Recebidas**
Enviada uma pibr.001.

**Dados adicionais**
Coloquei só uma mensagem ai, mas não está respondendo nada.
Está retornando status `204 - No content`, como se não tivesse nada pra receber.

**Comment by bermr** [comment]
o DICT também está instável

**Comment by rsabin** [comment]
Esqueci de dizer, está retornando status `204 - No content`, como se não tivesse nada pra receber.

**Comment by rsabin** [comment]
Esqueci de dizer, está retornando status `204 - No content`, como se não tivesse nada pra receber.

**Comment by JeanFabichaki** [comment]
Estamos recebendo erros 500 no Dict

**Comment by CharlesMendes** [comment]
O BACEN informou ontem a noite que: 
**[Informe Pix - 040/2020] DICT: Release da versão RC6 no ambiente de homologação**

- _**O DICT foi atualizado para a versão v1.0-RC6 no dia de hoje, 25/08/2020. Com isso, a versão RC4 será descontinuada, e a versão RC5 permanece temporariamente ativa.**_ 

Pode ser que seja esse o motivo, verificarem se estão usando a RC4.

**Comment by rsabin** [comment]
Meu problema é na mensageria, e não no dict.
Logo após a criação desta issue, voltou a funcionar milagrosamente, porém alguns minutos depois começou a dar erro relatado na #205. 400-bad request. Não mexemos em nada da aplicação deste lado.

**Comment by cristianokbc** [comment]
@rsabi, o processamento das mensagens foi habilitado às 8h58. A `PIBR.002` deve ter sido recebida pouco tempo depois. No período de homologação, a janela se inicia às 9h. Geralmente deixamos online o maior tempo possível, mas hoje estava de fato indisponível fora da janela.
