### ISSUE TITLE
[Problema] no [DICT] -[Porta 16522 com problema] 

### ISSUE THREAD

**Issue by simonevirgilio** [bacen/pix-perguntas-e-respostas#204]
**Descreva sua dúvida

Conforme orientados no informe SPI 027/2020, efetuamos todos os ajustes das portas de comunicação, conforme abaixo:

Porta de homologação para DICT e ICOM: 16522
Porta de produção para DICT e ICOM: 16422
Porta de transferência de arquivos - ARQ (homologação e produção): 1130

Até o momento, informamos que a comunicação ICOM está funcionando normalmente, e também a no que se refere a transferências de arquivos, porém, a comunicação com o DICT só está sendo possível sem o uso da referida porta (16522) (apesar de apresentar funcionamento normal na porta 443).

Há alguma anomalia reportada neste sentido?

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
@simonevirgilio, acredito que esse problema está relacionado à questão abaixo. Poderia verificar?

O cabeçalho HTTP “Host” enviado pelos participantes deve conter apenas o nome completo do host, sem a porta, conforme exemplos abaixo:
 
·         Uso correto: “Host: icom-h.pi.rsfn.net.br”
·         Uso não suportado: “Host: icom-h.pi.rsfn.net.br:16522”
 
O envio da porta causará fechamento da conexão.

**Comment by fescariot** [comment]
Boa tarde,
Por favor, veja esse informe, pois acho que pode responder ao seu questionamento: https://www.bcb.gov.br/content/estabilidadefinanceira/informesspi/InformeSPI-031-2020.pdf
