### ISSUE TITLE
[Problema] no [SPI] - Retorno da ICOM, cabeçalho inválido

### ISSUE THREAD

**Issue by rsabin** [bacen/pix-perguntas-e-respostas#205]
**Descreva sua dúvida ou problema**
Hoje a ICOM da mensageria começou a responder com um erro novo, não mudamos nada no envio.

**Sistema ou Área**
SPI, ICOM

**Identificador do Problema**
Nossos headers enviados:
`{Accept=[multipart/mixed, application/xml, application/problem+xml, */*], User-Agent=[Bergs 1.20], Accept-Encoding=[gzip, *], Content-Type=[application/xml, charset=utf-8]}`
Não tem alguns como _content-lenght, host, connection_ pois a biblioteca que utilizamos adiciona automaticamente com base no corpo e url.

**Mensagens Enviadas / Recebidas**
Resposta recebida: `400 - Bad request`
```
<?xml version="1.0" encoding="UTF-8"?>
<problem xmlns="urn:ietf:rfc:7807">
	<type>https://icom.pi.rsfn.net.br/api/v1/error/invalidHeader</type>
	<title>Um dos cabeçalhos enviados não era esperado</title>
</problem>
```

**URL de conexão**
`/api/v1/out/92702067/stream/start`

**Informações adicionais**
Enfim, qual é o cabeçalho inválido?

**Comment by rsabin** [comment]
Acho que descobri o problema, era aqui.
Ativaram um tal de **APM** nos servidores que usamos pra fazer a requisição, aparentemente esse negócio adiciona algum header extra. Ainda estou coletando dados pra saber o que houve, mas sei que desativei essa ferramenta e voltou a funcionar.

**Comment by cristianokbc** [comment]
@rsabin, conforme relatei na resposta ao incidente aberto aqui no Bacen, trata-se de um cabeçalho `singularityheader` enviado na requisição.

**Comment by rsabin** [comment]
@cristianokbc Obrigado, só me confirma uma coisa. Você **me respondeu** o incidente por email?
Eu recebi o aviso de criação da interação, mas não recebi a conclusão dela. Preciso saber se alguma regra está me impedindo de receber as respostas.
