### ISSUE TITLE
[Dúvida][QR CODE Dinâmico] - Validar a assinatura digital (JWSSignature) com a chave pública obtida

### ISSUE THREAD

**Issue by hernan89** [bacen/pix-perguntas-e-respostas#206]
Vocês poderiam me recomendar uma lib que implementa a RFC 7515 para eu verificar a assinatura do payload obtido a partir de uma URL de um QR CODE dinâmico?

**Sistema ou Área**
QR Code PIX Dinâmico

**Dados adicionais**
https://www.bcb.gov.br/content/estabilidadefinanceira/cedsfn/Manual%20de%20Seguranca%20do%20PIX%20v3.0.pdf (Definições do padrão JWS)

**Comment by ninrod** [comment]
@hernan89 como Banco Central eu não poderia recomendar uma lib específica, mas vou deixar a issue em aberto para encorajar contribuições da comunidade.

**Comment by alesaudate** [comment]
Acredito que depende da linguagem. O padrão em sí é o descrito em
https://jwt.io/ . Nesse site, você encontra uma listagem de bibliotecas
disponíveis por linguagem.

Em qua., 26 de ago. de 2020 às 12:21, Filipe Silva <notifications@github.com>
escreveu:

**Comment by ninrod** [comment]
Obrigado pelas contribuições prezados.
