### ISSUE TITLE
[Problema] no [DICT] -  Ao informar Status para "Listar Reivindicações" em RC5

### ISSUE THREAD

**Issue by fbjhon** [bacen/pix-perguntas-e-respostas#207]
**Descreva sua dúvida ou problema**
A partir de hoje o endpoint https://dict-h.pi.rsfn.net.br/api/v1-rc5/claims/ não retorna registros quando informado na query parameters o campo Status, se informado sem status retorna corretamente os dados

**Sistema ou Área**
DICT

**Identificador do Problema**
Retorna lista vazia: ?Participant=92702067&Status=OPEN&Limit=200
Retorna lista com situação OPEN: ?Participant=92702067&Limit=200

**Mensagens Enviadas / Recebidas**
XML das mensagens enviadas e recebidas (sem assinatura fica melhor)

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc5/claims/ 

**Dados adicionais**
Teste realizado entre 17:10 e 17:20 de hoje

**Comment by luizlaydner** [comment]
Veja o outro issue #208 que você abriu sobre essa questão.

**Comment by fbjhon** [comment]
Ocorre que essa issue é pra reportar que uma alteração na RC6 está afetando a RC5, causando indisponibilidade de ambiente.

**Comment by luizlaydner** [comment]
Foi introduzido um bug que afetou a rc5 também, como você relatou. Já foi corrigido.
