### ISSUE TITLE
[Dúvida] no [DICT] - Qual o formato do array de Status para "Listar Reivindicações"

### ISSUE THREAD

**Issue by fbjhon** [bacen/pix-perguntas-e-respostas#208]
**Descreva sua dúvida ou problema**

Na versão RC6 o DICT passou aceitar uma array de status na query parameters para o parâmetro Status, porém ao tentar passar um array no formato abaixo não retornou dados, mas consultando somente pelo participante retorna reivindicações com status OPEN e CONFIRMED:

Endpoin: https://dict-h.pi.rsfn.net.br/api/v1-rc5/claims/?Participant=92702067&Status=OPEN,CONFIRMED&Limit=200

**Sistema ou Área**
DICT, 

**Identificador do Problema**
**Mensagens Enviadas / Recebidas**

**URL de conexão**

**Dados adicionais**

**Comment by luizlaydner** [comment]
A forma de passar um array de Status é na verdade assim:

https://dict-h.pi.rsfn.net.br/api/v1-rc5/claims/?Participant=92702067&Status=OPEN&Status=CONFIRMED&Limit=200

A especificação precisa de um esclarecimento nesse ponto!
 
Identificamos também um bug relacionado a isso que vamos corrigir o mais rápido possível.

**Comment by fbjhon** [comment]
O erro está relacionado a não retornar dados? Nos testes com array de uma posição no formato acima informado não retorna dados.

**Comment by HenriqueSimoes82** [comment]
@fbjhon bug corrigido. Obrigado pelo reporte detalhado.
