### ISSUE TITLE
Problema no DICT - Erro ao fazer download de arquivo de cids

### ISSUE THREAD

**Issue by JeanFabichaki** [bacen/pix-perguntas-e-respostas#209]
**Descreva sua dúvida ou problema**
Após criar um arquivo e o status dele estar AVAILABLE ao tentar fazer o download a seguinte mensagem é retornada:

`<?xml version="1.0" encoding="UTF-8"?>
<problem xmlns="urn:ietf:rfc:7807">
    <type>https://icom.pi.rsfn.net.br/api/v1/error/notFound</type>
    <title>Não encontrado</title>
</problem>`

Se for feito a consulta do arquivo pelo ID o retorno é o seguinte :

`<GetCidSetFileResponse>    
<CidSetFile>
        <Id>13298</Id>
        <Status>AVAILABLE</Status>
        <Participant>59588112</Participant>
        <KeyType>CPF</KeyType>
        <RequestTime>2020-08-27T13:04:40.015Z</RequestTime>
        <CreationTime>2020-08-27T13:04:40.381Z</CreationTime>
        <Url>https://arq-h.pi.rsfn.net.br/api/v1/download/59588111/cidsetfile/59588112_CPF_13298_2020-08-27T13:04:40.033Z.txt</Url>
        <Bytes>68055</Bytes>
        <Sha256>ff5e025e5aee370b37db0c4e856b4dc462be5be6684eae2f2775ebf5f45929be</Sha256>
    </CidSetFile>
</GetCidSetFileResponse>`

**Sistema ou Área**
DICT

**URL de conexão**
https://arq-h.pi.rsfn.net.br/api/v1/download/59588111/cidsetfile/59588112_CPF_13298_2020-08-27T13:04:40.033Z.txt

**Comment by jonasgiehl** [comment]
Mesma coisa por aqui.

**Comment by leandrocredendio** [comment]
Estamos com o mesmo problema

**Comment by renatofq** [comment]
Mesmo problema

**Comment by judahreis** [comment]
Identificamos o problema que está causando a indisponibilidade. Estamos trabalhando na correção.

**Comment by gizelysc** [comment]
@judahreis esse problema está causando indisponibilidade em qualquer funcionalidade em homologação? 
Pois estamos com dificuldade e a comunicação com o Bacen está intermitente apresentando TimeoutException.

**Comment by judahreis** [comment]
@gizelysc, somente para download de arquivos gerados pelo DICT. Não identificamos nenhum outro problema.

**Comment by evertongodoi** [comment]
@judahreis e @gizelysc, realmente por aqui também detectamos diversos **conection_error** no dict-h durante o período da tarde.

**Comment by judahreis** [comment]
Pessoal, erro corrigido. Já é possível realizar download de arquivos novamente.

@evertongodoi e @gizelysc, por favor, verifiquem se o problema nas outras funcionalidades não é relativo ao header "Host", que não pode utilizar a porta, conforme esse comunicado: https://www.bcb.gov.br/content/estabilidadefinanceira/informesspi/InformeSPI-031-2020.pdf

O uso da porta no header Host pode fazer com que a conexão seja rejeitada.

**Comment by jorgebaruchi** [comment]
Boa tarde, 
Com as mudanças de porta, o BACEN irá retornar a URL já pronta para download, certo? **exemplo**:
https://arq-h.pi.rsfn.net.br:**1130**/api/v1/download/59588111/cidsetfile/59588112_CPF_13298_2020-08-27T13:04:40.033Z.txt

**Comment by jorgebaruchi** [comment]
@judahreis, fizemos um teste e a responsa do endpont GET /cids/files/{Id}, retornou o link abaixo (sem a porta):

* https://arq-h.pi.rsfn.net.br/api/v1/download/43180355/cidsetfile/43180355_CPF_21652_2020-08-31T17:11:42.338Z.txt

Com isso, estamos obtendo um "Connection timed out". 

Não deveria vir o link já correto (com a porta)? 
Acho inseguro que tenhamos que manipular a URL, adicionando portas.

Concorda?
