### ISSUE TITLE
[Problema] no [DICT] - Erro na validação da Key de Tipo E-mail

### ISSUE THREAD

**Issue by JeanFabichaki** [bacen/pix-perguntas-e-respostas#21]
**Descreva sua dúvida ou problema**

Ao tentar cadastrar uma entry com o e-mail Raphaelle_Hodkiewicz45@hotmail.com o seguinte erro é retornado:

The property: entry.key, with value: Raphaelle_Hodkiewicz45@hotmail.com has an error: Value does not match regex '^[a-z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)*$', 

Mas na documentação da api é referenciada a documentação https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address (e-mails válidos W3C HTML5) que tem como exemplo a seguinte regex:

`/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/`

Fazendo alguns testes foi notado que o problema está em não aceitar letras maiúsculas no e-mail. 

**Sistema ou Área**
DICT

**Identificador do Problema**
Correlation-Id = 0D62654A21A549C69AA16B6D9F8606C1
ISPB = 59588111

**Mensagens Enviadas / Recebidas**
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><CreateEntryRequest xmlns:ns2="http://www.w3.org/2000/09/xmldsig#"><Entry><Key>Raphaelle_Hodkiewicz45@hotmail.com</Key><KeyType>EMAIL</KeyType><Owner><Type>NATURAL_PERSON</Type><TaxIdNumber>58359210705</TaxIdNumber><Name>Mrs. Jovan Rau</Name><TradeName></TradeName></Owner><Account><Participant>59588111</Participant><AccountNumber>08007136</AccountNumber><AccountType>CACC</AccountType><Branch>1521</Branch></Account></Entry><RequestId>3d6acd3d-c8b7-4674-bccc-077de6644804</RequestId><Reason>USER_REQUESTED</Reason></CreateEntryRequest> 
```

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1/entries/

**Dados adicionais**
A regex que o Bacen está utilizando só aceita minúsculas antes do @

^[a-z0-9.!#$%&'*+\/=?^_`{|}~-]+@

**Comment by judahreis** [comment]
Jean,

Os e-mails válidos seguem a regex da W3C, mas devem ser cadastrados em letras minúsculas (inclusive após o @) no DICT.
