### ISSUE TITLE
Problema no DICT - Erro ao Criar Arquivo de CIDs

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#210]
**Descreva sua dúvida ou problema**
Estamos com problemas na geração do arquivo de CIDs, mesmo Bacen retornando que o arquivo 61820817_EMAIL_13388_2020-08-27T13:33:08.710Z.txt esta disponível [AVAILABLE] para download, estamos recebendo erro 404 - notFound.

**Sistema ou Área**
DICT

**Identificador do Problema**

Nome do arquivo: 61820817_EMAIL_13388_2020-08-27T13:33:08.710Z.txt
Data: 27-08-2020 às 10:33:41
URL Arquivo: https://arq-h.pi.rsfn.net.br/api/v1/download/61820817/cidsetfile/61820817_EMAIL_13388_2020-08-27T13:33:08.710Z.txt

**Mensagens Enviadas / Recebidas**
<?xml version="1.0" encoding="UTF-8"?><problem xmlns="urn:ietf:rfc:7807"><type>https://icom.pi.rsfn.net.br/api/v1/error/notFound</type><title>Não encontrado</title></problem>

**URL de conexão**
URL: https://dict-h.pi.rsfn.net.br/api/v1-rc5/cids/files/13388

**Comment by judahreis** [comment]
Duplicado: https://github.com/bacen/pix-perguntas-e-respostas/issues/209
