### ISSUE TITLE
Problema no DICT - Erro ao baixar arquivo de CIDs

### ISSUE THREAD

**Issue by jorgebaruchi** [bacen/pix-perguntas-e-respostas#211]
**Descrição:** Ao baixar o arquivo de CIDs em "arq-h.pi.rsfn.net.br" estamos obtendo erro 404 (NOT FOUND). Existem outras issues abertas para este erro:

https://github.com/bacen/pix-perguntas-e-respostas/issues/209
https://github.com/bacen/pix-perguntas-e-respostas/issues/210

**Sistema ou Área**
DICT

**XML Retornado pelo DICT**
```xml
GetCidSetFileResponse><CidSetFile>
  <Id>14137</Id>
  <Status>AVAILABLE</Status>
  <Participant>13370835</Participant>
  <KeyType>EVP</KeyType>
  <RequestTime>2020-08-27T16:39:13.007Z</RequestTime>
  <CreationTime>2020-08-27T16:39:13.563Z</CreationTime>
  <Url>https://arq-h.pi.rsfn.net.br/api/v1/download/13370835/cidsetfile/13370835_EVP_14137_2020-08-27T16:39:13.022Z.txt</Url>
  <Bytes>3705</Bytes>
  <Sha256>45c9b8f7fe81fd4bf793b519cbd6a8bf6a1841e079905b0c01dc7cdfd45e5804</Sha256>
</CidSetFile>
</GetCidSetFileResponse>
```

**Response:**
Receive error on dict type: https://icom.pi.rsfn.net.br/api/v1/error/notFound, details: details not receive, status code: null, other error info: ClearingErrorResponseDTO(type=https://icom.pi.rsfn.net.br/api/v1/error/notFound, title=Não encontrado, status=null, detail=null, violations=null) 

**Endereço de download:**
https://arq-h.pi.rsfn.net.br/api/v1/download/13370835/cidsetfile/13370835_EVP_14137_2020-08-27T16:39:13.022Z.txt

**Comment by judahreis** [comment]
Duplicado: https://github.com/bacen/pix-perguntas-e-respostas/issues/209
