### ISSUE TITLE
[Problema] no [SISTEMA SPI] - PACS.008 recebida sem campo InstrPrty

### ISSUE THREAD

**Issue by julianemelo1104** [bacen/pix-perguntas-e-respostas#212]
**Descreva sua dúvida ou problema**
Recebemos uma PACS.008 sem o campo InstrPrty, que conforme documentação, no Brasil é de utilização obrigatória e opcional ao mesmo tempo:
Na coluna Mult. Brasil está [1..1]
Na coluna Regra para o Brasil está como opcional.

Qual seria o correto?

**Sistema ou Área**
SPI

**Identificador do Problema**
EndToEnD: E6070119020200827161992094527602

**Mensagens Enviadas / Recebidas**

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Envelope xmlns="https://www.bcb.gov.br/pi/pacs.008/1.4">
	<AppHdr>
		<Fr>
			<FIId>
				<FinInstnId>
					<Othr>
						<Id>00038166</Id>
					</Othr>
				</FinInstnId>
			</FIId>
		</Fr>
		<To>
			<FIId>
				<FinInstnId>
					<Othr>
						<Id>01181521</Id>
					</Othr>
				</FinInstnId>
			</FIId>
		</To>
		<BizMsgIdr>M000381660KED6XZSA11GO32DI5LXQCQ</BizMsgIdr>
		<MsgDefIdr>pacs.008.spi.1.4</MsgDefIdr>
		<CreDt>2020-08-27T19:19:18.634Z</CreDt>
		<Sgntr>
			<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
				<ds:SignedInfo>
					<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
					<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
					<ds:Reference URI="#key-info-id">
						<ds:Transforms>
							<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
						</ds:Transforms>
						<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
						<ds:DigestValue>pHDbsKklpORCx1ABvvlCOZIg/+2QjO90lesGqdGitbE=</ds:DigestValue>
					</ds:Reference>
					<ds:Reference URI="">
						<ds:Transforms>
							<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
							<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
						</ds:Transforms>
						<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
						<ds:DigestValue>gT4UPxr+4jAX322WZ6YXHnzZovlGDnjnFMXkEPoDdTo=</ds:DigestValue>
					</ds:Reference>
					<ds:Reference>
						<ds:Transforms>
							<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
						</ds:Transforms>
						<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
						<ds:DigestValue>vAvSi3zR/7wjfM7+JpTQLxA2Zpt8yQMEmbWyft0V8mA=</ds:DigestValue>
					</ds:Reference>
				</ds:SignedInfo>
				
				<ds:KeyInfo Id="key-info-id">
					<ds:X509Data>
						<ds:X509IssuerSerial>
							<ds:X509IssuerName>CN=Autoridade Certificadora do SERPRO Final SSL, OU=Servico Federal de Processamento de Dados - SERPRO, OU=CSPB-1, O=ICP-Brasil, C=BR</ds:X509IssuerName>
							<ds:X509SerialNumber>66906355272994040667436154809</ds:X509SerialNumber>
						</ds:X509IssuerSerial>
					</ds:X509Data>
				</ds:KeyInfo>
			</ds:Signature>
		</Sgntr>
	</AppHdr>
	<Document>
		<FIToFICstmrCdtTrf>
			<GrpHdr>
				<MsgId>M000381660KED6XZSA11GO32DI5LXQCQ</MsgId>
				<CreDtTm>2020-08-27T19:19:18.634Z</CreDtTm>
				<NbOfTxs>1</NbOfTxs>
				<SttlmInf>
					<SttlmMtd>CLRG</SttlmMtd>
				</SttlmInf>
			</GrpHdr>
			<CdtTrfTxInf>
				<PmtId>
					<EndToEndId>E6070119020200827161992094527602</EndToEndId>
				</PmtId>
				<IntrBkSttlmAmt Ccy="BRL">8.99</IntrBkSttlmAmt>
				<AccptncDtTm>2020-08-27T16:19:18.080Z</AccptncDtTm>
				<ChrgBr>SLEV</ChrgBr>
				<Dbtr>
					<Nm>SQT MC LEOH AL ASSAD DA SI</Nm>
					<Id>
						<PrvtId>
							<Othr>
								<Id>61389299260</Id>
							</Othr>
						</PrvtId>
					</Id>
				</Dbtr>
				<DbtrAcct>
					<Id>
						<Othr>
							<Id>00795586</Id>
							<Issr>1500</Issr>
						</Othr>
					</Id>
					<Tp>
						<Cd>CACC</Cd>
					</Tp>
				</DbtrAcct>
				<DbtrAgt>
					<FinInstnId>
						<ClrSysMmbId>
							<MmbId>60701190</MmbId>
						</ClrSysMmbId>
					</FinInstnId>
				</DbtrAgt>
				<CdtrAgt>
					<FinInstnId>
						<ClrSysMmbId>
							<MmbId>01181521</MmbId>
						</ClrSysMmbId>
					</FinInstnId>
				</CdtrAgt>
				<Cdtr>
					<Id>
						<PrvtId>
							<Othr>
								<Id>69415250020</Id>
							</Othr>
						</PrvtId>
					</Id>
				</Cdtr>
				<CdtrAcct>
					<Id>
						<Othr>
							<Id>00000023</Id>
							<Issr>0101</Issr>
						</Othr>
					</Id>
					<Tp>
						<Cd>CACC</Cd>
					</Tp>
				</CdtrAcct>
			</CdtTrfTxInf>
		</FIToFICstmrCdtTrf>
	</Document>
</Envelope>xml version="1.0" encoding="UTF-8" standalone="no"?>
<Envelope xmlns="https://www.bcb.gov.br/pi/pacs.002/1.4">
	<AppHdr>
		<Fr>
			<FIId>
				<FinInstnId>
					<Othr>
						<Id>00038166</Id>
					</Othr>
				</FinInstnId>
			</FIId>
		</Fr>
		<To>
			<FIId>
				<FinInstnId>
					<Othr>
						<Id>01181521</Id>
					</Othr>
				</FinInstnId>
			</FIId>
		</To>
		<BizMsgIdr>M000381660KED1U30R11GO32DIMRKOHX</BizMsgIdr>
		<MsgDefIdr>pacs.002.spi.1.4</MsgDefIdr>
		<CreDt>2020-08-27T16:56:18.123Z</CreDt>
		<Sgntr>
			<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
				<ds:SignedInfo>
					<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
					<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
					<ds:Reference URI="#key-info-id">
						<ds:Transforms>
							<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
						</ds:Transforms>
						<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
						<ds:DigestValue>pHDbsKklpORCx1ABvvlCOZIg/+2QjO90lesGqdGitbE=</ds:DigestValue>
					</ds:Reference>
					<ds:Reference URI="">
						<ds:Transforms>
							<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
							<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
						</ds:Transforms>
						<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
						<ds:DigestValue>rVPPfolrJksi25ktapoFz3Z0HjFIal9m9zrULJlqHzo=</ds:DigestValue>
					</ds:Reference>
					<ds:Reference>
						<ds:Transforms>
							<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
						</ds:Transforms>
						<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
						<ds:DigestValue>hh/1cuXk5MxqXLIKkr9wK8kXhSiJ37gEeUTzoAihLAc=</ds:DigestValue>
					</ds:Reference>
				</ds:SignedInfo>
				<ds:SignatureValue>SuB0hGGLY+LOeNbr1LZk5yG0z7NoYsh6AUKUJn681kDQjDYdjbLV95MDguoZTUV9WYb21l+LrcS7&#13;0cjtNbA1W8U19LOKET4H9nn9/aIEggfW1diVaNEplhdVM3ZhLfamdRabxbC79hFZvKSXHsygkN0X&#13;c4RBkP+dwN485/w0PQy9uLPsMa5ai4X3mLPh6fyJT6IV88BnaQYg6zRdPtlIjBw+rwVYTpJ35d2J&#13;VqrJRNL+Zc1jMbuYIsvkfc0IWGEHt/UyOqlL+3DlAEKJv3WmZzs+EfEKCh0SA9OITc5bcZzBc83m&#13;o9jUZCaVsHPT1JKWE16ZrVU/NgEUAQML+LQJ5w==</ds:SignatureValue>
				<ds:KeyInfo Id="key-info-id">
					<ds:X509Data>
						<ds:X509IssuerSerial>
							<ds:X509IssuerName>CN=Autoridade Certificadora do SERPRO Final SSL, OU=Servico Federal de Processamento de Dados - SERPRO, OU=CSPB-1, O=ICP-Brasil, C=BR</ds:X509IssuerName>
							<ds:X509SerialNumber>66906355272994040667436154809</ds:X509SerialNumber>
						</ds:X509IssuerSerial>
					</ds:X509Data>
				</ds:KeyInfo>
			</ds:Signature>
		</Sgntr>
	</AppHdr>
	<Document>
		<FIToFIPmtStsRpt>
			<GrpHdr>
				<MsgId>M000381660KED1U30R11GO32DIMRKOHX</MsgId>
				<CreDtTm>2020-08-27T16:56:18.123Z</CreDtTm>
			</GrpHdr>
			<TxInfAndSts>
				<OrgnlInstrId>E0118152120200827165615gFkGQ1qga</OrgnlInstrId>
				<OrgnlEndToEndId>E0118152120200827165615gFkGQ1qga</OrgnlEndToEndId>
				<TxSts>RJCT</TxSts>
				<StsRsnInf>
					<Rsn>
						<Cd>AB09</Cd>
					</Rsn>
					<AddtlInf>Pagamento rejeitado pelo PSP do recebedor</AddtlInf>
				</StsRsnInf>
			</TxInfAndSts>
		</FIToFIPmtStsRpt>
	</Document>
</Envelope>

**Comment by cristianokbc** [comment]
Na pacs.008, o elemento `PmtTpInf` é opcional, conforme coluna "Mult. Brasil". A coluna "Regra para o Brasil" diz respeito a ele. Apenas quando `PmtTpInf` estiver presente é que o elemento `InstrPrty` é obrigatório.

Desse modo, a mensagem sem o elemento está correta.
