### ISSUE TITLE
[Problema] no [SPI] - Erro ao solicitar arquivo de extrato na porta 1130

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#213]
**Descreva sua dúvida ou problema**

Olá! Durante os testes de download de arquivos da ICOM (teste para solicitar o arquivo de extrato) estamos percebendo que dois IPs diferentes são retornados, um funciona com a porta 443 e outro com a porta 1130. 
Os testes da porta 443 funcionam normalmente, mas os da porta 1130 tem nos devolvido esse erro "Connect to icom-h.pi.rsfn.net.br:1130 [icom-h.pi.rsfn.net.br/200.218.67.205] failed: Connection timed out (Connection timed out)". 

Há informação sobre alguma inconsistência que possa estar acontecendo nessa api?

**Sistema ou Área**
SPI

**Comment by RogerNeris** [comment]
@monise Utilize o Informe n.18 que foi enviado por e-mail que vai ajudar muito para baixar os arquivos. 
Um outro detalhe que não está no informe é utilizar no header "Accept: */*".

**Comment by cristianokbc** [comment]
@monise, entendi que o problema não ocorre mais.
