### ISSUE TITLE
[Problema] no [DICT] - Internal Server Error na criação de chave sem agência 

### ISSUE THREAD

**Issue by fbjhon** [bacen/pix-perguntas-e-respostas#214]
**Descreva sua dúvida ou problema**
Ao tentar incluir um EVP sem informar agência ocorre um erro HTTP 500 Internal Server Error. 
Na documentação da API o campo consta como opcional, o mesmo erro não ocorre quando informado agência.

**Sistema ou Área**
DICT,

**Identificador do Problema**
Correlation-Id : ECE853CE2BD84E6DA4E9367546DC32EA

**Mensagens Enviadas / Recebidas**
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CreateEntryRequest>
  <Entry>
    <KeyType>EVP</KeyType>
    <Account>
      <Participant>92934215</Participant>
      <AccountNumber>3907652822</AccountNumber>
      <AccountType>SLRY</AccountType>
      <OpeningDate>2010-01-10T03:00:00Z</OpeningDate>
    </Account>
    <Owner>
      <Type>LEGAL_PERSON</Type>
      <TaxIdNumber>62827217000127</TaxIdNumber>
      <Name>Conta de teste BPX</Name>
      <TradeName>Conta de teste BPX</TradeName>
    </Owner>
  </Entry>
  <Reason>USER_REQUESTED</Reason>
  <RequestId>108532e9-40d6-4c71-ad6d-30269c05b44d</RequestId>
</CreateEntryRequest>

<problem xmlns="urn:ietf:rfc:7807">
    <type>https://dict.pi.rsfn.net.br/api/v1/error/InternalServerError</type>
  <title>Internal Server Error</title>
  <status>500</status>
  <detail>Internal server error. Please contact support for details.</detail>
  <correlationId>ECE853CE2BD84E6DA4E9367546DC32EA</correlationId>
</problem>

**URL de conexão**

**Dados adicionais**
 - O teste realizado é com participante indireto
 - Versão RC5

**Comment by HenriqueSimoes82** [comment]
@fbjhon bug corrigido. Obrigado pelo reporte detalhado.
