### ISSUE TITLE
Dúvida no Dict - Exclusão de vículo por motivo de fraude

### ISSUE THREAD

**Issue by renatofq** [bacen/pix-perguntas-e-respostas#215]
**Descreva sua dúvida ou problema**
Atualmente a API de remover vínculo lista como motivos aceitos para exclusão `USER_REQUESTED`, `ACCOUNT_CLOSURE`, `ENTRY_INACTIVITY` e `RECONCILIATION`. Mas não `FRAUD`. A omissão é proposital ou deveria ser possível remover uma chave caso o participante identifique uma fraud?

**Comment by luizlaydner** [comment]
Qual versão da especificação você está vendo? Esse foi um erro da especificação da API, mas que já foi corrigido.

Ver aqui: https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API_do_DICT-v1-rc6.html#operation/deleteEntry
