### ISSUE TITLE
[Dúvida] no [SPI] - Retorno múltiplas transações nas PACS (teste de capacidade)

### ISSUE THREAD

**Issue by julianemelo1104** [bacen/pix-perguntas-e-respostas#216]
**Descreva sua dúvida ou problema**
A partir da issue https://github.com/bacen/pix-perguntas-e-respostas/issues/149 gostaríamos de verificar, qual a previsão do Bacen para liberar PACS.002 em lotes? Pois mesmo no teste de performance, continuamos recebendo mensagens individuais.

**Sistema ou Área**
SP

**Comment by gstabel** [comment]
Boa tarde.
Em um cenário de alto volume (como no teste de capacidade de 40mil PACS.008 em 10min) se houver um pouco de atraso no envio, facilmente ultrapassamos a capacidade física de consumo com os 6 sockets, se as transações não forem agrupadas na mesma PCAS.002 no retorno.
Ultrapassando assim o indicador de 200 ms de leitura das transações disponíveis.

Pode-se fazer a seguinte análise.
Tempo de GET /stream: 50 ms, temos 20 mensagens por/segundo. Com 6 sockets temos um máximo do 120 tps.

Em uma distribução não-uniforme em poucos segundos já ultrapassamos esses valor. Vide diagrama em anexo.
Att.
Gabriel

**Comment by cristianokbc** [comment]
Gabriel,

Pretendemos publicar essa alteração em alguns dias (talvez na próxima semana). Contudo, cenários como o que descreveu normalmente são resolvidos com **multipart** com **gzip**. Receber várias mensagens em uma mesma requisição reduz significativamente o tráfego de rede e ainda resolve as questões de latência. Uma resposta compactada com 10 mensagens pacs.002 usa entre 5KB e 6KB, contra 10 requisições de 1.3KB cada sem multipart.

**Comment by gstabel** [comment]
Obrigado @cristianokbc!

Talvez seria interessante rever a documentação se esta é a estratégia preferida para cenários de alto volume.
A implementação do _multipart_ está definida como **opcional** na secção 2.2.1.1. de Manual das Interfaces de Comunicação. Sendo que a implementação de mais de uma transação por mensagem é **obrigatória** nas definições utilizadas do formato ISO20022, sugerindo que esta é a estratégia preferencial.

Grato!
Gabriel Stabel

**Comment by victorgilc** [comment]
Opa pessoal,

Estou tendo erro 400 (bad request) ao tentar um request multipart. 
No meu cabeçalho tenho apenas "Accept: multipart/fixed"

Alguém sabe por que isso está acontecendo?

**Comment by gstabel** [comment]
@victorgilc , o correto é "Accept: multipart/**m**ixed", com "m".

**Comment by victorgilc** [comment]
> @victorgilc , o correto é "Accept: multipart/**m**ixed", com "m".

Digitei errado, na aplicação está certo.
