### ISSUE TITLE
[Problema] no [DICT] - Erro 404 no Dowload do arquivo de Reconciliação 

### ISSUE THREAD

**Issue by simonevirgilio** [bacen/pix-perguntas-e-respostas#218]
A URL de download do arquivo de Reconciliacao está sempre retornando erro 404 - Nao encontrado. E até terça feira estava funcionando normalmente. Houve alguma alteração?

DICT

**Comment by judahreis** [comment]
@simonevirgilio, acabei de testar aqui, e não houve problema. Vc pode testar novamente? Se ainda der problema, pode me passar qual arquivo foi?
