### ISSUE TITLE
Problema no DICT - Solicitação de arquivos de CID não entram para processamento

### ISSUE THREAD

**Issue by kertony** [bacen/pix-perguntas-e-respostas#219]
Estamos solicitando arquivos de CID e o status fica como solicitado
  "id": 18185,
  "status": "REQUESTED",

Aparentemente não está entrando para processamento.

**Comment by kertony** [comment]
Agora acabou de voltar a gerar o arquivo, contudo, está gerando arquivos muito grandes, aparentemente para todos os tipos de chaves com tamanhos parecidos, cerca de 0,5GB.

**Comment by leandrocredendio** [comment]
Estamos com o mesmo problema, os arquivos gerados estão com estão com tamanhos muito grandes.

**Comment by gizelysc** [comment]
Também estamos com o mesmo problema.

**Comment by HenriqueSimoes82** [comment]
@kertony @leandrocredendio problema solucionado. Favor solicitar novamente a geração do arquivo.
