### ISSUE TITLE
[Dúvida] CAMT060 - CAMT052

### ISSUE THREAD

**Issue by mfabioe** [bacen/pix-perguntas-e-respostas#22]
Em relação ao período informado, o documento CAMT060.xls (v1.7) define que o horário inicial é obrigatório, e o horário final não.

FromToTime   <FrToTm> |   | [0..1] | [0..1]
-- | -- | -- | --
FromTime <FrTm> | horarioInicialResultado | [1..1] | [1..1]
ToTime <ToTm> | horarioFinalResultado | [0..1] | [0..1]

No entanto, ao enviar uma requisição de CAMT.052 informando uma data e horário inicial, recebemos uma ADMI.002 com a seguinte mensagem de erro: "horário inicial de resultado e/ou horário final de resultado inválido(s)".

Construímos o XML (válido) da CAMT.060 da seguinte maneira:
```
<RptgPrd>
  <FrToDt>
    <FrDt>2020-06-25</FrDt>
  </FrToDt>
  <FrToTm>
    <FrTm>00:00:00.000Z</FrTm>
  </FrToTm>
  <Tp>ALLL</Tp>
</RptgPrd>
```

O que está errado?
Caso a consulta esteja errada, o XML não deveria ter sido invalidado? (nesse caso acho que o .xls e o XSD devem ser corrigidos)

**Comment by rafael-omello** [comment]
O erro é que não foi informado o horarioFinalResultado. Conforme xls da camt.060: "Este campo é usado para indicar o horário final do periodo da relação de lançamentos. O período máximo a ser consultado será de 24 horas. Horário no formato padrão UTC (hh:mm:ss.sssZ)"
A CAMT.060 pode ser usada para 3 tipos de consultas: camt.052, camt.053 e camt.054. Caso o tipo de consulta seja, por exemplo, camt.054, esse campo não deve ser informado. Portanto, não pode ser considerado obrigatório.

**Comment by mfabioe** [comment]
@rafael-omello entendi... mas na CAMT.060 solicitacao de 054 o campo horarioInicialResultado também nao é utilizado e ele está como obrigatório.

**Comment by mfabioe** [comment]
Eu entendo que talvez devesse ser assim:

FromToTime   <FrToTm> |   | [0..1] | [0..1]
-- | -- | -- | --
FromTime <FrTm> | horarioInicialResultado | [1..1] | [1..1]
ToTime <ToTm> | horarioFinalResultado | [1..1] | [1..1]


Quando o FromToTime é informado, deve acompanhar FromTime e ToTime.

**Comment by rafael-omello** [comment]
O seu entendimento está correto. O campo FromToTime possui multiplicidade [0..1], o que indica que ele é opcional. O subcampo FromTime possui multiplicidade [1..1], o que indica que esse campo é obrigatório caso seja provido o campo pai FromToTime. O subcampo ToTime deveria estar com a multiplicidade [1..1] no xls da CAMT.060 também, indicando que ele é obrigatório caso seja provido o campo pai FromToTime.  Inclusive, é dessa forma que o sistema está implementado. Iremos alterar a multiplicidade do ToTime para [1..1] no xls em versões futuras do catalogo.

**Comment by mfabioe** [comment]
@rafael-omello beleza. seria bom se o XSD refletisse esse comportamento também.

**Comment by rafael-omello** [comment]
O campo em questão é opcional, não devendo ser utilizado, por exemplo, no caso do tipo de consulta ser camt.054. Portanto, não podemos torná-lo obrigatório no XSD.

**Comment by mfabioe** [comment]
@rafael-omello estou falando do ToTime, nao do FromToTime.

**Comment by mfabioe** [comment]
Acho q no XSD o ToTime deveria ser obrigatorio quando o FromToTime existe. Mas o FromToTime é opcional.

**Comment by rafael-omello** [comment]
O XSD irá refletir a alteração a ser realizada no XLS da camt.060.

**Comment by thiagolapa** [comment]
Estou enviando um camt.060, para retornar um camt.052. O enviado retorna sucesso, mas não esta retornando o camt.52.
Poderia me ajudar?
