### ISSUE TITLE
[Dúvida] no [SPI] - Testes Homologatórios Pagamento / Recebimento

### ISSUE THREAD

**Issue by celobento** [bacen/pix-perguntas-e-respostas#220]
@luizlaydner boa tarde! 

Em testes homologatórios do pagamento e recebimento, quando procedo conforme orientação que você passou (ISPB do virtual é ISPB-direto + 1 (se ISPB do direto é 12345678 , o virtual é 12345679)) https://github.com/bacen/pix-perguntas-e-respostas/issues/172,  recebo:

RC10 - ISPB do participante recebedor inexistente

Como proceder para os testes de pagamento e recebimento? passando um outro código ISPB como recebedor? 

**URL de conexão**
icom-h.pi.rsfn.net.br

**Comment by rafael-omello** [comment]
Dúvidas de negócio referentes ao SPI devem ser encaminhadas para spi@bcb.gov.br.
