### ISSUE TITLE
[Dúvida] no [SPI] - Teste Pagamento / Recebimento

### ISSUE THREAD

**Issue by celobento** [bacen/pix-perguntas-e-respostas#221]
**Descreva sua dúvida ou problema**
Procedendo com os testes homologatório, no item:

_2. Testes de liquidação de pagamento e de devolução, de consulta saldo da Conta PI e detalhes de um lançamento
b) Receber uma pacs.008 e acatar o seu recebimento, enviando uma pacs.002 com status de aceitação;_

Como procedo para receber uma pacs.008? pois em testes que eu fiz, recebi várias rejeições:

- O ISPB do remetente nÃƒÂ£o ÃƒÂ© o mesmo da Assinatura XML
- PSP do cliente pagador nÃƒÂ£o ÃƒÂ© participante do SPI
- outros....

Na issue https://github.com/bacen/pix-perguntas-e-respostas/issues/220 citei uma forma que foi orientada, mas não deu certo.

**Sistema ou Área**
SPI

**URL de conexão**
https://www.in.gov.br/web/dou/-/carta-circular-n-4.055-de-25-de-maio-de-2020-258703788

**Dados adicionais**
CARTA CIRCULAR Nº 4.055, DE 25 DE MAIO DE 2020

**Comment by rafael-omello** [comment]
Dúvidas de negócio referentes ao SPI devem ser encaminhadas para spi@bcb.gov.br.
