### ISSUE TITLE
[Dúvida] no [SPI] - TxID duplicado em QR-Code estático

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-perguntas-e-respostas#222]
No caso de QR-Code dinâmico, o PSP recebedor pode recusar o Pix se estiver além do prazo especificado ou tiver sido baixado. No caso de QR-Code estático que tenha TxID (O TxID é opcional no estático), o PSP pode - sob instrução do EC, se necessário - recusar um TxID por o TxID já ter sido usado ?

**Comment by ninrod** [comment]
@rubenskuhl , sim, é perfeitamente possível.
