### ISSUE TITLE
[Problema] no [ICOM] - Erro 400 no long pulling multipart/mixed

### ISSUE THREAD

**Issue by birouska** [bacen/pix-perguntas-e-respostas#223]
Ao fazer uma requisição GET no endpoint :

https://icom-h.pi.rsfn.net.br/api/v1/out/{ispb}/stream/start

Passando o Cabeçalho:

Accept=multipart/mixed

Estou recebendo a seguinte response:

http status = 400
body:
<?xml version="1.0" encoding="UTF-8"?><problem xmlns="urn:ietf:rfc:7807">
<type>https://icom.pi.rsfn.net.br/api/v1/error/invalidHeader</type>
<title>Um dos cabeçalhos enviados não era esperado</title>
</problem>

**Sistema ou Área**
SPI

**Identificador do Problema**
Erro no inicio do stream de leitura do endpoint do long pulling

**URL de conexão**
https://icom-h.pi.rsfn.net.br/api/v1/out/{ispb}/stream/start

Estamos fazendo a chamada conforme a página 19 do manual das interfaces de comunicação versão 1.5:

![image](https://user-images.githubusercontent.com/831059/91612298-815af280-e953-11ea-9441-4da729899266.png)

Esse problema foi identificado hoje às 28-08-2020 16:00:00.364 e estava funcionando normalmente no fim da semana passada..
Houve alguma alteração? Poderia verificar.

**Comment by gstabel** [comment]
O cabeçakho correto seria ":" ao invés "=";
> Accept: application/xml

Quando tivemos esse cenário de erro 400, nossa situação era um cabeçalho sendo adicionado pelo nosso proxy fora dos permitidos:

![image](https://user-images.githubusercontent.com/737080/91629529-2a2f3f00-e9a0-11ea-8c18-73f082073950.png)

**Comment by cristianokbc** [comment]
@birouska, entendi que o problema não ocorre mais, correto?

**Comment by birouska** [comment]
Correto @cristianokbc muito obrigado pela informação!!!
