### ISSUE TITLE
[Dúvida] no [QR Code] - diferença entre o Manual do BR Code e o Manual de Padrões para Iniciação do Pix

### ISSUE THREAD

**Issue by cbarril** [bacen/pix-perguntas-e-respostas#224]
Do Manual do Código BR: https://www.bcb.gov.br/content/estabilidadefinanceira/SiteAssets/Manual%20do%20BR%20Code.pdf

![image](https://user-images.githubusercontent.com/48329960/91614673-5a52ef80-e958-11ea-86a9-f9165a456f08.png)

Interpreto que o campo "Modelo de campo de dados adicionais (62) - Modelo específico do sistema de pagamento (59)" é obrigatório.

Mas, do Manual dos Pais de Iniciação do Pix:
https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II_ManualdePadroesparaIniciacaodoPix-versao1.pdf

![image](https://user-images.githubusercontent.com/48329960/91614748-7c4c7200-e958-11ea-8724-f9e3eddf125d.png)

Eu interpreto que este campo não é necessário.

Qual interpretação está correta?

**Comment by ninrod** [comment]
@cbarril: 

[Aqui](https://www.bcb.gov.br/estabilidadefinanceira/arranjosintegrantesspb) você encontra a página que fala sobre o Manual do Br Code.

A versão do manual do BR Code que você está utlizando é a `1.0.0`, antiga. A atual é a `2.0.0`. 

Esse é o link correto: https://www.bcb.gov.br/content/estabilidadefinanceira/spb_docs/ManualBRCode.pdf

**Comment by rubenskuhl** [comment]
O link do manual do BRCode para o site da EMV Co. (que iria para a versão 1.1) está quebrado, e no site só estão disponíveis a versão 1.0 e a clarificação SB-206.

**Comment by ninrod** [comment]
@rubenskuhl, de qual página você está falando? 

a página correta é essa aqui: https://www.bcb.gov.br/estabilidadefinanceira/arranjosintegrantesspb

Home > 
Estabilidade financeira> 
Sistema de Pagamentos Brasileiro (SPB)> 
Arranjos de pagamento > 
Arranjos de pagamento integrantes do SPB

**Comment by rubenskuhl** [comment]
Em https://www.bcb.gov.br/content/estabilidadefinanceira/spb_docs/ManualBRCode.pdf fica o manual do BRCode, versão 2.0.0, linkada a partir da página acima. Dentro do documento tem este link:
https://www.emvco.com/terms-of-use/?u=/wpcontent/uploads/documents/EMVCo-Merchant-Presented-QR-Specificationv1-1.pdf

É esse link que não funciona. Fazendo a busca na EMV Co. (https://www.emvco.com/document-search/?action=search_documents&publish_date=&emvco_document_version=&emvco_document_book=&px_search=&emvco_document_technology%5B%5D=qr-code) não aparece a versão 1.1 desse documento, apenas a versão 1.

**Comment by ninrod** [comment]
@rubenskuhl , ok. Estou encaminhando uma alteração do Manual do BR Code (2.0.1). Deve sair em breve. 

Obrigado.
