### ISSUE TITLE
[Problema] no [DICT] - Comunicação com a api

### ISSUE THREAD

**Issue by rogeriomazzotti** [bacen/pix-perguntas-e-respostas#227]
**Descreva sua dúvida ou problema**
Estamos com problemas na comunicação em todas funcionalidades do DICT.
O problema começou a ocorrer no final da tarde de sexta-feira (28/08)

Houve alguma mudança nos ips ou portas para comunicação?

Erros retornados:
System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

The circuit is now open and is not allowing calls.

**Sistema ou Área**
DICT

**Identificador do Problema**
Ocorrendo com vários participantes que estão homologando.

**Mensagens Enviadas / Recebidas**
Consulta de Chave
[Information] Sending HTTP request **"GET" https://dict-h.pi.rsfn.net.br/api/v1-rc5/entries/teste@teste.com.br**
2020-08-31 12:36:28.058 -03:00 [Error] Erro Envio Bacen
System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc5/

**Comment by Leonardo34** [comment]
@rogeriomazzotti a porta no ambiente de HML foi alterada para a 16522, não mais a default do HTTPs (443).  Você deveria chamar a seguinte url https://dict-h.pi.rsfn.net.br:16522/api/v1-rc5/, explicitando a porta.

Aqui tem um ponto de atenção que foi mencionado na issue #204 onde o header `'Host'` não pode contar a porta. Saliento que estamos tendo alguns problemas ainda na nossa estrutura de comunicação que estamos tendando resolver internamente, mas pode ser que estamos tendo um erro promovido pela mudança do dia 28/08. Mas ainda estamos fazendo análise.

**Comment by rogeriomazzotti** [comment]
@Leonardo34 , fizemos o ajuste no Header Host e a comunicação voltou a funcionar.
Obrigado pela ajuda.
