### ISSUE TITLE
Problema no DICT - Erro ao criar entry

### ISSUE THREAD

**Issue by JeanFabichaki** [bacen/pix-perguntas-e-respostas#228]
Estamos com um erro ao salvar uma nova entry para o participant 59588111, sendo que ele é o participante direto.

`<problem xmlns="urn:ietf:rfc:7807"><type>https://dict.pi.rsfn.net.br/api/v1/error/Forbidden</type><title>Forbidden</title><status>403</status><detail>Participant  is not an indirect participant of the submitter</detail><correlationId>AA9F1E9AA7DE4F378637F3C5883340DC</correlationId></problem>`

Sendo que para o participant 59588112, que é o participant virtual está funcionando.
O mesmo erro acontece para o participant 92702067

**Sistema ou Área**
DICT

**Identificador do Problema**
AA9F1E9AA7DE4F378637F3C5883340DC

**Comment by judahreis** [comment]
@JeanFabichaki, o problema que ocasionou o erro AA9F1E9AA7DE4F378637F3C5883340DC  foi que o participante solicitando o registro de chave foi o 92702067, mas foi utilizado um canal usando o certificado do 59588111.  Ambos participantes são participantes diretos, e não podem usar o canal um do outro.
