### ISSUE TITLE
[Dúvida] no [DICT] - Grade de disponibilidade das funcionalidades

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#23]
**Descreva sua dúvida ou problema**

Gostaria de tirar algumas dúvidas sobre as grades de disponibilidade do DICT.

1 - Sobre a disponibilidade das funcionalidades da categoria B, quando houver janela de manutenção, será possível consultar os pedidos de portabilidade/reivindicação?

2 - Entendemos que se não for possível consultar os pedidos de portabilidade/reivindicação durante o período de manutenção, não é necessário o cumprimento do ANS de 60 segundos, correto?

3 - Se durante a geração de arquivo de CIDs (categoria D) for encontrado alguma divergência e o PSP tenha que excluir ou inserir alguma chave no DICT e o DICT estiver em manutenção (categoria B), será retornado um erro ao excluir/incluir uma chave? Nesse caso, o PSP pode deixar a base dessincronizada?

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
Monise,

1 - Não será possível consultar Port/Reiv. durante manutenções, somente chaves.

2 - Você está correta. O ANS para recebimento de port/reiv só existe quando o DICT estiver fora de manutenção.

3 - Para realizar as correções na base, o PSP deverá esperar o término da janela de manutenção.
