### ISSUE TITLE
[Dúvida] no [DICT] - Teste de capacidade consulta de chaves

### ISSUE THREAD

**Issue by gabrielmendesbb** [bacen/pix-perguntas-e-respostas#231]
É possível fazer teste prévios do teste de capacidade p testar a nossa infra e a conectividade  c o BACEN??
Pq fizemos alguns com quantidade menor de dados, e estamos recebendo erro 500 do BACEN apos algumas consultas.

<problem xmlns=\"urn:ietf:rfc:7807\"><type>https://dict.pi.rsfn.net.br/api/v1/error/InternalServerError</type><title>Internal server Error</title><status>500</status><detail>Internal server error. Please contact support for details.</detail><correlationId>68AA84E5E65841BEA7FD9BE2ABBC5762</correlationId></problem>

**Comment by HenriqueSimoes82** [comment]
@gabrielmendesbb o erro acontecia quando se pesquisava uma chave com formato inválido, nesse caso o telefone estava sem o '+'. 
Sistema foi corrigido e agora uma mensagem é apresentada. Obrigado pelo reporte.
