### ISSUE TITLE
[Dúvida] no [ARQ-H] A consulta de lançamentos CAMT052 está funcional em homologação ?

### ISSUE THREAD

**Issue by RogerNeris** [bacen/pix-perguntas-e-respostas#232]
Verificamos que para qualquer data de movimento e qualquer período a mensagem CAMT052 retorna o mesmo nome de arquivo. Em levantamento das consultas feitas no mês de Agosto, verificamos que para qualquer dia testado foi retornado o mesmo arquivo. Nos testes, estamos realizando o download deste arquivo, que retorna um arquivo csv vazio e compactado.
A consulta de lançamentos está funcional em homologação ?

Segue uma amostra de exemplos de Mensagens CAMT052 com o mesmo arquivo retornado.
28/08 - M000381660KEEPI60G11GO32DIA9OW8H
28/08 - M000381660KEEQ3ZIR11GU4TP4MAR97E
28/08 - M000381660KEEW1CBL11GU4TP4C607HV
31/08 - M000381660KEIJG67611GU4TP435HU2P
31/08 - M000381660KEIY45HR11GU4TP4B6GQG2

Arquivo fixo retornado:
https://arq-h.pi.rsfn.net.br/api/v1/download/28127603/extrato/C3187429BAA97F399DF35AB00B44D76AE5F392EAD94EC17E5A3EA8B7D330FCD2

**Comment by rafael-omello** [comment]
A consulta de lançamentos CAMT.052 está sim funcional em homologação. Pelo que eu pude observar, os extratos mencionados por você sempre retornaram 0 lançamentos, ou seja, o arquivo de resultado é vazio. Como nos extratos o nome do arquivo é o hash dele, se o arquivo tiver sempre o mesmo conteúdo, terá sempre o mesmo nome.

**Comment by celobento** [comment]
@RogerNeris / @rafael-omello  bom dia.

Estou recebendo **Connection reset**. Quais cabeçalhos estás usando?

Usando os mesmos que uso pra leitura da stream estou recebendo rejeição.

**Comment by celobento** [comment]
Seguem os cabeçalhos que usei pra fazer funcionar:

Content-Type : application/xml; charset=UTF-8
Host : arq-h.pi.rsfn.net.br
Accept : */*
Accept-Encoding : gzip

**Comment by RogerNeris** [comment]
Usamos isso mesmo e a extensão do arquivo como fixo ZIP.
