### ISSUE TITLE
[Dúvida] no [ARQ-H] Arquivo de lançamentos está retornando incorretamente vazio.

### ISSUE THREAD

**Issue by RogerNeris** [bacen/pix-perguntas-e-respostas#233]
Estamos recebendo um arquivo vazio de lançamentos de períodos de movimento que contem transações financeiras trocadas com outros bancos participantes do PIX. Independente de qual período seja solicitado o extrato de lançamentos, este sempre retorna vazio. Verificamos este mesmo problema já ocorreu em diversas outras consultas em datas passadas.
Seria possível identificar porque o arquivo está retornando vazio ?

Segue uma amostra de exemplos de Mensagens CAMT060 que retornaram CAMT052 com o arquivo vazio incorretamente.
31/08 - M2812760303e512b3f1cc4c5cb86fdd0
31/08 - M28127603dad1b59a484441d9854facb

referência anterior: https://github.com/bacen/pix-perguntas-e-respostas/issues/232

**Comment by rafael-omello** [comment]
Não foi encontrado nenhum lançamento para os parâmetros de consulta passados nas duas mensagens listadas acima. Portanto, o comportamento do SPI foi correto ao gerar arquivos vazios nesses casos. Vale ressaltar que os campos FromTime e ToTime da CAMT.060 representam horas UTC. Ou seja, se as horas passadas não estavam em UTC, é bem provável que essa seja a causa de não ter sido retornado nenhum lançamento.

**Comment by RogerNeris** [comment]
Na mensagem CAMT060, as tags `<RptgPrd><FrToDt><FrDt>2020-08-31</FrDt></FrToDt><FrToTm><FrTm>12:00:00.150Z</FrTm><ToTm>20:00:00.250Z</ToTm></FrToTm><Tp>ALLL</Tp></RptgPrd>` não expressam o horário de Brasília ?

**Comment by rafael-omello** [comment]
Os campos FromDate <FrDt>, ToDate <ToDt>, FromTime <FrTm> e ToTime <ToTm> para as consultas de relação de lançamentos são datas/horas UTC.
