### ISSUE TITLE
Dúvida no SPI -  Conexão simultânea ICOM /msgs

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#236]
**Descreva sua dúvida ou problema**
Pessoal, ao realizar a teste de multiplos envios de mensagens ICOM, verificamos que ao abrir mais de uma conexão no /api/v1/in/{ispb}/msgs as vezes recebemos uma negação de conexão.
Gostaria de saber se o endpoint do ICOM /msgs para envio de mensagens, não aceita no mais de uma conexão simultânea?

**Sistema ou Área**
SPI

**URL de conexão**
/api/v1/in/{ispb}/msgs

**Comment by cristianokbc** [comment]
@evertongodoi, o endpoint deve aceitar, sim, múltiplas conexões. Admite até 6 requisições simultâneas de um mesmo participante (mais conexões, mas apenas 6 requisições). Verifique se esse comportamento não coincidiu com a indisponibilidade ocorrida mais cedo.
