### ISSUE TITLE
Problema no ICOM - Conexão Timeout Bacen

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#237]
**Descreva sua dúvida ou problema**
Estamos recebendo timeout no ICOM https://icom-h.pi.rsfn.net.br/api/v1/out/61820817/stream/start

Remote conection closed: HTTPSConnectionPool(host='icom-h.pi.rsfn.net.br'): Read timed out.

Esta com algum problema no Bacen?

**Sistema ou Área**
SPI, INFRA

**Comment by gstabel** [comment]
Estamos com problema para estabelecer o socket aqui,

```
# curl -X GET -v -k  --cacert /root/cert/root.crt --key *** --cert *** https://icom-h.pi.rsfn.net.br:16522/api/v1/out/01181521/stream/start
* About to connect() to icom-h.pi.rsfn.net.br port 16522 (#0)
*   Trying 200.218.66.141...
* Connected to icom-h.pi.rsfn.net.br (200.218.66.141) port 16522 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
...
> GET /api/v1/out/01181521/stream/start HTTP/1.1
> User-Agent: curl/7.29.0
> Host: icom-h.pi.rsfn.net.br:16522
> Accept: */*
>
* SSL read: errno -5961 (PR_CONNECT_RESET_ERROR)
* TCP connection reset by peer
* Closing connection 0
curl: (56) TCP connection reset by peer
 
```

**Comment by cristianokbc** [comment]
@evertongodoi, mais cedo tivemos indisponibilidade no serviço de leitura de mensagens, que foi revolvido.

@gstabel, o problema de _connection reset_ é causado pelo envio do cabeçalho "Host" com a porta. Favor consultar o [Informe SPI 031/2020](https://www.bcb.gov.br/content/estabilidadefinanceira/informesspi/InformeSPI-031-2020.pdf).
