### ISSUE TITLE
[Dúvida] no [QR Code] - Campo Identificador nos Requisitos Mínimos para Experiência do Usuário

### ISSUE THREAD

**Issue by fescariot** [bacen/pix-perguntas-e-respostas#238]
Boa tarde,

O campo "Identificador" (da transação) apresentado no documento de Requisitos Mínimos na criação de um QR Code (página 19) é passível de inclusão pelo usuário. Este campo informado pelo usuário recebedor deve ser transmitido no QR Code Estático dentro do campo "TxId"? Ou o campo "TxId" é gerado automaticamente pelo sistema? 

**Sistema ou Área**
QR Code

![image](https://user-images.githubusercontent.com/69052675/92026289-2b14f780-ed37-11ea-841c-e625296a3f29.png)

![image](https://user-images.githubusercontent.com/69052675/92026328-38ca7d00-ed37-11ea-95c8-242164c723dd.png)

Grata.

**Comment by ninrod** [comment]
Bom dia @fescariot , 

Estamos sofisticando o entendimento a respeito do funcionamento do txid à medida que reunimos feedbacks sobre a versão 1.2.0. Quero aguardar até que esse entendimento esteja sólido o suficiente para que eu possa trazer uma informação precisa. 

Volto com a resposta em breve.

**Comment by ninrod** [comment]
> O campo "Identificador" (da transação) apresentado no documento de Requisitos Mínimos na criação de um QR Code (página 19) é passível de inclusão pelo usuário. Este campo informado pelo usuário recebedor deve ser transmitido no QR Code Estático dentro do campo "TxId"? Ou o campo "TxId" é gerado automaticamente pelo sistema?

@fescariot , na versão `2.0.0` da API PIX (antiga API de Recebimentos), a ser liberada provavelmente amanhã, o entendimento é que o txid é de responsabilidade do usuário recebedor, em qualquer caso. 

Em outras palavras, sim, o txid informado deve ser transmitido no QR Code Estático intacto.

**Comment by rafaelcam** [comment]
Olá @ninrod não ficou muito claro para mim essa questão. Minha ideia é realmente utilizar o`txId` como campo de conciliação visto que é o único campo que passa por todo o arranjo.
A doc de requisitos mínimos coloca como obrigatório o preenchimento desse campo por parte do usuário recebedor.

É permitido que minha automação gere esse campo identificador e mostre para o usuário somente para visualização sem a possibilidade de editar o valor e deixar disponível apenas o campo de descrição para preenchimento por parte do usuário recebedor? 

No documento de requisitos mínimos de experiência ao usuário não fica claro essa possibilidade.

Obg!
