### ISSUE TITLE
[Dúvida] na [Iniciação de Pagamento] - Pagamento por Inserção Manual

### ISSUE THREAD

**Issue by esantanapr** [bacen/pix-perguntas-e-respostas#239]
No Manual de Fluxos do Processo de Efetivação do Pix, na geração da ordem de pagamento por inserção manual dos dados, a etapa 5 do fluxo é nomeada como "Consulta e valida dados". 

![insercao_manual](https://user-images.githubusercontent.com/70662674/92027341-c2c71580-ed38-11ea-8e3d-b54df0d2f48d.PNG)

Como nessa etapa "Caso o usuário pagador tenha inserido os dados manualmente, o PSP do usuário pagador não precisa consultar o DICT para validar os dados do recebedor", qual a forma de validação desses dados?

**Comment by carloschioquetta** [comment]
Nesse caso, PSP vai verificar se foram preenchidos todos os campos necessários, conforme documento de Requisitos mínimos para a experiência do usuário e se estão no formato correto. No caso de possuir acesso aos dados da conta (por exemplo, em caso de Pix entre usuários do mesmo PSP) deve buscar e apresentar o nome do recebedor, também conforme o documento citado.

**Comment by carloschioquetta** [comment]
Nesse caso, PSP vai verificar se foram preenchidos todos os campos necessários, conforme documento de Requisitos mínimos para a experiência do usuário e se estão no formato correto. No caso de possuir acesso aos dados da conta (por exemplo, em caso de Pix entre usuários do mesmo PSP) deve buscar e apresentar o nome do recebedor, também conforme o documento citado.

**Comment by carloschioquetta** [comment]
Nesse caso, PSP vai verificar se foram preenchidos todos os campos necessários, conforme documento de Requisitos mínimos para a experiência do usuário e se estão no formato correto. No caso de possuir acesso aos dados da conta (por exemplo, em caso de Pix entre usuários do mesmo PSP) deve buscar e apresentar o nome do recebedor, também conforme o documento citado.

**Comment by carloschioquetta** [comment]
Nesse caso, PSP vai verificar se foram preenchidos todos os campos necessários, conforme documento de Requisitos mínimos para a experiência do usuário e se estão no formato correto. No caso de possuir acesso aos dados da conta (por exemplo, em caso de Pix entre usuários do mesmo PSP) deve buscar e apresentar o nome do recebedor, também conforme o documento citado.

**Comment by carloschioquetta** [comment]
Nesse caso, PSP vai verificar se foram preenchidos todos os campos necessários, conforme documento de Requisitos mínimos para a experiência do usuário e se estão no formato correto. No caso de possuir acesso aos dados da conta (por exemplo, em caso de Pix entre usuários do mesmo PSP) deve buscar e apresentar o nome do recebedor, também conforme o documento citado.
