### ISSUE TITLE
[Dúvida|Problema] no [SISTEMA] - Exclusão de chave no DICT por suspeita de fraude

### ISSUE THREAD

**Issue by PamelaFabiao** [bacen/pix-perguntas-e-respostas#24]
No manual de especificações técnicas, item 2.6.4.2, informa que poderemos realizar a exclusão de uma chave de endereçamento no DICT que estiverem com suspeita de fraude. Essa operação deve ser realizada pelo PSP sem autorização prévia do usuário. 
Porém não localizamos um motivo de exclusão a ser utilizado nessa ocasião. Poderiam nos informar qual o código do motivo a ser utilizado nessa exclusão?

Outro ponto, o DICT informará aos PSP as chaves que estão sinalizadas por motivo fraude ou que foram excluídas por esse mesmo motivo no momento do pagamento?

**Comment by luizlaydner** [comment]
@PamelaFabiao  De fato não está constando na especificação da API do DICT o código para exclusão devido a suspeita/confirmação de fraude no uso da chave. Isso será corrigido na próxima _release candidate_ da especificação da API. O código a ser colocado no campo `Reason` da requisição para esse caso será `FRAUD` .
