### ISSUE TITLE
[Dúvida] no [QR Code] - Chaves públicas

### ISSUE THREAD

**Issue by fescariot** [bacen/pix-perguntas-e-respostas#240]
Bom dia,

Conforme Manual de Segurança do Pix Versão 3.0, o Bacen disponibilizará arquivo contendo todos os certificados ativos.
Gostaríamos de saber qual o caminho completo que serão disponibilizados estes arquivos no sistema STA. Há previsão de mais detalhes sobre esse assunto?

Issue parecida: https://github.com/bacen/pix-perguntas-e-respostas/issues/135

Grata, Fernanda.

**Comment by ninrod** [comment]
Prezada @fescariot ,

O BC ainda não iniciou a recepção de arquivos de certificados do tipo CERTQRC, mas após a recepção de arquivos desse tipo ser iniciada, o download do arquivo com todos os certificados CERTQRC dos PSPs não será realizado via STA, mas sim por meio da interface ARQ, conforme seção 4 do Manual das Interfaces de Comunicação, disponível em https://www.bcb.gov.br/estabilidadefinanceira/comunicacaodados.

**Comment by fescariot** [comment]
Boa tarde @ninrod ! 
Muito obrigada pelo retorno. 

Grata.
