### ISSUE TITLE
Dúvida na Portabilidade - Cenários

### ISSUE THREAD

**Issue by clovisj** [bacen/pix-perguntas-e-respostas#243]
**Descreva sua dúvida ou problema**
Encontramos divergências entre documentações referentes ao processo de portabilidade e gostaria de verificar qual seriam os cenários corretos a serem contemplados para a experiência do usuário.

Referente a portabilidade, segundo o documento - Manual Operacional do Diretório de Identificadores de Contas Transacionais (DICT). Tivemos o entendimento que existem 2 cenários em que o usuário pode pedir portabilidade, sendo eles:

1º - Durante o processo de cadastro de uma chave, em que ao tentarmos o registro como Banco Bari, o DICT retorna informando que já existe registro para esse chave em outro PSP, nesse caso, podemos disponibilizar que o usuário solicite a portabilidade.

2º - Dentro da área de gerenciamento de chaves, disponibilizarmos que o usuário voluntariamente venha até sua conta no Banco Bari e solicite a portabilidade de uma determinada chave para o Bari.

Agora, segundo o documento -  Especificações técnicas e de negócio do ecossistema de pagamentos instantâneos brasileiro, tivemos o entendimento que havia um cenário o qual o usuário já possui uma chave cadastrada no Banco Bari, e voluntariamente vem até sua conta e solicita que nós disponibilizemos essa chave para outra instituição.
Esse cenário é realmente exigido? Ou devemos seguir somente com os cenários 1 e 2 acima?

**Sistema ou Área**
Portabilidade

**Comment by carloschioquetta** [comment]
O processo de portabilidade é iniciado no PSP reivindicador, valendo, portanto, os fluxos determinados no Manual Operacional do DICT.
