### ISSUE TITLE
[Dúvida] no [DICT, SPI] - Sobre as ANS

### ISSUE THREAD

**Issue by msyamada** [bacen/pix-perguntas-e-respostas#245]
**Descreva sua dúvida ou problema**
Sobre os indicadores de ANS do manual de tempos do PIX, os tempos medidos devem considerar somente as operações realizadas com sucesso ou também aquelas operações em que houveram alguma exceção (ex.: quando ocorre um erro 503 - Service Unavailable na comunicação com o DICT)

**Sistema ou Área**
DICT e SPI

**Comment by carloschioquetta** [comment]
No DICT, devem ser considerados todas as operações de sucesso ou insucesso no cálculo dos ANS.
