### ISSUE TITLE
[Dúvida] no [QR Code] - Informações contidas

### ISSUE THREAD

**Issue by BrunoPanassi** [bacen/pix-perguntas-e-respostas#249]
De antemão peço desculpas se minhas dúvidas forem tolas, pois estou confuso com o que se refere as atividades sobre esse assunto para uma software house.

O que sei até o momento é que o PSP vai fornecer uma API para que a software house envie um JSON com os dados referentes à transação, para que retorne uma string, e a partir dessa string gerar um QR Code, e a partir da leitura desse QR Code, irá abrir o aplicativo do PSP para o pagamento, esta informação é válida? Caso sim, já existe documentação dos PSP´s sobre essa API?

**Comment by ninrod** [comment]
Prezado @BrunoPanassi sinta-se à vontade para fazer todas as perguntas que você julgar relevantes. O PIX é um arranjo de pagamentos instantâneos criado pelo Banco Central para o proveito da sociedade brasileira e o BCB tem todo o interesse em responder perguntas técnicas relacionadas a esse novo arranjo.

Com relação à sua pergunta, sim, o PSP fornecerá uma API que tem que ser necessariamente aderente à __[especificação OpenAPI 3.0](https://github.com/bacen/pix-api-recebimentos)__ estabelecida pelo Banco Central do Brasil.

Na versão `1.2.0` desta API, o endpoint específico que pode ser utilizado para criar um "documento de cobrança", que pode ser iniciado via  QR Code, encontra-se __[aqui](https://github.com/bacen/pix-api-recebimentos/blob/1.2.0/openapi.yaml#L46)__.

Já aproveito para adiantar que uma versão `2.0.0` será liberada "em breve", incorporando alterações realizadas em função de feedbacks do mercado com relação à versão `1.2.0` e também em função de um entendimento mais sofisticado do produto por parte do Banco Central. 

Por último, você encontra uma série de documentos importantes na página oficial do Banco Central __[aqui](https://www.bcb.gov.br/estabilidadefinanceira/forumpagamentosinstantaneos)__.
