### ISSUE TITLE
[Dúvida no DICT - Dados do cliente dono da chave

### ISSUE THREAD

**Issue by kertony** [bacen/pix-perguntas-e-respostas#25]
Realizamos o seguinte cenário de teste:
1.	Ação 1: Criamos uma chave de endereçamento apontando para uma conta e informando um nome
2.	Ação 2: Alteramos o nome do cliente no cadastro
3.	Ação 3: Criamos outra chave de endereçamento apontando para a mesma conta e informando o novo nome
4.	Ação 4: Solicitamos um PSP parceiro ajuda na consulta das chaves e as consultas retornaram nomes diferentes para cada chave
 
Dúvida:
1.	Como Trata-se da mesma conta e, claro, o mesmo PSP, consequentemente o mesmo cadastro, o BACEN não deveria impedir um nome diferente do já inserido para a conta ou atualizar o nome no cadastro (separado da chave) com a informação mais recente?
2.	Caso o item 1 não aconteça entendo que o Sync nunca irá funcionar, pois no cadastro consta o nome atualizado: 
  a.	entryAttributes = keyType "&" key "&" ownerTaxIdNumber "&" ownerName "&" ownerTradeName "&" participant "&" branch "&" accountNumber "&" accountType
  b.	cidBytes = hmacSha256(requestIdBytes, entryAttributes)
  c.	cid = lowercase-hexadecimal(cidBytes)
 

DICT

Sync

**Comment by judahreis** [comment]
Kertony,

Se houve mudança no nome do titular da chave, o participante precisa modificar todos os vínculos. Da forma com que está hoje o dict, seria necessário fazer a remoção da chave, e incluir novamente com os dados atualizados.

Me parece que é possível fazer uma melhoria na mensagem de modificação do vínculo para modificar apenas o nome também. Vamos analisar.

**Comment by judahreis** [comment]
@Kertony, adicionamos a melhoria de modificação de dados pessoais no nosso backlog. Acompanhe as releases para saber quando estará disponível (provavelmente só será implementado depois de novembro). Contudo, é importante que os participantes se preparem para atualizar os cadastros de mudanças de nome fazendo a remoção e seguida da inclusão com os dados atualizados.

**Comment by kertony** [comment]
Obrigado pelo retorno. Combinado. Vamos ajustar aqui do nosso lado.
