### ISSUE TITLE
[Dúvida] no SPI - Dúvida multiplas transações PACS.002

### ISSUE THREAD

**Issue by adrianbp** [bacen/pix-perguntas-e-respostas#250]
**Descreva sua dúvida ou problema**
Boa Tarde!
No cenário de multiplas transações dentro de uma mesma mensagem PACS.002. O PSP poderá receber tanto confirmação/rejeição de liquidação via PACS.008 quanto  confirmação/rejeição de devolução via PACS.004 ?

**Sistema ou Área**
SPI

Exemplo PACS002:

    <Document>
        <FIToFIPmtStsRpt>
            <GrpHdr>
                <MsgId>M00038166df3c551673d240089a9a578</MsgId>
                <CreDtTm>2020-04-08T12:46:26.317Z</CreDtTm>
            </GrpHdr>
            <TxInfAndSts>
                <OrgnlInstrId>E9999901020200408094660d8c628d1e</OrgnlInstrId>
                <OrgnlEndToEndId>E9999901020200408094660d8c628d1e</OrgnlEndToEndId>
                <TxSts>ACCC</TxSts>
                <FctvIntrBkSttlmDt>
                    <DtTm>2020-04-08T12:46:26.317Z</DtTm>
                </FctvIntrBkSttlmDt>
                <OrgnlTxRef>
                    <IntrBkSttlmDt>2020-04-08</IntrBkSttlmDt>
                </OrgnlTxRef>
            </TxInfAndSts>
            <TxInfAndSts>
                <OrgnlInstrId>D00038166201907261559y6j6mt9l0pi</OrgnlInstrId>
                <OrgnlEndToEndId>E00038166201907261559y6j6mt9l0pi</OrgnlEndToEndId>
                <TxSts>ACCC</TxSts>
                <FctvIntrBkSttlmDt>
                    <DtTm>2020-04-08T12:46:26.317Z</DtTm>
                </FctvIntrBkSttlmDt>
                <OrgnlTxRef>
                    <IntrBkSttlmDt>2020-04-08</IntrBkSttlmDt>
                </OrgnlTxRef>
            </TxInfAndSts>
            <TxInfAndSts>
                <OrgnlInstrId>E99999010202004080946d6fd8a70ea3</OrgnlInstrId>
                <OrgnlEndToEndId>E99999010202004080946d6fd8a70ea3</OrgnlEndToEndId>
                <TxSts>RJCT</TxSts>
                <StsRsnInf>
                    <Rsn>
                        <Cd>AB03</Cd>
                    </Rsn>
                    <AddtlInf>Informações complementares sobre o motivo do status</AddtlInf>
                </StsRsnInf>
            </TxInfAndSts>
            <TxInfAndSts>
                <OrgnlInstrId>D00038166201907261559y6j6mt9l8pi</OrgnlInstrId>
                <OrgnlEndToEndId>E999990102020040809469339e5d7e15</OrgnlEndToEndId>
                 <TxSts>RJCT</TxSts>
                <StsRsnInf>
                    <Rsn>
                        <Cd>AB03</Cd>
                    </Rsn>
                    <AddtlInf>Informações complementares sobre o motivo do status</AddtlInf>
                </StsRsnInf>
            </TxInfAndSts>
           
        </FIToFIPmtStsRpt>
    </Document>

**Comment by cristianokbc** [comment]
Sim, o participante poderá receber tanto confirmação/rejeição de liquidação via PACS.008 quanto confirmação/rejeição de devolução via PACS.004.
