### ISSUE TITLE
[Dúvida] no [DICT] - Estados possíveis para Cancelar um Relato de Infração

### ISSUE THREAD

**Issue by gizelysc** [bacen/pix-perguntas-e-respostas#251]
**Descreva sua dúvida **
Estou com dúvida em quais estados  da notificação de infração é possível que ocorra o Cancelamento.

Na documentação da Api do Dict diz que : O criador do relato pode cancelá-lo a qualquer momento, mesmo depois de fechado.

No Manual operacional do Dict diz que o PSP que fez a notificação pode cancelá-la enquanto a notificação de infração não estiver no estado “analisada" (pag 55).

Se puderem me ajudar nessa questão,  para esclarecer se uma notificação analisada (fechada) pode ser cancelada ou não.
Obrigada!

**Sistema ou Área**
DICT

**Comment by carloschioquetta** [comment]
A informação correta é a da API (o outro documento já foi corrigido): a contraparte pode argumentar algo que mude a opinião do PSP criador. Assim, o criador pode cancelar o relato mesmo após a análise da contraparte, o que decrementa o contador.
