### ISSUE TITLE
[Dúvida] no [QR Code] estático - Especificação do campo infoAdicional para o QR code estático

### ISSUE THREAD

**Issue by jocimarcan** [bacen/pix-perguntas-e-respostas#252]
Prezados,

Quanto ao pagamento por meio de QR code estático, é facultado ao usuário o preenchimento de dois campos de informações adicionais: Identificador e Descrição. No entanto, após analisar o Manual do BR code, o manual EMV QRCPS e o Manual de iniciação do Pix, percebi que os IDs dos campos Identificador e Descrição parecem não estar especificados. 

**(1) Como um outro PSP conseguirá identificar, e exibir a seu usuário inequivocamente em campos separados, o Identificador e a Descrição de um QR code estático que o meu PSP gerou, conforme exemplifica o manual de experiência do usuário?**

Geração do QR code estático, Manual de experiência do usuário, pag 7
![](https://raw.githubusercontent.com/jocimarcan/duvidasBacen/master/Infoadicionais/gera%C3%A7%C3%A3o.png)
Pagamento por QR code estático, Manual de experiência do usuário, pag 19
![](https://raw.githubusercontent.com/jocimarcan/duvidasBacen/master/Infoadicionais/pagamento.png)
Especificação do campo InfoAdicional, Manual de Iniciação ao Pix, pag 23
![](https://raw.githubusercontent.com/jocimarcan/duvidasBacen/master/Infoadicionais/Screenshot_2.png)

[Sugestão] Sugiro analisar a possibilidade de fornecer um calendário (data de criação e data de vencimento) no campo de InfoAdicional do QR code estático, à semelhança do que é feito para o QR code dinâmico. Isso resolveria um problema de ciclo de vida do QR code estático (quando um PSP, que gerou um QR code estático com TxId – embora há questões de colisão em aberto -, poderia seguramente excluí-lo de sua base de dados?). Ao mesmo tempo, possibilitaria atender algumas necessidades de negócio que apenas o QR code dinâmico atenderia: Isso representa vantagens e possíveis desvantagens.

Obrigado!

Referências:
https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II_ManualdePadroesparaIniciacaodoPix-versao1.pdf, pag 7
https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/IV_RequisitosMinimosparaExperienciadoUsuario-versao1.pdf, pag 19
https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/IV_RequisitosMinimosparaExperienciadoUsuario-versao1.pdf, pag 23

**Comment by CharlesMendes** [comment]
Algum retorno sobre esse ponto pessoal?

**Comment by ninrod** [comment]
@jocimarcan  e @CharlesMendes , minhas respostas:

> Quanto ao pagamento por meio de QR code estático, é facultado ao usuário o preenchimento de dois campos de informações adicionais: Identificador e Descrição. No entanto, após analisar o Manual do BR code, o manual EMV QRCPS e o Manual de iniciação do Pix, percebi que os IDs dos campos Identificador e Descrição parecem não estar especificados.

* O "identificador" é o `txid`, campo 62-05, conforme especificado no __[manual do BR Code](https://www.bcb.gov.br/content/estabilidadefinanceira/spb_docs/ManualBRCode.pdf)__. O Manual do BR Code torna o campo 62-05 obrigatório, mas o usuário pode optar por informar `***`. Se o gerador do QR optar por não utilizar um transactionID, o valor `***` deverá ser usado para indicar essa escolha. Essa definicão encontra-se no documento EMV QRCPS–MPM QRCodes for Payment Systems – Merchant Presented Mode, seção `4.8.1.2`.

* Quanto à "descrição", é o campo `infoAdicional`, conforme descrito na seção sobre QR EStático no manual de iniciação do PIX. 


> [Sugestão] Sugiro analisar a possibilidade de fornecer um calendário (data de criação e data de vencimento) no campo de InfoAdicional do QR code estático, à semelhança do que é feito para o QR code dinâmico. Isso resolveria um problema de ciclo de vida do QR code estático (quando um PSP, que gerou um QR code estático com TxId – embora há questões de colisão em aberto -, poderia seguramente excluí-lo de sua base de dados?). Ao mesmo tempo, possibilitaria atender algumas necessidades de negócio que apenas o QR code dinâmico atenderia: Isso representa vantagens e possíveis desvantagens.

* O QR Estático apresenta um escopo de funcionalidade bastante restrito. Questões como data de vencimento e outras possibilidades serão abarcadas somente via QR Dinâmico. Em tempo, o QR Estático não é gerado pelo PSP recebedor, mas sim diretamente pelo usuário recebedor por meio de algum elemento de software.

**Comment by jocimarcan** [comment]
@ninrod , acho que vale esclarecer um pouco mais. 
Ok, entendi que _txId = Identificador_ e que _infoAdicional = Descrição_, embora esse mapeamento não esteja evidente nos manuais. Mas olhe sua resposta e o que está no manual de iniciação do Pix, pag 16:

**Resposta:**
> Em tempo, o QR Estático não é gerado pelo PSP recebedor, mas sim diretamente pelo usuário recebedor por meio de algum elemento de software.

**Manual:**
![](https://raw.githubusercontent.com/jocimarcan/duvidasBacen/master/Infoadicionais/txIdInfoAdicional.png)

Acredito que a dúvida posta se enquadraria no primeiro _bullet point_ , uma vez que a geração do QR ocorre por meio de interface do aplicativo do PSP. Nesse caso, a resposta conflitaria com o manual.
Talvez sua resposta se refira ao segundo _bullet point_, quando o usuário recebedor, à revelia e independente de um PSP (certo?), gera um QR code estático, a fim de enfatizar que um QR code estático deve ser gerado no _frontend_, sem necessidade de armazenamento na sua geração (certo?).

**Comment by ninrod** [comment]
> Ok, entendi que txId = Identificador e que infoAdicional = Descrição, embora esse mapeamento não esteja evidente nos manuais. Mas olhe sua resposta e o que está no manual de iniciação do Pix, pag 16:

Estou realizando alterações nos manuais nesse momento. Se você quiser citar trechos específicos que você considera que não estão claros nesse contexto, eu posso avaliar melhorar a redação. 

> Acredito que a dúvida posta se enquadraria no primeiro bullet point , uma vez que a geração do QR ocorre por meio de interface do aplicativo do PSP. Nesse caso, a resposta conflitaria com o manual.
Talvez sua resposta se refira ao segundo bullet point, quando o usuário recebedor, à revelia e independente de um PSP (certo?), gera um QR code estático, a fim de enfatizar que um QR code estático deve ser gerado no frontend, sem necessidade de armazenamento na sua geração (certo?).

Adianto que essa redação do txid será alterada. O entendimento corrente é que o txid será criado pelo usuário recebedor e esse mesmo txid será atribuído à PACS008, em qualquer caso. Ademais, não há preenchimento de txid no fluxo de transf. manual. 

O conjunto de documentos relacionado à API PIX (de API de Recebimentos se chamará API PIX agora) deve ser liberado muito em breve, possivelmente amanhã, juntamente com a versão `2.0.0` da API PIX, então todas essas questões devem ficar mais evidentes. 

Além disso, esclareço que a geração do QR Estático não faz parte da API PIX. Qualquer elemento de software pode gerar um QR Estático. No caso específico do QR Estático gerado pelo aplicativo mobile, o fluxo de UX é regrado pelo documento de req. mínimos de UX do Pix. 

Vou tomar a liberade de fechar essa issue tendo em vista a proximidade dessa liberação. 

Como sempre, fiquem à vontade para trazer suas dúvidas em relação à nova versão da documentação.

**Comment by jocimarcan** [comment]
Obrigado @ninrod, esse mapeamento  (txId = Identificador e infoAdicional = Descrição) não tinha ficado evidente para mim nos manuais, mas ao menos agora temos essa _issue_, em que isso fica bem claro.

**Comment by mvleandro** [comment]
@ninrod Qual o domínio de valores aceitos para o txId? Vocês acham que realmente faz sentido deixar o usuário criar um identificador para o recebimento? O campo infoAdicionais já não cumpriria este papel?

Em tempo: Preciso de um identificador único para correlacionar o recebimento ao qrcode. Como fazer neste caso? Uma vez que se é o usuário que fornece o identificador eu não posso garantir que ele será único.

**Comment by ninrod** [comment]
@mvleandro, 
No caso do QR Estático, é o usuário ou a automação do usuário que deve tratar a unicidade ou não de seus identificadores. 

Quanto ao formato, peço que abra uma issue separada porque é uma pergunta interessante e eu não gostaria que o assunto ficasse perdido no meio de outra questão.
