### ISSUE TITLE
[Dúvida] no [DICT] - Inclusão de chave

### ISSUE THREAD

**Issue by gabrielmendesbb** [bacen/pix-perguntas-e-respostas#254]
Na versão 6 da API, na operação Criar Vínculo tem no retorno o atributo OpenClaimCreationDate.
Existe realmente esse campo? Como é possível incluir uma chave q está em processo de reivindicação ?
Mesma dúvida em relação ao Alterar. è possível alterar uma chave em processo de reinvidicação? Quando está em reivindicação a chave não fica "travada" (EntryLockedByClaim) para alterações?

**Comment by luizlaydner** [comment]
> Existe realmente esse campo?

Sim. Quando há alguma reivindicação ou portabilidade "aberta" (nem cancelada, nem concluída), o campo terá a data de criação da reivindicação/portabilidade.

> Como é possível incluir uma chave q está em processo de reivindicação ?

Se existe uma portabilidade ou reivindicação de posse em cima de uma chave que ainda não está num estado final (cancelada ou concluída), não é possível criar novo vínculo (registrar chave) ou nova portabilidade/reivindicação. 

> É possível alterar uma chave em processo de reivindicação?

Não.

> Quando está em reivindicação a chave não fica "travada" (EntryLockedByClaim) para alterações?

Exato. Um erro `EntryLockedByClaim` será retornado caso seja feita tentativa de updateEntry.
