### ISSUE TITLE
[Problema] no [SPI] - Campos DebtorAgent e CreditorAgent não retornado no extrato quando o lançamento é de aporte ou saque

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#256]
**Descreva sua dúvida ou problema**

Olá! Notamos que no arquivo de extrato que é enviado pelo SPI, os campos **DebtorAgent** e **CreditorAgent** estão definidos como **obrigatórios**, conforme previsto na mensagem **CAMT.052**:
 
![image](https://user-images.githubusercontent.com/5355541/92536048-104af300-f20f-11ea-81d6-601dcee88eb5.png)

Porém, quando há lançamentos de **aporte e saque na conta PI**, os campos DebtorAgent e CreditorAgent **não estão** sendo preenchidos, conforme exemplo do extrato que obtivemos:

![image](https://user-images.githubusercontent.com/5355541/92536104-36709300-f20f-11ea-968b-565b3c365d2f.png)

Estes campos são obrigatórios mesmo? Ou serão **opcionais** para operação de aporte e saque?

**Sistema ou Área**
 SPI

**Comment by rafael-omello** [comment]
Dúvidas de negócio referentes ao SPI devem ser encaminhadas para spi@bcb.gov.br.
