### ISSUE TITLE
[Dúvida] no [DICT] - Indicadores do ANS

### ISSUE THREAD

**Issue by msyamada** [bacen/pix-perguntas-e-respostas#257]
**Descreva sua dúvida ou problema**

**Indicador**: _"Experiência do usuário pagador no registro de chave (após término do processo de validação ativa)"_
- Dúvida 1:
Partindo da premissa que a categoria de atuação fica a critério do PSP, podendo este escolher atuar com registro de chaves em grade de horário reduzida. Para essa situação, por uma questão de experiência do usuário, ele pode acatar as solicitações de registro de chaves de seus clientes e persistir tais informações na DICT do Bacen de forma assíncrona (na próxima janela útil).
Nossa dúvida: caso o PSP atue com grade de horário reduzida para registro no DICT e realize tratamento para melhor experiência do usuário, como fica esse indicador de tempo decorrido a partir da confirmação do cliente? Em caso assíncrono, ele irá exceder os 20s previstos, sendo que o registro será efetuado na próxima janela útil apenas.

- Dúvida 2:
O indicador trata da experiência do usuário com o registro de chave, mas sua etapa inicial para a contagem do tempo começa com o envio da requisição para o DICT e não com uma ação do usuário pagador. A nomenclatura do indicador não precisaria ser ajustada? 

**Indicador**: _"Tempo decorrido entre a ação do usuário (confirmação ou cancelamento) e o envio da informação para o DICT (processo de portabilidade ou de reivindicação de posse)"_
As seguintes etapas de fluxo não estão incorretas? O correto não seria:
- PSP Doador com acesso direto: etapas 8 a 12 (portabilidade) e 8 a **19** (reivindicação)
- PSP Doador com acesso indireto: etapas 10 a 14 (portabilidade) e 10 a **25** (reivindicação)
? 

**Sistema ou Área**
DICT

**Comment by carloschioquetta** [comment]
1) Nos casos de pedidos depois de 20:00 horas e antes de 8:00 horas, o período do ANS começa a contar da abertura da grade às 8:00 horas.
2) O registro da chave se inicia com solicitação do usuário e seu tempo de processamento afeta sua experiência.
3) Os ANS da última versão do documento estão em acordo com o proposto.
