### ISSUE TITLE
[Dúvida] no [DICT] - Verificação da assinatura

### ISSUE THREAD

**Issue by gabrielmendesbb** [bacen/pix-perguntas-e-respostas#258]
No DICT em homologa está sendo feita a verificação da assinatura?
A principio está aceitando tudo.
Como fazer p testar se a assinatura da msg de envio está ok? para evitar problemas quando for p produção ?

**Comment by luizlaydner** [comment]
Para facilitar os testes em homologação, validamos a assinatura apenas se ela estiver presente.
Para produção, apenas requisições assinadas serão aceitas.
Para validar configurações de produção relacionadas a assinatura e certificados, o DICT aceitará algumas operações específicas na semana anterior ao lançamento. Detalhes sobre isso serão divulgados em breve.
