### ISSUE TITLE
[Dúvida] no [API PIX] - Como confirmar se um pagamento foi realizado? 

### ISSUE THREAD

**Issue by GSansaloni** [bacen/pix-perguntas-e-respostas#259]
Minha dúvida é sobre a confirmação de pagamentos. Atualmente as maquininhas entregam o comprovante de pagamento que aprova o pagamento aos funcionários das empresas que não tem acesso a conta da empresa. No PIX eu não eu encontrei como isso será feito. Exemplo garçom vai cobrar a conta de uma mesa, o cliente decidiu pagar com PIX. Como esse garçom vai saber que o cliente pagou a conta? 

 QR Code

**Comment by ninrod** [comment]
@GSansaloni , por meio da __[API de recebimentos](https://github.com/bacen/pix-api-recebimentos)__. 

No exemplo dado, a maquininha ou o dispositivo que for, consultará a API no endpoint `/documento/{txid}` para verificar se houve recebimento correspondente à cobrança solicitada.
