### ISSUE TITLE
[Problema] no [DICT] - Na inclusão de chave na reconciliação

### ISSUE THREAD

**Issue by alexandrepkill** [bacen/pix-perguntas-e-respostas#261]
**Descreva sua dúvida ou problema**
Descreva de forma clara e curta a dúvida ou problema.

**Sistema ou Área**
DICT, SPI, Iniciação de Pagamentos, QR Code, INFRA

**Identificador do Problema**
Correlation-Id 709DD243E0874778938A7651222D08A1

**URL de conexão**
https://dict-h.pi.rsfn.net.br:16522/api/v1-rc5/entries

[reconcile-problem.log](https://github.com/bacen/pix-perguntas-e-respostas/files/5204269/reconcile-problem.log)

**Comment by luizlaydner** [comment]
Seria gentil de sua parte explicar o problema e o seu entendimento dele.

**Comment by luizlaydner** [comment]
Parece estar relacionado ao #263 .
