### ISSUE TITLE
[Sugestão] no [BRCode] - Parser para BRCode 

### ISSUE THREAD

**Issue by naomijub** [bacen/pix-perguntas-e-respostas#262]
**Descreva sua dúvida ou problema**
Uma sugestão de Parser para o BR Code. Rápido, eficiente e seguro: https://github.com/naomijub/brcode

**Sistema ou Área**
QR Code 

**Dados adicionais**
Estamos desenvolvendo Integrações com Clojure, Javascript, Java e Dart

**Comment by ninrod** [comment]
Muito bom @naomijub!
