### ISSUE TITLE
[Problema] no [DICT] - Consulta de Entry por CID, retornando resultado mesmo depois de excluído.

### ISSUE THREAD

**Issue by guimapalmeira** [bacen/pix-perguntas-e-respostas#263]
**Descreva sua dúvida ou problema**
Olá, realizando uns testes de reconciliação de chaves, percebi que algumas chaves, que provalmente foram excluídas, e uttilizando-se  a consulta de Entry por CID, ainda retornam resultado. 
Ccomo minha reconciliação é baseada nos Logs de Eventos de CID, acabou me gerando um cálculo de VSync incorreto, **NOK**
Após realizar a Solicitação de geração do Arquivo de Cids e o processamento do mesmo, consigo tornar meu VSync OK, e foi quando percebi que os Cids que comentei acima, não existem no Arquivo de Cids.

**Sistema ou Área**
DICT

**Identificador do Problema**
Cids do tipo PHONE, que ainda trazem resultado no serviço de GET EntryBy Cid, que não eram pra existir:
0:'2453093f7b36eaea1d04843e181ab9965fd4144ab65f8d16abf92e7265e75a44'
1:'35c921287757dfc85316314bf810349c428b148744ffcd9e57abe5f756ce35b2'
2:'7b6d8d5f6d2d177fafe723caab33856bde8fc3bf5c5a55b61f6d6ee287aa4536'
3:'81f14f89090a34d87005237306f6bb834d347d6fbf6e64130e328a31be788312'
4:'c032e81bb987a38c1f3a4a83cd0f299252b08add3067dc195409f7c212bed05d'

**Mensagens Enviadas / Recebidas**
Arquivo gerado, que não contem os CIDs, mencionados acima e que me geram um VSYNC **OK**:
idArquivoCid : "64253"
urlArquivoCid : "https://arq-h.pi.rsfn.net.br:1130/api/v1/download/02038232/cidsetfile/02038232_PHONE_64253_2020-09-11T21:21:54.828Z.txt"

**Comment by luizlaydner** [comment]
O intervalo de tempo entre a exclusão e a consulta pelo CID é curto (< 5s) ?
Temos uma pendência de documentar na especificação o modelo de consistência dos dados oferecido pela API.

Resumidamente, hoje não temos garantia de [read-your-writes](https://jepsen.io/consistency/models/read-your-writes) . Uma escrita por um participante pode levar alguns segundos para "aparecer" na leitura da API, devido ao delay de replicação no nosso cluster de banco de dados.

Você poderia detalhar um pouco mais a forma como acontece seu processo de reconciliação? Quais operações especificamente usa?
Dependendo, podemos avaliar aqui de alterar o modelo de consistência para as operações envolvidas na reconciliação para passar a ser _read-your-writes_ .

**Comment by guimapalmeira** [comment]
Na verdade essas chave, a quem se referem os CIDs foram excluidas há algum tempo, vou pegar um exemplo:
a chave : **2453093f7b36eaea1d04843e181ab9965fd4144ab65f8d16abf92e7265e75a44**
foi adicionada: 12/08
"cid": "2453093f7b36eaea1d04843e181ab9965fd4144ab65f8d16abf92e7265e75a44",
"timestamp": "2020-08-12T12:28:07.852Z",
"type": "ADDED"

E removida: 10/09
"cid": "2453093f7b36eaea1d04843e181ab9965fd4144ab65f8d16abf92e7265e75a44",
"timestamp": "2020-09-10T12:59:18.405Z",
"type": "REMOVED"

E se eu consulta-lo no GET EntryByCid retorna resultado(suprimi a assinatura):
<GetEntryByCidResponse>
	<ds:Signature>	
	</ds:Signature>
	<Cid>2453093f7b36eaea1d04843e181ab9965fd4144ab65f8d16abf92e7265e75a44</Cid>
	<Entry>
		<Key>+5511981310073</Key>
		<KeyType>PHONE</KeyType>
		<Account>
			<Participant>02038232</Participant>
			<Branch>0001</Branch>
			<AccountNumber>8693078024</AccountNumber>
			<AccountType>CACC</AccountType>
			<OpeningDate>2020-01-30T00:00:00Z</OpeningDate>
		</Account>
		<Owner>
			<Type>NATURAL_PERSON</Type>
			<TaxIdNumber>30390904880</TaxIdNumber>
			<Name>Joana Braga</Name>
		</Owner>
		<CreationDate>2020-08-12T12:28:07.841Z</CreationDate>
		<KeyOwnershipDate>2020-08-12T12:28:07.838Z</KeyOwnershipDate>
	</Entry>
	<RequestId>a0ff6547-ceec-4a5e-8fb2-61eafd34bba5</RequestId>
</GetEntryByCidResponse>

Esse mesmo cenário se repete para as chaves que comentei acima.

E sobre o cenário que você comentou, preciso avaliar um pouco mais, mas pensando rápido, acredito que um delay de 5s não afetaria meu fluxo, já que todos os eventos teriam o mesmo delay para aparecer, pois eu controlo por data.

Att,
Guilherme Palmeira.

**Comment by luizlaydner** [comment]
@guimapalmeira , identificamos um bug. No `getEntryByCid` estamos incorretamente retornando entry removida pela confirmação de portabilidade/reivindicação. Correção será publicada em breve.

**Comment by luizlaydner** [comment]
> Resumidamente, hoje não temos garantia de [read-your-writes](https://jepsen.io/consistency/models/read-your-writes) . Uma escrita por um participante pode levar alguns segundos para "aparecer" na leitura da API, devido ao delay de replicação no nosso cluster de banco de dados.
> 

Uma atualização sobre essa questão que eu tinha levantado...
Discutimos internamente aqui e chegamos a conclusão de que é importante garantir uma consistência _read-your-write_ para todas as operações da API do DICT. Não garantir esse nível de consistência na API não é intuitivo e poderia causar bugs na implementação de clientes da API. Isso não constará na especificação, pois é o "natural" e esperado.

**Comment by guimapalmeira** [comment]
Opa @luizlaydner, obrigado pelas respostas.
Ficamos aguardando a resolução do problema.
Identificamos algumas intercorrências nos serviços hoje(CidEvemts, GetEntryByCid, DownalodArquivoCids) , mas compreendemos que sejam subidas e correções em andamento.

Obrigado,
Guilherme Palmeira.

**Comment by guimapalmeira** [comment]
Olá @luizlaydner vou aproveitar essa thread pra comentar sobre uma issue, porque acho que tem a ver.

Atualmente, quando faço o download do Arquivo de Cids, vocês estão expurgando o mesmo?
Ou seja, se eu tentar baixar um arquivo de cids, e me tiver algum problema pra salvar ele do meu lado, e retentar ele, está ,e gerando um erro que o arquivo não existe mais. Dai eu tenho que Solicitar um nova geração, me gerando um novo custo?
Vai ficar assim mesmo? (Antes não era).

Obrigado,
Guilherme Palmeira.

**Comment by luizlaydner** [comment]
@guimapalmeira Sobre os arquivos de cids não encontrados, houve necessidade de apagar arquivos já gerados em homologação. Faltou da nossa parte comunicar isso. Você deve ter tentando baixar um arquivo que foi apagado, mas esse não é o comportamento normal.

O comportamento normal é que o arquivo gerado permaneça lá disponível para ser baixado. Não excluímos após tentativa de download. Obviamente que arquivos muito antigos (não sei precisar o prazo) serão eventualmente apagados, pois perdem utilidade e usam recursos.

**Comment by luizlaydner** [comment]
O tempo que o arquivo permanece disponível para download após geração é **24h**
