### ISSUE TITLE
[Dúvida] no [DICT] - API para aferir ANS "3.2.1.1"

### ISSUE THREAD

**Issue by WagnerLau** [bacen/pix-perguntas-e-respostas#266]
No "Manual de Tempos do PIX - v1.1", é citado que será aferido o ANS:
"_3.2.1.1. Recebimento (acknowledge) de nova portabilidade ou reivindicação de posse ou de nova notificação de infração e mudança no status do pedido_"

Tal ANS possui 2 indicadores, que devem respeitar o tempo de 60 segundos:

1. Tempo decorrido entre a criação de uma portabilidade ou reivindicação de posse ou notificação de infração e o seu recebimento (acknowledge) pelo doador (PSP do recebedor, no caso de notificação de infração);

2. Tempo decorrido entre a mudança de status de um processo de portabilidade ou de reivindicação de posse ou notificação de infração para “Cancelado” ou “Confirmado”, no caso de portabilidade ou reivindicação de posse, ou para “Analisado”, no caso de
notificação de infração) e o seu recebimento (acknowledge) pelo reivindicador (PSP do pagador, no caso de notificação de infração)

**Dúvidas:**

- Para o indicador "1", o PSP deverá utilizar a API "Listar Reivindicações" ou a API "Receber Reivindicação" para aferir o recebimento do PSP Doador?
- Para o indicador "2", o PSP deverá utilizar a API "Listar Reivindicações" ou a API "Receber Reivindicação" para aferir o recebimento do PSP Reivindicador?

**Comment by WagnerLau** [comment]
Prezados,
Algum retorno sobre as dúvidas listadas acima?

**Comment by carloschioquetta** [comment]
1) Deve ser utilizado o recebimento (“Receber Reivindicação”). Listar API não é suficiente para se informar o recebimento de uma reivindicação.
2) Igual ao item anterior.
