### ISSUE TITLE
[DUVIDA] OwnerTradeName - Cadastro de Vínculo

### ISSUE THREAD

**Issue by sdnaves** [bacen/pix-perguntas-e-respostas#267]
Bom dia,

Ao olhar a documentação do CID, verificamos a existência do campo ownerTradeName, porém ao criar um vínculo, não existe o campo nos exemplos da documentação. Gostaria de saber se seria um campo opcional ou se existe alguma logica por trás que trata ao receber um CNPJ.

**Comment by luizlaydner** [comment]
`Entry > Owner > TradeName`  é o nome fantasia de uma PJ. 
É campo opcional ao criar vínculo em que o dono da chave é uma pessoa jurídica. 
Veja o [schema](https://github.com/bacen/pix-dict-api/blob/43667dea920a221b64f3b965308a2c6ea71ffc80/openapi/schemas.yaml#L93)

Para exemplificar, a criação de um vínculo de PJ teria o seguinte XML na requisição (versão 1.0.0-RC6)
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<CreateEntryRequest>
    <Entry>
        <Key>+5561988880000</Key>
        <KeyType>PHONE</KeyType>
        <Account>
            <Participant>12345678</Participant>
            <Branch>0001</Branch>
            <AccountNumber>0007654321</AccountNumber>
            <AccountType>CACC</AccountType>
            <OpeningDate>2010-01-10T03:00:00Z</OpeningDate>
        </Account>
        <Owner>
            <Type>LEGAL_PERSON</Type>
            <TaxIdNumber>11222333000150</TaxIdNumber>
            <Name>Padaria 3 Irmãos LTDA</Name>
            <TradeName>Padaria 3 Irmãos</TradeName>
        </Owner>
    </Entry>
    <Reason>USER_REQUESTED</Reason>
    <RequestId>a946d533-7f22-42a5-9a9b-e87cd55c0f4d</RequestId>
</CreateEntryRequest>
```
