### ISSUE TITLE
[Problema] no [DICT] - Erro ao incluir Entry com participante Indireto

### ISSUE THREAD

**Issue by JeanFabichaki** [bacen/pix-perguntas-e-respostas#269]
**Descreva sua dúvida ou problema**

Estamos com um erro ao tentar criar uma entry com o Participant 09515813 que é um participante indireto do 59588111.
`
<problem xmlns="urn:ietf:rfc:7807"><type>https://dict.pi.rsfn.net.br/api/v1/error/Forbidden</type><title>Forbidden</title><status>403</status><detail>Participant  is not an indirect participant of the submitter</detail><correlationId>508FE58C91264D2F8616D3170E95A003</correlationId></problem>
`

**Sistema ou Área**
DICT

**Identificador do Problema**
Correlation-Id 508FE58C91264D2F8616D3170E95A003

**Mensagens Enviadas**
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
 <CreateEntryRequest xmlns:ns2="http://www.w3.org/2000/09/xmldsig#"><Entry><Key>mose_denesik11@gmail.com</Key><KeyType>EMAIL</KeyType><Owner><Type>NATURAL_PERSON</Type><TaxIdNumber>00966731922</TaxIdNumber><Name>Louis  Sauer</Name><TradeName/></Owner><Account><Participant>09515813</Participant><AccountNumber>75746451</AccountNumber><AccountType>CACC</AccountType><Branch>323</Branch><OpeningDate>1900-01-01T00:00:00Z</OpeningDate></Account></Entry><RequestId>c506f8e9-fbb9-4f4f-8a18-f3f617248186</RequestId><Reason>USER_REQUESTED</Reason></CreateEntryRequest>`

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc5/entries/

**Comment by luizlaydner** [comment]
Poderia informar se a situação permanece ?
Lembrando que /api/v1-rc5 foi desativada e /api/v1-rc6 será desativada em 23/09 .
/api/v1 já está disponível em homologação.

**Comment by JeanFabichaki** [comment]
Olá, o erro parou de acontecer. Obrigado.
