### ISSUE TITLE
[Dúvida] no [DICT] - Qual "razão" informar no Cancelamento de Reivindicação de Posse após o trigésimo dia pelo PSP Reivindicador?

### ISSUE THREAD

**Issue by CharlesMendes** [bacen/pix-perguntas-e-respostas#270]
**Descreva sua dúvida ou problema**
Qual "razão" informar no Cancelamento de Reivindicação de Posse após o trigésimo dia pelo PSP Reivindicador?

**Sistema ou Área**
DICT

**Identificador do Problema**
N/D

**Mensagens Enviadas / Recebidas**
N/D

**URL de conexão**
N/D

**Dados adicionais**
Na versão do Manual Operacional DICT v1.1, Cap. "6. Fluxo de reivindicação de posse de chave", é descrito que:
`Caso o usuário reivindicador não faça a validação de posse até o trigésimo dia após o início do processo de reivindicação, o PSP reivindicador deve necessariamente cancelar a solicitação no DICT, para que a chave em disputa possa ser liberada.`

Na API [DICT RC-6 Cancelar Reivindicação](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API_do_DICT-v1-rc6.html#operation/cancelClaim),  existe o quadro abaixo:
![image](https://user-images.githubusercontent.com/1323305/93266065-ef8b1c00-f77f-11ea-8100-93e862fc89b6.png)

**Sugestão:** Poderíamos usar o Reason: "DEFAULT_OPERATION" para o PSP Reivindicador? 
Ou qual reason devemos usar? (uma vez que não foi Solicitação do Usuário, nem Fraudes e Encerramento de Contas)

**Comment by CharlesMendes** [comment]
Encontrei essa observação no Manual Operacional DICT, porém, não condiz com a RC-6 no quadro de motivos, nesse caso deveria ser atualizado a API DICT certo?

![image](https://user-images.githubusercontent.com/1323305/93268281-4d6d3300-f783-11ea-9d73-de911a2dfebe.png)

**Comment by luizlaydner** [comment]
No cancelamento de reivindicação de posse após o 30o dia por falta de validação de posse do usuário reivindicador, o campo `Reason` deve ser preenchido com `DEFAULT_OPERATION` .
A especificação da API será atualizada em breve para refletir essa possibilidade.
Obrigado!
