### ISSUE TITLE
[Dúvida] no [SPI] - Obter Chave Pix no QR Code Dinâmico sem acessar a URL

### ISSUE THREAD

**Issue by CharlesMendes** [bacen/pix-perguntas-e-respostas#271]
**Descreva sua dúvida ou problema**
Devo acessar primeiro a URL no QR Code Dinâmico para obter no payload a Chave Pix? ou a Chave Pix já estará disponível sem ter que acessar antes a URL?

**Sistema ou Área**
Iniciação de Pagamentos, QR Code

**Identificador do Problema**
Conteúdo BR Code (QR Code Dinâmico)

**Mensagens Enviadas / Recebidas**
N/D

**URL de conexão**
N/D

**Dados adicionais**
No novo documento III_ManualdeFluxosdoProcessodeEfetivacaodoPix - versao1.1, foram removidas as referências a URL contida no QR Code Dinâmico. Mas no documento de II_ManualdePadroesparaIniciacaodoPix - versao1, continua a informação do conteúdo padrão BR Code conforme abaixo (com a URL a obter o payload e inclusive a Chave Pix somente após acesso a URL)

![image](https://user-images.githubusercontent.com/1323305/93272113-2b77ae80-f78b-11ea-8684-78a1b2c6c45f.png)

**Comment by ninrod** [comment]
> Devo acessar primeiro a URL no QR Code Dinâmico para obter no payload a Chave Pix? ou a Chave Pix já estará disponível sem ter que acessar antes a URL?

@CharlesMendes  a chave pix  consta no payload retornado pelo endpoint representado pela URL.

**Comment by rubenskuhl** [comment]
bx.com.br citado como exemplo é um domínio válido. Para exemplos usando domínios, exemplo.com.br ou example.com.br são mais seguros.

**Comment by ninrod** [comment]
> bx.com.br citado como exemplo é um domínio válido. Para exemplos usando domínios, exemplo.com.br ou example.com.br são mais seguros.

@rubenskuhl acabou passando. Obrigado. 

> Devo acessar primeiro a URL no QR Code Dinâmico para obter no payload a Chave Pix? ou a Chave Pix já estará disponível sem ter que acessar antes a URL?

@CharlesMendes , a chave PIX encontra-se dentro do payload de cobrança, portanto deve-se acessar primeiro o endpoint localizado pela URL e obter a chave PIX dentro desse payload retornado.
