### ISSUE TITLE
Dúvida no DICT - Teste carga Dict

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#272]
**Descreva sua dúvida ou problema**
Realizamos um teste de carga na data de ontem e obtivemos o seguinte retorno: De acordo com os nossos registros, as cargas realizadas não mantiveram um minimo de mil consultas por minuto durante os 10 minutos. Ainda que o total de consultas tenha sido atingido, a distribuição não foi homogênea ao longo do tempo. No caso realizei 10k consultas em 7 min aproximadamente e parei o disparo.

Gostaria de saber se durante os 10 minutos posso ultrapassar as 10k de consultas Dict ? E se desta forma eu passaria no teste de carga?

Obrigado!

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
@evertongodoi  veja https://github.com/bacen/pix-perguntas-e-respostas/issues/183#issuecomment-676642027

**Comment by evertongodoi** [comment]
@luizlaydner Obrigado pelo retorno!
