### ISSUE TITLE
[Dúvida] no [iniciação de pagamentos] - Como é feita a leitura do EVP

### ISSUE THREAD

**Issue by Jenicrist** [bacen/pix-perguntas-e-respostas#273]
Quando o usuário inicia uma transação utilizando uma chave EVP, quais informações exibimos como retorno para a tela de resumo antes da confirmação e criação da ordem de pagamento?

Quais a informações do "dono" do EVP exibimos ao pagador?

**Comment by ninrod** [comment]
@Jenicrist , as mesmas informações que seriam exibidas no caso de se utilizar e-mail, CPF ou telefone. Mais informações sobre isso você encontra no __[Manual de Requisitos Mínimos para a Experiência do Usuário](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/IV_RequisitosMinimosparaExperienciadoUsuario-versao1.pdf)__.
