### ISSUE TITLE
[Problema] no [DICT] - Reivindicador não recebe "ConfirmReason"

### ISSUE THREAD

**Issue by WagnerLau** [bacen/pix-perguntas-e-respostas#274]
**Descreva sua dúvida ou problema**
Ao chamar a API "Confirmar Reivindicação" pelo PSP Doador, o DICT está retornando no XML do response o parâmetro "ConfirmReason", com o valor enviado na requisição, no caso em questão retornou:
<ConfirmReason>USER_REQUESTED</ConfirmReason>
Porém, quando chamamos a API "Listar Reivindicações" pelo PSP Reivindicador, o parâmetro "ConfirmReason" não é retornado no XML do response da requisição.

Quando o PSP Reivindicador terá essa informação "ConfirmReason" pela API "Listar Reivindicações"?

**Sistema ou Área**
DICT, INFRA

**Identificador do Problema**
Identificador da Reivindicação (Homologação):
<Id>d58278ce-35a1-4045-b142-36b6800b42e4</Id>

**Comment by WagnerLau** [comment]
Prezados,
Algum retorno sobre o problema citado acima?

**Comment by luizlaydner** [comment]
Falha nossa aqui. Vamos corrigir.

**Comment by WagnerLau** [comment]
Ok, muito obrigado pelo retorno.
