### ISSUE TITLE
[Dúvida|Problema] no [SISTEMA] - Título

### ISSUE THREAD

**Issue by GSansaloni** [bacen/pix-perguntas-e-respostas#275]
Link de pagamentos

Eu não consegui achar no site do BC uma regulamentação, instrução técnica ou API sobre o link de pagamento. Quero saber como irá funcionar.

**Comment by ninrod** [comment]
@GSansaloni , o link para pagamentos foi removido do lançamento do PIX. 

Foi endereçada ao mercado uma consulta a respeito de funcionalidades que substituirão o link de pagamentos: PDF (c/ propriedades) e copy/paste do payload.
