### ISSUE TITLE
Problema no DICT - Problema ao realizar integração com o DICT

### ISSUE THREAD

**Issue by Leonardo34** [bacen/pix-perguntas-e-respostas#276]
**Descreva sua dúvida ou problema**
Senhores, estou com problema em todas operações do DICT, todas elas retornam erro 400 sem nenhuma mensagem explicativa. 

**Sistema ou Área**
DICT

**Identificador do Problema**
`<type>https://dict.pi.rsfn.net.br/api/v1/error/BadRequest</type><title>Bad  Request</title><status>400</status><detail>No message available</detail><correlationId>1E2EC1A138B7409F857A4FC413ADA211</correlationId></problem>`

**Mensagens Enviadas / Recebidas**
Retorno de uma consulta de chave: 

`<type>https://dict.pi.rsfn.net.br/api/v1/error/BadRequest</type>
<title>Bad  Request</title>
<status>400</status>
<detail>No message available</detail>
<correlationId>1E2EC1A138B7409F857A4FC413ADA211</correlationId>
`

**Dados adicionais**
Comportamento começou na manhã do dia de hoje aparentemente.

**Comment by HenriqueSimoes82** [comment]
@Leonardo34 ontem, no final do dia, foi disponibilizada uma nova versão da API do Dict, onde a versão 'v1-rc5' foi removida. 
Você deve fazer suas chamadas para a 'v1' ou para 'v1-rc6'
