### ISSUE TITLE
[Dúvida] no [DICT] - Atualização de ISPB em conta de uma chave

### ISSUE THREAD

**Issue by slheckler** [bacen/pix-perguntas-e-respostas#277]
**Descreva sua dúvida ou problema**
Consigo enviar uma requisição de atualização de Chave com alteração no elemento <Participant> da <Account> e receber um retorno 200 OK mas sem o dado alterado no objeto de retorno. Notei que a documentação indica "[...] atualização da informação da conta de um cliente, **permanecendo este no mesmo PSP**." isto se refere à informação do ISPB? Este campo é ignorado na atualização?

**Sistema ou Área**
Atualizar Vínculo do DICT

**Identificador do Problema**
Atualização de participant.

**Mensagens Enviadas / Recebidas**
Requisição:
```
<UpdateEntryRequest>
    <Key>eryn.collins@yahoo.com</Key>
    <Account>
        <Participant>59588112</Participant>
        <Branch>2778</Branch>
        <AccountNumber>29017056</AccountNumber>
        <AccountType>CACC</AccountType>
        <OpeningDate>2010-01-10T03:00:00Z</OpeningDate>
    </Account>
    <Reason>USER_REQUESTED</Reason>
</UpdateEntryRequest>
```
Resposta:
```
<Entry>
        <Key>eryn.collins@yahoo.com</Key>
        <KeyType>EMAIL</KeyType>
        <Account>
            <Participant>59588111</Participant>
            <Branch>2778</Branch>
            <AccountNumber>29017056</AccountNumber>
            <AccountType>CACC</AccountType>
            <OpeningDate>2010-01-10T03:00:00Z</OpeningDate>
        </Account>
        <Owner>
            <Type>LEGAL_PERSON</Type>
            <TaxIdNumber>00323513000133</TaxIdNumber>
            <Name>Arnoldo Hoppe</Name>
        </Owner>
        <CreationDate>2020-09-16T20:01:42.875Z</CreationDate>
        <KeyOwnershipDate>2020-09-16T20:01:42.872Z</KeyOwnershipDate>
    </Entry>
```

**URL de conexão**
http://srv-pixuat01.bvnet.bv:81/api/v1/entries/eryn.collins@yahoo.com

Dados adicionais
Abaixo a requisição:
![bug_update_entry_bacen_desenho](https://user-images.githubusercontent.com/67338770/93485930-fded4b00-f8d9-11ea-87d5-32748d6f4ece.png)

**Comment by luizlaydner** [comment]
Havia uma omissão na validação dessa operação.
Em breve será publicada versão atualizada com correção.
Obrigado pelo relato!

**Comment by slheckler** [comment]
Muito obrigado pela disponibilidade!

**Comment by luizlaydner** [comment]
Correção foi publicada hoje.

**Comment by slheckler** [comment]
Perfeito, obrigado!
