### ISSUE TITLE
[Dúvida] CAMT060 - CAMT054 sem resposta

### ISSUE THREAD

**Issue by mfabioe** [bacen/pix-perguntas-e-respostas#28]
Não estamos recebendo resposta de CAMT.060 que solicita CAMT.054.
Ainda não está implementada no bacen?

**Comment by rafael-omello** [comment]
Já está implementado sim. Qual é o msgId da mensagem com problema?

**Comment by mfabioe** [comment]
M003603058287cc3727e04549ad4c90e

**Comment by rafael-omello** [comment]
Verifiquei aqui e foi gerada uma CAMT.054 com msgId M000381660KC265VYH103CTWOJGEWM72 em resposta a CAMT.060 com msgId M003603058287cc3727e04549ad4c90e.

**Comment by mfabioe** [comment]
@rafael-omello verificamos aqui, acabamos descobrindo que no XSD o identificador da CAMT.054 deveria retornar com D e não com M. Poderia verificar?
