### ISSUE TITLE
[Dúvida] no [DICT] - Validação ativa de posse de chave antes de doador cancelar portabilidade

### ISSUE THREAD

**Issue by esantanapr** [bacen/pix-perguntas-e-respostas#281]
Relacionado ao issue #90, o manual Operacional do DICT apresenta que do ponto de vista do usuário doador, se quiser Cancelar o pedido de portabilidade ou reivindicação de posse da chave, deve previamente fazer a validação de posse da chave.

No caso da portabilidade, visto que a chave pertence ao mesmo dono, é realmente necessário realizar a validação ativa de posse antes de o cliente doador solicitar o cancelamento?

**Comment by esantanapr** [comment]
Alguma atualização em relação a esse ponto?

**Comment by mpostemsky** [comment]
Bom dia, temos a mesma dúvida.

**Comment by carloschioquetta** [comment]
Sim, conforme descrito no Manual Operacional do DICT, o cancelamento depende de validação de posse pelo usuário.
