### ISSUE TITLE
Conexão no DICT

### ISSUE THREAD

**Issue by rafaelpkcortes** [bacen/pix-perguntas-e-respostas#283]
Bom dia, 

O Dict esta em manutenção esse final de semana?
Estamos vendo uma alteração de ip´s constante.
Mas o telnet não fecha na porta 16522.
IP: 200.218.66.145
IP: 200.218.67.209

**Comment by luizlaydner** [comment]
Está fora hoje. Testes internos estão sendo realizados.

**Comment by rafaelpkcortes** [comment]
Tem alguma previsão de retorno entre hoje ou amanhã

**Comment by luizlaydner** [comment]
Após 18h de hoje, provavelmente.

**Comment by rafaelpkcortes** [comment]
Excelente, muito obrigado.

**Comment by thiagotemal** [comment]
Sabem informar se terá manutenção amanhã também?

**Comment by fguarig** [comment]
Boa tarde!!!

Estamos tendo esse mesmo problema desde a semana passada. Continua em manutenção? 


Obrigado,
Fabio Guariglia
