### ISSUE TITLE
[Dúvida] no [QR Code] - Experiencia do Usuário com QR Code Estático valor em branco

### ISSUE THREAD

**Issue by rturk** [bacen/pix-perguntas-e-respostas#284]
**Descreva sua dúvida ou problema**
Favor confirmar a experiência do usuário final ao escanear um QR Code estático com valor em branco, ao ler a documentação nosso entendimento é que compete ao usuário determinar o valor, correto?

Desta forma teremos a seguinte história como válida: 
EU como um usuário usando meu App ao escanear um QR Code estático com o valor em aberto eu que vou determinar o valor da transação.

**Sistema ou Área**
QR Code

**Dados adicionais**
- É possível determinar, em um QR Code estático, com valor em aberto o valor mínimo?
- É possível determinar, em um QR Code estático, com valor em aberto o valor máximo?

**Comment by ninrod** [comment]
> EU como um usuário usando meu App ao escanear um QR Code estático com o valor em aberto eu que vou determinar o valor da transação.

correto. 

> É possível determinar, em um QR Code estático, com valor em aberto o valor mínimo?
É possível determinar, em um QR Code estático, com valor em aberto o valor máximo?

Não é possível.
