### ISSUE TITLE
[Problema] no [DICT] -  Connection timeout

### ISSUE THREAD

**Issue by gizelysc** [bacen/pix-perguntas-e-respostas#285]
**Descreva sua dúvida ou problema**
Gostaria de confirmar com vocês se há alguma indisponibilidade na comunicação pois as chamadas ao Dict estão retornando erro 504.
**Sistema ou Área**
DICT
**Identificador do Problema**
ISPB 28127603

**Comment by luizlaydner** [comment]
DICT e ICOM estão fora hoje para testes internos. 
#283
