### ISSUE TITLE
[Dúvida] APIPix - 

### ISSUE THREAD

**Issue by mariapessoacaldas** [bacen/pix-perguntas-e-respostas#286]
**Descreva sua dúvida ou problema**
Por favor, gostaria de entender se o padrão da API Pix (Recebimentos) é obrigatório apenas para as Automações Comerciais ou para todos os clientes recebedores diretos.

**Sistema ou Área**
QR Code

**Comment by ninrod** [comment]
A API Pix é obrigatoria para todos os PSPs que queiram fornecer uma integração automatizada a seus clientes no contexto do arranjo Pix

**Comment by rubenskuhl** [comment]
+1 para APIs padronizadas, -1 para APIs proprietárias.
