### ISSUE TITLE
[Dúvida] API Pix - Padronização

### ISSUE THREAD

**Issue by mariapessoacaldas** [bacen/pix-perguntas-e-respostas#287]
**Descreva sua dúvida ou problema**
As APIs fornecidas pelos participantes podem conter campos "adicionais" aos informados no layout?
Ou seja, utilizar o padrão (esqueleto), incluindo novos campos opcionais.

**Sistema ou Área**
QR Code

**Comment by ninrod** [comment]
Boa tarde. Não é permitido.
