### ISSUE TITLE
[Dúvida] APi Pix - Padronização

### ISSUE THREAD

**Issue by mariapessoacaldas** [bacen/pix-perguntas-e-respostas#288]
A API poderá possuir campos adicionais (opcionais) aos padronizados ou deverá ser exatamente igual a API divulgada? 

**Sistema ou Área**
QR Code

**Comment by rubenskuhl** [comment]
O @ninrod é quem pode responder autoritativamente, mas em outros tópicos desse tema o que ele havia mencionado é que os recursos presentes na API padronizada só podem ser especificados na forma da API padronizada (métodos, campos etc.), mas que recursos diferentes podem ser diferentes. 

Um exemplo que me ocorre é que a API é só de Recebimento e de exposição do QR-Code dinâmico por enquanto, não de pagamento. Então uma API de pagamento poderia seguir métodos proprietários, pelo menos enquanto o BACEN não padronizar o IP (Iniciador de Pagamento) como parte do Open Banking (Q3 2021).

**Comment by mariapessoacaldas** [comment]
Além disso, é importante esclarecer se as instituições poderão oferecer APIs adicionais. (por exemplo outras visões de consultas). Obrigada.

**Comment by rubenskuhl** [comment]
Vou dar um exemplo de algo que não poderia ser adicional IMHO: uma API de conciliação que mostrasse os Pix recebidos num determinado intervalo de tempo. Isso já está incluso no GET do /cob de múltiplas cobranças inclusive com paginação. 
Já por exemplo saber o saldo atual e saber a totalização de transações Pix num determinado intervalo de tempo são coisas que não observei na API padronizada, que mesmo num uso só de recebimentos poderiam estar em APIs proprietárias.

**Comment by ninrod** [comment]
> A API poderá possuir campos adicionais (opcionais) aos padronizados ou deverá ser exatamente igual a API divulgada?

Deve ser exatamente igual à API divulgada. 

> Além disso, é importante esclarecer se as instituições poderão oferecer APIs adicionais. (por exemplo outras visões de consultas).

De acordo com o regramente vigente, não é uma possibilidade.
