### ISSUE TITLE
[Dúvida] no [DICT] - Campo reason quando PSP reivindicador confirma o pedido após o 14º dia

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#29]
**Descreva sua dúvida ou problema**

Na versão 6.2 do manual de especificação, no fluxo de reivindicação do reivindicador, existe um novo fluxo: se após o 14º dia o PSP doador não confirmar/cancelar o pedido, o PSP reivindicador pode realizar a confirmação.

![image](https://user-images.githubusercontent.com/5355541/86170418-79b4d400-baf1-11ea-9653-8af8ba53eeba.png)

Pensando nesse fluxo, qual razão deve ser passado pelo PSP reivindicador? 
Hoje no swagger só tem os motivos listados para a visão do PSP doador.

![image](https://user-images.githubusercontent.com/5355541/86170301-4d00bc80-baf1-11ea-98fc-8a3fbb48a2b3.png)

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
Monise,

Em uma análise preliminar, a API está correta: o PSP reivindicador NÃO pode seguir sem a confirmação do doador. O doador precisa confirmar, a fim de manter coerência com a base interna (para booktransfer). Vamos atualizar o documento de negócio.

**Comment by carloschioquetta** [comment]
Prezados,
O fluxo será atualizado no Manual Operacional do Dict.

**Comment by monise** [comment]
@carloschioquetta @judahreis Boa tarde pessoal! No novo documento de especificação do DICT "_X_ManualOperacionaldoDICT-versao1-1.pdf_" ainda continua o requisito de que o PSP reivindicador poderia confirmar o processo de reivindicação após o 14º dia se não tiver uma resposta do PSP doador.

Essa regra **não deve** ser desenvolvida né? ela será retirada?

![image](https://user-images.githubusercontent.com/5355541/90160192-d6014980-dd67-11ea-9b0a-47545ed32de7.png)
