### ISSUE TITLE
[Dúvida] no [Pix] - PSP Direto | Indireto x Pagamentos duplicados

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-perguntas-e-respostas#291]
**Descrição do problema
Um PSP direto alegou em um vídeo (https://www.youtube.com/watch?v=6Tor9r6F9kM) que os PSP Indiretos não tem como recusar pagamentos feitos em duplicidade (imaginando para simplificação que se trata de QR-Code Dinâmico que sempre tem TxID). Isso sugere que como a transação já foi confirmada pelo PSP Direto, a única opção do PSP Indireto seria fazer devolução do Pix. 

Isso traria para os estabelecimentos a necessidade de codificar seus sistemas de forma diferente para PSPs diretos e para PSPs indiretos, contrariando o objetivo de competição. 

É isso mesmo ? Ou antes de confirmar um Pix que tem como destino um PSP Indireto, o PSP Direto precisa antes consultar o Indireto ? Ou o PSP Direto já deveria pelo TxID recusar o Pix ? 

**Sistema ou Área**
SPI

**Comment by rafael-omello** [comment]
Dúvidas de negócio relativas ao SPI devem ser encaminhadas para spi@bcb.gov.br.
