### ISSUE TITLE
[Dúvidaa] Api Pix 2.0

### ISSUE THREAD

**Issue by mariapessoacaldas** [bacen/pix-perguntas-e-respostas#292]
**Descreva sua dúvida ou problema**
Não encontramos vencimento dentro da estrutura calendário. Além disso verificamos que houve uma alteração substancial no campo calendario.expiração, passando de data e hora com granularidade de segundos, para quantidade de segundos até expiração.
Não encontramos os campos de juros, multa e desconto/abatimento e calendario.recebivelaposvencimento. 
Não encontramos valor.permitealteracao
Não encontramos valor.valor.final
Não encontramos o campo id.documento
A revisão não está mais na estrutura id. Ela deverá ser retornada sem estar contida nenhuma estrutura?
A revisão está iniciando com 1 e não zeros como indica no documento Padrão de iniciação

Por favor, podem confirmar se de fato esses campos serão excluídos/ alterados?

**Sistema ou Área**
QR Code

**Comment by rubenskuhl** [comment]
No release da versão 2.0.0(https://github.com/bacen/pix-api/releases/tag/2.0.0) constam algumas dessas mudanças:

[2.0.0]
Adicionado
Endpoint para criação de Cobranças
Endpoint para gerenciamento de Cobranças
Endpoint para consulta parametrizada de Cobranças
Endpoint para gerenciamento de Pix
Endpoint para consulta parametrizada de Pix
Endpoint para solicitar devolução de Pix
Endpoint para consultar devolução de Pix
Endpoint para configurar Webhooks
Endpoint para exibir informações de Webhooks
Endpoint para cancelar Webhooks
Endpoint para acesso ao Payload JSON de Cobrança
Autenticação e Autorização baseada em OAuth2
Removido
Recursos para gerenciamento de Documentos
Configuração de vencimento em calendário
Configuração de juros, multa e desconto em valor

**Comment by ninrod** [comment]
@mariapessoacaldas , sim. a versão `2.0.0` trouxe realmente mudanças significativas (por isso incrementamos o Major)  Essa release organizou os casos de uso estruturados em torno do "pagamento no ato". Essas questões a respeito de juros e multa e vencimento serão tratadas "em breve".
