### ISSUE TITLE
Problema no [DICT] - Intersal Sever Error 

### ISSUE THREAD

**Issue by serdanr** [bacen/pix-perguntas-e-respostas#293]
**Descreva sua dúvida ou problema**
Erro 500 Bacen Relato de Infração

**Sistema ou Área**
DICT

**Identificador do Problema**
Erro 500 Bacen

**URL de conexão**
api/v1/infraction-reports

**Dados adicionais**

**Comment by luizlaydner** [comment]
Poderia informar o CorrelationId ?

**Comment by bermr** [comment]
também estou tendo!
CorrelationId: `AA98A24FEA534FCBA01D16286C7A7FF8`

**Comment by evertongodoi** [comment]
@luizlaydner por aqui também estamos recebendo erro 500 - Internal server error, durante a criação do relato de infração. correlationId: 7F1772982AA44F3EB8FA81D31CB0097E.

Obrigado!

**Comment by evertongodoi** [comment]
Teste realizado, operações de infração funcionando corretamente.
