### ISSUE TITLE
[Dúvida] no  QR Code estático - Botão "Avançado" na tela de selecionar chave

### ISSUE THREAD

**Issue by jaquelinejardim** [bacen/pix-perguntas-e-respostas#295]
Na página 18 do manual de requisitos a segunda tela apresenta um botão de Avançado, no entanto não foi apresentado nenhum exemplo do que deve acontecer ao clicar nessa opção. O que deve acontecer quando esta opção for acionada?

**Comment by vallerao** [comment]
Aparentemente, houve confusão em relação ao número da página. O item está na página 19 do referido documento.
O botão ali identificado é uma forma de se levar o usuário da geração do QR Code estático à geração do QR Code dinâmico, caso a instituição ofereça a geração desse tipo de QR Code.
Lembramos que, como todas as demais telas do documento, as ilustrações tem como intenção apenas esclarecer as obrigações contidas nos textos à esquerda das páginas desse material. Portanto, não há obrigação de se utilizar esse botão e não será elaborada tela exemplificando o que é mostrado quando se clica nesse botão.
