### ISSUE TITLE
[Dúvida] no [SPI] - Onde posso encontrar a base de participantes do Pix?

### ISSUE THREAD

**Issue by mvleandro** [bacen/pix-perguntas-e-respostas#297]
**Descreva sua dúvida ou problema**
Caros, preciso saber onde encontrar a base de participantes do Pix de modo que eu consiga fazer um DE/PARA do ISPB para o nome da instituição, para exibir o nome da instituição ao cliente final em vez do número do ISPB.

**Sistema ou Área**
SPI

**Comment by rsabin** [comment]
Veja se o #73 responde.

[IN nº17](https://www.bcb.gov.br/estabilidadefinanceira/exibenormativo?tipo=Instru%C3%A7%C3%A3o%20Normativa%20BCB&numero=17)

**Comment by mvleandro** [comment]
@rsabin  Eu entendi que receberemos via CAMT.014 a inclusão de novos participantes, mas sabe dizer se existe alguma mensagem que envie todos os participantes habilitados? O que acontece se alguma mensagem for perdida?

**Comment by rafael-omello** [comment]
Conforme Art. 4º da Instrução Normativa BCB n° 17 de 18/9/2020, o Banco Central do Brasil disponibilizará, no seu sítio da internet, a partir de 21 de outubro de 2020, arquivo atualizado diariamente contendo a relação de participantes diretos e indiretos cadastrados em ambiente de produção do SPI.
