### ISSUE TITLE
[Dúvida] no [QR Code] - Tipo de caracteres aceitos

### ISSUE THREAD

**Issue by mvleandro** [bacen/pix-perguntas-e-respostas#298]
**Descreva sua dúvida ou problema**
Caros, gostaria de saber quais tipos de caracteres são aceitos no conteúdo da string EMV do QRCode. Existe alguma expressão regular que eu precise usar para validar a entrada do usuário?

Pergunto isso porque no padrão EMV são aceitos apenas caracteres ASCII maiusculos.

Na documentação aparecem caracteres maiusculos e minusculos e também não deixa claro se são aceitos acentos e caracteres especiais (e se sim, quais).

Poderiam esclarecer?

**Sistema ou Área**
QR Code

**Comment by ninrod** [comment]
> Pergunto isso porque no padrão EMV são aceitos apenas caracteres ASCII maiusculos.

boa noite @mvleandro. Essa informação não procede. O padrão EMV para QR Codes determina o uso de UTF-8.

Maiores informações podem ser encontradas no documento "EMV for QR Codes: merchant presented mode".
