### ISSUE TITLE
[Dúvida] no [QR Code] estático - Formato do campo TXID

### ISSUE THREAD

**Issue by mvleandro** [bacen/pix-perguntas-e-respostas#299]
**Descreva sua dúvida ou problema**
Esta é uma dúvida referente à thread já fechada https://github.com/bacen/pix-perguntas-e-respostas/issues/252

Qual o domínio de valores aceitos para o txId? Vocês acham que realmente faz sentido deixar o usuário criar um identificador para o recebimento? O campo infoAdicionais já não cumpriria este papel?

Em tempo: Preciso de um identificador único para correlacionar o recebimento ao qrcode. Como fazer neste caso? Uma vez que se é o usuário que fornece o identificador eu não posso garantir que ele será único.

O que vocês recomendam para eu correlacionar o recebimento ao QRCode gerado?

**Comment by ninrod** [comment]
@mvleandro , boa noite. 

Assumo que estamos falando aqui exclusivamente do QR Estático. 

O QR Estático no PIx admite um txid localizado no campo 62-05. O QR Estático é regrado pelo  Manual do BR Code que segue o Padrão EMV for QR Codes - merchant presented mode. O EMV diz que o formato desse campo é ANS - alpha numeric special. 

Estamos estudando restringir um pouco mais a variedade de caracteres disponíveis porque alguns caracteres que fazem parte do ANS ficam incompatíveis em uma URL. De saída, letras [a-z] e números [0-9] é uma escolha bastante segura. 

Quanto ao correlacionamento: 

No fluxo de QR estático, No contexto da API Pix, basta o PSP expor, para o recebedor, os pix recebidos em sua conta que estão relacionados a um txid. O recebedor programará sua conciliação usando os endpoints da API [específicos para esse fim](https://github.com/bacen/pix-api/blob/master/openapi.yaml#L267-L272) ou o webhook pix.

**Comment by mvleandro** [comment]
@ninrod  Entendi o ponto sobre o formato porém ainda não está claro como eu correlaciono o txId ao qrCode uma vez que se é o usuário que escolhe este valor ele não tem como ser único.

**Comment by ninrod** [comment]
@mvleandro quando qual seria o seu papel? (usuário recebedor? PSP?)

**Comment by mvleandro** [comment]
@ninrod  Reabri este ponto aqui..

https://github.com/bacen/pix-perguntas-e-respostas/issues/320

**Comment by ninrod** [comment]
@mvleandro , ok.
