### ISSUE TITLE
[Dúvida] no [DICT] - Processo conclusão do pedido de reivindicação - PSP reivindicador

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#30]
**Descreva sua dúvida ou problema**
Olá! Tenho uma dúvida referente ao tempo de ANS para conclusão do pedido de reivindicação por parte do PSP reivindicador.
No manual versão 6.2, diz que o ANS é de 60 segundos, que entendo que deveria ocorrer assim que o PSP reivindicador fica sabendo da confirmação do pedido pelo PSP doador.

![image](https://user-images.githubusercontent.com/5355541/86193133-9406a600-bb21-11ea-880c-000132cbcfbe.png)

Porém, na descrição do fluxo do PSP reivindicador, fala que se o pedido for confirmado pelo PSP doador, o PSP reivindicador, deve fazer a validação ativa da posse de chave novamente.

![image](https://user-images.githubusercontent.com/5355541/86193014-45f1a280-bb21-11ea-8969-2eadc93700fd.png)

1 - Nesse caso, devemos fazer a validação ativa primeiro ou chamar o serviço de conclusão?

2 - O passo 8 do fluxo, seria chamar o serviço de conclusão? Se não for, qual serviço deve ser chamado nesse passo?

Eu havia entendido que é necessário validar a posse da chave novamente, nesse caso, o ANS nunca seria cumprido, por ser um tempo muito curto.

**Sistema ou Área**
DICT

**Comment by monise** [comment]
Olá! Gostaria de confirmar se o fluxo no cenário de **reivindicação de posse de chave**, **visão reivindicador** é:

1 - Quando o PSP reivindicador tem o retorno do pedido, **independente** se ele foi confirmado ou cancelado, ele deve chamar o serviço de complete? (serviço _POST /claims/{ClaimId}/complete_)

2 - E para o caso do pedido ter sido confirmado, após a validação da posse da chave, devemos chamar o serviço de atualização da chave? (serviço _PUT /entries/{Key}_)

Obrigada

**Comment by carloschioquetta** [comment]
Prezada,
Nesse caso, o período de 60 segundo se refere ao período entre a confirmação ou cancelamento da reivindicação pelo PSP doador e a consulta dessa situação na API pelo PSP reivindicador. Assim, não se espera que a reivindicação seja concluída nesse período, uma vez que, no caso de confirmação, ela deve ser concluída apenas após o usuário reivindicador fazer a segunda validação de posse.

A conclusão da reivindicação se dá no Passo 7. No passo 8, o DICT recebe a conclusão e atualiza os dados.

A conclusão (complete) é enviada após o PSP reivindicador identificar a confirmação ou o cancelamento pelo PSP reivindicador e, no caso de confirmação, após a segunda validação de posse.

**Comment by monise** [comment]
Obrigada pelo retorno!

1 - Apenas para confirmar, segundo o swagger, o _complete_ só utilizamos caso o pedido tenha sido **confirmado**, certo?
![image](https://user-images.githubusercontent.com/5355541/86675871-7083a580-bfd0-11ea-91b9-38335e56377f.png)

2 - Para cancelamento, o PSP reivindicador tem que realizar alguma ação?

3 - E não é necessário em nenhuma etapa da reivindicação, utilizar o serviço de atualização (PUT /entries/{Key})

Obrigada!

**Comment by judahreis** [comment]
Monise,

1. Vc está correta, o complete só é chamado para claims confirmadas.
2. Para cancelamento, é necessário chamar o endpoint /claims/{claimId}/cancel. Enquanto ele não for invocado, a claim permanece waiting_resolution, e pode gerar sanções ao participante doador se exceder o período de 7 dias.
3. Não é necessária nenhuma ação em entry depois de completar a claim. O própria complete irá fechar a claim e atualizar o vínculo da chave, não sendo necessário invocar /entries/{key}.
