### ISSUE TITLE
[Problema] DICT - Atualizar Vínculo - EVP

### ISSUE THREAD

**Issue by CarlosAguilart** [bacen/pix-perguntas-e-respostas#300]
**Descreva seu problema**
Erro 500 Bacen Atualizar Vínculo

**Sistema ou Área**
DICT

**Identificador do Problema**
Erro 500 Bacen

**URL de conexão**
https://dict-h.pi.rsfn.net.br:16522/api/v1/entries/{Key}

**Dados adicionais**

**Comment by luizlaydner** [comment]
Por gentileza, teria o correlationId desse problema ?

**Comment by CarlosAguilart** [comment]
> Por gentileza, teria o correlationId desse problema ?

O problema não apresentou correlationId no corpo de resposta.
