### ISSUE TITLE
Emissão de QR Code estático - API PIX

### ISSUE THREAD

**Issue by b-alencar** [bacen/pix-perguntas-e-respostas#302]
Prezados, há expectativa de emissão de QR Code estatico via API PIX? Não há nenhum campo onde possa se informar qual o tipo de QR Code o cliente deseja emitir nessa API.

**Comment by ninrod** [comment]
A "emissão" de QR estático encontra-se fora da API Pix. 

Contudo, é possível filtrar Pix por txid na API Pix via `GET /pix?txid=[txid]`.
