### ISSUE TITLE
[Dúvida] no [DICT] - Campo DonorParticipant é required ou opcional 

### ISSUE THREAD

**Issue by marinafsiq** [bacen/pix-perguntas-e-respostas#304]
**Descreva sua dúvida ou problema**
Gostaríamos saber se o campo DonorParticipant que vem na Claim (em especial na resposta do endpoint de listar reivindicações) é required ou opcional.

**Sistema ou Área**
DICT

**Dados adicionais**
Gostaríamos de tirar uma dúvida em relação ao campo DonorParticipant que vem na Claim (em especial na resposta do endpoint de listar reivindicações).
Na documentação da API, temos que o DonorParticipant não é required (ver foto abaixo).  
![dict-api-donor](https://user-images.githubusercontent.com/7493039/93947460-2037fc00-fd12-11ea-85c8-db38334841a6.png)

Porém, baixei o "spec.json" da última release da API (este link), e lá está escrito que no esquema de resposta do endpoint em questão um dos campos required é o campo "Donor". Mas, não existe no esquema um campo "Donor", só existe "DonorParticipant". (Veja foto abaixo) 
![spec-dict-api-donor](https://user-images.githubusercontent.com/7493039/93947484-32199f00-fd12-11ea-9c16-88f9bcadc8ed.png)

Então, o campo DonorParticipant é required ou opcional? 
Se ele for opcional, em quais cenários ele vem preenchido?
Com essa resposta descobrimos se podemos sempre utilizar este campo ou não.

Muito obrigado desde já!

**Comment by luizlaydner** [comment]
Há erro na especificação. `DonorParticipant` é campo obrigatório de `ExtendedEntry`. Vamos corrigir na próxima versão minor da API.
Muito obrigado por apontar!

**Comment by marinafsiq** [comment]
Muito obrigada por confirmar este ponto pra gente! :)

**Comment by luizlaydner** [comment]
Versão da spec da API 1.0.1 foi publicada. Ver aqui https://github.com/bacen/pix-dict-api/releases/tag/v1.0.1
Essa nova versão corrige o erro apontado nesse issue.
