### ISSUE TITLE
[Dúvida] no [DICT] - Apóstrofo no nome de cliente

### ISSUE THREAD

**Issue by marinafsiq** [bacen/pix-perguntas-e-respostas#305]
**Descreva sua dúvida ou problema**
Gostaria de esclarecer uma dúvida a respeito do caractere apóstrofo (') no nome do beneficiário no momento de registro de chave no DICT. Atualmente, estamos tomando o seguinte erro:

```
<detail>Invalid parameters</detail><correlationId>B8A416F26736419696765F7E1500EB91</correlationId><violations><violation><reason>Value has a character not allowed</reason><value>Camylle O'Hara</value><property>entry.owner.name</property>
```

O que devemos fazer na situação em que o cliente possuir tal caractere em seu nome? (ou outros caracteres especiais)

**Sistema ou Área**
DICT

**Identificador do Problema**
correlationId: B8A416F26736419696765F7E1500EB91
ISPB: 18236120

**Comment by luizlaydner** [comment]
@marinafsiq , veja https://github.com/bacen/pix-perguntas-e-respostas/issues/99#issuecomment-663062576 .

Para nomes de pessoas físicas, a regex utilizada atualmente não permite apóstrofo.
Vamos ver aqui se relaxamos essa restrição, visto que esses nomes são relativamente comuns.

**Comment by marinafsiq** [comment]
Muito obrigada pelo esclarecimento.

Vocês vão tentar relaxar esta restrição já para o dia 5?
Se não forem relaxar a restrição até dia 5, como devo proceder? Retirar os apóstrofos (e outros caracteres especiais) do nome do cliente antes de fazer o request para o Bacen?

Mais uma vez, muito obrigada!!

**Comment by luizlaydner** [comment]
Fizemos ajuste no backend já para permitir. Alteração deve ser publicada hoje após 18h.
Portanto, pro dia 05/10 em produção, serão aceitos nomes com apóstrofo.
Especificação será ajustada depois.

**Comment by marinafsiq** [comment]
Muitíssimo obrigada pela ajuda, esclarecimento e rapidez na resposta! :)

**Comment by rodriguesdanilo** [comment]
Olá pessoal, ontem enviamos alguns nomes com apóstrofo mas houve retorno de `Violation`. Por exemplo no `correlationId` **`6BC962091F404DCEBE3F9A80242255CC`**.

Poderiam verificar se o ajuste foi publicado?

**Comment by luizlaydner** [comment]
@rodriguesdanilo O ajuste foi publicado. 
O char unicode ['APOSTROPHE' (U+0027)](https://www.fileformat.info/info/unicode/char/27/index.htm) é permitido para nomes de pessoas físicas.
O char unicode ['RIGHT SINGLE QUOTATION MARK' (U+2019)](https://www.fileformat.info/info/unicode/char/2019/index.htm), **não** é permitido.

**Comment by davidbsr** [comment]
É possível divulgar o Regex atual para validarmos nas nossas aplicações antes de chegar no BC?

**Comment by luizlaydner** [comment]
@davidbsr 

Regex para nomes de [pessoas físicas](https://github.com/bacen/pix-dict-api/blob/a5cce64c812e38b1072e2aff7b9b1930eff66683/openapi/schemas.yaml#L71) .
Regex para nomes de [pessoas jurídicas](https://github.com/bacen/pix-dict-api/blob/a5cce64c812e38b1072e2aff7b9b1930eff66683/openapi/schemas.yaml#L92) .

A única alteração de regex que houve mas que não refletida na especificação ainda foi permitir ['APOSTROPHE' (U+0027)](https://www.fileformat.info/info/unicode/char/27/index.htm) em nomes de pessoas físicas, solicitado aqui nessa issue. 
Com entrada em produção do DICT, não tivemos tempo de atualizar ainda a especificação.

**Comment by luizlaydner** [comment]
Release v1.0.1 da spec da API foi feita. Inclui a atualização da regex de nome de pessoa física.
Ver em https://github.com/bacen/pix-dict-api/releases/tag/v1.0.1
