### ISSUE TITLE
[Dúvida] no [DICT] - Erro ao fechar relato de infração

### ISSUE THREAD

**Issue by VictorPToledo** [bacen/pix-perguntas-e-respostas#307]
**Descreva sua dúvida ou problema**
Ao tentar fechar um relato de infração seguindo o padrão de documentação do BACEN a assinatura seria um campo vazio, porém ao enviar a querry para o BACEN ele retorna a seguinte mensagem "XML signature does not match digests or certificate"

**Sistema ou Área**
DICT - Fechar relato de infração

**Identificador do Problema**
Signature

**Comment by luizlaydner** [comment]
@VictorPToledo Em homologação, para facilitar testes, é possível enviar requisições sem o campo `Signature` . Caso a tag esteja presente, ela será validada. Tag presente mas vazia nesse caso é inválido. 

Nos exemplos da API a tag `Signature` apenas consta para lembrar da sua existência.
Em produção, todas requisições com corpo terão a assinatura validada.

Mais  detalhes, [veja aqui](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API_do_DICT-v1.0.html#section/Seguranca/Assinatura-digital).

**Comment by VictorPToledo** [comment]
Se eu tento enviar sem assinatura reclama que está faltando a mesma.
