### ISSUE TITLE
[Dúvida] no [DICT] - Url de verificação

### ISSUE THREAD

**Issue by gabrielmendesbb** [bacen/pix-perguntas-e-respostas#308]
Existe algum endpoint de  verificação do serviço DICT? tipo um /health
Pq estou tendo problemas com conexão onde o bacen me retorna erro 502. geralmente reinicio meu serviço e volta funcionar. se tivesse esse endpoint de verificação poderia configurar meu serviço p reiniciar sozinho caso perdesse a conexao com o dict.

**Comment by luizlaydner** [comment]
Você pode usar a consulta ao CNPJ do BC para esse propósito (teste de conectividade com DICT). A chave CNPJ do BC é `0038166000105` .

Usar um pool de conexões é uma boa opção para gerenciar as conexões HTTP. Para java, tem por exemplo [PoolingHttpClientConnectionManager](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.html).
Se necessário ajuda do lado do BC para investigar problema de conectividade, contate o atendimento via telefone.

**Comment by marioary** [comment]
@luizlaydner boa tarde, há alguma forma de fazer esse tipo de verificação também no ICOM e no ARQ?

**Comment by gabrielmendesbb** [comment]
@luizlaydner 
na consulta de chave 0038166000105 veio erro "key does not match any valid key types".
deveria retornar dados da chave de teste do bacen?

**Comment by luizlaydner** [comment]
Faltou um zero no copiar/colar: `00038166000105`

**Comment by luizlaydner** [comment]
> @luizlaydner boa tarde, há alguma forma de fazer esse tipo de verificação também no ICOM e no ARQ?

@marioary
ICOM tem mensagem específica para  teste de conectividade: `PIBR.001` . Veja o catálogo de serviços do SFN [Volume VI - Pagamentos Instantâneos](https://www.bcb.gov.br/content/estabilidadefinanceira/cedsfn/Catalogos/Catalogo_de_Servicos_do_SFN_Volume_VI_Versao_501.pdf) , seção sobre "Mensagens para teste de conectividade" .


ARQ , creio que não tenha endpoint para esse propósito.
