### ISSUE TITLE
[Problema] CAMT054 - Validação XSD

### ISSUE THREAD

**Issue by mfabioe** [bacen/pix-perguntas-e-respostas#31]
A validação XSD da CAMT.054 está dando o seguinte erro:
Value '' is not facet-valid with respect to pattern '[D][0-9]{8}[0-9]{4}[0-1][0-9][0-3][0-9][0-2][0-9][0-5][0-9][a-zA-Z0-9]{11}' for type 'InstrIdType'.

trecho do XML com problema, retornado pelo Bacen:
`<Refs>
    <InstrId />
    <EndToEndId>E00360305202006301337fd3a1f001c1</EndToEndId>
    <ClrSysRef />
    <TxId />
</Refs>`

Devido a existência do campo, mesmo não tendo valor, ele é validado. E quando ele existe, deve obedecer o formato definido no XSD.
Não seria o caso de ser retirado quando não tiver valor para que a validação pelo XSD seja realizada corretamente?

**Comment by LeoGonCha** [comment]
Qual é o identificador msgId da mensagem enviada com problema?

**Comment by mfabioe** [comment]
@LeoGonCha acho que todas CAMT.054 que solicitamos tiveram esse problema.
Esse é um exemplo: M000381660KC3C5VND1037IY6H7XBQOW
Possui outros campos, além do InstrId que estão sem valor.

**Comment by cristianokbc** [comment]
@mfabioe, de fato há um bug na geração do XML. Vamos resolver e avisaremos quando a versão corrigida estiver publicada.

**Comment by rafael-omello** [comment]
Versão corrigida já está publicada.
