### ISSUE TITLE
[Problema] no [DICT] - Relato de Infração retorna erro quando não informado "ReportDetails"

### ISSUE THREAD

**Issue by WagnerLau** [bacen/pix-perguntas-e-respostas#310]
**Descreva sua dúvida ou problema**
Ao realizar enviar uma requisição para API "Criar Relato de Infração", sem informar o parâmetro opcional "ReportDetails", o DICT está retornando o erro:
_type: https://dict.pi.rsfn.net.br/api/v1/error/InternalServerError
title: Internal Server Error
status: 500
detail: Internal server error. Please contact support for details._

Quando o parâmetro opcional "ReportDetails" é informado, o erro citado não é retornado. Retornando o status "201" como esperado.

Vocês podem verificar esse problema?

**Sistema ou Área**
DICT

**Identificador do Problema**
ISPB: 36586946
Dt.Hr. do Problema: 2020-09-23 15:24:03.704
Correlation-Id: C7CA875111584EF78D1C1BCF6D405F2D
TransactionId: E3658694620200922125124115918874

**Comment by luizlaydner** [comment]
Identificamos a causa do problema. Será corrigido e liberado muito em breve.
