### ISSUE TITLE
[Problema] no [DICT] - ConfirmReason ou CancelReason não enviados na listagem

### ISSUE THREAD

**Issue by alexandrepkill** [bacen/pix-perguntas-e-respostas#311]
**Descreva sua dúvida ou problema**
Essa é uma issue duplicada da https://github.com/bacen/pix-perguntas-e-respostas/issues/274 que foi fechada e acabei abrindo por não saber se está sendo tratada de algum modo. Estamos enfrentando aqui o mesmo problema. Sabe me dizer quando ou release que isso vai ser liberado ?

**Comment by luizlaydner** [comment]
A correção já foi feita e liberada!

No entanto, as reivindicações/portabilidades com status='CANCELLED' anteriores a 2020-09-19 estão sem campos `CancelReason` e `CancelledBy`. Como as informações não estavam sendo gravadas, ficarão assim mesmo. 

Reivindicações/portabilidades canceladas a partir de 2020-09-19 terão esses campos preenchidos.
