### ISSUE TITLE
[Dúvida] no [DICT] - Cálculo do CID da chave recebida na conclusão de uma Reivindicação

### ISSUE THREAD

**Issue by WagnerLau** [bacen/pix-perguntas-e-respostas#312]
**Descreva sua dúvida ou problema**
A documentação "API do DICT" divulgado no site do BACEN, é informado o seguinte cálculo para o CID:

_entryAttributes = keyType "&" key "&" ownerTaxIdNumber "&" ownerName "&" ownerTradeName "&" participant "&" branch "&" accountNumber "&" accountType
cidBytes = hmacSha256(requestIdBytes, entryAttributes)
cid = lowercase-hexadecimal(cidBytes)_

Para calcular o CID de uma chave de endereçamento recebida na conclusão de uma reivindicação, o "requestIdBytes" que deve ser utilizado é o "id" (Identificador da Reivindicação)?

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
> Para calcular o CID de uma chave de endereçamento recebida na conclusão de uma reivindicação, o "requestIdBytes" que deve ser utilizado é o "id" (Identificador da Reivindicação)?

Não. 
Deve ser usado o campo `RequestId` do `CompleteClaimRequest`. O `RequestId` dessa requisição fica então associado ao `Entry` que ela cria, sendo utilizado no cálculo do CID.

**Comment by WagnerLau** [comment]
Prezados,

Ainda sobre este mesmo tema "Cálculo do CID", tenho mais uma dúvida:
- Após enviar uma requisição para API "Atualizar Vínculo", devemos utilizar o mesmo "RequestId" utilizado na "Criação do Vínculo" para realizar o cálculo do CID?
Obs.: Visto que a API "Atualizar Vínculo" não possui "RequestId".
