### ISSUE TITLE
[Problema] no [DICT] - Error 500 ao consultar vínculo por CID disponibilizado em arquivo

### ISSUE THREAD

**Issue by thomassouzazup** [bacen/pix-perguntas-e-respostas#315]
**Descreva sua dúvida ou problema**
Solicitamos um arquivo na DICT, baixamos ele e um dos CIDs disponibilizado está retornando erro 500 sempre que consultamos vínculo via CIDs o CID com erro é o f730d90036285585a6349cd6a337d0b1814da4602ed331a4ab389b90ddc7192e

**Sistema ou Área**
DICT

**Identificador do Problema**
06B4D8153A574370815EE959418D870E

**Mensagens Enviadas / Recebidas**
/cids/entries/f730d90036285585a6349cd6a337d0b1814da4602ed331a4ab389b90ddc7192e

<problem xmlns="urn:ietf:rfc:7807">
    <type>https://dict.pi.rsfn.net.br/api/v1/error/InternalServerError</type>
    <title>Internal Server Error</title>
    <status>500</status>
    <detail>Internal server error. Please contact support for details.</detail>
    <correlationId>06B4D8153A574370815EE959418D870E</correlationId>
</problem>

**URL de conexão**
https://dict-h.pi.rsfn.net.br:16522/api/v1

**Dados adicionais**
O CID informado foi retirado do arquivo baixado do arq-h e não foi alterado.

**Comment by luizlaydner** [comment]
@thomassouzazup, os vínculos com os seguintes CIDs do seu PSP:

```
812616d4f1790f2162ea7e1433ac4d4fb70fa8b0b36fa3d3a0bee5dc9474613f  - chave 16938960011
f730d90036285585a6349cd6a337d0b1814da4602ed331a4ab389b90ddc7192e  - chave contalis@teste.com
```

Foram registrados com nomes de pessoa que parecem ter tido problema de encoding em algum ponto.
Há na string do nome um [REPLACEMENT CHARACTER](https://www.fileformat.info/info/unicode/char/0fffd/index.htm), o que reforça essa hipótese.

Como na data em que essas chaves foram registradas em homologação não havia validação dos caracteres permitidos para nomes de pessoas físicas e jurídicas (ver [aqui](https://github.com/bacen/pix-dict-api/blob/a5cce64c812e38b1072e2aff7b9b1930eff66683/openapi/schemas.yaml#L71) na especificação da API), é possível que tenha sido aceito um caractere que cause problema no cálculo do CID.

Você poderia passar os bytes da string codificada em UTF-8 do `OwnerName` para os vínculos com das chaves acima ?

**Comment by thomassouzazup** [comment]
@luizlaydner, realmente este é o problema, consultando os registros em nossa base constatei que o nome para os dois registos é o seguinte
PMD ZÃ ZÃ RIO BLAZ

É possível deleta-ló da base de dados do Bacen para que não ocorra do registro ser retornado no arquivo de CIDs? Deletar também os demais que estiverem na mesma situação para que possamos rodar o sincronismo sem este erro 500.

**Comment by thomassouzazup** [comment]
@luizlaydner, realmente este é o problema, consultando os registros em nossa base constatei que o OwnerName para os dois registos é o seguinte

\x50\x4D\x44\x20\x5A\xC3\x83\xC2\x89\x20\x5A\xC3\x83\xC2\x89\x20\x52\x49\x4F\x20\x42\x4C\x41\x5A

É possível deleta-ló da base de dados do Bacen para que não ocorra do registro ser retornado no arquivo de CIDs? Deletar também os demais que estiverem na mesma situação para que possamos rodar o sincronismo sem este erro 500.

**Comment by HenriqueSimoes82** [comment]
@thomassouzazup registros deletados.
