### ISSUE TITLE
[Dúvida| no [QR-CODE] - Juros e Multa

### ISSUE THREAD

**Issue by b-alencar** [bacen/pix-perguntas-e-respostas#316]
Prezados, boa noite!

Nos requisitos mínimos de experiencia do usuário que foi lançado hoje os campos de juros e multa permanecem na experiencia, porém, foram retirados do retorno das APIs. Esse modelo será equalizado? Podemos ter campos adicionais na geração de QR Code? O valor final também está relacionado no manual de experiencia e não está nas APIs.

**Comment by ninrod** [comment]
Prezado @b-alencar , os juros e multa, entre outras questões correlatas, serão objeto de especificação na API. Esperamos, em breve, lançar uma nova versão da API, compatível com a `2.0.0`, tratando destes pontos. Apenas resolvemos quebrar a entrega em duas partes.
