### ISSUE TITLE
[Dúvida] APi Pix 2.0 - Indiretos

### ISSUE THREAD

**Issue by mariapessoacaldas** [bacen/pix-perguntas-e-respostas#318]
**Descreva sua dúvida ou problema**
A API Pix padronizada é obrigatória para os Indiretos? 

**Sistema ou Área**
Api Pix, Qr Code

**Comment by ninrod** [comment]
@mariapessoacaldas , bom dia.

Se o PSP recebedor indireto quiser oferecer uma integração automatizada Pix para seus clientes, então deve implementar a API Pix. 

O PSP recebedor não é obrigado a oferecer uma integração automatizada Pix para seus clientes.

**Comment by franciscotfmc** [comment]
@ninrod , boa noite!

O BC já sinalizou que o envio de Pix entrará na agenda evolutiva da API Pix.

Me parece fazer sentido que o gerenciamento de chaves também seja especificado aqui, e o próprio participante indireto possa também utilizar a API Pix.

Nesse caso, ele poderia ter acesso a um scope extra: _cadastrar chaves em nomes de terceiros._, scope que não fica disponível para recebedores Pix.

Faz sentido?

**Comment by ninrod** [comment]
bom dia @franciscotfmc . 

> O BC já sinalizou que o envio de Pix entrará na agenda evolutiva da API Pix.

Não entendi. O que exatamente "envio de Pix" quer dizer? 

> Me parece fazer sentido que o gerenciamento de chaves também seja especificado aqui, e o próprio participante indireto possa também utilizar a API Pix.

Pode até fazer sentido sim, você gerenciar suas chaves via API, mas já está estabelecido que a gerência de chaves acontecerá no contexto do relacionamento do usuário recebedor com seu PSP e já não há tempo hábil para mudar esse entendimento.

**Comment by franciscotfmc** [comment]
Boa tarde @ninrod!

> Não entendi. O que exatamente "envio de Pix" quer dizer?

Desculpe, acho que me expressei mal. O que tentei dizer é que está prevista na agenda evolutiva do Pix a padronização também de funcionalidades para envio de pagamentos. Isso siginifica que praticamente todo o arcabouço de funcionalidades necessárias para o participante indireto estará, salvo o gerenciamento das chaves, padronizado pela API Pix.

Por que não adicionar, na agenda evolutiva da API Pix, os endpoints para gerenciamento das chaves também? 

Penso que isso possa facilitar a incorporação de futuros participantes indiretos no arranjo de pagamentos instantâneos.
