### ISSUE TITLE
[Dúvida] Quando cliente final paga PIX dinâmico via QR, qual retorno de  dados?

### ISSUE THREAD

**Issue by felipesalomao** [bacen/pix-perguntas-e-respostas#319]
Quando gero um QR Code dinâmico para pagamento de um pedido em específico, é possível resgatar dados específicos do comprador como cpf, email ou nome do pagador?

**Comment by ninrod** [comment]
@felipesalomao , sim é possível. Você encontra essa informação na especificação da API Pix: https://github.com/bacen/pix-api
