### ISSUE TITLE
[Dúvida] no [DICT] - Remover Vinculo para Participante Indireto via Direto

### ISSUE THREAD

**Issue by asampaio77** [bacen/pix-perguntas-e-respostas#32]
Nas definições da API do BACEN "Remover Vínculo", só há possibilidade de informar as tags abaixo:
      Signature
      KEY - chave de endereçamento
      Reason - motivo da exclusão
     
Conforme definido em consulta realizada ao Bacen anteriormente, o PSP direto, não poderia/deveria armazenar os dados do PSPI. Como na requisição acima nao há possibilidade de repassar informação que a origem da requisição é um Participante indireto (ISPB indireto), como o PSP direto e o proprio BACEN identificarão neste caso, se aquela solicitação de exclusão/remoção da chave pode ser concretizada?
 
Exemplo: Um PSP direto possui convenio com 2 PSPIs, sendo que chegou uma requisição de 
1 PSPI solicitando a exclusao de chave de outro PSPI do mesmo PSP, como o PSP direto nao possui a 
base internalizada dos PSPIs, repassará a solicitação ao BACEN, neste caso será processada a exclusão ?

**Comment by luizlaydner** [comment]
@asampaio77  Esse defeito da API foi corrigido na [v1.0.0-RC4](https://github.com/bacen/pix-dict-api/releases/tag/v1.0.0-RC4) . 

> **Adicionado**
Campo Participant em AcknowledgeClaimRequest, CancelClaimRequest, ConfirmClaimRequest, CompleteClaimRequest e DeleteEntryRequest

 
Essa versão da API, no entanto, não foi ainda para o ambiente de homologação. Deve ir essa semana ainda. Será comunicado.
