### ISSUE TITLE
[Dúvida] no [ICOM] - Cenário de falha na interrupção de streams

### ISSUE THREAD

**Issue by pealima** [bacen/pix-perguntas-e-respostas#321]
**Descreva sua dúvida ou problema**

Gostaríamos de levantar algumas dúvidas relacionadas à conexão com a ICOM, de modo a garantir que não haverá perdas na maneira como consumimos as mensagens recebidas.

Considerando o seguinte cenário excepcional de falha:

- Iniciamos a leitura de uma stream A
  - `GET /api/v1/out/{ispb}/stream/start`
- Ocorre uma falha no processamento interno
- Por conta desta falha, não conseguimos realizar a interrupção usando o método DELETE, conforme descrito na etapa 7 do exemplo no item 2.2.2.5 do Manual de Interfaces de Comunicação (p.22).
  - `DELETE /api/v1/out/11111111/stream/8e20a682c86f`
  - Dado que não executamos a chamada acima, entendemos que não informamos à ICOM que as últimas mensagens entregues a nós foram corretamente guardadas, marcando-as como efetivamente lidas.
- Nós realizamos uma chamada para início de leitura da saída de uma nova stream B e abandonamos a stream A, de acordo com o item 2.2.2 do Manual de Interfaces de Comunicação (p.18).
  - `GET /api/v1/out/{ispb}/stream/start`

Neste cenário, temos as seguintes perguntas:

1. Dada a não interrupção do stream A, e considerando que podem ter mensagens advindas deste stream que não foram processadas, existe a possibilidade destas mensagens não serem enviadas no stream B ou em outro que venha a ser aberto? 
2. Caso positivo para a pergunta (1), por quanto tempo as mensagens estarão disponíveis no stream B ou em outro que venha a ser aberto?
3. De acordo com o Manual, "a falha em finalizar a leitura com DELETE pode causar a entrega posterior de mensagens em duplicidade ou ainda atraso na entrega de algumas mensagens" (p.20). Há alguma estimativa ou garantia de quanto tempo de atraso poderá ocorrer na entrega destas mensagens no stream B ou em outro que venha a ser aberto?
4. O que acontece com a stream A que foi abandonada sem a interrupção por meio do DELETE? Ela será fechada automaticamente após um determinado período de tempo? Caso positivo, há uma estimativa deste tempo?

**Sistema ou Área**
SPI

**Identificador do Problema**
n/a

**Mensagens Enviadas / Recebidas**
n/a

**URL de conexão**
n/a

**Dados adicionais**
Referência à versão 1.5 do [Manual das Interfaces de Comunicação](https://www.bcb.gov.br/content/estabilidadefinanceira/cedsfn/Manual%20das%20Interfaces%20de%20Comunica%C3%A7%C3%A3o-1.5.pdf)

**Comment by cristianokbc** [comment]
1. Não há a possibilidade de perda de mensagem, apenas atraso, pois elas serão enviadas novamente após um período de espera.
2 e 3. Hoje o tempo é 10s, mas podemos reavaliar, se necessário.
4. Internamente não há, de fato, um fechamento. Após algum tempo, normalmente haverá um PullNext com um mesmo caminho já enviado no stream A. É como se houvesse uma junção do stream antigo com o novo (ou outro qualquer mais antigo que ainda esteja "ativo"). Isso ocorre no mesmo tempo dos itens 2 e 3.
