### ISSUE TITLE
[Dúvida] no [DICT] - Cálculo do CID ao Atualizar Vínculo

### ISSUE THREAD

**Issue by WagnerLau** [bacen/pix-perguntas-e-respostas#324]
**Descreva sua dúvida ou problema**
A documentação "API do DICT" divulgado no site do BACEN, é informado o seguinte cálculo para o CID:

entryAttributes = keyType "&" key "&" ownerTaxIdNumber "&" ownerName "&" ownerTradeName "&" participant "&" branch "&" accountNumber "&" accountType
cidBytes = hmacSha256(requestIdBytes, entryAttributes)
cid = lowercase-hexadecimal(cidBytes)

Para calcular o CID de uma chave de endereçamento após enviar uma requisição a API "Atualizar Vínculo", o "requestIdBytes" que deve ser utilizado é o "RequestId" utilizado na "Criação do Vínculo" para realizar o cálculo do CID?
Obs.: Visto que a API "Atualizar Vínculo" não possui "RequestId".

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
> Para calcular o CID de uma chave de endereçamento após enviar uma requisição a API "Atualizar Vínculo", o "requestIdBytes" que deve ser utilizado é o "RequestId" utilizado na "Criação do Vínculo" para realizar o cálculo do CID?

Exato. O `RequestId` é um campo que fica associado ao vínculo. 
Ele é gerado pelo participante no momento da criação do vínculo, pelas operações `createEntry` e `completeClaim` . 
O cálculo do CID é sempre feito com o requestId associado ao vínculo.
