### ISSUE TITLE
[Problema] no [DICT] - Sync-verifications

### ISSUE THREAD

**Issue by marxms** [bacen/pix-perguntas-e-respostas#326]
**[Problema] no [DICT] – [RECONCILIÇÃO - Sincronização via Arquivo Cids] Endpoint ‘/sync-verifications’ retornando NOK em todas as requisições**

**Descreva sua dúvida ou problema**
Prezado, em alguns testes da funcionalidade de reconciliação, após a base dados interna concluir com sucesso a sincronização dos cids, foi verificado que o vsync calculado é o mesmo vsync calculado do arquivo de cids fornecido pelo bacen, porém, ao requisitar a api de verificação, a mesma sempre está invalidando o cálculo submetido.
Foi realizado o seguinte teste de contraprova para verificar a integridade do cálculo realizado:
O Ambiente de homologação foi congelado e uma primeira sincronização foi submetida, posteriormente em runtime da aplicação verificamos que o cálculo de vsync do conteúdo do arquivo era o mesmo calculado por todos os registros ativos obtidos na base de dados interna, ao fim da sincronização foi submetido ao endpoint ‘/sync-verifications’ e obtida a invalidação. Em seguida foi submetido um novo processo de sincronização via arquivo cids e feito o cálculo do arquivo anterior, o arquivo atual e os registros da base, tendo em vista que não havia nenhum cid a ser incluído ou excluído do ambiente interno, já que o mesmo estava congelado, e todos os 3 vsyncs convergiram. O mesmo teste ocorreu para validar o vsync calculado dos 3 cids que constam no exemplo da documentação provida na página oficial da API do DICT.

**Sistema ou Área**
DICT

**Identificador do Problema**
N/E

**Mensagens Enviadas / Recebidas**
GET /cids/files/116319
GET /cids/files/116384
POST /sync-verifications
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CreateSyncVerificationRequest>
    <Signature/>
    <SyncVerification>
        <Participant>xxxxxxxx</Participant>
        <KeyType>EMAIL</KeyType>
        <ParticipantSyncVerifier>9ea5d154d89e3b9323d64e88619e3ab279f05e222b25b9695f99e815da4d2712</ParticipantSyncVerifier>
    </SyncVerification
</CreateSyncVerificationRequest>

**URL de conexão**
https://dict-h.pi.rsfn.net.br:16522/api/v1

**Dados adicionais**

•	O vsync enviado no request /sync-verifications foi o mesmo calculado para todos as chaves no ambiente interno também
•	O Problema também ocorre para outros tipos de cids
•	Não foi identificada nenhuma mudança no calculo de vsync, e o algoritmo utilizado para executar a tarefa obteve sucesso no exemplo abaixo provido pelo bacen:
cids = ['28c06eb41c4dc9c3ae114831efcac7446c8747777fca8b145ecd31ff8480ae88', 
        '4d4abb9168114e349672b934d16ed201a919cb49e28b7f66a240e62c92ee007f', 
        'fce514f84f37934bc8aa0f861e4f7392273d71b9d18e8209d21e4192a7842058']

vsync = xor(xor(cids[0], cids[1]), cids[2])  = '996fc1dd3b6b14bcf0c9fe8320eb66d7e2a3fd874ccf767b2e939641b1ea8eaf'

**Comment by dhincerti** [comment]
Olá!
Teriam algum posicionamento sobre esta dúvida?
Conseguimos fazer a sincronização e verificação, somente para o tipo EVP até o momento, e precisamos de um feedback sobre essa questão.
Obrigado!

**Comment by dhincerti** [comment]
Realizamos testes gerando o vsync, a partir das informações retornadas da pela [API Listar Eventos de CIDs](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API_do_DICT-v1.0.html#operation/listCidSetEvents) e constatamos que o valor final do vsync só é obtido, quando o primeiro CID é ignorado no cálculo, conforme evidências anexas.

O problema é que, para o arquivo gerado, não é possível saber, qual CID deve ser ignorado.
Me parece ser um bug. Poderiam avaliar o mais rápido possível, por favor?

Obrigado!

![image (7)](https://user-images.githubusercontent.com/5710799/94834655-05871680-03e7-11eb-862b-91af131f3aa7.png)
![Screenshot from 2020-10-01 12-55-57](https://user-images.githubusercontent.com/5710799/94834142-5ea27a80-03e6-11eb-8426-0b057f42daad.png)
![Screenshot from 2020-10-01 12-57-10](https://user-images.githubusercontent.com/5710799/94834138-5d714d80-03e6-11eb-8c64-951778aaa529.png)

**Comment by HenriqueSimoes82** [comment]
@dhincerti o seu problema não parece ser o mesmo que o reportado pelo @marxms 

Você está sempre incluindo nos seus testes a variável "sync_verifier_start", que é o primeiro CID, por isso o seu segundo teste dá erro, você está considerando 2 vezes o mesmo CID.

Para investigar se o vsync está com problema, preciso do ISPB do participante, poderia informar?

**Comment by dhincerti** [comment]
60701190

**Comment by luizlaydner** [comment]
Prezado @dhincerti , identificamos com base no relato que você deu um inconsistência entre a definição do campo `SyncVerifierStart` que está na especificação da API e o que o DICT está retornando.

Na definição da especificação está constando que :

> SyncVerifierStart : Verificador de sincronismo +**antes**+ do primeiro evento

No entanto, a implementação não está assim. Falha nossa.
DICT está retornando no campo `SyncVerifierStart` o verificador de sincronismo +**após**+ o primeiro evento. 
Isso explica o fato apontado por vocês

> valor final do vsync só é obtido, quando o primeiro CID é ignorado no cálculo

Nessa altura, nos parece mais sensato corrigir a especificação da API no lugar de alterar o comportamento da implementação. Podem existir implementações já baseadas nesse comportamento. 
Bug virou feature ;) .

Portanto, a especificação da API do DICT será atualizada para que conste assim:

`SyncVerifierStart` : Verificador de sincronismo +**após**+ o primeiro evento

**Comment by dhincerti** [comment]
@luizlaydner , não tenho certeza se entendi.
No caso da reconciliação por arquivo, como saberíamos qual o primeiro evento?

**Comment by luizlaydner** [comment]
@dhincerti Fazendo uma analogia com o git, o endpoint [listCidSetEvents](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API_do_DICT-v1.0.html#operation/listCidSetEvents) é o log de commits e o [arquivo de cids](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API_do_DICT-v1.0.html#operation/createCidSetFile) é a "working tree" do repositório.

O arquivo de cids gerado não tem ordem garantida. Ele é todo o conjunto de CIDs cadastrados no DICT pro participante para um tipo de chave.
Os eventos de cids mostram as alterações ao longo do tempo (adição e remoção de cids).

**Comment by dhincerti** [comment]
@luizlaydner, peço desculpas, pois talvez tenhamos misturados dois assuntos em um só.

Vou retomar o primeiro...

Com toda a aplicação congelada, para garantir que não teríamos nem uma alteração na massa de dados durante os testes, nós fizemos o download de um arquivo de cids e sincronizamos a base com ele.
Geramos um vsync com todos os cids do arquivo e geramos um vsync com os dados atualizados da base.
Os dois eram iguais, o que deve indicar que a base foi sincronizada corretamente.

Ao final deste teste, fizermos uma chamada na [API Verificar Sincronismo](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API_do_DICT-v1.0.html#operation/createSyncVerification), utilizando o mesmo vsync dito acima, e recebemos um NOK.

Outro fato é que, a API de verificação de sincronismo, retorna exatamente o valor do `sync_verification_end` da API de eventos, logo, pensei que para gerar o mesmo vsync através dos cids do arquivo, iria precisar "ignorar" o "primeiro evento". Mas não teria como saber qual dos cids retornados no arquivo seria o primeiro, visto que não são ordenados.

Como disse, não tenho certeza se as coisas estão relacionadas ou não, mas ainda estamos com o problema para gerar o mesmo vsync gerado pela API de verificação, quando se trato do fluxo de sincronização por arquivo.

Poderiam ajudar nessa também, por favor?

Obrigado!

**Comment by luizlaydner** [comment]
Estamos investigando a 1a parte do relato.

**Comment by HenriqueSimoes82** [comment]
@dhincerti e @marxms corrigimos o vsync. Poderiam verificar e me avisar se está tudo OK agora?

**Comment by zup-christoph** [comment]
O problema do primeiro evento não estar incluído no calculo do Vsync foi resolvido:
![image](https://user-images.githubusercontent.com/62247361/94933711-2744d400-04a1-11eb-86b0-c96798933aa4.png)
Agora vamos testar o calculo do Vsync utilizando todos os CIDs encontrados no arquivo de CIDS baixado.

Assim que concluído, postamos o resultado.

**Comment by mmchristoph** [comment]
O problema do primeiro evento não estar incluído no calculo do Vsync foi resolvido:
![image](https://user-images.githubusercontent.com/62247361/94933711-2744d400-04a1-11eb-86b0-c96798933aa4.png)
Agora vamos testar o calculo do Vsync utilizando todos os CIDs encontrados no arquivo de CIDS baixado.
Feito o teste, postaremos o resultado.

**Comment by mmchristoph** [comment]
Fizemos o teste do sincronismo do tipo CNPJ e tudo funcionou corretamente, ou seja, o Vsync calculado do nosso lado e do lado do Bacen bateram e, com isso, a resposta da API Verificar Sincronismo foi OK.

Obrigado a todos os envolvidos! @luizlaydner @HenriqueSimoes82

**Comment by luizlaydner** [comment]
Versão 1.0.1 da spec da API foi liberada, ver aqui : https://github.com/bacen/pix-dict-api/releases/tag/v1.0.1 
Foi feita correção da definição do campo `SyncVerifierStart` na operação de listCidSetEvents .
