### ISSUE TITLE
Problema no DICT - Erro ao atualizar vinculo

### ISSUE THREAD

**Issue by fCamargosRibeiro** [bacen/pix-perguntas-e-respostas#327]
**Descreva sua dúvida ou problema**
Ao tentar atualizar um vinculo, obtive o erro:
"The 5 entries limit has been exceeded for the set: participant, branch and account number.There are currently 5 entries and 0 claimed.". Mas como só estava atualizando os dados de uma das chaves não deveria dar esse erro, afinal não vou estrapolar o limite de chaves.

**Sistema ou Área**
DICT

**Identificador do Problema**
1B9074F79A9441B0B1C0EFB3DC1E6393. ISPB: 01181521 "timestamp": "2020-09-25T23:04:33.678+00:00"

**Mensagens Enviadas / Recebidas**
```
<UpdateEntryRequest>
	<Key>41753828015</Key>
	<Reason>BRANCH_TRANSFER</Reason>
	<Account>
		<Participant>01181521</Participant>
		<Branch>0136</Branch>
		<AccountNumber>057357</AccountNumber>
		<AccountType>CACC</AccountType>
		<OpeningDate>1993-07-15T00:00:00.000Z</OpeningDate>
	</Account>
</UpdateEntryRequest>

<problem xmlns="urn:ietf:rfc:7807">
	<type>https://dict.pi.rsfn.net.br/api/v1/error/EntryLimitExceeded</type>
	<title>Bad Request</title>
	<status>400</status>
	<detail>The 5 entries limit has been exceeded for the set: participant, branch and account number.There are currently 5 entries and 0 claimed.</detail>
	<correlationId>1B9074F79A9441B0B1C0EFB3DC1E6393</correlationId>
</problem>

```
**URL de conexão**
https://host/api/v1/entries/{Key}

**Comment by HenriqueSimoes82** [comment]
@fCamargosRibeiro problema corrigido.
