### ISSUE TITLE
Problema no DICT- Padrão cadastro tipo chave PHONE

### ISSUE THREAD

**Issue by fCamargosRibeiro** [bacen/pix-perguntas-e-respostas#328]
**Descreva sua dúvida ou problema**
Hoje cadastramos uma chave do tipo telefone, seguindo o padrão de + DDI DD NUMERO, o cadastro foi com sucesso, pedimos para outra IF fazer uma reivindicação para essa mesma chave, porém a outra IF mandou o numero + DD NUMERO, sem o DDI, aí cadastrou com sucesso e não entrou no fluxo de reivindicação. Gostaria de perguntar o que vai ser feito nesses casos, porque nesse cenário o usuário ficou com 2 contas para a mesma chave, existe algum bloqueio para isso na geração de qr-code que aí a chave cadastrada errada nunca iria chegar um pagamento para ela. 

**Sistema ou Área**
DICT

**Identificador do Problema**
 ISPB: 01181521 - Entre 11 e 12 horas de 25-09

**Mensagens Enviadas / Recebidas**
```
<CreateEntryRequest>
	<Entry>
		<Key>+5551989858283</Key>
		<KeyType>PHONE</KeyType>
		<Account>
			<Participant>01181521</Participant>
			<Branch>0101</Branch>
			<AccountNumber>719811</AccountNumber>
			<AccountType>CACC</AccountType>
			<OpeningDate>2003-08-11T00:00:00.000Z</OpeningDate>
		</Account>
		<Owner>
			<Type>NATURAL_PERSON</Type>
			<TaxIdNumber>18515207087</TaxIdNumber>
			<Name>Werno Molling</Name>
		</Owner>
	</Entry>
	<Reason>USER_REQUESTED</Reason>
	<RequestId>b71a2fc9-2869-422e-80ad-ce55038f4995</RequestId>
</CreateEntryRequest>

<CreateEntryResponse>
	<Entry>
		<Key>+5551989858283</Key>
		<KeyType>PHONE</KeyType>
		<Account>
			<Participant>01181521</Participant>
			<Branch>0101</Branch>
			<AccountNumber>719811</AccountNumber>
			<AccountType>CACC</AccountType>
			<OpeningDate>2003-08-11T00:00:00Z</OpeningDate>
		</Account>
		<Owner>
			<Type>NATURAL_PERSON</Type>
			<TaxIdNumber>18515207087</TaxIdNumber>
			<Name>Werno Molling</Name>
		</Owner>
		<CreationDate>2020-09-25T13:25:33.189Z</CreationDate>
		<KeyOwnershipDate>2020-09-25T13:25:33.186Z</KeyOwnershipDate>
	</Entry>
</CreateEntryResponse>
```

**URL de conexão**
https://host/api/v1/entries/

**Comment by judahreis** [comment]
@fCamargosRibeiro, obrigado pelo report. 

Baseado em seu relato, vamos forçar o padrão +55DDNNNNNNNNN, pelo menos na abertura do DICT. Isso garantirá que erros como o que vc relatou não aconteçam em produção.

Quanto atualizarmos, fechamos o issue.

**Comment by monise** [comment]
@judahreis nós estamos seguindo a expressão regular que existe no cadastro de chaves.
![image](https://user-images.githubusercontent.com/5355541/94494817-7e5b5800-01c6-11eb-9450-7b6f05961c21.png)

Você acha que podemos continuar usando essa expressão para fazer o cadastro ou o correto é validar usando +55DDNNNNNNNNN?

**Comment by fCamargosRibeiro** [comment]
> @judahreis nós estamos seguindo a expressão regular que existe no cadastro de chaves.
> ![image](https://user-images.githubusercontent.com/5355541/94494817-7e5b5800-01c6-11eb-9450-7b6f05961c21.png)
> 
> Você acha que podemos continuar usando essa expressão para fazer o cadastro ou o correto é validar usando +55DDNNNNNNNNN?

@monise eles podem falar melhor, mas a expressão valida até certo ponto, o problema que ela aceita telefones sem o DDI, então acaba pode acontecer o cenário que falei se for só por ela.

**Comment by judahreis** [comment]
@fCamargosRibeiro, @monise, infelizmente, vamos ter que voltar atrás. Alguns participantes já estão realizando validação de números internacionais. Portanto, não podemos limitar ao padrão +55\d{11}. Vamos voltar à expressão original. O Banco Central irá monitorar e supervisionar os PSPs que estiverem fazendo cadastros errados em produção.

**Comment by CharlesMendes** [comment]
@judahreis a regex do dict não permite cadastrar lor exemplo celulares dos EUA ou Portugal, devemos usar essa regex ou sera atualizada?

^\+[1-9][0-9]\d{1,14}$

Exemplo de número de Portugal:
+351 911 572 776

Como devemos tratar?
