### ISSUE TITLE
[Dúvida] no [DICT] - PI-PayerId de "usuário final"

### ISSUE THREAD

**Issue by gstabel** [bacen/pix-perguntas-e-respostas#33]
Boa tarde. Com relação a "Consultar Vínculo" e "rate-limiting" a documentação (versão 1.0.0-RC3) diz o seguinte:

> O parâmetro PI-PayerId é o identificador pseudonimizado do **usuário final**, vinculado a um participante. Requisições vindas de um mesmo usuário, para um mesmo participante, devem usar o mesmo identificador. Como sugestão de implementação, pode ser utilizado o valor hexadecimal da aplicação de HMAC-SHA-256 a um **identificador do usuário**, com chave de **conhecimento restrito** ao participante.

Gostaria de confirmar o nosso entendimento.
1. Nesse contexto o "usuário final" seria, por exemplo, o cliente/usuário usando o aplicativo da instituição, correto?

2. E o "identificador do usuário" único de "conhecimento restrito" seria, por exemplo, um código interno da instituição associado ao login do usuário que estaria utilizando a aplicativo para realizar a consulta?

3. No caso de uma conta de empresa (CNPJ) ou conjunta, onde dois usuários acessam o aplicativo com dois logins diferentes para a mesma conta. Devemos informar UM identificador em todas as consultas (pois existe apenas UMA conta)? Ou dois identificadores, um para cada usuário (com logins e CPFs distintos) que acessam a conta?

4. No nosso caso temos mais de um aplicativo/canal de acesso dentro da instituição. O identificador único deve ser o mesmo "cross" canais? Ou nesse contexto cada usuário, em aplicativo diferente, pode ser considerado um usuário diferente?

Grato.
Gabriel C. Stabel

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
_Usuário final_ é o cliente do prestador de serviço de pagamento, usuário do aplicativo da instituição.

O importante é que o PI-PayerID seja 1) Fixo para um mesmo cliente do PSP e 2) Não seja possível, sem informações adicionais, deduzir a identidade do usuário que está fazendo a consulta (é um id pseudonimizado)

Na sugestão de implementação com HMAC-SHA-256, o "identificador do usuário" poderia ser um id interno do cliente. A "chave  de conhecimento restrito" se refere ao segredo usado no HMAC-SHA-256. Veja aqui o exemplo no [quickstart](https://github.com/bacen/pix-dict-quickstart/blob/c012f39242e91818ae683c1079944a142a7e2094/src/main/java/br/gov/bcb/pi/dict/App.java#L60).

**Comment by gstabel** [comment]
Obrigado @luizlaydner! Você respondeu tão rápido que eu editei minutos depois, melhorando as minhas perguntas e duvidas. :)
Desde já agradeço!

**Comment by luizlaydner** [comment]
Complementando...

> No caso de uma conta de empresa (CNPJ) ou conjunta, onde dois usuários acessam o aplicativo com dois logins diferentes para a mesma conta. Devemos informar UM identificador em todas as consultas (pois existe apenas UMA conta)? Ou dois identificadores, um para cada usuário (com logins e CPFs distintos) que acessam a conta?

> No nosso caso temos mais de um aplicativo/canal de acesso dentro da instituição. O identificador único deve ser o mesmo "cross" canais? Ou nesse contexto cada usuário, em aplicativo diferente, pode ser considerado um usuário diferente?

No cenário de vários titulares para uma única conta, cada um teria o seu PI-PayerId, independente do canal de acesso.

A intenção desse _rate-limiting_ é evitar que usuários finais abusem o serviço e façam consultas sem relação nenhuma a pagamentos.
