### ISSUE TITLE
[Problema] no PIX - ENVIO EM MULTIPART

### ISSUE THREAD

**Issue by phsmonte** [bacen/pix-perguntas-e-respostas#331]
Bom dia,

Estamos testando o envio/retorno em multipart por conta dos testes de carga.

O pacote montado é um MultipartContent mixed com boundary = "simple boundary", tal qual a documentação.

Pseuco-código utilizado para montar o pack:

msgs =  executa Obtem10Mensagens()
pack = novo MultipartContent 
pack.Tipo = multipart/mixed
pack.Boundary = "simple boundary"

para cada mensagem em msgs
    buffer = executa ObtemMensagemZipadaComContentTypeApplicationXmECharsetUtf8(mensagem)
    pack.Add(buffer)
fim para

Ou seja: é um pack Multipart onde cada um dos ítens está zipado e contém os headers solicitados.

Ao enviar os dados recebi 

`**<?xml version="1.0" encoding="UTF-8"?><problem xmlns="urn:ietf:rfc:7807"><type>https://icom.pi.rsfn.net.br/api/v1/error/invalidHeader</type><title>Um dos cabeçalhos enviados não era esperado</title></problem>**`

Verificando a documentação eu vi que havia uma instrução dizendo que o envio de "Transfer-Encoding - gzip,chunked" não era recomendado e que poderia ser descontinuado no futuro.

Então eu efetuei a alteração para mandar Transfer-Encoding - chunked e Content-Encoding=gzip e o pacote multipart foi enviado com sucesso. No entanto recebi como retorno 10 ADMI.002 com o seguinte erro:

`**<admi.002.001.01><RltdRef><Ref>Caractere inválido detectado: &#31;</Ref></RltdRef><Rsn><RjctgPtyRsn>Erro no processamento da ICOM</RjctgPtyRsn><RjctnDtTm>2020-09-28T07:31:03.700Z</RjctnDtTm><RsnDesc>Não foi possível interpretar o XML</RsnDesc></Rsn></admi.002.001.01>**`

Nossas mensagens são enviadas sem espaços em branco entre tags, formatação ou quebra de linhas. Quando fiz a alteração segundo o manual para não enviar mais Transfer-encoding=gzip,chunked acabei alterando também a configuração para envio de mensagem em separado (ou seja, uma a uma) para enviar da mesma maneira (Transfer-Encoding - chunked e Content-Encoding=gzip).

Enviei uma mensagem em separado e recebi a mesma ADMI.002.

Alterei o envio de mensagem em separado para enviar novamente como "Transfer-encoding=gzip,chunked", enviei outra mensagem e recebi PACS.002.

Ou seja:

a) A rotina do lado do BACEN está esperando receber multipart com headers diferentes da mensagem em separado e
b) Quando recebe multipart não consegue interpretar o conteúdo por conta de algum bug do lado de vocês relacionado ao header supracitado.

Poderiam responder isso com URGÊNCIA? O que está errado nesse envio?

**Comment by gstabel** [comment]
Bom dia.
Verifique seus cabeçalhos HTTP. Pelo mensagem de erro o problema não está no _multipart_.
O erro indica que está sendo enviado um cabeçalho fora dos permitidos definido na documentação do ICOM:

https://www.bcb.gov.br/content/estabilidadefinanceira/cedsfn/Manual%20das%20Interfaces%20de%20Comunica%C3%A7%C3%A3o-1.5.pdf

Att.
Gabriel

**Comment by cristianokbc** [comment]
@phsmonte, você não deve compactar mensagem a mensagem, mas o bloco todo, tal como o exemplo "Envio de múltiplas mensagens com multipart" da seção 2.2.1.4.

O texto "simple boundary" é um exemplo. Você pode usar qualquer texto aqui, desde que seja usado para dividir as partes. O ideal é usar textos mais complexos.

Se você enviar cada parte compactada, o sistema tentará interpretar o binário compactado como XML, o que causará o erro que você citou.

Cada parte deve conter como cabeçalho apenas o "Content-Type".

Exemplo:

```
POST /api/v1/in/11111111/msgs HTTP/1.1
Host: icom.pi.rsfn.net.br
Content-Type: multipart/mixed; boundary="890exqwsjcf938reuc4rx9fxoiedjkds2ijd"
Transfer-Encoding: chunked
Content-Encoding: gzip

// tudo abaixo compactado em apenas um bloco (obviamente essa linha não deve ser enviada)
--890exqwsjcf938reuc4rx9fxoiedjkds2ijd
Content-type: application/xml; charset=utf-8

<xml>Mensagem 1</xml>
--890exqwsjcf938reuc4rx9fxoiedjkds2ijd
Content-type: application/xml; charset=utf-8

<xml>Mensagem 2</xml>
--890exqwsjcf938reuc4rx9fxoiedjkds2ijd--
// o bloco compactado vai até aqui (linha não deve ser enviada)
```
