### ISSUE TITLE
[Dúvida] no [Api de Recebimento] - A api do Pix substitui a api de Recebimento?

### ISSUE THREAD

**Issue by mvleandro** [bacen/pix-perguntas-e-respostas#333]
**Descreva sua dúvida ou problema**
Gostaria de entender se a Api do Pix entrou para substituir a Api de recebimento.

Caso afirmativo, qual o prazo será dado para realizar esta substituição?

**Comment by ninrod** [comment]
> Gostaria de entender se a Api do Pix entrou para substituir a Api de recebimento.

Foi uma mudança de nome, tanto que a API Pix está na versão `2.0.0`.
