### ISSUE TITLE
Dúvidas sobre o encerramento da Portabilidade

### ISSUE THREAD

**Issue by tatiama2020** [bacen/pix-perguntas-e-respostas#334]
Tendo em vista que o documento aponta esse processo:

De forma resumida, o processo de reivindicação de posse ocorre da seguinte forma:
1. A pedido do cliente, PSP reivindicador cria um pedido de reivindicação de posse. DICT altera estado da reivindicação para “Aberta”.
2. PSP doador recebe a reivindicação. DICT altera o estado da reivindicação para “Aguardando resolução”.
3. Durante período de resolução e período de encerramento3, PSP doador tenta contato com cliente que terá a chave desvinculada, a fim de verificar a possibilidade de que esteja ocorrendo uma reivindicação de posse ilegítima.
4. PSP doador, ao final do prazo de resolução, não havendo indícios de fraude, deverá confirmar a reivindicação. Chave deixa de estar vinculada à conta no PSP doador. DICT altera estado da reivindicação para “Confirmada”.
5. PSP reivindicador encerra reivindicação, ao final do prazo de encerramento. Chave passa a estar vinculada à conta no PSP reivindicador. DICT altera estado da reivindicação para “Encerrada”.

Nós não recebemos o status encerrado do BACEN, somente OPEN, WAITING_RESOLUTION, CONFIRMED, CANCELLED e CONPLETED
Com isso nossos testes tem sido reprovados e não acatado o encerramento da Portabilidade.

**Comment by luizlaydner** [comment]
A documentação não tem sido 100% consistente, mas onde tiver status "Encerrado"  ou "Concluído" para reivindicação/portabilidade entenda como sendo equivalente ao "COMPLETED" que consta na especificação da API.

[Veja essa seção da especificação](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API_do_DICT-v1.0.html#tag/Claim).
