### ISSUE TITLE
[Dúvida] no [DICT] - Como sabemos se estamos aptos a realizar os testes de conectividade em Produção

### ISSUE THREAD

**Issue by fbjhon** [bacen/pix-perguntas-e-respostas#335]
**Descreva sua dúvida ou problema**

Segundo nossas evidências atendemos a todos os requisitos dos testes homologatórios, tentamos hoje realizar o teste de conectividade sincronizando a base vazia e recebemos o retorno "Inactive or unregistered participant. Ispb: 92702067". 

Nossa dúvida:  Existe alguma pendencia dos testes homologatórios para não termos o registro em produção?

**Sistema ou Área**
DICT

**Identificador do Problema**

<correlationId>09BA016898544151B9A3899D93C56227</correlationId>

**Mensagens Enviadas / Recebidas**
<problem>  
  <type>https://dict.pi.rsfn.net.br/api/v1/error/Forbidden</type>
  <title>Forbidden</title>
  <status>403</status>
  <detail>Inactive or unregistered participant. Ispb: 92702067</detail>
  <correlationId>09BA016898544151B9A3899D93C56227</correlationId>
</problem>
**URL de conexão**
URL para onde a mensagem foi enviada

**Dados adicionais**
Qualquer informação adicional que ajude a identificar o problema ou dúvida.

**Comment by luizlaydner** [comment]
Para comunicar problemas ou dúvidas relativas ao ambiente de produção, os participantes devem utilizar exclusivamente os canais de email (suporte.ti@bcb.gov.br) ou telefone (61 3414-5100) do Banco Central do Brasil. O canal do GitHub (github.com/bacen/pix-perguntas-e-respostas) não poderá ser utilizado para tal fim, e issues referentes a produção serão encerradas automaticamente.
