### ISSUE TITLE
[Dúvida] no [DICT] - Transação de consulta chave dict já está disponível em produção??

### ISSUE THREAD

**Issue by gabrielmendesbb** [bacen/pix-perguntas-e-respostas#336]
Estamos testando a conectividade com BACEN em produção usando a transação de consultar entry, passando o cnpj do BACEN como chave (como foi nos orientado em outra issue).
Mas estamos recebendo erro 499.
Essa transação já está disponível em produção ?
Senão, como consigo testar a conectividade com o DICT BACEN?

Resquisição:  /api/v1/entries/00038166000105
Resposta:  [29/Sep/2020:17:01:46 +0000] "GET /api/v1/entries/00038166000105 HTTP/1.1" 499 0 "-" "kube-probe/1.18" "-

**Comment by luizlaydner** [comment]
Para comunicar problemas ou dúvidas relativas ao ambiente de produção, os participantes devem utilizar exclusivamente os canais de email (suporte.ti@bcb.gov.br) ou telefone (61 3414-5100) do Banco Central do Brasil. O canal do GitHub (github.com/bacen/pix-perguntas-e-respostas) não poderá ser utilizado para tal fim, e issues referentes a produção serão encerradas automaticamente.
