### ISSUE TITLE
[Dúvida] no [DICT] - Testes en produção

### ISSUE THREAD

**Issue by mlardone** [bacen/pix-perguntas-e-respostas#337]
Duvida:
O que vai a acontecer depois do 5 de outubro com as chaves cadastradas agora como testes de conectividade em produção? van a ficar no banco de dados de bacen ou van a elimina-las?

Sistema: DICT

**Comment by luizlaydner** [comment]
Para comunicar problemas ou dúvidas relativas ao ambiente de produção, os participantes devem utilizar exclusivamente os canais de email (suporte.ti@bcb.gov.br) ou telefone (61 3414-5100) do Banco Central do Brasil. O canal do GitHub (github.com/bacen/pix-perguntas-e-respostas) não poderá ser utilizado para tal fim, e issues referentes a produção serão encerradas automaticamente.
