### ISSUE TITLE
Problema no DICT - Solicitação de reivindicação de posse

### ISSUE THREAD

**Issue by ekiametis** [bacen/pix-perguntas-e-respostas#34]
**Descreva sua dúvida ou problema**

Tentamos solicitar uma reivindicação de posse e ao solicitar ocorre erro, onde tem-se o seguinte detalhamento: `Claim type inconsistent.`

Gostaria de saber se estou mandando algum dado errado na requisição, ou se realmente é um problema, pois não estamos conseguindo solicitar reivindicação de posse?

**Sistema ou Área**
DICT

**Identificador do Problema**
Correlation-Id: 44FAD5B7CB05470BBAF7AEE62729FACC.
ISPB: 02038232

**Mensagens Enviadas / Recebidas**
1. XML de Requisição

```
<?xml version="1.0" encoding="UTF-8"?>
<CreateClaimRequest>
   <Claim>
      <Type>OWNERSHIP</Type>
      <Key>+5561998880001</Key>
      <KeyType>PHONE</KeyType>
      <ClaimerAccount>
         <Participant>02038232</Participant>
         <Branch>7988</Branch>
         <AccountNumber>453463</AccountNumber>
         <AccountType>CACC</AccountType>
      </ClaimerAccount>
      <Claimer>
         <Type>NATURAL_PERSON</Type>
         <TaxIdNumber>35484829100</TaxIdNumber>
         <Name>GUSTAVO SOARES BATISTA do Sicoob</Name>
      </Claimer>
   </Claim>
</CreateClaimRequest>
```

2. XML de Resposta

```
<?xml version="1.0" encoding="UTF-8"?>
<problem xmlns="urn:ietf:rfc:7807">
   <type>https://dict.pi.rsfn.net.br/api/v1/error/ClaimTypeInconsistent</type>
   <title>Bad Request</title>
   <status>400</status>
   <detail>Claim type inconsistent</detail>
   <correlationId>44FAD5B7CB05470BBAF7AEE62729FACC</correlationId>
</problem>
```

**URL de conexão**
POST - https://dict-h.pi.rsfn.net.br/api/v1/claims

**Dados adicionais**
Instituição: Sicoob

**Comment by Leonardo34** [comment]
@ekiametis Quais são os dados da chave `+5561998880001` ? 

Já tive esse problema quando estávamos por engano fazendo uma reivindicação de posse com os mesmos dados de owner da chave já cadastrada.

**Comment by ekiametis** [comment]
@Leonardo34 , que bacana, primeiramente muito obrigado pelo seu comentário :)

Mas olha só ... os dados dessa chave são estes:

```
<?xml version="1.0" encoding="UTF-8"?>
<GetEntryResponse>
   <Entry>
      <Key>+5561998880001</Key>
      <KeyType>PHONE</KeyType>
      <Account>
         <Participant>00000000</Participant>
         <Branch>7988</Branch>
         <AccountNumber>453463</AccountNumber>
         <AccountType>CACC</AccountType>
      </Account>
      <Owner>
         <Type>NATURAL_PERSON</Type>
         <TaxIdNumber>35484829100</TaxIdNumber>
         <Name>GUSTAVO SOARES BATISTA</Name>
      </Owner>
      <CreationDate>2020-07-01</CreationDate>
      <KeyOwnershipDate>2020-07-01</KeyOwnershipDate>
   </Entry>
</GetEntryResponse>
```

É um chave do participante com ISPB 00000000. O ISPB que estamos tentando realizar a solicitação é o 02038232.
Será que tem algo parecido com o problema que vocês passaram?

**Comment by luizlaydner** [comment]
Duplicado #8 .
Obrigado @Leonardo34 .
Da nossa parte, vamos melhorar a mensagem retornada para ficar mais claro o problema.

**Comment by ekiametis** [comment]
@Leonardo34 olhando a issue #8 realmente entendi agora o que você havia dito. Muito obrigado por sua ajuda!
@luizlaydner Muito obrigado pela rápida resposta, com a issue #8 pude entender realmente o problema.

Obrigado a todos!

**Comment by Leonardo34** [comment]
@ekiametis Exatamente o mesmo ponto, é um cenário de negócio que não está sendo atendido. Quando você faz uma reivindicação de posse para uma chave (OWNERSHIP), é esperado que esta chave esteja sendo "trocada de pessoa". 

No seu cenário, a chave é do owner:

     ```
      <Owner>
         <Type>NATURAL_PERSON</Type>
         <TaxIdNumber>35484829100</TaxIdNumber>
         <Name>GUSTAVO SOARES BATISTA</Name>
      </Owner>
```

E você está cadastrando uma claim, do tipo OWNERSHIP, para o mesmo portador da conta. Ou seja, um mesmo usuário fazendo uma reivindicação de posse para uma chave que já é dele. 

Na issue #8 eu fiz a sugestão de alterar a mensagem de erro, deixando explicito esse erro.

**Comment by ekiametis** [comment]
@Leonardo34 , excelente!

Com as dicas que deram aqui, consegui testar a solicitação de reivindicação de posse. Obrigado!!
