### ISSUE TITLE
DICT - XSD

### ISSUE THREAD

**Issue by eduardomohr** [bacen/pix-perguntas-e-respostas#341]
Boa tarde

Assim como no ICOM o Bacen tem planos de disponibilizar o XSD do DICT v1.0 ? 

Caso sim, qual seria a data prevista?

Obrigado
Eduardo

**Comment by luizlaydner** [comment]
Não haverá XSD para o DICT. API está especificada no formato openapi 3.0.
Ver o projeto https://github.com/bacen/pix-dict-api
