### ISSUE TITLE
[Dúvida] no [DICT] - Como inferir a razão do cancelamento?

### ISSUE THREAD

**Issue by Vitormdias** [bacen/pix-perguntas-e-respostas#342]
**Descreva sua dúvida ou problema**
Ficamos em dúvida em como escolher a reason para alguns casos do cancelamento, especificamente as reasons **USER_REQUESTED** e **FRAUD**, o cliente deve informar qual o motivo pra gente? ou temos informações suficientes para inferir a razão correta?

Os casos que devemos usar **DEFAULT_OPERATION** e **ACCOUNT_CLOSURE** já estão claros.

Ownership Reivindicador
Portability Doador
Portability Reivindicador

![image](https://user-images.githubusercontent.com/18128585/94613756-77dae800-027b-11eb-8394-e76d1f334ad9.png)

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
`USER_REQUESTED` é para ser usado quando o cliente final, por desejo próprio, solicita o cancelamento.
`FRAUD` é para quando o participante avalia que existem indícios de que a solicitação de reivindicação/portabilidade foi feita de forma fraudulenta (ex: clonagem de celular, roubo de credenciais)
