### ISSUE TITLE
[Problema] no [DICT] - Campo DATA está sendo retornado em UTC

### ISSUE THREAD

**Issue by rsabin** [bacen/pix-perguntas-e-respostas#35]
**Descreva sua dúvida ou problema** 
Fiz a inserção de um vínculo no DICT próximo das 22h de um dia.
O DICT retornou a data de inserção já com o dia seguinte.
Aparentemente o campo que contám apenas DATA foi convertido pra fuso horário utc.

**Sistema ou Área**
DICT

**Identificador do Problema**
UUID: 9b52bdbb-a3e9-4c48-99f4-5962ee50af82
ISPB: 92702067
DtHr: 01/07/20 22:13:52

**Mensagens Enviadas / Recebidas**
Este foi o retorno do DICT BACEN:
```
<CreationDate>2020-07-02</CreationDate>
<KeyOwnershipDate>2020-07-02</KeyOwnershipDate>
```

**Dados adicionais**
Quando os campos que transitam são data+hora, entendo que seja representado em formato utc, ou seja, sufixo "-00:00" ou simplesmente "Z".
Porém quando o campo é apenas data não tem a representação utc, de modo que não há como saber qual fuso horário para conversão/desconversão.

**Comment by luizlaydner** [comment]
Vamos fazer uma alteração na API (deve entrar na v1.0.0-RC5) para que esses campos _date_ passem a ser _date-time_ com informação de tz. 
Daí evita que tenhamos que padronizar na API o fuso de campos _date_.
Obrigado pela descrição detalhada!

**Comment by luizlaydner** [comment]
@rsabin Campos `CreationDate` e `KeyOwnershipDate` agora [são date-time](https://github.com/bacen/pix-dict-api/blob/b7710e5856014e5a4ac93eff110b7102cae6c411/openapi/schemas.yaml#L139) na v1.0.0-RC5 . Deverá estar disponível no ambiente de homologação hoje ao final do dia.
