### ISSUE TITLE
[Problema] no [DICT] de homolog

### ISSUE THREAD

**Issue by thespamer** [bacen/pix-perguntas-e-respostas#350]
Host de homologação falhando em alguns momentos no teste de carga.

Estamos batendo no host dict-h.pi.rsfn.net.br:16522 para homologar e estamos recebendo erros de handshake TLS, situação intermitente, funciona em alguns horários do dia. 

Há alguma janela de manutenção do dict em homologação ou algum grupo onde são informadas as manutenções?

*DICT INFRA

**Comment by gizelysc** [comment]
Olá bom dia. 
Estamos também recebendo erro d e forma intermitente para os teste gerais.

**Comment by jonasgiehl** [comment]
O mesmo por aqui. Ocorre também na ICOM

**Comment by thiagotemal** [comment]
Estamos recebendo erros com frequência nas operações de chaves .Poderiam confirmar se existe algum problema?

**Comment by erickrmattos** [comment]
Também notamos agora que estamos com maior frequencia de erros.
O endpoint de Concluir Reivindicação `/claims/{ClaimId}/complete` parece estar fora completamente, estamos recebendo apenas respostas como:
```
{:problem {:type "https://dict.pi.rsfn.net.br/api/v1/error/InternalServerError", :status "500", :detail "Internal server error. Please contact support for details.", :correlationId "5FDFF942C6BE4F759309EF4EDF51CA84"}}
```
Os outros endpoints estão com problema também, mas acabam funcionando, esse de Concluir Reivindicação só responde com esse erro.

**Comment by erickrmattos** [comment]
☝️ Conseguimos agora completar, mas ainda estamos recebendo muitos 500s da API.

**Comment by AlexandreRioli** [comment]
> Host de homologação falhando em alguns momentos no teste de carga.
> 
> Estamos batendo no host dict-h.pi.rsfn.net.br:16522 para homologar e estamos recebendo erros de handshake TLS, situação intermitente, funciona em alguns horários do dia.
> 
> Há alguma janela de manutenção do dict em homologação ou algum grupo onde são informadas as manutenções?
> 
> *DICT INFRA

Boa tarde!
Também estamos recebendo erro de forma intermitente para testes gerais.
