### ISSUE TITLE
DICT

### ISSUE THREAD

**Issue by rafaelpkcortes** [bacen/pix-perguntas-e-respostas#351]
**Descreva sua dúvida ou problema**
Problema de comunicação com o DICT
Estamos realizando um GET no DICT em produção: realizando um GET no endpoint https://dict.pi.rsfn.net.br:16422/api/v1/claims e estamos recebendo status 500
Estamos recebendo the operation was canceled
**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
Para problemas ou dúvidas relativas ao ambiente de produção, os participantes devem utilizar exclusivamente os canais de email (suporte.ti@bcb.gov.br) ou telefone (61 3414-5100) do Banco Central do Brasil. O canal do github não poderá ser utilizado para tal fim.
