### ISSUE TITLE
[Dúvida|Problema] no [SISTEMA] - Título

### ISSUE THREAD

**Issue by CarlosAguilart** [bacen/pix-perguntas-e-respostas#352]
Descreva sua dúvida ou problema
Ao tentar criar um relato de infração seguindo o padrão de documentação do BACEN a assinatura seria um campo vazio, porém ao enviar a querry para o BACEN ele retorna a seguinte mensagem "XML signature does not match digests or certificate"

Ao tentar enviar sem assinatura no código retorna o mesmo erro.

Sistema ou Área
DICT - Criar relato de infração

Identificador do Problema
Signature

**Comment by luizlaydner** [comment]
Prezado @CarlosAguilart , em homologação, para desabilitar a validação da assinatura, tente remover a tag `<Signature></Signature>` do corpo da mensagem .

Se você já tentou isso, não consigo te ajudar apenas com as informações que você passou.
Favor informar o correlationId que vem na resposta de erro.

**Comment by CarlosAguilart** [comment]
A resposta não apresenta CorrelationId. Somente o erro de status 400 com o seguinte detail: XML signature does not match digests or certificate.
