### ISSUE TITLE
[Dúvida|Problema] no [SISTEMA] - Problemas com DICT e SPI

### ISSUE THREAD

**Issue by abcbrasil-28195667** [bacen/pix-perguntas-e-respostas#354]
**ATENÇÃO:** Não crie issue para questões relativas ao ambiente de produção !

**Descreva sua dúvida ou problema**
Descreva de forma clara e curta a dúvida ou problema.

Boa tarde!

Estamos com problema de conexão com o DICT e SPI, ontem por volta das 16 horas parou de funcionar.

**Sistema ou Área**
DICT, SPI

**Identificador do Problema**
Correlation-Id (no caso de erro do DICT), ou ResourceId (no caso do SPI/ICOM). Se possível, indique também o ISPB, e a data-hora em que identificou o problema.

DICT / SPI/ICOM 
ISPB: 28195667
Problema de Conectividade Erro 400, telenet também não fecha.

**Mensagens Enviadas / Recebidas**
XML das mensagens enviadas e recebidas (sem assinatura fica melhor)

**URL de conexão**

https://icom-h.pi.rsfn.net.br
https://dict-h.pi.rsfn.net.br

**Dados adicionais**
Qualquer informação adicional que ajude a identificar o problema ou dúvida.

**Comment by luizlaydner** [comment]
Por gentileza, coloque detalhes mais específicos sobre o problema para que seja possível auxiliá-lo.

**Comment by abcbrasil-28195667** [comment]
Bom dia Luiz,

Não estamos fechando conectividade com o Bacen, conforme abaixo. 
Fizemos testes de diversos locais mais sem sucesso.

[ec2-user@ip-172-22-80-94 ~]$ telnet dict-h.pi.rsfn.net.br 443
Trying 200.218.66.145...
^C
[ec2-user@ip-172-22-80-94 ~]$ telnet icom-h.pi.rsfn.net.br 443
Trying 200.218.66.141...
^C
[ec2-user@ip-172-22-80-94 ~]$

bash-5.0# nc -v icom-h.pi.rsfn.net.br:443
nc: icom-h.pi.rsfn.net.br:443 (200.218.66.141:443): Operation timed out
bash-5.0# nc -v dict-h.pi.rsfn.net.br:443
nc: dict-h.pi.rsfn.net.br:443 (200.218.66.145:443): Operation timed out



Domain | Receive Time | Serial # | Type | Threat/Content Type | Config Version | Generate Time | Source address | Destination address | NAT Source IP | NAT Destination IP | Rule | Source User | Destination User | Application | Virtual System | Source Zone | Destination Zone | Inbound Interface | Outbound Interface | Log Action | Time Logged | Session ID | Repeat Count | Source Port | Destination Port | NAT Source Port | NAT Destination Port | Flags | IP Protocol | Action | Bytes | Bytes Sent | Bytes Received | Packets | Start Time | Elapsed Time (sec) | Category | tpadding | Sequence Number | Action Flags | Source Country | Destination Country | cpadding | Packets Sent | Packets Received | Session End Reason | DG Hierarchy Level 1 | DG Hierarchy Level 2 | DG Hierarchy Level 3 | DG Hierarchy Level 4 | Virtual System Name | Device Name | Action Source
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 05/10/2020 10:01 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 10:01 | 172.22.81.124 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.2005 | ethernet1/3.15 | Log-Panorama | 05/10/2020 10:01 | 98372 | 1 | 59344 | 443 | 0 | 0 | 0x20019 | tcp | allow | 78 | 78 | 0 | 1 | 05/10/2020 10:01 | 0 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 1 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 10:01 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 10:01 | 172.22.81.124 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.2005 | ethernet1/3.15 | Log-Panorama | 05/10/2020 10:01 | 18788 | 1 | 59344 | 443 | 0 | 0 | 0x20019 | tcp | allow | 78 | 78 | 0 | 1 | 05/10/2020 10:01 | 0 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 1 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 10:01 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 10:01 | 172.22.81.124 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.2005 | ethernet1/3.15 | Log-Panorama | 05/10/2020 10:01 | 2400 | 1 | 59344 | 443 | 0 | 0 | 0x20019 | tcp | allow | 78 | 78 | 0 | 1 | 05/10/2020 10:01 | 0 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 1 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 10:01 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 10:01 | 172.22.81.124 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.2005 | ethernet1/3.15 | Log-Panorama | 05/10/2020 10:01 | 200229 | 1 | 59344 | 443 | 0 | 0 | 0x20019 | tcp | allow | 312 | 312 | 0 | 4 | 05/10/2020 10:00 | 7 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 4 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 09:57 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 09:57 | 172.22.81.124 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.2005 | ethernet1/3.15 | Log-Panorama | 05/10/2020 09:57 | 77440 | 1 | 59344 | 443 | 0 | 0 | 0x20019 | tcp | allow | 78 | 78 | 0 | 1 | 05/10/2020 09:57 | 0 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 1 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 09:57 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 09:57 | 172.22.81.124 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.2005 | ethernet1/3.15 | Log-Panorama | 05/10/2020 09:57 | 515 | 1 | 59344 | 443 | 0 | 0 | 0x20019 | tcp | allow | 78 | 78 | 0 | 1 | 05/10/2020 09:57 | 0 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 1 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 09:57 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 09:57 | 172.22.81.124 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.2005 | ethernet1/3.15 | Log-Panorama | 05/10/2020 09:57 | 129235 | 1 | 59344 | 443 | 0 | 0 | 0x20019 | tcp | allow | 78 | 78 | 0 | 1 | 05/10/2020 09:56 | 0 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 1 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 09:56 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 09:56 | 172.22.81.124 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.2005 | ethernet1/3.15 | Log-Panorama | 05/10/2020 09:56 | 56757 | 1 | 59344 | 443 | 0 | 0 | 0x20019 | tcp | allow | 312 | 312 | 0 | 4 | 05/10/2020 09:56 | 7 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 4 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 08:46 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 08:46 | 172.22.80.94 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.1055 | ethernet1/3.15 | Log-Panorama | 05/10/2020 08:46 | 55631 | 1 | 43222 | 443 | 0 | 0 | 0x20019 | tcp | allow | 78 | 78 | 0 | 1 | 05/10/2020 08:46 | 0 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 1 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 08:46 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 08:46 | 172.22.80.94 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.1055 | ethernet1/3.15 | Log-Panorama | 05/10/2020 08:46 | 231829 | 1 | 43222 | 443 | 0 | 0 | 0x20019 | tcp | allow | 312 | 312 | 0 | 4 | 05/10/2020 08:46 | 7 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 4 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 08:40 | 1801023407 | TRAFFIC | drop | 2049 | 05/10/2020 08:40 | 10.64.67.131 | 200.218.67.209 |   | DENYALL | abcbrasil\a.ricardofp | not-applicable | vsys1 | REDE_LOCAL | SPB_EXT | ethernet1/1 | Log-Panorama | 05/10/2020 08:40 | 0 | 1 | 59336 | 443 | 0 | 0 | 0x0 | tcp | deny | 62 | 62 | 0 | 1 | 05/10/2020 08:40 | 0 | any | 0 | 2,09E+10 | 0x0 | 10.0.0.0-10.255.255.255 | Brazil | 0 | 1 | 0 | policy-deny | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 08:40 | 1801023407 | TRAFFIC | drop | 2049 | 05/10/2020 08:40 | 10.64.67.131 | 200.218.67.209 |   | DENYALL | abcbrasil\a.ricardofp | not-applicable | vsys1 | REDE_LOCAL | SPB_EXT | ethernet1/1 | Log-Panorama | 05/10/2020 08:40 | 0 | 1 | 59336 | 443 | 0 | 0 | 0x0 | tcp | deny | 66 | 66 | 0 | 1 | 05/10/2020 08:40 | 0 | any | 0 | 2,09E+10 | 0x0 | 10.0.0.0-10.255.255.255 | Brazil | 0 | 1 | 0 | policy-deny | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 08:40 | 1801023407 | TRAFFIC | drop | 2049 | 05/10/2020 08:40 | 10.64.67.131 | 200.218.67.209 |   | DENYALL | abcbrasil\a.ricardofp | not-applicable | vsys1 | REDE_LOCAL | SPB_EXT | ethernet1/1 | Log-Panorama | 05/10/2020 08:40 | 0 | 1 | 59336 | 443 | 0 | 0 | 0x0 | tcp | deny | 66 | 66 | 0 | 1 | 05/10/2020 08:40 | 0 | any | 0 | 2,09E+10 | 0x0 | 10.0.0.0-10.255.255.255 | Brazil | 0 | 1 | 0 | policy-deny | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 08:37 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 08:37 | 172.22.80.94 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.2005 | ethernet1/3.15 | Log-Panorama | 05/10/2020 08:37 | 137486 | 1 | 43216 | 443 | 0 | 0 | 0x20019 | tcp | allow | 78 | 78 | 0 | 1 | 05/10/2020 08:37 | 0 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 1 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 08:37 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 08:37 | 172.22.80.94 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.2005 | ethernet1/3.15 | Log-Panorama | 05/10/2020 08:37 | 237052 | 1 | 43216 | 443 | 0 | 0 | 0x20019 | tcp | allow | 78 | 78 | 0 | 1 | 05/10/2020 08:37 | 0 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 1 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 08:36 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 08:36 | 172.22.80.94 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.2005 | ethernet1/3.15 | Log-Panorama | 05/10/2020 08:36 | 28423 | 1 | 43216 | 443 | 0 | 0 | 0x20019 | tcp | allow | 78 | 78 | 0 | 1 | 05/10/2020 08:36 | 0 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 1 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 05/10/2020 08:36 | 1801023407 | TRAFFIC | end | 2049 | 05/10/2020 08:36 | 172.22.80.94 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.2005 | ethernet1/3.15 | Log-Panorama | 05/10/2020 08:36 | 132536 | 1 | 43216 | 443 | 0 | 0 | 0x20019 | tcp | allow | 312 | 312 | 0 | 4 | 05/10/2020 08:36 | 7 | any | 0 | 2,09E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 4 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy
1 | 02/10/2020 10:06 | 1801023407 | TRAFFIC | end | 2049 | 02/10/2020 10:06 | 172.22.80.94 | 200.218.67.209 |   | Transito-AWS-RSFN-DC2 | incomplete | vsys1 | AWS | TRANSITO | ethernet1/10.1055 | ethernet1/3.15 | Log-Panorama | 02/10/2020 10:06 | 230094 | 1 | 42164 | 443 | 0 | 0 | 0x20019 | tcp | allow | 156 | 156 | 0 | 2 | 02/10/2020 10:06 | 1 | any | 0 | 2,08E+10 | 0x0 | 172.16.0.0-172.31.255.255 | Brazil | 0 | 2 | 0 | aged-out | 11 | 0 | 0 | 0 |   | PA-3020A | from-policy

No aguardo.

Obrigado.

>

**Comment by abcbrasil-28195667** [comment]
[] http-outgoing-1 << HTTP/1.1 400 Bad Request                                                                                        spi-messaging-84c6c95fb6-6vvbc:[05/10/2020 14:16:55.591 Z] [---- traceId -----              ] [receive-1                        ] [DEBUG] [org.apache.http.headers                                                [] http-outgoing-1 << Content-Encoding: gzip                                                                                          spi-messaging-84c6c95fb6-6vvbc:[05/10/2020 14:16:55.591 Z] [---- traceId -----              ] [receive-1                        ] [DEBUG] [org.apache.http.headers                                                [] http-outgoing-1 << Content-Length: 189                                                                                             spi-messaging-84c6c95fb6-6vvbc:[05/10/2020 14:16:55.591 Z] [---- traceId -----              ] [receive-1                        ] [DEBUG] [org.apache.http.headers                                                [] http-outgoing-1 << Content-Type: application/problem+xml                                                                           spi-messaging-84c6c95fb6-6vvbc:[05/10/2020 14:16:55.591 Z] [---- traceId -----              ] [receive-1                        ] [DEBUG] [org.apache.http.impl.execchain.  ainClientExec                         [] Connection can be kept alive indefinitely                                                                                          spi-messaging-84c6c95fb6-6vvbc:[05/10/2020 14:16:55.591 Z] [---- traceId -----              ] [receive-1                        ] [DEBUG] [org.apache.http.impl.conn.Pooli  gHttpClientConnectionManager          [] Connection [id: 1][route: {s}->https://icom-h.pi.rsfn.net.br:16522] can be kept alive indefinitely                                 spi-messaging-84c6c95fb6-6vvbc:[05/10/2020 14:16:55.591 Z] [---- traceId -----              ] [receive-1                        ] [DEBUG] [org.apache.http.impl.conn.Defau  tManagedHttpClientConnection          [] http-outgoing-1: set socket timeout to 0                                                                                           spi-messaging-84c6c95fb6-6vvbc:[05/10/2020 14:16:55.591 Z] [---- traceId -----              ] [receive-1                        ] [DEBUG] [org.apache.http.impl.conn.Pooli  gHttpClientConnectionManager          [] Connection released: [id: 1][route: {s}->https://icom-h.pi.rsfn.net.br:16522][total available: 3; route allocated: 3 of 14; total  allocated: 3 of 14[]                                                                                                                                                        spi-messaging-84c6c95fb6-6vvbc:[05/10/2020 14:16:55.593 Z] [---- traceId -----              ] [receive-1                        ] [ERROR] [matera.spi.messaging.receive.ap  lication.service.MessagingReceiverTask[] Unexpected error trying to receive messages from URL /api/v1/out/28195667/stream/start                                             spi-messaging-84c6c95fb6-6vvbc:matera.spi.messaging.receive.exception.FetchClearingMessageException: Error receiving message from the clearing                              spi-messaging-84c6c95fb6-6vvbc:    at matera.spi.messaging.receive.domain.service.MessageReceiver.fetchMessage(MessageReceiver.java:36) ~[classes!/:1.2.1]                  spi-messaging-84c6c95fb6-6vvbc:    at matera.spi.messaging.receive.application.service.MessagingReceiverTask.run(MessagingReceiverTask.java:65) ~[classes!/:1.2.1]          spi-messaging-84c6c95fb6-6vvbc:    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]                                                spi-messaging-84c6c95fb6-6vvbc:    at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]                                                                spi-messaging-84c6c95fb6-6vvbc:    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]                           spi-messaging-84c6c95fb6-6vvbc:    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]                                                  spi-messaging-84c6c95fb6-6vvbc:    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]                                                 spi-messaging-84c6c95fb6-6vvbc:    at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]                                                                               spi-messaging-84c6c95fb6-6vvbc:Caused by: matera.spi.messaging.commons.exception.BadRequestException: Error when calling clearing service. Status Code: 400. Information R  eturned: ClearingErrorResponseDTO(title=Um dos cabeçalhos enviados não era esperado, type=https://icom.pi.rsfn.net.br/api/v1/error/invalidHeader, status=null, detail=null  , instance=null, httpResponseStatus=400)

**Comment by abcbrasil-28195667** [comment]
Srs.
Podem encerrar o chamado, muito obrigado.
Problema solucionado.
