### ISSUE TITLE
[Dúvida] no [QR Code] - Modelo arquivo com certificados ativos de QR Codes dinâmicos

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#355]
**Descreva sua dúvida ou problema**

Bom dia! Gostaria de saber se já foi definido o modelo do arquivo que será disponibilizado na interface ARQ para o PSP contendo os certificados ativos de QR Codes dinâmicos.

![image](https://user-images.githubusercontent.com/5355541/95085926-3a041680-06f6-11eb-8bcc-ef0d4a51bb9c.png)

**Sistema ou Área**
QR Code

**Comment by ninrod** [comment]
@monise, bom dia. 

Vou verificar se há algum update e te respondo aqui.

**Comment by ninrod** [comment]
@monise, boa tarde. 

Até o dia 06/10, será realizada publicação de nova versão do Manual de Segurança do Pix contendo algumas informações adicionais sobre o processo de validação dos certificados de sites de QR Code.

Nesta data, será também enviado um comunicado disponibilizado o processo de recepção dos arquivos CERTQRC, bem como a possibilidade de download do arquivo contendo os certificados associados aos sites de QR Code dos demais PSPs.
