### ISSUE TITLE
[Dúvida] no [DICT] - Download arquivos CID

### ISSUE THREAD

**Issue by WagnerLau** [bacen/pix-perguntas-e-respostas#356]
**Descreva sua dúvida ou problema**
Ontem (05/10/2020) em ambiente de PRODUCAO, realizamos o download do arquivo de CIDs do DICT com sucesso, porém, logo após esse horário a solicitação do arquivo de CIDs ficou indisponível pelo DICT.
A fim de realizar o sincronismo do DICT Local com o DICT do BACEN, a funcionalidade de download do arquivo CID é essencial após o horário das 18hs.

Por gentileza, qual o horário no qual estará disponível está funcionalidade (download do arquivo de CIDs)?

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
Para problemas ou dúvidas relativas ao ambiente de **produção**, os participantes devem utilizar exclusivamente os canais de email (suporte.ti@bcb.gov.br) ou telefone (61 3414-5100) do Banco Central do Brasil. O canal do github não poderá ser utilizado para tal fim.
