### ISSUE TITLE
[Dúvida] - Uso por estrangeiros

### ISSUE THREAD

**Issue by Velenthis** [bacen/pix-perguntas-e-respostas#359]
Será possível, e se sim, o quão dificil será pra um estrangeiro se cadastrar e usar o Pix? Poderia o Pix ser usado como uma arma de soft power contra países como a Argentina, Paraguai e Venezuela?

**Comment by ninrod** [comment]
@Velenthis , bom dia. 

> Será possível, e se sim, o quão dificil será pra um estrangeiro se cadastrar e usar o Pix?

Não se pode excluir essa possibilidade em termos de cenários futuros.

> Poderia o Pix ser usado como uma arma de soft power contra países como a Argentina, Paraguai e Venezuela?

O objetivo do Pix é ser um instrumento parar agregar eficiência e solidez ao sistema financeiro nacional, tema que é um dos pilares da missão institucional do BCB.
