### ISSUE TITLE
Erro ao chamar GET - /cids/file/ID

### ISSUE THREAD

**Issue by dfredmota** [bacen/pix-perguntas-e-respostas#36]
Boa Tarde,

Estou tentando executar o método GET "/cids/files/{Id}"  que recupera os dados do arquivo de cids e o mesmo esta retornando o seguinte erro:

![prin1](https://user-images.githubusercontent.com/5722243/86409956-4a889900-bc90-11ea-9899-4f127c116f7c.png)
![print2](https://user-images.githubusercontent.com/5722243/86409958-4bb9c600-bc90-11ea-996c-5e7feec63ffb.png)

Alguém saberia informar o que pode estar ocorrendo?

**Comment by judahreis** [comment]
@dfredmota, não conseguimos reproduzir o erro. Caso o problema persista, pode nos enviar o CorrelationId?
