### ISSUE TITLE
[Dúvida] no [ARQ] - Download de todos os certificados de sites de QR Codes dinâmicos ativos no Pix

### ISSUE THREAD

**Issue by ccmario** [bacen/pix-perguntas-e-respostas#361]
**Descreva sua dúvida ou problema**
O novo manual de segurança, versão 3.1, esclareceu alguns detalhes sobre o arquivo contendo todos os certificados CERTQRC ativos no Pix, mas ainda restaram dúvidas considerando que será retornado um arquivo compactado:

* Sabendo que os PSP's deverão enviar o certificado no formato PEM (sem a cadeia de certificação), qual será o conteúdo do arquivo "certqrc.zip" obtido através do ARQ? Teremos os mesmos arquivos no formato PEM enviados por todos os participantes?

Dependemos do registro de pelo menos um certificado ativo, mesmo que em ambiente de homologação, para avaliarmos este retorno então, se possível, gostaríamos de tentar antecipar esta resposta para avançarmos com as tratativas de segurança para leitura de QR Code Dinâmico Pix em virtude do prazo que se aproxima.

**Sistema ou Área**
QR Code

Obrigado!

**Comment by monise** [comment]
Boa tarde! Estamos com a mesma dúvida. Já foi definido qual será o conteúdo do arquivo?

**Comment by jgslima** [comment]
Olá. É necessária a definição para viabilizar o desenvolvimento pelos PSPs a tempo.
Obrigado.

**Comment by ccmario** [comment]
Boa tarde @ninrod!

Ainda estamos aguardando uma resposta oficial para seguir com as tratativas. Não sei se há alguma indefinição com relação a este item, mas avaliamos o download do arquivo do ambiente de homologação e constatamos que ele contém vários certficados (extensão ".cer") que, aparentemente, estão corrompidos ou foram gerados apenas como exemplo. Tentamos validá-los como PEM ou DER e não tivemos sucesso. Diante disso, gostaríamos de saber:

- Podemos considerar que o conteúdo do arquivo compactado corresponderá aos certificados x.509 (no formato PEM) enviados por cada PSP na transação CERTQRC através do STA?

- Existe previsão de quando esta transação será disponibilizada para o ambiente de produção (só está habilitada em homologação), visto o prazo de até sete dias para registro do certificado pelo BC e a data de 03/11 que se aproxima?

Obrigado!

**Comment by ninrod** [comment]
@ccmario , pode acionar o suporte oficial? acho que é via caixa Pix, tem um ramal específico também.

Essa parte não consigo te responder porque cai em outra área. 

Vou tentar também acionar o pessoal para responderem aqui.

**Comment by jgslima** [comment]
Existe previsão da liberação da definição do arquivo?
O prazo está para se tornar inviável.
Obrigado

**Comment by franciscotfmc** [comment]
@ccmario estamos analisando esse item aqui também. O que eu achei estranho foi que existem poucos certificados lá no ambiente de homologação até então. Você tem algum QR Code Dinâmico válido aí que eu possa tentar validar por aqui? _(fazendo parser e get no payload)_

**Comment by ninrod** [comment]
> Existe previsão de quando esta transação será disponibilizada para o ambiente de produção (só está habilitada em homologação), visto o prazo de até sete dias para registro do certificado pelo BC e a data de 03/11 que se aproxima?

Existe. 

“As funcionalidades de envio de certificados CERTQRC e de recuperação do arquivo de certificados deve ser disponibilizada em produção em 21/10.”

**Comment by jgslima** [comment]
@ninrod Filipe,
Não sei se ficou claro. Nossa demanda é para sabermos qual é a definição do conteúdo do arquivo. Ex.: será um .zip com cada item aendo um certificado no formato PEM?
Aparentemente a expectativa do Banco Central é que os PSPs desenvolvam a leitura deste arquivo para Novembro. Está correta esta expectativa?
Se a expectativa é esta, é necessário clarificar o conteúdo do arquivo.
Obrigado!

**Comment by ninrod** [comment]
Entendo a questão do tempo e da necessidade de conhecer a definição. O time responsável está ciente e responderá.

**Comment by anogma** [comment]
> Não sei se há alguma indefinição com relação a este item, mas avaliamos o download do arquivo do ambiente de homologação e constatamos que ele contém vários certficados (extensão ".cer") que, aparentemente, estão corrompidos ou foram gerados apenas como exemplo. Tentamos validá-los como PEM ou DER e não tivemos sucesso.

@ccmario, o arquivo certqrc-h.zip disponibilizado no ARQ de homologação foi gerado a partir dos certificados já enviados pelos participantes e deveria conter, sim certificados válidos em formato PEM.

Como foi feita a sua validação?

Daqui um comando como o que segue é executado com sucesso:
`openssl x509 -in xxxxxx.cer -inform pem -text`

**Comment by cristianokbc** [comment]
> Não sei se há alguma indefinição com relação a este item, mas avaliamos o download do arquivo do ambiente de homologação e constatamos que ele contém vários certficados (extensão ".cer") que, aparentemente, estão corrompidos ou foram gerados apenas como exemplo. Tentamos validá-los como PEM ou DER e não tivemos sucesso.

@ccmario, o arquivo certqrc-h.zip disponibilizado no ARQ de homologação foi gerado a partir dos certificados já enviados pelos participantes e deveria conter, sim certificados válidos em formato PEM.

Como foi feita a sua validação?

Daqui um comando como o que segue é executado com sucesso:
`openssl x509 -in xxxxxx.cer -inform pem -text`

**Comment by ccmario** [comment]
Bom dia @cristianokbc e @anogma! Tentei executando o mesmo comando e obtive a mensagem abaixo:

openssl x509 -in certificado-1.cer -inform pem -text
unable to load certificate
140519015612864:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE

Irei solicitar à area responsável para realizar novo download e confirmar se o arquivo compactado recuperado pelo ARQ não está corrompido ou se houve alguma falha interna. De qualquer forma, já temos as respostas que precisávamos.

Obrigado!
