### ISSUE TITLE
[Problema] no [DICT] - Erro 500 ao atualizar chave sem agência

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#363]
**Descreva sua dúvida ou problema**

Olá! Estamos recebendo um erro 500 quando tentamos atualizar uma chave que no registro atual não possui agência, mas que está recebendo como atualização um número de agencia e conta diferente.

Esse cenário é permitido?

**Sistema ou Área**
DICT

**Identificador do Problema**
Chave: 8612322594

![121169708_621109221896244_8256213385340976495_n](https://user-images.githubusercontent.com/5355541/95466418-b4c96d80-0952-11eb-9895-b2ce926e3717.png)

**Comment by HenriqueSimoes82** [comment]
Olá @monise , esse cenário é permitido sim. Problema foi corrigido. Obrigado pelo reporte.
