### ISSUE TITLE
[Dúvida e Problema] no [DICT] - Tamanho do AccountNumber

### ISSUE THREAD

**Issue by WagnerLau** [bacen/pix-perguntas-e-respostas#364]
**Descreva sua dúvida ou problema**
**Item 1:**
Em testes de inclusão de chaves realizados no ambiente de Homologação, utilizando o "AccountNumber = 1", o DICT retornou a mensagem de erro/validação abaixo:
- reason = must match "^[0-9]{2,20}$"
Está mensagem indica que o "AccountNumber" deve possuir no mínimo 2 dígitos.

Porém, no swagger do DICT disponibilizado no site do BACEN "API_do_DICT-v1.0.html", a definição do "AccountNumber" está como:
- string ^[0-9]{1,20}$
Está definição indica que o "AccountNumber" deve possuir no mínimo 1 dígito.

Diante o exposto, qual o valor mínimo para o "AccountNumber"? O swagger ou validação do DICT será ajustado?

**Item 2:**
Ainda falando sobre o "AccountNumber", o mesmo possui a descrição abaixo no swagger do DICT (API_do_DICT-v1.0.html):
- "Número de conta, incluindo verificador. Se verificador for letra, substituir por 0."
Sendo que pode possuir os "AccountType" como "Conta Corrente/Conta de Pagamento", "Conta-Salário" e "Conta de Poupança".

Analisando outro documento do BACEN, referente ao catálogo de mensagens (Dicionário de Tipos, pág. 87):
https://www.bcb.gov.br/content/estabilidadefinanceira/cedsfn/Catalogos/Catalogo_de_Servicos_do_SFN_Volume_IV_Versao_501.pdf
A descrição da "Conta de Pagamento" informa que:
- "Número da conta bancária ou de pagamento com dígito (se este existir), se houver valor alfanumérico, este deve ser convertido para 0"

Diante o exposto, uma conta "Bancária" ou de "Pagamento" pode não possuir dígito verificador, neste caso o valor a ser informado no "AccountNumber" poderá possuir apenas 1 dígito. Em um exemplo de possuir um cliente que possui o valor da Conta de Pagamento igual a "1", sem dígito verificador, deveríamos informar na inclusão de chave de endereçamento o "AccountNumber = 1"?

**Sistema ou Área**
DICT

**Comment by HenriqueSimoes82** [comment]
Olá @WagnerLau, o correto é o que está definido na API. A aplicação já foi atualizada para aceita 1 dígito. Agradeço o reporte.
