### ISSUE TITLE
[Dúvida] no [DICT] - Ponto em nomes de Pessoa Física 

### ISSUE THREAD

**Issue by fbjhon** [bacen/pix-perguntas-e-respostas#365]
**Descreva sua dúvida ou problema**
Temos no nosso cadastro nomes de pessoas físicas com "."(ponto) exemplo Fulano S. Silva, e estamos recebendo erro na inclusão desses clientes, existe a possibilidade de o Bacen remover essa restrição?

**Sistema ou Área**
DICT

**Identificador do Problema**
Correlation-Id (no caso de erro do DICT), ou ResourceId (no caso do SPI/ICOM). Se possível, indique também o ISPB, e a data-hora em que identificou o problema.

**Mensagens Enviadas / Recebidas**
XML das mensagens enviadas e recebidas (sem assinatura fica melhor)

**URL de conexão**
URL para onde a mensagem foi enviada

**Dados adicionais**
Qualquer informação adicional que ajude a identificar o problema ou dúvida.

**Comment by renatofrota** [comment]
> **Descreva sua dúvida ou problema**
> Temos no nosso cadastro nomes de pessoas físicas com "."(ponto) exemplo Fulano S. Silva, e estamos recebendo erro na inclusão desses clientes, existe a possibilidade de o Bacen remover essa restrição?

Não sou fonte oficial de informação mas duvido que o façam. O nome da pessoa não deveria estar abreviado no seu cadastro (certamente não está abreviado no CPF da pessoa).

**Comment by luizlaydner** [comment]
Os nomes de pessoas físicas e jurídicas devem estar de acordo com o que consta no cadastro oficial de CPF e CNPJ.
Pontos não são aceitos para nomes de pessoas físicas.
