### ISSUE TITLE
[Dúvida] no [SPI] - Negada por Timeout

### ISSUE THREAD

**Issue by fernandogodoy** [bacen/pix-perguntas-e-respostas#366]
Pensando em um cenário onde o PSP recebedor, recebe uma mensagem para o fluxo de validação e, tendo este, demorado para conclusão do processo. 
Neste cenário devolvendo ao SPI uma mensagem de OK, porém, no limite do tempo.

Ao receber a mensagem de resposta do PSP recebedor e, considerando latência de rede, esta pode ter seu tempo excedido conforme normas do manual de tempos e, neste caso, entendo que seria negaria por timeout.

Para este cenario, será enviada uma mensagem ao PSP pagador informando o motivo da negada para que este, atualize as informações relacionadas a tentativa de pagamento do PIX iniciado?

**Comment by rafael-omello** [comment]
Quando uma PACS.008 que já foi encaminhada para o PSP recebedor for rejeitada por timeout pelo SPI, serão encaminhadas mensagens de rejeição para o PSP pagador e para o PSP recebedor.
