### ISSUE TITLE
[Problema] na [Documentação] - Remova a marca d'água da documentação

### ISSUE THREAD

**Issue by feinstein** [bacen/pix-perguntas-e-respostas#368]
As documentações do Pix vem com a seguinte marca d'água:

![image](https://user-images.githubusercontent.com/8120472/95920966-ca8dc700-0d86-11eb-9769-975d771f60df.png)

Fica péssimo de ler a documentação, principalmente em um celular, com as linhas verticais da marca d'água contrastando com o texto.

**Comment by ninrod** [comment]
@feinstein , por favor: 

- qual é o nome do documento?
-  qual é exatamente a versão do documento que você está acessando?
- qual é a URL que você está usando para acessar o documento?

**Comment by feinstein** [comment]
@ninrod vejo a marca d'água nos seguintes documentos:

* "Documento de especificações - versão 5.0.pdf".
* "Anexo IV - Manual de Segurança PIX v2.0.pdf".

Não me recordo a URL em que achei eles. São os únicos que abri até o momento, então nada impede que outros também não tenham.

**Comment by ninrod** [comment]
@feinstein, o manual de segurança está em uma versão antiga. 

Recomendo que você busque versões atualizadas dos documentos neste link: https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos

**Comment by feinstein** [comment]
Os documentos nesse link estão todos separados e sem um local em comum para achar todos.

Seria interessante criar um repositório aqui que contenha todos os arquivos do Pix.

**Comment by renatofrota** [comment]
> Os documentos nesse link estão todos separados e sem um local em comum para achar todos.
> 
> Seria interessante criar um repositório aqui que contenha todos os documentos do Pix.

Estão todos no botão "Regulamentação Relacionada ao Pix".

Mas acho a ideia do repositório (onde os arquivos poderiam ser devidamente versionados, sem alteração do seu nome) interessante.

**Comment by feinstein** [comment]
@renatofrota voce viu o "Documento de especificações - versão 5.0.pdf" em "Regulamentação Relacionada ao Pix"?

**Comment by renatofrota** [comment]
> @renatofrota voce viu o "Documento de especificações - versão 5.0.pdf" em "Regulamentação Relacionada ao Pix"?

Você se refere a [esse arquivo](https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/Documento%20de%20especifica%C3%A7%C3%B5es%20-%20vers%C3%A3o%205-0.pdf). O arquivo em questão é obsoleto.

O link para ele estava [nesta página](https://www.bcb.gov.br/estabilidadefinanceira/forumpagamentosinstantaneos), assim como o link para a [versão 6.0](https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/Documento%20de%20especifica%C3%A7%C3%B5es%20-%20vers%C3%A3o%206-0.pdf), que também é obsoleta.

Conforme a informação atual _na mesma página em questão_, toda a documentação (Regulamentação e Manuais Técnicos) foi migrada para a [Página do Pix](https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos) (endereço que já foi fornecido acima) e não existem versões mais recentes deste documento em particular por que o seu conteúdo foi desmembrado em outros documentos mais específicos.

**Comment by feinstein** [comment]
Ah, que maravilha, passei os ultimos 2 dias lendo um documento obsoleto 🤦.

Obrigado @renatofrota, vou dar uma olhada, estou com muita dificuldade de achar nesse mar de informações as poucas coisas que eu realmente quero saber se são possíveis de serem feitas e como devem ser feitas.

**Comment by renatofrota** [comment]
> Ah, que maravilha, passei os ultimos 2 dias lendo um documento obsoleto facepalm.
> 
> Obrigado @renatofrota, vou dar uma olhada, estou com muita dificuldade de achar nesse mar de informações as poucas coisas que eu realmente quero saber se são possíveis de serem feitas e como devem ser feitas.

Disponha.

Se você não trabalha para um PSP e não vai se comunicar diretamente com o DICT, você provavelmente está mais interessado no arquivo __Manual de Padrões para Iniciação do Pix__ (não vou colocar o link direto justamente por razão de obsolescência, veja na [Página do Pix](https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos) o link para a versão mais atual).

**Comment by ninrod** [comment]
@renatofrota , obrigado.

**Comment by ninrod** [comment]
@feinstein, o corpo documental do Pix realmente ficará localizado na página do BCB mesmo. Peço desculpas pela confusão. O Pix está seguindo um cronograma bastante arrojado e por vezes temos que correr e quebrar alguns elementos.

**Comment by feinstein** [comment]
Tudo bem, entendo.
