### ISSUE TITLE
[Problema] no [DICT] - Campo LastModified não está sendo atualizado - pedido de portabilidade

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#37]
**Descreva sua dúvida ou problema**

Notamos que o campo **LastModified** **não está** sendo atualizado conforme realizamos as operações em cima de um pedido de portabilidade. 
Esse comportamento está correto? Pois nosso entendimento, era de que esse campo seria atualizado toda vez que o status do pedido fosse alterado.

**Sistema ou Área**
DICT

**Dados adicionais**

**Id do pedido:** 26f11683-71de-4d07-8cd5-906fdff512f

![image](https://user-images.githubusercontent.com/5355541/86410924-1910cd00-bc92-11ea-802b-bc32440b0091.png)

![image](https://user-images.githubusercontent.com/5355541/86410820-e36be400-bc91-11ea-8ec6-641c4494f24d.png)

**Comment by luizlaydner** [comment]
LastModified deve ser atualizado quando status se altera. 
Há bug, vamos corrigir! Obrigado.
