### ISSUE TITLE
Dúvida na Iniciação de Pagamentos - Campo recebivelAposVencimento removido

### ISSUE THREAD

**Issue by gpneto** [bacen/pix-perguntas-e-respostas#370]
**Descreva sua dúvida ou problema**
Verificamos que na atualização do documento "Manual de Padrões para Iniciação do Pix"  foi removido o campo recebivelAposVencimento.

Poderiam verificar se está correto na página 14 na tabela apresentada ainda constar o campo calendario.recebivelAposVencimento.

Outro ponto, nós como PSP iriamos utilizar esse campo recebivelAposVencimento para calcular o valor de juros e multa no QR Code Dinâmico.

Por exemplo se o campo recebivelAposVencimento = true e o documento está vencido, neste caso no payload JSON assinado iria retornar o valor final já atualizado com o juros e multa do cadastro.

Por outro lado se o documento está vencido e recebivelAposVencimento = false ao acessar a URL que retorna o payload JSON assinado nós iriamos retornar  HTTP status 410 ‘gone’.

**Sistema ou Área**
 Iniciação de Pagamentos

**Dados adicionais**
![Captura de Tela 2020-10-14 às 09 37 15](https://user-images.githubusercontent.com/20403814/95989652-eb92fe00-0e00-11eb-83db-a4db9fa5a482.png)

**Comment by ninrod** [comment]
> Verificamos que na atualização do documento "Manual de Padrões para Iniciação do Pix" foi removido o campo recebivelAposVencimento.

Exatamente. Esses campos estão em "revisão" e uma nova estrutura será apresentada na versão `2.1.0` a ser publicada muito em breve.
