### ISSUE TITLE
[Problema] no [DICT] - Portabilidade não concluída

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-perguntas-e-respostas#374]
Solicitei num PSP portabilidade de chaves cadastradas em outro PSP.  Como o PSP onde estão as chaves está com problema (mesmo já com 10 dias de operação em produção do DICT), não consegui confirmar a portabilidade. 

Meu entendimento do DICT é que em não havendo recusa da portabilidade, ela seria completada após uma semana. Porém, não foi isso que aconteceu... sem entrar no caso específico, o entendimento sobre a portabilidade está correto ? Se estiver correto, o que pode ter acontecido ?

**Comment by franciscotfmc** [comment]
@rubenskuhl, 

Quando o período de portabilidade expira, o processo é resolvido mantendo-se a chave no PSP original. 

Então teoricamente ela deveria, neste momento, estar marcada como ativa e você poderia iniciar outro processo de portabilidade _(a menos que o PSP não tenha finalizado o processo de portabilidade automaticamente)_.

**Comment by rubenskuhl** [comment]
> @rubenskuhl,
> 
> Quando o período de portabilidade expira, o processo é resolvido mantendo-se a chave no PSP original.
> 
> Então teoricamente ela deveria, neste momento, estar marcada como ativa e você poderia iniciar outro processo de portabilidade _(a menos que o PSP não tenha finalizado o processo de portabilidade automaticamente)_.

Qual PSP deveria finalizar o processo que não foi completado, o original ou o potencialmente novo ?

**Comment by franciscotfmc** [comment]
O PSP doador _(no exemplo, o original)_, precisa cancelar o processo de portabilidade (já que não houve confirmação do usuário).

O potencialmente novo não pode fazer nada que não seja a pedido do usuário (neste caso, confirmar a portabilidade).

**Comment by rubenskuhl** [comment]
> O PSP doador _(no exemplo, o original)_, precisa cancelar o processo de portabilidade (já que não houve confirmação do usuário).
> 
> O potencialmente novo não pode fazer nada que não seja a pedido do usuário (neste caso, confirmar a portabilidade).

Então foi double-fail do PSP. Reclamação já aberta no BACEN.
