### ISSUE TITLE
[Dúvida] no [DICT] - Intervalo de consulta de reivindicações

### ISSUE THREAD

**Issue by iliojunior** [bacen/pix-perguntas-e-respostas#375]
Quando o PSP consulta a API "Listar Reivindicações", passando como parametro de Limit o maior valor permitido (200) e se a response retorna true em "HasMoreElements", o que significa que há mais itens no lado do BC a processar. O PSP não poderia, ou até deveria, já fazer outra requisição imediatamente ?

Tendo em vista os ANSs e experiências de usuário esperadas.

**Comment by luizlaydner** [comment]
> O PSP não poderia, ou até deveria, já fazer outra requisição imediatamente ?

Sim, poderia.
