### ISSUE TITLE
[Problema] no [DICT] - Erro "Invalid reason" ao confirmar pedido de portabilidade

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#38]
**Descreva sua dúvida ou problema**

Estamos testando o fluxo de portabilidade, porém quando tentamos **confirmar** um pedido em aberto (já fizemos o passo do _acknowledge_) para o PSP doador, o DICT está retornando o erro **_Invalid reason_**, no entanto, estamos passando uma razão válida, que seria o motivo **USER_REQUESTED**, simulando o fluxo onde o usuário confirma que deseja realizar a portabilidade de chaves.

Poderiam, por favor, verificar o que pode ter ocorrido? 
Nossa requisição está correta?

**Sistema ou Área**
DICT

**Identificador do Problema**

  <correlationId>C3EFA3CAC51846AFA690BA07717649B6</correlationId>

**Dados adicionais**

**Request**

```
POST /api/v1/claims/26f11683-71de-4d07-8cd5-906fdff512f8/confirm

<ConfirmClaimRequest>
    <ClaimId>26f11683-71de-4d07-8cd5-906fdff512f8</ClaimId>
    <Reason>USER_REQUESTED</Reason>
</ConfirmClaimRequest>
```

**Response**

```
HTTP Status 400

<problem xmlns="urn:ietf:rfc:7807">
    <type>https://dict.pi.rsfn.net.br/api/v1/error/InvalidReason</type>
    <title>Bad Request</title>
    <status>400</status>
    <detail>Invalid reason</detail>
    <correlationId>C3EFA3CAC51846AFA690BA07717649B6</correlationId>
</problem>
```

**Comment by luizlaydner** [comment]
É um bug, mesma causa do apontado na issue #14 . 

Com a adição do campo `Participant` no `ConfirmClaimRequest` feita na API [v1.0.0-RC4](https://github.com/bacen/pix-dict-api/releases/tag/v1.0.0-RC4), ele foi corrigido. v1.0.0-RC4 deve ser disponibilizada em homologação hoje ainda.

Obrigado pelo detalhamento do problema @monise  !
