### ISSUE TITLE
[Problema] no [DICT] - Identificados campos novos campos na API, gerando erro.

### ISSUE THREAD

**Issue by gizelysc** [bacen/pix-perguntas-e-respostas#381]
**Descreva sua dúvida ou problema**

Estamos recebendo campos novos que não estavam mapeados nem no repositório https://github.com/bacen/pix-dict-api.git nem na documentação da API ou página do pix. 
Os seguintes campos foram incluídos :
responseTime   e correlationId

 Os campos foram identificados nas funções: 
listClaims, confirmClaim e cancelClaim

Já precisamos considerá-los? Tem alguma documentação? 
Se possível, alterar o repositório com os novos campos.

Também gostaria de confirmar se essa alteração irá para produção.
Obrigada.

**Sistema ou Área**
DICT

**Comment by gizelysc** [comment]
Pessoal, poderiam me atualizar sobre esse campos?

**Comment by luizlaydner** [comment]
Os campos `responseTime` e `correlationId` serão adicionados a uma nova versão da especificação da API que será publicada em breve. 
Esses novos campos estarão presentes em todas respostas do DICT e tem propósito de agilizar o processo de suporte aos participantes.
Em homologação, de fato foram adicionados sem antes publicarmos a especificação atualizada. Vamos evitar isso no futuro, publicando sempre em conjunto a nova versão da especificação.
Os campos irão eventualmente para produção, mas isso será comunicado com alguma antecedência.
De qualquer forma, vale ressaltar que a adição de campos novos em respostas não quebra a API. É uma alteração compatível.
**É muito importante que a implementação dos clientes sejam capazes de lidar com campos novos não conhecidos**.

**Comment by gizelysc** [comment]
Ok, pessoal!
Obrigada pelo retorno!

**Comment by luizlaydner** [comment]
Versão 1.0.1 da spec da API foi publicada. Ver aqui: https://github.com/bacen/pix-dict-api/releases/tag/v1.0.1
Essa versão inclui os campos mencionados nessa issue.

**Comment by robsonpeixoto** [comment]
O que significa `ResponseTime`? É o instante que o payload da response foi criado?

**Comment by luizlaydner** [comment]
> O que significa ResponseTime? É o instante que o payload da response foi criado?

Exato.
