### ISSUE TITLE
[Dúvida] na [Lista de Participantes]

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-perguntas-e-respostas#382]
No site do Pix, https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos , a lista de participantes publicada ainda é a de 15.10. Até 16.10 era o prazo para entrar na janela atual que tem em Go Live em 16.11; essa lista será publicada na mesma URL ?

**Comment by ninrod** [comment]
@rubenskuhl , bom dia. 

Deve ser atualizada ainda hoje.

**Comment by rubenskuhl** [comment]
21.10 07h35 ainda não localizei atualização na página https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos sobre participantes, por isso a dúvida de se o local de publicação se mantém...

**Comment by julianemelo1104** [comment]
> 21.10 07h35 ainda não localizei atualização na página https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos sobre participantes, por isso a dúvida de se o local de publicação se mantém...

Você tentou fazer o download trocando a nomenclatura e passando a data do dia?
https://www.bcb.gov.br/content/estabilidadefinanceira/spi/participantes-spi-20201021.csv
Dessa forma eu consegui baixar.

**Comment by rubenskuhl** [comment]
> > 21.10 07h35 ainda não localizei atualização na página https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos sobre participantes, por isso a dúvida de se o local de publicação se mantém...
> 
> Você tentou fazer o download trocando a nomenclatura e passando a data do dia?
> https://www.bcb.gov.br/content/estabilidadefinanceira/spi/participantes-spi-20201021.csv
> Dessa forma eu consegui baixar.

Essa lista tem apenas 97 participantes, e a lista publicada em https://www.bcb.gov.br/content/estabilidadefinanceira/pix/ListadeparticipantesdoPix-15.10.pdf já tinha mais de 700 participantes. 

O que tenho feito é atualizar a página https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos e olhar o arquivo do link "Lista de Participantes do Pix".

**Comment by rubenskuhl** [comment]
Ah, e eu tentei https://www.bcb.gov.br/content/estabilidadefinanceira/pix/ListadeparticipantesdoPix-16.10.pdf, https://www.bcb.gov.br/content/estabilidadefinanceira/pix/ListadeparticipantesdoPix-19.10.pdf , https://www.bcb.gov.br/content/estabilidadefinanceira/pix/ListadeparticipantesdoPix-20.10.pdf e https://www.bcb.gov.br/content/estabilidadefinanceira/pix/ListadeparticipantesdoPix-21.10.pdf sem sucesso.

**Comment by ninrod** [comment]
@rubenskuhl , parece que há uma questão na publicação desta informação. Vou averiguar e retorno em seguida.

**Comment by rubenskuhl** [comment]
> @rubenskuhl , parece que há uma questão na publicação desta informação. Vou averiguar e retorno em seguida.

A falta de publicidade nessa informação impede a efetiva seleção de PSPs por interessados, já que não se sabe quais estarão disponíveis para o Go Live e quais não. E como há uma lista de participantes diretos publicada, os indiretos não conseguem competir como poderiam com os participantes diretos.

**Comment by ninrod** [comment]
@rubenskuhl , entendo a criticidade. Vamos tentar publicar esta lista o mais rápido possível.

**Comment by vallerao** [comment]
O prazo final de habilitação dos participantes em homologação foi 16/10. 
A relação dos participantes diretos já está disponível em https://www.bcb.gov.br/estabilidadefinanceira/sistemapagamentosinstantaneos.
A relação completa dos participantes deve ser publicada em https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos até o final desta semana. 
Como o tema é essencialmente negocial, sugerimos contato por meio do email pix@bcb.gov.br. (O canal Github tem um foco em questões técnicas de TI, especialmente ligadas ao processo de desenvolvimento e homologação.)
