### ISSUE TITLE
Dúvida - Horário de funcionamento DICT

### ISSUE THREAD

**Issue by nataliapaivafreitas** [bacen/pix-perguntas-e-respostas#383]
Olá!! Qual será o horário de funcionamento do DICT para gerenciamento de chaves após o dia 16/11?

**Comment by luizlaydner** [comment]
@nataliapaivafreitas Essa informação consta na [resolução BCB n° 1 de 12/8/2020 ](https://www.bcb.gov.br/estabilidadefinanceira/exibenormativo?tipo=Resolu%C3%A7%C3%A3o%20BCB&numero=1), que institui o Pix. Veja os arts 79 e 80 .
