### ISSUE TITLE
[Problema] no [DICT] - PSP Indireto não consegue criar um Relato de Infração

### ISSUE THREAD

**Issue by luismaialf** [bacen/pix-perguntas-e-respostas#384]
**Descreva sua dúvida ou problema**
Estamos tentando criar um Relato de Infração para uma transação de um PSP Indireto nosso porém sempre tomamos o erro Forbidden abaixo.
Fizemos um teste criando o relato para a mesma transação, porém informando dessa vez o ISPB do participante DIRETO, e o sistema acatou a criação identificando como DebitedParticipant o PSP Direto (00000000) e não o Debitado (00655522).

**Sistema ou Área**
DICT

**Identificador do Problema**
Correlation-Id e80f4d1e12bc3f087ae66be8441a4155
Data-hora 2020-10-13 07.34.42.

**Mensagens Enviadas / Recebidas**
Requisição - Criar Relato de Infração PSPI
```
<CreateInfractionReportRequest>
	<Participant>00655522</Participant>
	<InfractionReport>
		<TransactionId>E0065552220201008144402000000703</TransactionId>
		<InfractionType>FRAUD</InfractionType>
		<ReportDetails>TESTE SPX</ReportDetails>
	</InfractionReport>
</CreateInfractionReportRequest>
```

Reposta - Criar Relato de Infração PSPI
```
<problem xmlns="urn:ietf:rfc:7807">
	<type>https://dict.pi.rsfn.net.br/api/v1/error/Forbidden</type>
	<title>Forbidden</title>
	<status>403</status>
	<detail>Participant is not allowed to access this resource</detail>
	<correlationId>942502906ec43ca5dd74fedb2fcdf4eb</correlationId>
</problem>
```

Requisição - Criar Relato de Infração PSP Direto
```
<CreateInfractionReportRequest>
	<Participant>00000000</Participant>
	<InfractionReport>
		<TransactionId>E0065552220201008144402000000703</TransactionId>
		<InfractionType>FRAUD</InfractionType>
		<ReportDetails/>
	</InfractionReport>
</CreateInfractionReportRequest>
```

Consulta do Relato de Infração aberto pelo PSP com transação do PSPI
```
<GetInfractionReportResponse>
	<InfractionReport>
		<TransactionId>E0065552220201008144402000000703</TransactionId>
		<InfractionType>FRAUD</InfractionType>
		<Id>68c6dff0-8752-45d5-8162-b4619e74c3ce</Id>
		<Status>OPEN</Status>
		<DebitedParticipant>00000000</DebitedParticipant>
		<CreditedParticipant>60746948</CreditedParticipant>
		<ReportedBy>DEBITED_PARTICIPANT</ReportedBy>
		<CreationTime>2020-10-14T14:56:08.419Z</CreationTime>
		<LastModified>2020-10-14T14:56:08.419Z</LastModified>
	</InfractionReport>
	<correlationId>e80f4d1e12bc3f087ae66be8441a4155</correlationId>
	<responseTime>2020-10-19T17:57:45.352Z</responseTime>
</GetInfractionReportResponse>
```

**Comment by luizlaydner** [comment]
Há um bug. Estamos providenciando a correção. 
Obrigado pela clareza do relato!

**Comment by HenriqueSimoes82** [comment]
@luismaialf bug corrigido. Obrigado pelo relato.

**Comment by eduardoanobre** [comment]
Luis Maia, gostaria de ser uma empresa PSP indireta. você pode passar seu contato para admin@9i.com.br ?
