### ISSUE TITLE
[Dúvida] no [Iniciação de Pagamentos] - Posso fazer Pix a partir de uma conta salário?

### ISSUE THREAD

**Issue by gizelysc** [bacen/pix-perguntas-e-respostas#387]
**Descreva sua dúvida ou problema**

Qual a aderência da conta salário com relação a fazer um Pix (pagador)?
Os bancos são obrigados, proibidos ou facultados a disponibilizar a transação para faz PIX (pagar) em conta salário?

**Sistema ou Área**
 Iniciação de Pagamentos

**Comment by ninrod** [comment]
> Qual a aderência da conta salário com relação a fazer um Pix (pagador)?
Os bancos são obrigados, proibidos ou facultados a disponibilizar a transação para faz PIX (pagar) em conta salário?

O correntista poderá receber e enviar Pix utilizando sua conta salário.

**Comment by CharlesMendes** [comment]
BACEN, poderiam revisar a ultima resposta acima?
![image](https://user-images.githubusercontent.com/1323305/99281522-5cb73e00-2811-11eb-9322-dbbfee867c5a.png)

Entendemos que a Conta Salário não é uma contra Transacional, dessa forma não poderia receber Pix nem realizar Pix, poderiam revisar e confirmar a resposta?

**Comment by ninrod** [comment]
>Entendemos que a Conta Salário não é uma contra Transacional, dessa forma não poderia receber Pix nem realizar Pix, poderiam revisar e confirmar a resposta?

Sim, eu respondi errado. A conta salário é bem especial. Recomendo procurar o DECEM/DEBAN para esclarecimentos. 

pix-operacional@bcb.gov.br
