### ISSUE TITLE
[Dúvida] no [arq] - camt.052 está vindo sempre vazio independente da data e horário

### ISSUE THREAD

**Issue by GabrielSouzasbl** [bacen/pix-perguntas-e-respostas#388]
sempre que solicito uma camt.052 a partir da camt.060 o resultado é um arquivo vazio:

última solicitação: C3187429BAA97F399DF35AB00B44D76AE5F392EAD94EC17E5A3EA8B7D330FCD2.

isso acontece para todos os testes de datas e horários.

**Comment by rafael-omello** [comment]
Provavelmente está sendo solicitado extrato de um período em que não se tem nenhum lançamento. Para que possamos fazer uma avaliação concreta é necessário envio do msgId da CAMT.060 consultada.

**Comment by GabrielSouzasbl** [comment]
conforme solicitado, alguns msgId das CAMT.060 consultadas.

M090893561092f88f07f11a467f66b2d
M09089356ba11fdc7d862d35da23d1a6
