### ISSUE TITLE
[Problema] no [DICT] - Verificador de Sincronismo

### ISSUE THREAD

**Issue by guimapalmeira** [bacen/pix-perguntas-e-respostas#39]
**Descreva sua dúvida ou problema**
Boa tarde, estou com problemas para validar o "VSync" para os tipos EMAIL e PHONE.
Ontem estava tudo certo, e hoje começou a dar divergencia apenas para alguns tipos. 
Foi testado inclusive para Participante Indireto e correu tudo bem. Pra o Direto apresenta diferenças.
Tendo em vista que o sistema que faz o cálculo é o mesmo, e mesmo extraindo os Cids pelos Events, fazendo o calculo "manual" não bate com o o Bacen.
Gostaria de saber se foi identificado algum problema por parte do DICT?

**Sistema ou Área**
DICT

**Identificador do Problema**
A exemplo para meu ISPB 02038232(part. Direto), meu VSync  calculado para EMAIL é 59e38295d95d7eff52293da00825dcf5b1f379683e442ca899b64476485b3169, porém no Bacen se espera o eb498e5377aa77ad18ecdf4f76a0cda3be7e960d6cccc261a4393a8fd11ae278, segundo os eventos de CID.

**Comment by HenriqueSimoes82** [comment]
Guilherme,

Identificamos o problema e efetuamos a correção. Pode testar novamente.

Obrigado pelo report detalhado!
