### ISSUE TITLE
Dúvida - DICT de homologação

### ISSUE THREAD

**Issue by nataliapaivafreitas** [bacen/pix-perguntas-e-respostas#392]
Boa tarde!! Por gentileza, qual a grade de funcionamento do DICT de homologação durante a semana e aos finais de semana?

**Comment by luizlaydner** [comment]
Em homologação está sempre disponível, a princípio.
No entanto, a disponibilidade fora da janela de 09:00 às 18:00 durante a semana não é garantida (pode haver manutenções eventuais e não há suporte).
