### ISSUE TITLE
Dúvida no QR Code - Geração do QRCode Estático

### ISSUE THREAD

**Issue by quilombodigital** [bacen/pix-perguntas-e-respostas#393]
Olá,

Eu tenho interesse em gerar QrCodes estáticos gratuitamente para uso no comércio de rua por pessoas de baixa renda, portanto qualquer custo envolvido inviabilizaria esta ação.

Ao começar a ler a documentação eu fiquei um pouco confuso porquê no vídeo abaixo é dito que o qrcode estático também tem que utilizar um PSP e comunicar a sua geração ao sistema PIX:
https://youtu.be/6Tor9r6F9kM?t=395

Em uma thread daqui do github um dos usuários disse que o acesso ao backend poderia ser "opcional".
https://github.com/bacen/pix-api/issues/57

Mas eu gostaria de uma informação oficial respondendo a pergunta:

**Um QRCODE Estático pode ser gerado sem qualquer comunicação e com apenas a informação da chave pix do usuário e detalhes da compra(valor,descrição)? Preciso de um PSP, ou do ID dele para um qrcode estático?** 

Obrigado, Ricardo Andere de Mello

**Comment by renatofrota** [comment]
> Ao começar a ler a documentação eu fiquei um pouco confuso porquê no vídeo abaixo é dito que o qrcode estático também tem que utilizar um PSP e comunicar a sua geração ao sistema PIX:
> https://youtu.be/6Tor9r6F9kM?t=395

No ponto específico do vídeo que você marcou, o gráfico apresentado diz respeito à como um PSP lida com a solicitação de geração de QR Code estático por parte de um cliente (usando o aplicativo do PSP). Para simplificar, PSP nesse contexto é o "Banco onde o cliente tem conta".

> **Um QRCODE Estático pode ser gerado sem qualquer comunicação e com apenas a informação da chave pix do usuário e detalhes da compra(valor,descrição)?

Pode. Ler [aqui](https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos) (botão "Regulamentação relacionada ao Pix" > Manual de Padrões para Iniciação do Pix).

> Preciso de um PSP, ou do ID dele para um qrcode estático?**

Precisa de um PSP porque é num PSP que o Pix (o dinheiro) será recebido. Mas é a Chave PIX vinculada no QR Code estático que determina o recebedor, não importa em qual PSP aquela Chave PIX esteja vinculada no momento do recebimento.

**Comment by quilombodigital** [comment]
Ok, muito obrigado pela resposta.

Creio que minha confusão se deu pelo fato que achei que a chave PIX seria uma chave única, independente de PSP, o que permitiria que somente o seu uso no qrcode fosse necessário para gerar um qrcode válido.

Pela sua resposta compreendi que a chave é na verdade a tupla {psp id, chavepix}

Ainda assim supondo que eu tenha o id dos PSPs, num exemplo fictício, o id do nubank seria 012. Eu poderia gerar apontar para uma chave pix minha do nubank, gerar esse qrcode estático e disponibilizar, ou o qrcode necessariamente também tem que ser gerado pelo PSP?

Eu poderia manter uma lista de Ids de PSPs para isso? Imagino que seja pública, correto?

Obrigado pela atenção.

**Comment by renatofrota** [comment]
> Ok, muito obrigado pela resposta.
> 
> Creio que minha confusão se deu pelo fato que achei que a chave PIX seria uma chave única, independente de PSP, o que permitiria que fosse necessário o para gerar um qrcode válido.
> 
> Pela sua resposta compreendi que a chave é na verdade a tupla {psp id, chavepix}

A Chave Pix é única e independente de PSP. Mas ela sempre estará _associada a um PSP_.

Exemplo: você abre o app do Nubank (pra citar o mesmo exemplo) e registra uma chave (CPF/CNPJ, Telefone, E-mail ou chave aleatória). A chave está vinculada ao Nubank agora mas, no futuro, você pode portá-la para outra instituição.

> Ainda assim supondo que eu tenha o id dos PSPs, num exemplo fictício, o id do nubank seria 012. Eu poderia apontar para uma chave pix minha do nubank, gerar esse qrcode estático e disponibilizar

Os PSPs não serão identificados por ID (não de forma a estarem presentes no QR Code na forma de um ID). O QR Code é agnóstico em relação a qual PSP receberá o pagamento, pois a chave vinculada ao QR Code pode estar vinculada a um PSP hoje e a outro PSP amanhã, conforme a resposta acima. O mesmo QR Code gerado hoje, servirá amanhã (mesmo que a Chave Pix constante no QR Code esteja, então, vinculada a um novo PSP).

> ou o qrcode necessariamente também tem que ser gerado pelo PSP?

Ele pode ser gerado pelo PSP (como no vídeo que você indicou) ou por você mesmo, seguindo o manual de iniciação que eu passei na resposta anterior. Em outras palavras, a Chave Pix é vinculada ao recebedor efetivo dos Pix enviados para ela (seja digitando a chave manualmente ou pela leitura de um QR Code estático que a indique como recebedora) mas é __móvel__ entre diferentes PSP.

> Eu poderia manter uma lista de Ids de PSPs para isso? Imagino que seja pública, correto?

Não tem nenhuma necessidade de manter lista de PSPs ou seus IDs, vide as respostas acima.

> Obrigado pela atenção.

Disponha.

**Comment by quilombodigital** [comment]
Muito obrigado pela atenção. você sanou com clareza as minhas dúvidas.
