### ISSUE TITLE
Dúvida no DICT - O que acontece com uma chave após o cancelamento de um reivindicação confirmada

### ISSUE THREAD

**Issue by erickrmattos** [bacen/pix-perguntas-e-respostas#395]
**Descreva sua dúvida ou problema**
Estamos com dúvida relacionada ao seguinte cenário:

1. O usuário 1 cadastra uma chave na PSP 1;
2. O usuário 2 tenta registrar a mesma chave na PSP 2;
3. Um reivindicação de posse é gerada pelo PSP 2, sendo o PSP 1 o doador;
4. Após 7 dias, sem ter uma resposta do usuário 1, o PSP 1 confirma a reivindicação com reason `DEFAULT_OPERATION` ( a chave é deletada da PSP 1 e tem o status mudado no DICT automaticamente após a confirmação);
5. No oitavo dia, o usuário 1 cancela a reivindicação com reason `FRAUD` querendo manter a chave. A reivindicação se encerra aqui.

No [manual](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/X_ManualOperacionaldoDICT-versao1-1.pdf) página 36 é informado:

> Usuário pode validar a posse da chave em até sete dias. Caso a chave tenha sido validada, o processo é finalizado para ele. Como a chave já terá sido excluída da base interna e do DICT, o usuário que registrou a chave originalmente deve registrar novamente sua chave, se assim desejar.

Nossa duvida: o que acontece com a chave razão da reivindicação? Ela é reativada ou uma nova é gerada no DICT? Isso é importante, porque as nova chave teria um novo CID e precisamos saber se utilizamos o antigo ou um novo para o processo de reconciliação. 

Obrigado!

**Sistema ou Área**
DICT

**Comment by CharlesMendes** [comment]
Após o 7 dia a chave é excluída, e caso no 8 dia o usuário 1 valide a posse, a Reivindicação é cancelada e a chave fica livre para ser cadastrada por qualquer usuario e qualquer PSP

Logo, nao usara mesmo CID

**Comment by erickrmattos** [comment]
Obrigado Charles
