### ISSUE TITLE
[Problema] no [arq] - camt.052 está vindo sempre vazio independente da data e horário

### ISSUE THREAD

**Issue by GabrielSouzasbl** [bacen/pix-perguntas-e-respostas#396]
sempre que solicito uma camt.052 a partir da camt.060 o resultado é um arquivo vazio: #388 

última solicitação: C3187429BAA97F399DF35AB00B44D76AE5F392EAD94EC17E5A3EA8B7D330FCD2.

isso acontece para todos os testes de datas e horários.

alguns msgId das CAMT.060 consultadas.

M090893561092f88f07f11a467f66b2d
M09089356ba11fdc7d862d35da23d1a6
M0908935635f38b87f604c3d33f4e7c0
M0908935678a38c6cdaf5a519e969276
M0908935660882c5af385a067f843473

**Comment by rafael-omello** [comment]
As consultas realizadas via CAMT.060 mencionadas acima foram de faixas de data/hora em que não existia nenhum lançamento para o ISPB consultado, por isso que os arquivos retornados estão vazios.
