### ISSUE TITLE
[Dúvida] no [ICOM] - Interrupção de recebimento de mensagens

### ISSUE THREAD

**Issue by jrdevgyn** [bacen/pix-perguntas-e-respostas#397]
**Descreva sua dúvida ou problema**

Cenário: O _client_ para de receber mensagens do Bacen a partir de um tempo (indeterminado), após o _start_. O fluxo volta a funcionar normalmente quando reiniciamos o serviço.

Dúvida 01: Existe um tempo máximo recomendado para manter um fluxo(_long polling_) ?

Dúvida 02: O _client_ realiza uma requisição para obter uma mensagem e logo em seguida faz a próxima requisição para obter a próxima mensagem, mesmo que a primeira requisição citada não tenha recebido mensagens. Um intervalo precisa ser definido entre essas chamadas?

Dúvida 03: Mesmo fazendo requisições de forma frequente, precisamos definir o header keep-alive?

Dúvida 04: Dado que o serviço faz muitas requisições e que não possui intervalo definido entre elas, existe a chance do serviço ICOM estar invalidando/cancelando a conexão do _client_ por algum motivo? Se sim, algum erro é retornado? Estou suspeitando que a conexão está se perdendo aqui e por isso fica perdida no limbo (por conta da reutilização das conexões no pool).

Dúvida 05: O _client_ precisa chamar o endpont de _start_ novamente após o serviço ICOM cair/reiniciar, ou isso é transparente e nenhuma ação diferente precisa ser realizada?

Dúvida 05: Esse problema já aconteceu com outros _clients_? Se sim, estavam fazendo alguma configuração indevida?

Muito obrigado!

**Sistema ou Área**
SPI

**Comment by cristianokbc** [comment]
Dúvida 1: não existe um tempo máximo recomendado.

Dúvida 2: Isso em teoria é impossível, pois a próxima requisição em uma mesma "linha" deve usar o PullNext retornado na requisição anterior. Se forem duas threads, iniciadas por dois starts diferentes, não há problema. Talvez eu não tenha compreendido bem a pergunta.

Dúvida 3: não é preciso usar o header Keep-Alive. O HTTP 1.1 elimina essa necessidade.

Dúvida 4: Há apenas o retorno Too Many Requests caso o participante tente mais de 6 requisições simultâneas. Não existe caso de "não retorno". Dependendo de como o DNS estiver configurado (IP "velho"), a conexão pode ser reiniciada (connection reset), mas nesse caso é possível verificar pelo lado do cliente.

Dúvida 5: normalmente nenhuma ação precisa ser realizada. Contudo, se houver algum erro (algum retorno 4xx ou 5xx), recomendamos recomeçar o stream.

Não lembro de ter acontecido com outros clientes.
