### ISSUE TITLE
[Dúvida] no [SPI] - Chave de Idempotência

### ISSUE THREAD

**Issue by WagnerLau** [bacen/pix-perguntas-e-respostas#399]
**Descreva sua dúvida ou problema**
Qual(is) informações formam a chave de idempotência que o SPI vai utilizar para identificar se a requisição atual é idempotente ou não?

A requisição atual deve ser tratada como a idempotência de uma requisição anterior ou não?

**Sistema ou Área**
SPI

**Comment by rafael-omello** [comment]
Dúvidas de negócio a respeito do SPI devem ser encaminhadas para spi@bcb.gov.br.
