### ISSUE TITLE
DICT - Chaves de outros participantes disponíveis para consulta em Homologação

### ISSUE THREAD

**Issue by judahreis** [bacen/pix-perguntas-e-respostas#4]
Se algum participante quiser colocar alguns exemplos de chave dos 5 tipos (CPF, CNPJ, PHONE, EMAIL e EVP) para que outros participantes possam consultá-las, esse é o tópico. Esta tem sido uma demanda frequente.

_Lembrando que, alternativamente, todos os participantes diretos podem atuar como um participante indireto virtual (ISPB+1), a fim de facilitar a homologação de cenários que necessitam de dois participantes distintos. Por exemplo, o participante de ISPB 11223344 pode tanto enviar mensagens através do seu participante direto (ISPB 11223344) quanto com o seu participante virutal indireto (ISPB+1, ou seja 11223345)._

**Comment by CharlesMendes** [comment]
**Chaves de Acesso - Banco Original S.A.**
_ISPB: 92894922 - PSP Emissor e Recebedor_

PSP | TIPO | CHAVE
-- | -- | --
92894922 | EMAIL | mateus.dias@vivaprev.com.br
92894922 | PHONE | +5511959407120
92894922 | CPF | 74364051527
92894922 | CNPJ | 07404701495860
92894922 | PHONE | +5511976399474

**Comment by Leonardo34** [comment]
Chaves de Acesso - Banco Votorantim
_ISPB: 59588111_
PSP | TIPO | CHAVE
-- | -- | --
59588111 | CPF | 40936760205
59588111 | EMAIL | leonardo.morais@cwi.com.br
59588111 | EMAIL | leonardo.broch@cwi.com.br
59588111 | PHONE | +999438952
59588111 | CPF | 03658978091

**Comment by Leonardo34** [comment]
Pessoal, gostaria de solicitar se possível, o compartilhamento de chaves do tipo PHONE, EMAIL e EVP, para a conclusão das consultas solicitadas no roteiro de homologação do DICT. Se necessário também posso contribuir com os demais neste fórum para compartilhar mais chaves de meu pertence para testes.

**Comment by abaguiar** [comment]
Leonardo34 suas chaves foram consultadas com sucesso, até mesmo a chave telefone que esta fora do padrão.

**Comment by bermr** [comment]
Um EVP para consulta: e0397f8f-7484-4402-be55-bc5b1d46146e

**Comment by Bigua** [comment]
Olá

Chaves da Caixa

CPF/CNPJ | Nº   da agência | Nº   da conta | Tipo   de conta
-- | -- | -- | --
100.200.300-88 | 2637 | 00010000000001234567 | CACC
999.888.777-65 | 1999 | 00370000000000234168 | SLRY
200.400.600-88 | 0005 | 00130000000000001234 | SVGS
00.123.123/0001-04 | 0001 | 00030000000000239993 | CACC

Qualquer dúvida, ou para marcar testes conjuntos, meu telegram é @otalbigua

**Comment by HarrissonAzevedo** [comment]
ISPB 00000000
Banco do Brasil

**CPF:** 
948.896.080-95
001.387.678-31
 826.061.498-74

**Email**
emailteste4@bbmail.com
emailteste@bbmail.com
emailteste2@bbmail.com 

**Agência e Conta.**
Conta: "753920"
Agência:  "0551"

**Comment by abaguiar** [comment]
> Olá
> 
> Chaves da Caixa
> 
> CPF/CNPJ	Nº da agência	Nº da conta	Tipo de conta
> 100.200.300-88	2637	00010000000001234567	CACC
> 999.888.777-65	1999	00370000000000234168	SLRY
> 200.400.600-88	0005	00130000000000001234	SVGS
> 00.123.123/0001-04	0001	00030000000000239993	CACC
> Qualquer dúvida, ou para marcar testes conjuntos, meu telegram é @otalbigua



> Um EVP para consulta: e0397f8f-7484-4402-be55-bc5b1d46146e

EVP localizada com sucesso! 
![Captura de Tela 2020-06-29 às 14 38 02](https://user-images.githubusercontent.com/67381936/86037856-62ed7f00-ba16-11ea-85d6-3d098773ffb8.png)

**Comment by abaguiar** [comment]
> ISPB 00000000
> Banco do Brasil
> 
> **CPF:**
> 948.896.080-95
> 001.387.678-31
> 826.061.498-74
> 
> **Email**
> [emailteste4@bbmail.com](mailto:emailteste4@bbmail.com)
> [emailteste@bbmail.com](mailto:emailteste@bbmail.com)
> [emailteste2@bbmail.com](mailto:emailteste2@bbmail.com)
> 
> **Agência e Conta.**
> Conta: "753920"
> Agência: "0551"
> 
> Todas CACC

Todas chaves e-mail localizadas.
![Captura de Tela 2020-06-29 às 14 40 31](https://user-images.githubusercontent.com/67381936/86038540-7a793780-ba17-11ea-9036-de392497958f.png)
![Captura de Tela 2020-06-29 às 14 40 54](https://user-images.githubusercontent.com/67381936/86038544-7cdb9180-ba17-11ea-9855-46574bf20851.png)
![Captura de Tela 2020-06-29 às 14 41 11](https://user-images.githubusercontent.com/67381936/86038552-7fd68200-ba17-11ea-8ab6-72ff6487950a.png)

**Comment by abaguiar** [comment]
> 826.061.498-74

2 CPFs localizados, 1 não

<img width="622" alt="Captura de Tela 2020-06-30 às 11 46 25" src="https://user-images.githubusercontent.com/67381936/86141030-f2069f80-bac7-11ea-8505-361be0a18260.png">
<img width="622" alt="Captura de Tela 2020-06-30 às 11 48 51" src="https://user-images.githubusercontent.com/67381936/86141037-f468f980-bac7-11ea-89cb-c23eead4e04b.png">
<img width="622" alt="Captura de Tela 2020-06-30 às 11 50 37" src="https://user-images.githubusercontent.com/67381936/86141201-2712f200-bac8-11ea-8fd4-d1e0d2e3102d.png">

**Comment by abaguiar** [comment]
> 00.123.123/0001-04

Todas chaves localizadas!
<img width="622" alt="Captura de Tela 2020-06-30 às 11 52 43" src="https://user-images.githubusercontent.com/67381936/86141599-9e488600-bac8-11ea-8340-8f83abc49071.png">
<img width="622" alt="Captura de Tela 2020-06-30 às 11 53 02" src="https://user-images.githubusercontent.com/67381936/86141603-a0124980-bac8-11ea-8aef-628308fc00aa.png">
<img width="622" alt="Captura de Tela 2020-06-30 às 11 53 22" src="https://user-images.githubusercontent.com/67381936/86141608-a0aae000-bac8-11ea-8e5c-8c2900c748ab.png">
<img width="622" alt="Captura de Tela 2020-06-30 às 11 53 43" src="https://user-images.githubusercontent.com/67381936/86141611-a1437680-bac8-11ea-8a61-59d2d8f86c4f.png">

**Comment by abaguiar** [comment]
> Se algum participante quiser colocar alguns exemplos de chave dos 5 tipos (CPF, CNPJ, PHONE, EMAIL e EVP) para que outros participantes possam consultá-las, esse é o tópico. Esta tem sido uma demanda frequente.
> 
> _Lembrando que, alternativamente, todos os participantes diretos podem atuar como um participante indireto virtual (ISPB+1), a fim de facilitar a homologação de cenários que necessitam de dois participantes distintos. Por exemplo, o participante de ISPB 11223344 pode tanto enviar mensagens através do seu participante direto (ISPB 11223344) quanto com o seu participante virutal indireto (ISPB+1, ou seja 11223345)._

Chaves para consulta:


INTER | CNPJ | 77077000177
INTER | CPF CC | 01474894688
INTER | CPF CS | 01474894689
INTER | EVP | a0026c84-0b0e-44a1-9afe-5c842303b54f
INTER | email | chaveemailtpix@bancointer.com.br
INTER | telefone | +553130033070

**Comment by simonevirgilio** [comment]
Chaves Banco BS2

CPF: 425.625.836-12
CNPJ: 68.507.323/0001-00
E-mail: clientepix@bs2.com
Telefone: +5531991878666
EVP: afd86cb1-2fa8-45e3-b2ee-648ae5eba081
