### ISSUE TITLE
[Dúvida] no [DICT] - Chamar serviço de arquivo CID fora da grade

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#40]
**Descreva sua dúvida ou problema**

Tenho algumas dúvidas referente a disponibilização do serviço de arquivos de CID.

1 - A geração do arquivo de CID está classificado como categoria D na grade de disponibilização. A categoria D não tem janela de manutenção, correto?

2 - Se chamarmos o serviço POST /cids/files/ fora do horário de disponibilização, será retornado um erro ou o DICT aceita a solicitação, mas o arquivo só será disponibilizado dentro da grade de horário?

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
Monise, em homologação o arquivo é gerado e disponível a qualquer momento. Em produção ainda não há definição sobre o tema (se vai dar erro, ou se aceita e disponibiliza depois).
