### ISSUE TITLE
[Problema] no [DICT] - Problema ao consultar lista de relatos

### ISSUE THREAD

**Issue by fCamargosRibeiro** [bacen/pix-perguntas-e-respostas#401]
**Descreva sua dúvida ou problema**
Ao fazer o processo de polling dos relato de infração um campo (ReportDetails) não está retornando na listagem e depois na consulta ele vem, mas isso vem causando confusão, pois gravamos no banco com o campo nulo.

**Sistema ou Área**
DICT

**Identificador do Problema**
`<CorrelationId>cb6b41c2f27a31e5c621725071f223c8</CorrelationId>
	<ResponseTime>2020-10-29T02:59:49.894Z</ResponseTime>`

**Mensagens Enviadas / Recebidas**
`<ListInfractionReportsResponse>
	<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
		<ds:SignedInfo>
			<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
			<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
			<ds:Reference URI="#key-info-id">
				<ds:Transforms>
					<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
				</ds:Transforms>
				<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
				<ds:DigestValue>pHDbsKklpORCx1ABvvlCOZIg/+2QjO90lesGqdGitbE=</ds:DigestValue>
			</ds:Reference>
			<ds:Reference URI="">
				<ds:Transforms>
					<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
					<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
				</ds:Transforms>
				<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
				<ds:DigestValue>ONypVDKnKieqJgkFrRtM+gHUmmCatQnvOJCxSt0FHwI=</ds:DigestValue>
			</ds:Reference>
		</ds:SignedInfo>
		<ds:SignatureValue>tth4awG0/6DuD/b1sP8tVQM4gV6jVTHsW2rc5hQYQeCC2kOwJzPGkl3lrALjcxkgnkK5MVX8Cs7vOSCXjueurfhTG7ePxghsUdEuUJ9P2z4feGiZZcvVvQwmR5L8RhdI6ielwAXIPHRJJ1E5Eh33mWV9sjzA37FqsV8F+dd78EngG6fLqqUbv61WfICjCe6+rcSTtZebSBI0TyjR1xVAZ02rPQNYuI08aPDxtNxhOm1hqs3qyjU9t8T8gfnTo121Y818BNlkA6hX4ziCd3enNPkVYHjZNNXVdPR2khms9z8ejYJBWf32xinHfdts+WT/PzfqGdJRcOisHFjGqSd3Nw==</ds:SignatureValue>
		<ds:KeyInfo Id="key-info-id">
			<ds:X509Data>
				<ds:X509IssuerSerial>
					<ds:X509IssuerName>CN=Autoridade Certificadora do SERPRO Final SSL, OU=Servico Federal de Processamento de Dados - SERPRO, OU=CSPB-1, O=ICP-Brasil, C=BR</ds:X509IssuerName>
					<ds:X509SerialNumber>66906355272994040667436154809</ds:X509SerialNumber>
				</ds:X509IssuerSerial>
			</ds:X509Data>
		</ds:KeyInfo>
	</ds:Signature>
	<CorrelationId>cb6b41c2f27a31e5c621725071f223c8</CorrelationId>
	<ResponseTime>2020-10-29T02:59:49.894Z</ResponseTime>
	<HasMoreElements>false</HasMoreElements>
	<InfractionReports>
		<InfractionReport>
			<TransactionId>E9270206720201023170400001496005</TransactionId>
			<InfractionType>FRAUD</InfractionType>
			<Id>6a175aa1-a38f-4503-8775-ea224151d2fb</Id>
			<Status>OPEN</Status>
			<DebitedParticipant>92702067</DebitedParticipant>
			<CreditedParticipant>01181521</CreditedParticipant>
			<ReportedBy>DEBITED_PARTICIPANT</ReportedBy>
			<CreationTime>2020-10-28T17:13:21.186Z</CreationTime>
			<LastModified>2020-10-28T17:13:21.186Z</LastModified>
		</InfractionReport>
	</InfractionReports>
</ListInfractionReportsResponse>`

**URL de conexão**
api/v1/infraction-reports/

**Dados adicionais**
Consulta realizada onde o campo é retornado: 

`<GetInfractionReportResponse>
	<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
		<ds:SignedInfo>
			<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
			<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
			<ds:Reference URI="#key-info-id">
				<ds:Transforms>
					<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
				</ds:Transforms>
				<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
				<ds:DigestValue>pHDbsKklpORCx1ABvvlCOZIg/+2QjO90lesGqdGitbE=</ds:DigestValue>
			</ds:Reference>
			<ds:Reference URI="">
				<ds:Transforms>
					<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
					<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
				</ds:Transforms>
				<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
				<ds:DigestValue>F9qx6oW8DRS/qXdNGDln38eqs+mbcqWOx85NxPXAM48=</ds:DigestValue>
			</ds:Reference>
		</ds:SignedInfo>
		<ds:SignatureValue>ZxUQSOtT/4pg+o5M6HgE03acuYBQ5erUkExmvJXPBe68vcSp5KzPUq+YgDBzvDli6sBA691yICZSO5+MNER7fnoejGVfreaMQDEn/AAg4HY6g1Bg36gr5BtMAMcPWROenSD2Tb7QU7ggUDlVvR3lnTBclb7CbmxlSjjXalvDMd0GigkB5ngaB4qDoavZrH1hgofYy6L/gNO7hm/Pb+QcWY25Nai/tkfEVjzauHL1UhZt6ZRzfNAFt1EFOIPkz9h1okapla9I12hdZtGXzEBv9GsoirxpdJ+LGDjDsY4HxyOo3t23xApmLdOBM2Y9uwhaVAPbieGevUnF9hBxnXvMxg==</ds:SignatureValue>
		<ds:KeyInfo Id="key-info-id">
			<ds:X509Data>
				<ds:X509IssuerSerial>
					<ds:X509IssuerName>CN=Autoridade Certificadora do SERPRO Final SSL, OU=Servico Federal de Processamento de Dados - SERPRO, OU=CSPB-1, O=ICP-Brasil, C=BR</ds:X509IssuerName>
					<ds:X509SerialNumber>66906355272994040667436154809</ds:X509SerialNumber>
				</ds:X509IssuerSerial>
			</ds:X509Data>
		</ds:KeyInfo>
	</ds:Signature>
	<CorrelationId>bb4a3bee0eb9d749b423f0182333e6db</CorrelationId>
	<ResponseTime>2020-10-29T12:34:08.764Z</ResponseTime>
	<InfractionReport>
		<TransactionId>E9270206720201023170400001496005</TransactionId>
		<InfractionType>FRAUD</InfractionType>
		<ReportDetails>MSG INTERNA E9293421520201028140800001496315E9293421520201028140800001496315E9293421520201028140800001496315E9293421520201028140800001496315E9293421520201028140800001496315E9293421520201028140800001496315E9293421520201028140800001496315</ReportDetails>
		<Id>6a175aa1-a38f-4503-8775-ea224151d2fb</Id>
		<Status>ACKNOWLEDGED</Status>
		<DebitedParticipant>92702067</DebitedParticipant>
		<CreditedParticipant>01181521</CreditedParticipant>
		<ReportedBy>DEBITED_PARTICIPANT</ReportedBy>
		<CreationTime>2020-10-28T17:13:21.186Z</CreationTime>
		<LastModified>2020-10-29T02:59:54.965Z</LastModified>
	</InfractionReport>
</GetInfractionReportResponse>`

**Comment by luizlaydner** [comment]
Na [listagem de relatos de infração](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API_do_DICT_v1-0-1.html#operation/listInfractionReport) há uma opção _IncludeDetails_, que controla se os campos de detalhe são retornados ou não. O valor padrão é **false**, mas você pode habilitar passando **true** .
