### ISSUE TITLE
[Dúvida] no [DICT] - Horário em 16/11, 1º dia da Operação Plena

### ISSUE THREAD

**Issue by CharlesMendes** [bacen/pix-perguntas-e-respostas#403]
**Descreva sua dúvida ou problema**
_Minha dúvida é referente apenas ao Primeiro dia de operação do DICT Operação Plena (16/11)_

Segundo a Resolução BCB n° 1 de 12/8/2020, os horário de funcionamento do DICT serão:

Art. 79. O registro, a exclusão, a alteração, a portabilidade, a reivindicação de posse, a consulta e a solicitação de devolução estão disponíveis 24 (vinte e quatro) horas por dia, em todos os dias do ano.
Art. 80. O registro, a exclusão, a alteração, a portabilidade, a reivindicação de posse e a solicitação de devolução devem estar disponíveis para os usuários finais das 8h às 20h, no horário de Brasília, em todos os dias do ano.
Parágrafo único. A critério de cada participante do Pix, as funcionalidades discriminadas no caput podem ser ofertadas aos usuários finais nos demais horários em que elas estejam disponíveis no DICT.

**Sistema ou Área**
DICT

**Identificador do Problema**
N/A

**Mensagens Enviadas / Recebidas**
N/A

**URL de conexão**
N/A

**Dados adicionais**
Como o SPI irá iniciar as 9h do dia 16/11, o DICT deve iniciar as 8h do dia 16/11?

A seguinte tabela abaixo, para o DICT, está correta? 
(considerando período mínimo obrigatório de operação)

**1º Fase) Operação Restrita do DICT – (5/10 a 2/11)**
Funcionalidades: registros/exclusão/portabilidade/reivindicações
Período: 5/10 a 2/11
- 9h às 18h
- Excetuados os finais de semana e feriados
	
**2º Fase) Operação Restrita do DICT – (3/11 a 15/11)**
Funcionalidades: registros/exclusão/portabilidade/reivindicações
Período: 3/11 a 15/11
Segue horário do SPI Operação Restrita
- 9h às 22h
- Excetuados os quinta pra sexta (9h da quinta as 22h da sexta), dias 5/6 novembro e 12/13 novembro

**3º Fase) Operação Plena do DICT – (16/11 em diante)**
Funcionalidades: registros/exclusão/portabilidade/reivindicações
Período: 16/11 em diante
- 8h às 20h
- Todos os dias, incluindo finais de semana e feriados

**Comment by carloschioquetta** [comment]
No dia 16/11, o DICT somente abrirá às 9 horas (IN 9). Logo, somente nesse dia, as funcionalidades estarão disponíveis a partir desse horário. A partir do dia 17/11, começa às 8 horas.

**Comment by franciscotfmc** [comment]
Dúvida: se o PSP quiser, ele pode manter registro, exclusão, portabilidade e reivindicação 24/7 a partir do 17/11, ou somente de 8h às 20h?

**Comment by luizlaydner** [comment]
@franciscotfmc 

Art. 80. O registro, a exclusão, a alteração, a portabilidade, a reivindicação de posse e a solicitação de devolução devem estar disponíveis para os usuários finais das 8h às 20h, no horário de Brasília, em todos os dias do ano.
Parágrafo único. A critério de cada participante do Pix, as funcionalidades discriminadas no caput podem ser ofertadas aos usuários finais nos demais horários em que elas estejam disponíveis no DICT.
