### ISSUE TITLE
[Dúvida| no [DICT] - Relato de Infração de FRAUD e AML_CTF para mesma transação

### ISSUE THREAD

**Issue by rodolfocasusa** [bacen/pix-perguntas-e-respostas#404]
Descreva de forma clara e curta a dúvida ou problema.
Ao tentar abrir um relato de infração do tipo FRAUD e AML_CTF para mesma transação, o DICT informa que já existe um relato de infração para a transação informada. 

A dúvida é, não é permitido que as equipes de Prevenção à Fraude e Prevenção à Lavagem de Dinheiro abram uma infração para a mesma transação?

**Sistema ou Área**
DICT

**Identificador do Problema**
N/A

**Mensagens Enviadas / Recebidas**
N/A

**URL de conexão**
N/A

**Dados adicionais**
N/A

**Comment by luizlaydner** [comment]
> A dúvida é, não é permitido que as equipes de Prevenção à Fraude e Prevenção à Lavagem de Dinheiro abram uma infração para a mesma transação?

Atualmente não é permitido. Mas se você puder compartilhar um cenário em que isso faz sentido (envie para dict@bcb.gov.br), podemos avaliar mudar essa validação.
