### ISSUE TITLE
[Problema] no [DICT] - Erro ao realizar operações com Participante Indireto

### ISSUE THREAD

**Issue by JeanFabichaki** [bacen/pix-perguntas-e-respostas#407]
Estamos recebendo o erro **Participant is not an indirect participant of the submitter** para operações que estavam funcionando normalmente. Foi realizada alguma alteração nos cadastros de participantes diretos/indiretos no ambiente de Homologação?

**Sistema ou Área**
DICT

**Identificador do Problema**
1e2940807c4b5a4de7de67c2e2f00974

**Mensagens Enviadas / Recebidas**
<problem xmlns="urn:ietf:rfc:7807"><type>https://dict.pi.rsfn.net.br/api/v1/error/Forbidden</type><title>Forbidden</title><status>403</status><detail>Participant is not an indirect participant of the submitter</detail><correlationId>1e2940807c4b5a4de7de67c2e2f00974</correlationId></problem>

**URL de conexão**
https://dict-h.pi.rsfn.net.br:16522/api/v1/entries

**Comment by luizlaydner** [comment]
Poderia informar ispb dos participantes de homologação ?

**Comment by JeanFabichaki** [comment]
Resolvido, foi enviado a REDA novamente. Obrigado.
