### ISSUE TITLE
[Dúvida|Problema] no [ICOM] - caracter inválido

### ISSUE THREAD

**Issue by paulaselihevic12** [bacen/pix-perguntas-e-respostas#409]
**ATENÇÃO:** Não crie issue para questões relativas ao ambiente de produção !

**Descreva sua dúvida ou problema**
Olá! gostaria de tirar uma dúvida, por gentileza, de quais caracteres (qual padrão) deveriamos aceitar no campo de mensagem (informacoesEntreUsuarios - Unstructured <Ustrd>) da pac008.
Tivemos alguns erros, seguem dois textos que foram rejeitados pela admin02 por caracter inválido:
- 1234567890@#$_&-+()/*“‘:;!?~`|•√π÷×¶∆}{=°^¥€¢¢%©®™✓[]
- 11382&;&(!;&@/&/!23$![£|£€|+€]€}~+|¥’b

**Sistema ou Área**
ICOM

**Identificador do Problema**
ISPB 18236120

**Comment by cristianokbc** [comment]
@paulaselihevic12, os caracteres válidos são documentados no[ Catálogo de Serviços do SFN, Volume VI](https://www.bcb.gov.br/content/estabilidadefinanceira/cedsfn/Catalogos/Catalogo_de_Servicos_do_SFN_Volume_VI_Versao_501.pdf), seção "Codificação das Mensagens".
