### ISSUE TITLE
[Dúvida] no [DICT] - Consequências para uma conta com infração

### ISSUE THREAD

**Issue by diogotechera** [bacen/pix-perguntas-e-respostas#411]
**Descreva sua dúvida ou problema**
Existe alguma consequência para uma conta que tiver uma transação notificada como Infração? 
(Ela é bloqueada? Entra em uma lista de Risco etc?)

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
A consequência é que o contador de [dados anti-fraude](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API_do_DICT_v1-0-1.html#operation/getEntry) é incrementado. 
Os dados anti-fraude devem ser usados na avaliação de risco de uma transação pelo participante do pagador.
Uma possibilidade também facultada ao participante onde a chave está domiciliada é [remover o vínculo](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API_do_DICT_v1-0-1.html#operation/deleteEntry) por fraude.
