### ISSUE TITLE
[Dúvida|Problema] no [DICT] - RequestId necessário para o cálculo do CID após uma reivindicação

### ISSUE THREAD

**Issue by CaioMarsiglia** [bacen/pix-perguntas-e-respostas#413]
**Descreva sua dúvida ou problema**

1) Usuário cria a chave no banco X;
2) Eu, no banco Y, tento criar a chave e retorna EKCDP (por exemplo);
3) Eu abro o processo de reivindicação no banco Y;
4) O usuário aprova no banco X;
5) Eu recebo no banco Y a confirmação e completo o processo de reivindicação.
6) Quando completo, o banco Y vai atualizar a dict local com o status EC da chave e precisa calcular o CID dessa chave. Entretanto, o requestId (que é um UUID gerado na criação da chave, no caso gerado no banco X) não é retornado em nenhuma rota. Ou seja, eu não consigo calcular o CID dessa chave sem esse valor. Consequência, CID errado, base descasada. (quando vamos fazer o processo de reconciliação)

**Sistema ou Área**
DICT

**Identificador do Problema**
Não se aplica

**Mensagens Enviadas / Recebidas**
Não se aplica

**URL de conexão**
Não se aplica

**Dados adicionais**
é possível retornar esse valor em alguma rota? A rota de getEntryByCid não é válida nesse cenário, visto que não temos o CID ainda criado para verificar o requestId da chave.

**Comment by luizlaydner** [comment]
O `RequestId` passado na operação de [concluir reivindicação/portabilidade](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API_do_DICT_v1-0-1.html#operation/completeClaim) é gerado pelo participante reivindicador (banco Y, no seu exemplo) e não pelo doador (banco X, no seu exemplo).

A operação de concluir reivindicação tem como conseqüência criar um novo vínculo, que fica então associado ao requestId passado na requisição.
