### ISSUE TITLE
Header - Requisição de GET

### ISSUE THREAD

**Issue by eduardomohr** [bacen/pix-perguntas-e-respostas#417]
O header  “Cache-Control”  é adicionado em outras requisições de GET no DICT porém somente no Long pooling  (exemplo: "GET /api/v1/out/123456/stream/start") nós recebemos um erro no retorno com a descrição que "um dos cabeçalhos enviados não era esperado". 

O nosso DataPower por padrão adiciona o header “Cache-Control” para operações de GET e estamos buscando uma solução para remover do header porém a ferramenta não esta permitindo remover.

Poderia por favor informar porque o mesmo erro não ocorre em todos os GET do Bacen ?

**Comment by cristianokbc** [comment]
Conforme documentado no Manual das Interfaces de Comunicação, há uma lista de cabeçalhos válidos para a interface ICOM. O Cache-Control não é aceito, por ora.

Temos a intenção de incluir como cabeçalho válido nesta semana.

**Comment by eduardomohr** [comment]
Obrigado pelo retorno e atualização na API.
