### ISSUE TITLE
[Dúvida] no [SPI] - Envio Pix Participante Indireto

### ISSUE THREAD

**Issue by simonevirgilio** [bacen/pix-perguntas-e-respostas#420]
Estamos com um caso em ambiente de homologação,onde um Participante Indireto esta conseguindo enviar Pix pera ele mesmo. Existe algum impeditivo?

Sei que indiretos com o mesmo liquidante não pode transacionar mensagens no Pix. Mas não localizei na documentação, sobre envio e recebimento com mesmo ISPB.

**Sistema ou Área**
SPI

**Comment by rafael-omello** [comment]
Favor enviar exemplos de MsgId ou EndToEndIds em que o caso reportado está ocorrendo.  Não entendi a segunda questão, pode tentar explicar em mais detalhes?
