### ISSUE TITLE
Dúvida no SPI & ICOM - Pagamento retorna timeout, recebedor recebe pagamento

### ISSUE THREAD

**Issue by FelipeSantosAvCode** [bacen/pix-perguntas-e-respostas#426]
**Descreva sua dúvida ou problema**
Ola,

Tenho uma duvida em nível de negocio. Por gentileza, me corrijam se estiver com o entendimento errado.

Em um cenário aonde o PSP realiza um pagamento, o PSP recebedor recebe este pagamento, mas não envia a PACS de resposta, fazendo com que o PSP pagador receba um timeout.

Sendo assim, o PSP recebedor recebendo um credito, mas com o negativo do Bacen, o PSP pagador realiza um "desfazimento", não realizando o debito na conta, possivelmente criando uma diferença de valores na conta PI.

Como ocorre os créditos e débitos neste cenário, como ficaria o saldo da conta PI de cada PSP?

**Comment by cristianokbc** [comment]
@FelipeSantosAvCode, esse cenário não é possível.

Quando o pagador envia a pacs.008, o SPI envia uma pacs.008 para o recebedor que deve responder com uma pacs.002. Só após a pacs.002 recebida pelo Bacen é que o SPI faz a liquidação e envia pacs.002 para o recebedor e o pagador.

Caso o recebedor não responda a primeira pacs.008, ocorre o timeout. Nesse cenário, o Bacen envia pacs.002 aos dois participantes informando o timeout.
