### ISSUE TITLE
[Dúvida] - Onde obter o media kit do Pix?

### ISSUE THREAD

**Issue by renatofrota** [bacen/pix-perguntas-e-respostas#427]
Na [página do Pix](https://www.bcb.gov.br/estabilidadefinanceira/pix) está disponível um manual de uso da marca que estabelece como a marca pode ser utilizada, inclusive regras bastante específicas quanto ao _placement_ do logo e do ícone. Porém, não encontrei onde baixá-los.

**Comment by ninrod** [comment]
@renatofrota , boa tarde. 

os arquivos estão disponíveis em https://www.bcb.gov.br/estabilidadefinanceira/participantespix

**Comment by renatofrota** [comment]
Obrigado!
