### ISSUE TITLE
[Problema] no [DICT] - Mudança no comportamento do endpoint de Listar Reivindicações

### ISSUE THREAD

**Issue by JeanFabichaki** [bacen/pix-perguntas-e-respostas#432]
**Descreva sua dúvida ou problema**
Foram feitas modificações na API de Listar Reivindicações? 
Percebemos que nossa rotina interna está com comportamentos estranhos. E fazendo alguns testes percebemos que o parâmetro isDonor e isClaimer em alguns cenários são obrigatórios.
A API também está aceitando o parâmetro **includeIndirectParticipants** que não está na documentação somente foi discutido aqui https://github.com/bacen/pix-dict-api/issues/12 

**Sistema ou Área**
DICT

**URL de conexão**
https://dict-h.pi.rsfn.net.br:16522/api/v1/claims/

**Comment by luizlaydner** [comment]
@JeanFabichaki estamos olhando aqui. Não deveria ter alterado comportamento.

**Comment by luizlaydner** [comment]
@JeanFabichaki  a adição do parâmetro `includeIndirectParticipants` não quebra compatibilidade da API e pode ser adicionada em homologação sem aviso prévio.

**Comment by JeanFabichaki** [comment]
Entendido @luizlaydner, mas em algumas listagem os dados só são retornado informando o isDonor=true  sendo que o único parâmetro que deveria ser obrigatório é participant.

**Comment by luizlaydner** [comment]
@JeanFabichaki identificamos aqui o problema. Vamos corrigir e publicar em breve.
Obrigado pelo relato!

**Comment by JeanFabichaki** [comment]
@luizlaydner Beleza, obrigado pelo retorno rápido.

**Comment by HenriqueSimoes82** [comment]
Prezado @JeanFabichaki, problema corrigido. Obrigado pelo relato.

**Comment by JeanFabichaki** [comment]
@HenriqueSimoes82 e @luizlaydner estamos recebendo o seguinte erro:

![image](https://user-images.githubusercontent.com/1520459/99853443-b7c69900-2b61-11eb-93b4-c0fd49205b3c.png)
 
A alteração foi publicada novamente no ambiente?

**Comment by luizlaydner** [comment]
@JeanFabichaki a última versão do [manual operacional do DICT](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/X_ManualOperacionaldoDICT-versao2-1.pdf), conforme divulgado pelo informe pix de 13/11, incluiu uma seção sobre limitação de requisições. Nessa seção há uma tabela que contém os limites associados a cada _endpoint_ do DICT. O erro da requisição que você reportou acima é porque excedeu o limite de requisições para o endpoint de listClaims. Em homologação, a alteração que implementa as políticas de _rate-limit_ foi publicada e as políticas estão habilitadas conforme a tabela mencionada. 

Nós vamos ainda atualizar a especificação da API do DICT para incluir os detalhes disso.

Para produção, pretendemos publicar essa alteração em breve. A limitação de requisições é muito importante para estabilidade do sistema. Em produção, habilitaremos as políticas de limitação de forma gradual, controlada e monitorada, a fim de evitar impactos maiores para os participantes.
