### ISSUE TITLE
[Dúvida] no [SPI] - Associação entre mensagens PBR

### ISSUE THREAD

**Issue by RogerNeris** [bacen/pix-perguntas-e-respostas#433]
**Descreva sua dúvida ou problema**
Como podemos associar mensagens PBR001 e PBR002 ? 
Verificamos nos ambientes de homologação/produção que as tags MsgId e BizMsgIdr são totalmente diferentes para mensagens que deveriam ser associadas.

**Sistema ou Área**
SPI

**Comment by cristianokbc** [comment]
A associação pode ser feita com o campo Data. O `<OrgnlData>` da pibr.002 é sempre igual ao `<Data>` da pibr.001.

Basta então preencher o `<Data>` com um valor único.
