### ISSUE TITLE
[Dúvida] no [DICT] - Publicação da nova versão em homologação.

### ISSUE THREAD

**Issue by gabrielmendesbb** [bacen/pix-perguntas-e-respostas#44]
Já tem previsão de quando a versão v1.0.0-RC4 estará disponível em HOMOLOGAÇÃO ?

**Comment by judahreis** [comment]
Foi publicada na sexta-feira, dia 03.

**Comment by luizlaydner** [comment]
@gabrielmendesbb 
Você pode checar o acesso às 2 versões atualmente disponíveis em :
https://dict-h.pi.rsfn.net.br/api/v1-rc3/spec.html 
https://dict-h.pi.rsfn.net.br/api/v1-rc4/spec.html

**Comment by gabrielmendesbb** [comment]
No site do bacen não consta a ultima versão da API.
https://www.bcb.gov.br/estabilidadefinanceira/forumpagamentosinstantaneos
Vão publicar lá?
