### ISSUE TITLE
[Dúvida] no [SPI] - Mecanismo de retry quando PSP não recebe PACS.002

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#442]
**Descreva sua dúvida ou problema**

Olá! Com relação ao mecanismo de retry previsto quando o PSP não recebe o retorno da PACS.002 e o PSP tem que enviar novamente a PACS.008, deve ser enviado o **mesmo** _AcceptanceDateTime <AccptncDtTm>_ da mensagem **original**? e o _MessageIdentification <MsgId>_ deve ser o **mesmo** também? 

**Sistema ou Área**
SPI

**Comment by rafael-omello** [comment]
Deverá ser enviada com o mesmo AcceptanceDateTime da mensagem original mas o MessageIdentification pode ser diferente. É importante frisar que quando o participante envia a PACS.008 e recebe uma resposta HTTP 201, o participante receberá uma resposta PACS.002 ou ADMI.002 relativa a mensagem previamente enviada. Não há necessidade de reenvio nesse caso.

**Comment by jgslima** [comment]
@rafael-omello obrigado.

Achamos importante esclarecer.

No antigo documento "Especificações técnicas e de negócio do ecossistema de pagamentos instantâneos brasileiro", havia uma seção chamada "_Resolução de pagamento não respondido_", que continha por exemplo a sub-seção "_REENVIO DO ESTÍMULO PELO PSP DO PAGADOR_", que dizia:

"`Nesta seção é apresentado o fluxo a partir do qual o PSP do pagador, que seja participante direto do SPI, reenvia a mensagem de pagamento, previamente encaminhada (etapa #4 do fluxo 1.1.1), para a qual não obteve resposta do SPI até o tempo máximo definido para caracterização de timeout.`"

O atual documento "Manual de Fluxos do Processo de Efetivação do Pix" realmente não contém seção relativa ao reenvio de mensagens.

Portanto, para confirmar. Uma vez que o PSP tenha enviado uma pacs.008 ou uma pacs.004 para o SPI e tendo recebido 201 com um PIResourceID, não é mais mesmo necessário reenviar a pacs.008 ou pacs.004?

Obrigado
