### ISSUE TITLE
[Dúvida] no [DICT E SPI] - Homologacao

### ISSUE THREAD

**Issue by coutor** [bacen/pix-perguntas-e-respostas#445]
Há uma lista de testes com casos de uso para as homologações ao DICT e SPI?

**Comment by rafael-omello** [comment]
Dúvidas de negócio referentes ao SPI devem ser encaminhadas para spi@bcb.gov.br e dúvidas de negócios referentes ao DICT devem ser encaminhadas para dict@bcb.gov.br.
