### ISSUE TITLE
[Dúvida] no [SPI] - Multipart

### ISSUE THREAD

**Issue by coutor** [bacen/pix-perguntas-e-respostas#446]
A funcionalidade "multipart" é opcional ou mandatória?
Há uma lista de funcionalidades mandatórias de fácil acesso?

**Comment by cristianokbc** [comment]
A funcionalidade multipart não é mandatória em nenhum dos _endpoints_, mas é **muito importante** especialmente no de leitura das mensagens. Na nossa experiência, não implementá-la limita muito a taxa de transferência.

Não há uma lista de funcionalidades mandatórias mas em geral elas são precedidas pelo termo "deve", na documentação.

**Comment by coutor** [comment]
Obrigada pelo retorno.

Em relação a compressão gzip também não é mantatória, correto?

Abs,
