### ISSUE TITLE
[Dúvida] no [DICT] - Limitação de Requisições é individual para cada PSP seja direto ou indireto?

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#447]
**Descreva sua dúvida ou problema**

Olá! Com relação ao comunicado _[Comunicado aos participantes do Pix - 14/2020] Publicação de nova versão da API do DICT_

Temos a seguinte dúvida quando um PSP direto tem vários PSP indiretos: as políticas de limitação de requisições serão aplicadas de **forma individual para cada PSP** seja direto ou indireto?

Ou seja, o PSP direto tem a sua quota de requisições, o PSP Indireto 1 tem a sua quota de requisições, o PSP Indireto 2 tem a sua quota de requisições... E assim por diante.  

![image](https://user-images.githubusercontent.com/5355541/101059720-593fe880-356d-11eb-878f-9a2ffc8665d8.png)

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
> as políticas de limitação de requisições serão aplicadas de forma individual para cada PSP seja direto ou indireto?

Exato. As políticas são aplicadas a cada participante (ISPB), independe se participante direto ou indireto.

**Comment by monise** [comment]
@luizlaydner obrigada pelo retorno! Só para confirmar, no cenário em que o certificado usado na comunicação seja do direto, mas as requisições são feitas pelo indireto, usando o ISPB do indireto, o indireto terá seus limites de requisições independente dos limites do direto, correto?

**Comment by luizlaydner** [comment]
Os limites são controlados de forma individual para cada participante, não importa se direto ou indireto. Os limites de um participante direto **não são compartilhados** entre os indiretos dele.

**Comment by luizlaydner** [comment]
Exemplificando, na operação de [consultar vínculo](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API%20do%20DICT%20-%20v1.1.0.html#operation/getEntry), o controle de limite de requisições é feito através do header `PI-RequestingParticipant` (pode ser um direto ou indireto).
