### ISSUE TITLE
[Dúvida] no [ANS] - Devo considerar transações com sucesso e falha?

### ISSUE THREAD

**Issue by rafaelchagasb** [bacen/pix-perguntas-e-respostas#448]
**Descreva sua dúvida ou problema**

No item 3.1.2.1 Experiência do usuário pagador do Manual de Tempos do Pix é informado que devemos apurar os tempos decorridos entre t6a – t0’.

A  dúvida é se devemos filtrar somente pelas operações ocorridas com sucesso. 

Caso as operações de falha sejam contemplatadas, como ficaria a questão dos tempos decorridos de um timeout? Esses não prejudicariam a métrica caso fossem considerados?

**Sistema ou Área**
SPI - ANS

**Comment by brenolobo** [comment]
O Manual de Tempos cita que ‘Para fins de contabilização dos ANS, todas as mensagens devem ser consideradas, inclusive aquelas de erro.’ (seção 3. Acordos de nível de serviço)
Dessa forma, todas as operações devem ser consideradas.
Importante observar que é esperado que o volume de timeout seja baixo e, por isso, o impacto nos indicadores deve ser limitado.
