### ISSUE TITLE
Dúvida no DICT - Disponibilização da RC4

### ISSUE THREAD

**Issue by Leonardo34** [bacen/pix-perguntas-e-respostas#45]
**Descreva sua dúvida ou problema**
Temos alguma data prevista para liberação da RC4 do DICT no ambiente de HML ? 

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
Foi publicada na sexta-feira, dia 03.

**Comment by luizlaydner** [comment]
@Leonardo34 , você pode checar o acesso às 2 versões atualmente disponíveis em :
https://dict-h.pi.rsfn.net.br/api/v1-rc3/spec.html
https://dict-h.pi.rsfn.net.br/api/v1-rc4/spec.html
