### ISSUE TITLE
Problema no DICT - ERRO 500 com efetivação do cadastro

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#459]
**Descreva sua dúvida ou problema**
Hoje 16/12/1010 no período da manhã tivemos um problema ao cadastrar uma chave Dict: 07649086000127 type: CNPJ, ao realizar a chamada de cadastrado às 09:34 (2020-12-16T12:34:23.245Z)UTC, recebemos a resposta 500 e ao realizar o retry(Para garantir a idempotência da operação) também recebemos o retorno 500 da API Bacen, por este motivo a key não foi cadastrada no banco de dados local da instituição para garantir a consistência e sincronismo do sistema.

Porem ao verificar agora, o DICT Bacen realizou o cadastro da chave mesmo retornando erro 500 nas chamadas, gostaríamos de saber o motivo do problema reportado e como devemos proceder.

**Sistema ou Área**
DICT

**Mensagens Enviadas / Recebidas**
XML Envio:
```
<CreateEntryRequest><Entry><Key>07649086000127</Key><KeyType>CNPJ</KeyType><Account><Participant>31895683</Participant><Branch>0001</Branch><AccountNumber>0010001354</AccountNumber><AccountType>CACC</AccountType><OpeningDate>2005-11-18T00:00:00Z</OpeningDate></Account><Owner><Type>LEGAL_PERSON</Type><TaxIdNumber>07649086000127</TaxIdNumber><Name>INDUSTRIAL DO BRASIL ADM CREDITOS</Name></Owner></Entry><Reason>USER_REQUESTED</Reason><RequestId>39d97165-b1de-43e8-987e-5521ce110124</RequestId></CreateEntryRequest>

```
Responde Bacen:
`<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1></body></html>`

**URL de conexão**
https://dict-h.pi.rsfn.net.br:16522/api/v1/entries/

**Comment by andersonsaalves** [comment]
Problema corrigido e ambiente atualizado.

**Comment by evertongodoi** [comment]
@andersonsaalves obrigado.
