### ISSUE TITLE
[Problema] no [SPI] - Troca de certificados do Bacen

### ISSUE THREAD

**Issue by rsabin** [bacen/pix-perguntas-e-respostas#466]
**Descreva sua dúvida ou problema**
Hoje em torno das 10h25 o Bacen trocou os seus certificados, durante o processo a comunicação parou completamente. 
**É um problema e dúvida ao mesmo tempo, se isso acontecerá igual em produção.**

**Sistema ou Área**
DICT, SPI, INFRA

**Identificador do Problema**
Das **10h25 até 10h26** não conseguimos comunicação com o Bacen. Nosso get longpooling estava recebendo `Connection Reset`. 
Das **10h33 até 10h34** o longpooling retornou erro `503`. Xml de saída está abaixo.

**Mensagens Enviadas / Recebidas**
Mensagem recebida com o erro 503:
`<?xml version="1.0" encoding="UTF-8"?><problem xmlns="urn:ietf:rfc:7807"><type>https://icom.pi.rsfn.net.br/api/v1/error/serviceUnavailable</type><title>IP de destino não disponivel para este servico no momento. Confira se a resolução de DNS respeita o TTL.</title></problem>`

**URL de conexão**
https://icom-h.pi.rsfn.net.br:16522/api/v1/out/92702067/stream/start

**Dados adicionais**
Não houve teste de envio de Pix nesse horário, mas a princípio o erro seria o mesmo para ambos os casos.

Agradeço e aguardo retorno.

**Comment by cristianokbc** [comment]
@rsabin, a troca dos certificados de canal ocorreu aproximadamente às 11h13. Para os participantes, ela tem efeito apenas em novas conexões. Não houve mudança que deveria afetar a comunicação.

Contudo, durante a troca realizamos testes para garantir que os participantes entendessem os novos certificados de todos os sites em que a ICOM roda. Por isso ocorreu o 503. Durante a desativação de um local, ele pode causar connection reset ou 503 para forçar o participante a fechar a conexão e fazer uma nova consulta ao DNS. No processo, o DNS ainda pode responder com o IP antigo por poucos segundos (menos do que o timeout de uma transação). Nos testes, esse tempo foi de cerca de 10 segundos.

Esse comportamento é mais comum no endpoint de leitura de mensagens mas comportamento semelhante pode ocorrer nos demais em situações excepcionais.

Em produção isso também pode ocorrer. Esperamos que sempre com períodos curtos.

É importante sempre se atentar ao TTL do DNS, que hoje é zero.

**Comment by rsabin** [comment]
Olá @cristianokbc, poderia complementar a resposta com a seguinte situação:
Quando ocorrem essas "trocas" de site, as conexões abertas no site anterior retornam imediatamente Connection Reset?
Pergunto porque eventualmente recebemos esse erro, o qual conseguimos contornar normalmente, porém tem gerado alertas em nossas ferramentas de monitoração. 
A questão é exatamente se essa é uma ocorrência normal.
