### ISSUE TITLE
[Dúvida] no [SPI] - Timeout nas requisições

### ISSUE THREAD

**Issue by wallace-brito** [bacen/pix-perguntas-e-respostas#468]
**Descreva sua dúvida ou problema**
Gostaria de saber opinião de vocês, se é recomendado utilizar algum timeout nas requisições para o SPI.

Pensando no cenário:
O PSP recebe uma PACS.008, no momento do envio da PACS.002 essa requisição demore 60 segundos.
Em decorrência dessa demora do envio da PACS.002, resultará no timeout desse PIX.

Uma forma que pensei para contornar esse problema, seria de estabelecer um timeout de 5 segundos.
E caso ultrapasse os 5s, realizar a nova requisição.

**Sistema ou Área**
SPI

**Comment by cristianokbc** [comment]
@wallace-brito, não vejo problemas em fazer algo assim. É preciso tomar algum cuidado com esse tempo, apenas. Outro cuidado é no limite da quantidade tentativas de envio.
