### ISSUE TITLE
[Dúvida] no [QR Code] - EMV QR Code estático - Campo 60 "Merchant City"

### ISSUE THREAD

**Issue by gstabel** [bacen/pix-perguntas-e-respostas#47]
Boa tarde.
Na documentação "Anexo I –Padrões para Iniciação do PIX" página 10 define o campo ID 60 "Merchant City", tamanho de 15 caracteres.

Não identificamos nenhum caso de uso que utilize essa informação, nem nos exemplos de requisitos de interface.
Esse campo deve conter informação de qual cidade? Qual o objetivo e uso esperado deste informação?

Desde já grato.
Gabriel C. Stabel

**Sistema ou Área**
QR Code

**Comment by ninrod** [comment]
Boa tarde. É um campo definido pelo padrão EMV. Consta apenas no QR Code gerado pela automação.

A automação está livre para colocar nesse campo uma informação que faça sentido. Por exemplo,  a cidade em que a empresa do usúario recebedor (o "merchant) está sediada.
