### ISSUE TITLE
[Dúvida|Problema] no [SISTEMA] - Chave de endereçamento - Celular

### ISSUE THREAD

**Issue by PamelaFabiao** [bacen/pix-perguntas-e-respostas#48]
Na chave de celular teremos o prefixo do país (+55), porém esse prefixo deve ser fixo ou teremos que permitir a inclusão de chave de celular de outro país?

**Comment by judahreis** [comment]
@PamelaFabiao, o DICT verifica somente se o padrão está de acordo com o padrão ISO (^\+[1-9][0-9]\d{1,14}$). Isso significa que números de outros países também são aceitos. Contudo, vale lembrar que o PSP tem total responsabilidade sobre o dado e que, se fez a inclusão, é porque fez a validação de posse do celular para o número registrado, exatamente como foi registrado.
