### ISSUE TITLE
[Problema] no [DICT] - Erro no retorno da consulta de chave após atualização de nome no vínculo

### ISSUE THREAD

**Issue by wallace-brito** [bacen/pix-perguntas-e-respostas#482]
**Descreva sua dúvida ou problema**
Prezados,

Após consumir o endpoint atualização de vínculo alterando o nome, ao realizar a consulta de vínculo temos o erro com status 400 indicando que o _cid para o vínculo identificado pela chave Key(type=CPF, content=59597064073) não corresponde ao valor esperado._  (detalhes abaixo)

Gostaria de entender o retorno desse erro, já que a atualização de vínculo retornou sucesso.
Grato.

**Sistema ou Área**
DICT

**Identificador do Problema**
Correlation-Id: e986fde4eef27aae453c467712a19116, b1f485344c942becb91851e5ac275039, ad35c7d07cca28973159ffe3d5951bd3, 918990cfabbfe7a2913ef9bfd0fe71a7
ISPB: 09089356 e 09089357 
Data e hora: 09/03/2021 10:07:51

**Mensagens Enviadas / Recebidas**

Requisição da criação de vínculo:

`
<CreateEntryRequest>
  <Signature></Signature>
  <Entry>
    <Key>59597064073</Key>
    <KeyType>CPF</KeyType>
    <Account>
      <Participant>09089357</Participant>
      <Branch>0001</Branch>
      <AccountNumber>5290696</AccountNumber>
      <AccountType>CACC</AccountType>
      <OpeningDate>2020-08-13T20:28:27.000Z</OpeningDate>
    </Account>
    <Owner>
      <Type>NATURAL_PERSON</Type>
      <TaxIdNumber>59597064073</TaxIdNumber>
      <Name>JOSE DA SILVA</Name>
    </Owner>
  </Entry>
  <Reason>USER_REQUESTED</Reason>
  <RequestId>bc48b8b5-beb2-4331-9927-2de6fc69744d</RequestId>
</CreateEntryRequest>
`

Resposta da criação de vínculo com sucesso:

`
<CreateEntryResponse>
  <CorrelationId>e986fde4eef27aae453c467712a19116</CorrelationId>
  <ResponseTime>2021-03-09T12:59:07.797Z</ResponseTime>
  <Entry>
    <Key>59597064073</Key>
    <KeyType>CPF</KeyType>
    <Account>
      <Participant>09089357</Participant>
      <Branch>0001</Branch>
      <AccountNumber>5290696</AccountNumber>
      <AccountType>CACC</AccountType>
      <OpeningDate>2020-08-13T20:28:27Z</OpeningDate>
    </Account>
    <Owner>
      <Type>NATURAL_PERSON</Type>
      <TaxIdNumber>59597064073</TaxIdNumber>
      <Name>JOSE DA SILVA</Name>
    </Owner>
    <CreationDate>2021-03-09T12:59:07.750Z</CreationDate>
    <KeyOwnershipDate>2021-03-09T12:59:07.746Z</KeyOwnershipDate>
  </Entry>
  <RequestId>bc48b8b5-beb2-4331-9927-2de6fc69744d</RequestId>
</CreateEntryResponse>
`

Ao realizar a consulta de vínculo, temos a resposta com sucesso:

`
<GetEntryResponse>
  <CorrelationId>b1f485344c942becb91851e5ac275039</CorrelationId>
  <ResponseTime>2021-03-09T13:04:27.410Z</ResponseTime>
  <Entry>
    <Key>59597064073</Key>
    <KeyType>CPF</KeyType>
    <Account>
      <Participant>09089357</Participant>
      <Branch>0001</Branch>
      <AccountNumber>5290696</AccountNumber>
      <AccountType>CACC</AccountType>
      <OpeningDate>2020-08-13T20:28:27Z</OpeningDate>
    </Account>
    <Owner>
      <Type>NATURAL_PERSON</Type>
      <TaxIdNumber>59597064073</TaxIdNumber>
      <Name>JOSE DA SILVA</Name>
    </Owner>
    <CreationDate>2021-03-09T12:59:07.750Z</CreationDate>
    <KeyOwnershipDate>2021-03-09T12:59:07.746Z</KeyOwnershipDate>
  </Entry>
  <Statistics>
    <LastUpdated>2021-03-09T12:59:34.067Z</LastUpdated>
    <Counters>
      <Counter by="KEY" d3="0" d30="0" m6="0" type="SETTLEMENTS"/>
      <Counter by="OWNER" d3="0" d30="0" m6="0" type="SETTLEMENTS"/>
      <Counter by="ACCOUNT" d3="0" d30="0" m6="0" type="SETTLEMENTS"/>
      <Counter by="KEY" d3="0" d30="0" m6="0" type="REPORTED_FRAUDS"/>
      <Counter by="OWNER" d3="0" d30="0" m6="0" type="REPORTED_FRAUDS"/>
      <Counter by="ACCOUNT" d3="0" d30="0" m6="0" type="REPORTED_FRAUDS"/>
      <Counter by="KEY" d3="0" d30="0" m6="0" type="CONFIRMED_FRAUDS"/>
      <Counter by="OWNER" d3="0" d30="0" m6="0" type="CONFIRMED_FRAUDS"/>
      <Counter by="ACCOUNT" d3="0" d30="0" m6="0" type="CONFIRMED_FRAUDS"/>
    </Counters>
  </Statistics>
</GetEntryResponse>
`

Requisição da atualização de vínculo, alterando o nome de `JOSE DA SILVA` para `JOSE DA SILVA TESTE`:

`
<UpdateEntryRequest>
  <Signature></Signature>
  <Key>59597064073</Key>
  <Account>
    <Participant>09089357</Participant>
    <Branch>0001</Branch>
    <AccountNumber>5290696</AccountNumber>
    <AccountType>CACC</AccountType>
    <OpeningDate>2020-08-13T20:28:27.000Z</OpeningDate>
  </Account>
  <Owner>
    <Type>NATURAL_PERSON</Type>
    <TaxIdNumber>59597064073</TaxIdNumber>
    <Name>JOSE DA SILVA TESTE</Name>
  </Owner>
  <Reason>USER_REQUESTED</Reason>
</UpdateEntryRequest>
`

Resposta da atualização de vínculo com sucesso:

`
<UpdateEntryResponse>
  <CorrelationId>ad35c7d07cca28973159ffe3d5951bd3</CorrelationId>
  <ResponseTime>2021-03-09T13:07:51.976Z</ResponseTime>
  <Entry>
    <Key>59597064073</Key>
    <KeyType>CPF</KeyType>
    <Account>
      <Participant>09089357</Participant>
      <Branch>0001</Branch>
      <AccountNumber>5290696</AccountNumber>
      <AccountType>CACC</AccountType>
      <OpeningDate>2020-08-13T20:28:27Z</OpeningDate>
    </Account>
    <Owner>
      <Type>NATURAL_PERSON</Type>
      <TaxIdNumber>59597064073</TaxIdNumber>
      <Name>JOSE DA SILVA TESTE</Name>
    </Owner>
    <CreationDate>2021-03-09T12:59:07.750Z</CreationDate>
    <KeyOwnershipDate>2021-03-09T12:59:07.746Z</KeyOwnershipDate>
  </Entry>
</UpdateEntryResponse>
`

Ao realizar novamente a consulta de vínculo, tem-se o erro abaixo:

`<problem xmlns="urn:ietf:rfc:7807">`
`  <type>https://dict.pi.rsfn.net.br/api/v1/error/BadRequest</type>`
` <title>Bad Request</title>`
`  <status>400</status>`
`  <detail>cid for entry identified by key Key(type=CPF, content=59597064073) does not match expected value. Data has possibly been tampered. Entry(key=Key(type=CPF, content=59597064073), status=ACTIVE, openClaimCreationDate=null, taxIdNumber=59597064073, personType=NATURAL_PERSON, ownerName=JOSE DA SILVA TESTE, ownerKnownName=null, participant=09089357, branch=0001, account=5290696, accountOpeningDate=2020-08-13T20:28:27Z, requestId=bc48b8b5-beb2-4331-9927-2de6fc69744d, cid=ab46e2a5f764dc74b2bc859e77eeeacf4ca6788535dcd2556f1c6b1d72a931ef, keyOwnershipSince=2021-03-09T12:59:07.746Z, creationDate=2021-03-09T12:59:07.750Z, lastModified=2021-03-09T13:07:51.957Z)</detail>
  <correlationId>918990cfabbfe7a2913ef9bfd0fe71a7</correlationId>
</problem>
`

**URL de conexão**
https://dict-h.pi.rsfn.net.br:16522/api/v1/entries

**Comment by lucianoprevedello** [comment]
BACEN, Poderiam olhar essa situação? Percebi a mesma situação ao consumir o endpoint para atualizar o vínculo.

https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API%20do%20DICT-v1.2.0.html#operation/updateEntry

**Comment by higorhaider** [comment]
Estamos enfrentando o mesmo problema, além de outros comportamentos estranhos oriundos do mesmo problema.

Acredito que está faltando o BACEN atualizar o código do CID na base deles após atualizar o nome, hoje, está sendo atualizado APENAS o nome. A alteração do nome gera alteração na composição do código CID e o mesmo também deve ser atualizado. 

Esta inconsistência no código CID da chave gera diversas anomalias na aplicação conforme relatado pelos colegas acima.

Poderíamos ao menos ter uma resposta?

Obrigado.

**Comment by HenriqueSimoes82** [comment]
Prezados, problema corrigido, Obrigado por reportar.
