### ISSUE TITLE
[Dúvida] no [DICT] - Dúvidas grade para geração arquivo de CIDs

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#49]
Gostaria de tirar algumas dúvidas sobre o processo de sincronismo.

1 - A categoria D, **não** é sujeita a manutenção?

2 - Se chamarmos o serviço de arquivo fora do horário, é retornado um erro ou o DICT acata a solicitação e só retorna o arquivo a partir das 20h?

3 - Se solicitarmos a geração do arquivo próximo do fechamento da grade, é possível consultar o arquivo solicitado fora da grade?

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
@monise ,
1 - Categoria D está sujeita a manutenção eventual
2 e 3 - Em homologação, não há limitação para a hora solicitada e o retorno do arquivo. Em produção ainda não avaliamos como será o comportamento se o pedido for feito próximo ou fora da janela D.
