### ISSUE TITLE
[Dúvida] no [SPI] - Garantia de entrega / long pooling

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#50]
Gostaríamos de saber se para implementar o long pooling, para a garantia de entrega os senhores fizeram uso internamente do **Apache Pulsar** ou de outra ferramenta similar?

**Sistema ou Área**
SPI

**Comment by adilson-silva** [comment]
Não. A garantia de entrega e alcançada através do mecanismo descrito na seção 2.2.2.2 do manual de interface de comunicação. Cada chamada a url retornada em “PI-Pull-Next” indica que o participante recebeu a(s) mensagem(s) correspondente(s) com sucesso.
