### ISSUE TITLE
[Dúvida] no [SPI] - Múltiplas conexões no Polling

### ISSUE THREAD

**Issue by mfabioe** [bacen/pix-perguntas-e-respostas#51]
Na nossa instituição temos 3 ambientes antes de produção: desenvolvimento, teste de qualidade de software e homologação.
Cada ambiente tem um long polling com o SPI.
A dúvida é sobre o funcionamento do polling quando se trata de múltiplas conexões.
Como são distribuídas as mensagens para as conexões?
Podemos esperar que todos os ambientes com long polling irão receber todas as mensagens ou as mensagens são entregues somente para a conexão mais antiga com o Bacen?

**Comment by adilson-silva** [comment]
No caso de múltiplas conexões de long pooling em uma mesma url (o atual ambiente de homologação do BACEN) as mensagens são divididas. Atualmente não há mecanismo para distinguir de onde originou a conexão do participante.

Lembrando que no futuro serão pelo menos dois ambientes (produção e homologação) com urls distintas.
