### ISSUE TITLE
[Dúvida] no [SPI] - Campos alfanuméricos

### ISSUE THREAD

**Issue by douglasrs89** [bacen/pix-perguntas-e-respostas#53]
**Descreva sua dúvida ou problema**

Na documentação da **PACS008**, temos, por exemplo o campo **informacoesEntreUsuarios** que permite **Máximo 140 caracteres alfanuméricos**. Porém, no **XSD** da **PACS008**, o campo de referencia **Ustrd**, permite um **Max140Text** que por sua vez, tem em seu layout um **xs:string** sem nenhum **Pattern**, logo, acaba permitindo tudo.

Um exemplo parecido, porém, que está coerente, é o **idContaTransacional** que permite **Máximo 77 caracteres alfanuméricos com caracteres especiais**. E no **XSD** da **PACS008**, o campo de referente **Id**, permite um **Max77Text** que tem o mesmo layout do **Ustrd**, porém, nesse caso por não ter um **Pattern**, acaba **permitindo alfanuméricos com caracteres especiais**, igual na documentação da **PACS008**.

A dúvida é... 
Devo seguir qual documento? No caso da **informacoesEntreUsuarios** deve permitir qualquer tipo de caractere **!@#$%ˆ&*(ÇÉÃ** ou somente alfanumérico **[0-9A-Za-z]** ?

Obs: o mesmo acontece para outros campos, como por exemplo o **nomeUsuarioPagador**.

```
        <xs:sequence>
            <xs:element name="Ustrd" type="Max140Text"/>
        </xs:sequence>
```

```
    <xs:simpleType name="Max140Text">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="140"/>
        </xs:restriction>
    </xs:simpleType>
```

```
        <xs:sequence>
            <xs:element name="Id" type="Max77Text"/>
        </xs:sequence>
```

```
    <xs:simpleType name="Max77Text">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="77"/>
        </xs:restriction>
    </xs:simpleType>
```

**Sistema ou Área**
SPI

**Comment by gstabel** [comment]
Boa tarde.
Temos a mesma dúvida do @douglasrs89.

Realizando um teste com uma PACS008 vemos que o sistema apresenta erro ADMI002 (vide abaixo).
Avaliando a documentação do XSD todos os caracteres UTF-8 deveriam ser aceitos, sem restrições,

Grato.

```
<BizMsgIdr>M000381660KCKTEB1310F6CH72EGH32V</BizMsgIdr>
...
<CdtTrfTxInf>
	<PmtId>
		<EndToEndId>E0118152120200713180248yLtNJ0JGZ</EndToEndId>
		<TxId>ID123456</TxId>
	</PmtId>
	...
	<RmtInf>
		<Ustrd>Reunião</Ustrd>
	</RmtInf>
</CdtTrfTxInf>
```

```
<admi.002.001.01>
	<RltdRef>
		<Ref>UEkBc0lX/Er2t943BFpIVb0PKurt798K</Ref>
	</RltdRef>
	<Rsn>
		<RjctgPtyRsn>Erro no processamento da ICOM</RjctgPtyRsn>
		<RjctnDtTm>2020-07-13T18:02:49.810Z</RjctnDtTm>
		<RsnDesc>Não foi possível interpretar o XML</RsnDesc>
	</Rsn>
</admi.002.001.01>
```

**Comment by cristianokbc** [comment]
@douglasrs89, trataremos com mais detalhes os caracteres especiais em versões futuras do catálogo. Tanto informacoesEntreUsuarios quanto nomeUsuarioPagador aceitarão caracteres especiais, sendo que nomeUsuarioPagador será mais restrito.

@gstabel, aceitamos caracteres acentuados e vários outros. Na mensagem enviada por vocês a codificação do XML estava incorreta. O caractere "ã" enviado estava em codificação ISO-8856, e não UTF-8. Nessas situações a ICOM gera uma ADMI.002.

**Comment by paulaselihevic12** [comment]
Olá! tenho a mesma dúvida, já foi definido quais caracteres especiais serão aceitos em informacoesEntreUsuarios? obrigada!

**Comment by gstabel** [comment]
Conforme documentação:
Catalogo_de_Servicos_do_SFN_Volume_VI_Versao_500.pdf, pág. 6

> A definição de caractere, para este Catálogo, é a utilizada no padrão XML 1.0. Trata-se de uma “unidade atômica de texto, como especificado pela norma ISO/IEC 10646:2000. Caracteres legais são a tabulação (tab), o retorno de carro (Carriage Return), a alimentação de linha (Line Feed) e os caracteres legais dos padrões Unicode e ISO/IEC 10646:2000”.
> 
> O subconjunto de caracteres Unicode que são aceitos como texto nas mensagens XML do Catálogo estão compreendidos nas faixas “0000-007F” (“Basic Latin (ASCII)”) e “0080-00FF” (“Latin-1 Supplement”). Em ambas as faixas, os caracteres de controle (“C0” e “C1”) que não são aceitos nem recomendados no padrão XML 1.0 também não serão aceitos no conteúdo de mensagens deste Catálogo.
> 
> Portanto, para as mensagens definidas neste Catálogo, um caractere válido é definido pela seguinte expressão regular, contendo códigos de caracteres Unicode:
> Caractere ::= #x0009 | #x000A | #x000D | [#x0020-#x007E] | #x0085 | [#x00A0-#x00FF]
