### ISSUE TITLE
[Problema] no [DICT] - Campo lastModified não segue padrão date-time RFC 3339

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#55]
**Descreva sua dúvida ou problema**

A data **lastModified** retornada pelo DICT não está seguindo o padrão date-time especificado no swagger que por sua vez segue a RFC 3339 (https://tools.ietf.org/html/rfc3339#section-5.6)

Esse formato está correto?

**Sistema ou Área**
DICT

**Dados adicionais**

`GET /api/v1/claims?Status=OPEN&IsClaimer=false&ModifiedAfter=2020-07-02T18%3A51%3A04Z&Type=PORTABILITY&Participant=24313102&IsDonor=true`

Response para busca de reivindicações

`<ListClaimsResponse>
    <Claims>
        <Claim>
            <Type>PORTABILITY</Type>
            <Key>16462812923</Key>
            <KeyType>CPF</KeyType>
            <ClaimerAccount>
                <Participant>13370835</Participant>
                <Branch>3234</Branch>
                <AccountNumber>32</AccountNumber>
                <AccountType>CACC</AccountType>
            </ClaimerAccount>
            <Claimer>
                <Type>NATURAL_PERSON</Type>
                <TaxIdNumber>16462812923</TaxIdNumber>
                <Name>Isabelle Ribeiro Barros</Name>
            </Claimer>
            <Id>26f11683-71de-4d07-8cd5-906fdff512f8</Id>
            <Status>OPEN</Status>
            <DonorParticipant>24313102</DonorParticipant>
            <ResolutionPeriodEnd>2020-07-09T18:52:00Z</ResolutionPeriodEnd>
            <LastModified>2020-07-02T18:52:04.985Z</LastModified>
        </Claim>
    </Claims>
</ListClaimsResponse>`

**Comment by luizlaydner** [comment]
@monise, Não consegui enxergar de que forma a data **lastModified** não está de acordo com o formato ISO-8601

Rodando o código abaixo, parsing é feito sem problema. Tem algo que não estou considerando ?

```java
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

public class Test {
    public static void main(String[] args) {
        ZonedDateTime dateTime = ZonedDateTime.parse("2020-07-02T18:52:04.985Z", DateTimeFormatter.ISO_DATE_TIME);
        System.out.println(dateTime);
    }
}

```
