### ISSUE TITLE
[Problema] no [DICT] - Erro ao consultar chave do PSP direto através do indireto dele

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#57]
**Descreva sua dúvida ou problema**

Olá! Estamos consultando uma chave do PSP direto **através** do PSP **indireto**** dele** e no nosso entendimento, o PSP indireto deveria consultar essa chave no DICT, uma vez que ela só está registrada na base do PSP direto.

Nosso entendimento está correto?

Pois estamos recebendo o seguinte erro nesse cenário:

`https://dict.pi.rsfn.net.br/api/v1/error/EntryCannotBeQueriedForBookTransfer, details: Entry queried is in custody of participant making the query, status code: 400, other error info: ClearingErrorResponseDTO(type=https://dict.pi.rsfn.net.br/api/v1/error/EntryCannotBeQueriedForBookTransfer, title=Bad Request, status=400, detail=Entry queried is in custody of participant making the query, violations=null) 
`

Poderiam, verificar, por favor?

**Sistema ou Área**
DICT

**Identificador do Problema**

ISPB do PSP direto: 13370835
Chave cadastrada pelo PSP direto: f9a12808-b207-4246-af01-1e1b37869d85
ISPB do indireto: 18191228

Requisição realizada

` GET /api/v1/entries/f9a12808-b207-4246-af01-1e1b37869d85 HTTP/1.1 
 PI-EndToEndId: E18191228202007081159lXMrbK137Vm 
 PI-PayerAccountServicer: 18191228 
 PI-PayerId: da3f67eeadbe2ef77968739498698953c9b92408bed323306c6d46fc1b8cf7d2 
 Host: dict-h.pi.rsfn.net.br 
 Accept-Encoding: gzip 
 Accept: application/xml 
 Content-Type: application/xml; charset=utf-8 
 "GET /api/v1/entries/f9a12808-b207-4246-af01-1e1b37869d85 HTTP/1.1[\r][\n]" 
 "PI-EndToEndId: E18191228202007081159lXMrbK137Vm[\r][\n]" 
 "PI-PayerAccountServicer: 18191228[\r][\n]" 
 "PI-PayerId: da3f67eeadbe2ef77968739498698953c9b92408bed323306c6d46fc1b8cf7d2[\r][\n]" 
 "Host: dict-h.pi.rsfn.net.br[\r][\n]" 
 "Accept-Encoding: gzip[\r][\n]" 
 "Accept: application/xml[\r][\n]" 
 "Content-Type: application/xml; charset=utf-8[\r][\n]" 
 "[\r][\n]" 
 "HTTP/1.1 400 [\r][\n]" 
 "Cache-Control: no-store[\r][\n]" 
 "Content-Type: application/problem+xml[\r][\n]" 
 "Content-Length: 1986[\r][\n]" 
 "Date: Wed, 08 Jul 2020 11:59:20 GMT[\r][\n]" 
 "Connection: close[\r][\n]" `

**Comment by judahreis** [comment]
@monise, vamos corrigir o problema em uma release hoje, até o fim do dia. Obrigado por reportar.

**Comment by HenriqueSimoes82** [comment]
@monise 

Problema corrigido. Pode testar novamente. Obrigado.
