### ISSUE TITLE
[Dúvida] no [DICT] - Arquivo de CIDs em UpperCase

### ISSUE THREAD

**Issue by guimapalmeira** [bacen/pix-perguntas-e-respostas#58]
**Descreva sua dúvida ou problema**
O arquivo de Cids está trazendo os CIDs em **caixa alta**, sei que não influencia no cálculo do vSync, mas gostaria de saber se ficará dessa forma, ja que o cids que vem no ENDPOINT de /cid/events vem em **caixa baixa**.

**Sistema ou Área**
DICT

**Dados adicionais**
Utilizando o endpoint de /cids/events, responde os cids em caixa baixa
![image](https://user-images.githubusercontent.com/20684648/86972160-d72bcf00-c148-11ea-9309-1d076b8f20ef.png)

Fazendo o download em https://arq-h.pi.rsfn.net.br/api/v1/download/02038232/cidsetfile/02038232_EMAIL_1090_2020-07-08T18:30:00.977Z.txt vem em caixa alta.
![image](https://user-images.githubusercontent.com/20684648/86972375-3a1d6600-c149-11ea-8698-3179e7d5263c.png)

Agradeço desde já,
Guilherme Palmeira.

**Comment by judahreis** [comment]
@guimapalmeira, não temos previsão de troca. Contudo, é esperado que o participante não faça diferenciação de maiúsculas ou minúsculas tanto no endpoint como no arquivo. Pode haver troca sem aviso prévio.
