### ISSUE TITLE
[Problema] no [DICT] - Erro na consulta de listar reivindicações

### ISSUE THREAD

**Issue by renatofq** [bacen/pix-perguntas-e-respostas#59]
**Descreva sua dúvida ou problema**
A listagem de revindicação está retornando erro dependendo dos parâmetros informados em homologação. 
Não não é erro intermitente, é de acordo com os parâmetros informados. Ex.: IsClaimer=true&Status=OPEN funciona normalmente. Já outras combinações ocorre erro 500 consistentemente. 

Abaixo está descrito um exemplo de uma das combinações que falha.

**Sistema ou Área**
DICT

**Identificador do Problema**
4d130cf65e82ab581fbb9306fb3b6eb3

**Mensagens Enviadas / Recebidas**

Requisição
```
GET /api/v1/claims?Participant=00000000&IsClaimer=true&Status=WAITING_RESOLUTION HTTP/1.1
Host: dict-h.pi.rsfn.net.br
User-Agent: curl/7.71.1
accept: application/xml
```
Resposta
``` XML
<?xml version="1.0"?>
<problem xmlns="urn:ietf:rfc:7807">
  <type>https://dict.pi.rsfn.net.br/api/v1/error/InternalServerError</type>
  <title>Internal Server Error</title>
  <status>500</status>
  <detail>Internal server error. Please contact support for details.</detail>
  <correlationId>4d130cf65e82ab581fbb9306fb3b6eb3</correlationId>
</problem>
```

**Comment by ekiametis** [comment]
Bom dia!

Estou com o mesmo problema na versão:  `/v1-rc4`

**Comment by HenriqueSimoes82** [comment]
@renatofq 

Problema corrigido. Pode testar novamente. Obrigado pelo reporte detalhado.
