### ISSUE TITLE
Dúvida no DICT - Fluxo Final Reivindicação

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#6]
**Descreva sua dúvida ou problema**
Dúvida sobre a parte final do fluxo de reconciliação Dict, quando recebemos na chamada "Consultar Reivindicações" o status COMPLETED de uma claim, nos devemos realizar uma chamada de "Concluir Reivindicação" e na sequencia uma chamada de "Atualizar Vinculo" ?

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
Everton,

Se a CLAIM está no status COMPLETED, significa q o PSP Reivindicador já chamou o POST
/claims/{ClaimId}/complete, o que atualizou o status, e também já realizou as mudanças no vínculo da chave. Não é necessário atualizar o vínculo depois.
