### ISSUE TITLE
[Problema] no [DICT] - [INDIRETO] Download Arquivo Cids - Acesso não permitido

### ISSUE THREAD

**Issue by guimapalmeira** [bacen/pix-perguntas-e-respostas#61]
**Descreva sua dúvida ou problema**
Ao tentar efetuar um Download de arquivo  de Cids para participante **Indireto**, estamos tomando erro de "Acesso não permitido".

**Sistema ou Área**
DICT

**Identificador do Problema**
Ao tentar-se efetuar o download dos CIDs para **Participante Indireto** do qual somos o liquidante(ispb 02038232).
https://arq-h.pi.rsfn.net.br/api/v1/download/03766873/cidsetfile/03766873_EMAIL_1093_2020-07-09T20:48:11.731Z.txt
Recebemos erro **403 Forbbiden**.

**Mensagens Recebidas**
<?xml version="1.0" encoding="UTF-8"?><problem xmlns="urn:ietf:rfc:7807"><type>https://icom.pi.rsfn.net.br/api/v1/error/forbidden</type><title>Acesso não permitido</title></problem>

**Comment by adilson-silva** [comment]
Verificando os logs, o certificado não corresponde ao ispb da consulta (03766873).

**Comment by guimapalmeira** [comment]
Opa @adilson-silva muito obrigado pela resposta.

Mas como descevri na issue, esse ispb(03766873) se refere a um participante **Indireto**, ao qual nossa instituição(02038232) é o participante Direto responsável, dessa forma, nós(participante direto) que teremos que efetuar a requisicão, correto!?

Att,
Guilherme.

**Comment by judahreis** [comment]
Realmente isso é um problema na versão atual. Vamos modificar o sistema para salvar os arquivos na URL do participante direto.

**Comment by guimapalmeira** [comment]
Obrigado @judahreis , 
vamos aguardar qualquer novidade.

Att,
Guilherme Palmeira.

**Comment by HenriqueSimoes82** [comment]
@guimapalmeira 

Problema corrigido. Para testar, peço que solicite o aquivo novamente. A solução não contempla os arquivos já gerados. 

Obrigado pelo reporte detalhado.
