### ISSUE TITLE
[Dúvida] [QR CODE] - Dúvidas sobre certificados digitais para assinatura de QR CODE Dinâmico

### ISSUE THREAD

**Issue by RogerNeris** [bacen/pix-perguntas-e-respostas#62]
No anexo “4 – Manual de Segurança” dentro item 1.4 está sendo detalhado todas as especificações de segurança para o QR CODE Dinâmico. Neste item são citados 2 certificados que deve ser emitido por AC com ampla aceitação por navegadores e clientes de mercado, com características tipo EV e cadastrado no STA. Eu gostaria de ajuda em algumas questões:
1)	Estes certificados são diferentes dos 2 certificados utilizados para comunicação e assinatura de liquidação e DICT. Para atendem todos os fluxos SPI seria indicado 8 certificados (homologação e produção)?
1)	Podemos entender que se indica uma AC internacional?  
2)	É obrigatório ser ICP Brasil?  Neste item aparentemente não cita isso e também ICP Brasil pode não ser amplamente aceito por navegadores sem a importação da cadeia intermediária.
3)	Eu não encontrei o tipo de arquivo de STA indicado no item 1.4.2 dentro do site do STA de homologação. O cadastro não é feito via upload do STA ?

Sistema ou Área : QR CODE

**Comment by anderjoy** [comment]
@RogerNeris 
Estou com as mesmas dúvidas...
Bolei uma estratégia maluca, só pra ter alguma coisa.

**Comment by ninrod** [comment]
@RogerNeris @anderjoy:

1. "Estes certificados são diferentes dos 2 certificados utilizados para comunicação e assinatura de liquidação e DICT. Para atendem todos os fluxos SPI seria indicado 8 certificados (homologação e produção)?"
**R:** Cada PSP precisará de, no mínimo, 2 certificados para cada ambiente: 1 para CERTPIC e CERTPIA e outro para o CERTQRC e assinatura do payload JSON. No total, considerando homologação e produção, seriam 4 certificados. No entanto, a recomendação do BC é que sejam utilizados certificados distintos para cada finalidade (essa recomendação consta na seção 1.3.1 do Manual de Segurança do PIX), o que resultaria na necessidade dos PSPs adquirirem 8 certificados no total (4 por ambiente).

2. Podemos entender que se indica uma AC internacional?
**R:** Não, o BCB indica uma AC amplamente conhecida, não precisa ser, necessariamente, uma AC internacional.

3. É obrigatório ser ICP Brasil? Neste item aparentemente não cita isso e também ICP Brasil pode não ser amplamente aceito por navegadores sem a importação da cadeia intermediária.
**R:** Não é obrigatório ser ICP Brasil. 

4. Eu não encontrei o tipo de arquivo de STA indicado no item 1.4.2 dentro do site do STA de homologação. O cadastro não é feito via upload do STA?
**R**: Vou deixar a issue aberta e assim que eu obtiver a resposta eu atualizo aqui.
