### ISSUE TITLE
[Problema] no [SPI] - Erro EndToEndId de um pagamento de Participante indireto

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#64]
**Descreva sua dúvida ou problema**

Olá! Estamos realizando um pagamento do **participante indireto** passando pelo participante direto dele. No nosso entendimento, no campo endToEndId deve ser informado o ISPB do participante indireto, correto?

Porém, quando fazemos isso, recebemos uma ADMI.002 com o seguinte erro:

`<RsnDesc>
      O código ISPB contido no identificador da ordem de pagamento está diferente do ISPB do debitado
</RsnDesc>`

Poderiam, por favor, verificar?

**Sistema ou Área**
SPI

**Identificador do Problema**
MsgId: M133708351594404493056vCQvdhERD8
Participante direto: 13370835
Participante indireto: 24313102
EndToEnd: E243131022020071018060wXkti9xrUK

**Mensagens Enviadas / Recebidas**

**PACS.008**

`<Document>
        <FIToFICstmrCdtTrf>
            <GrpHdr>
                <MsgId>
                    M133708351594404493056vCQvdhERD8
                </MsgId>
                <CreDtTm>
                    2020-07-10T18:08:13.071Z
                </CreDtTm>
                <NbOfTxs>
                    1
                </NbOfTxs>
                <SttlmInf>
                    <SttlmMtd>
                        CLRG
                    </SttlmMtd>
                </SttlmInf>
                <PmtTpInf>
                    <InstrPrty>
                        HIGH
                    </InstrPrty>
                </PmtTpInf>
            </GrpHdr>
            <CdtTrfTxInf>
                <PmtId>
                    <EndToEndId>
                        E243131022020071018060wXkti9xrUK
                    </EndToEndId>
                </PmtId>
                <IntrBkSttlmAmt Ccy="BRL">
                    1
                </IntrBkSttlmAmt>
                <AccptncDtTm>
                    2020-07-10T18:06:30.296Z
                </AccptncDtTm>
                <ChrgBr>
                    SLEV
                </ChrgBr>
                <Dbtr>
                    <Nm>
                        joao ferreira
                    </Nm>
                    <Id>
                        <PrvtId>
                            <Othr>
                                <Id>
                                    16244303504
                                </Id>
                            </Othr>
                        </PrvtId>
                    </Id>
                </Dbtr>
                <DbtrAcct>
                    <Id>
                        <Othr>
                            <Id>
                                35
                            </Id>
                            <Issr>
                                1
                            </Issr>
                        </Othr>
                    </Id>
                    <Tp>
                        <Cd>
                            CACC
                        </Cd>
                    </Tp>
                </DbtrAcct>
                <DbtrAgt>
                    <FinInstnId>
                        <ClrSysMmbId>
                            <MmbId>
                                24313102
                            </MmbId>
                        </ClrSysMmbId>
                    </FinInstnId>
                </DbtrAgt>
                <CdtrAgt>
                    <FinInstnId>
                        <ClrSysMmbId>
                            <MmbId>
                                00000000
                            </MmbId>
                        </ClrSysMmbId>
                    </FinInstnId>
                </CdtrAgt>
                <Cdtr>
                    <Id>
                        <PrvtId>
                            <Othr>
                                <Id>
                                    98262017315
                                </Id>
                            </Othr>
                        </PrvtId>
                    </Id>
                </Cdtr>
                <CdtrAcct>
                    <Id>
                        <Othr>
                            <Id>
                                753920
                            </Id>
                            <Issr>
                                551
                            </Issr>
                        </Othr>
                    </Id>
                    <Tp>
                        <Cd>
                            CACC
                        </Cd>
                    </Tp>
                </CdtrAcct>
                <RmtInf>
                    <Ustrd>
                        Campo livre
                    </Ustrd>
                </RmtInf>
            </CdtTrfTxInf>
        </FIToFICstmrCdtTrf>
    </Document>`

**ADMI.002**

`    <Document>
        <admi.002.001.01>
            <RltdRef>
                <Ref>
                    M133708351594404493056vCQvdhERD8
                </Ref>
            </RltdRef>
            <Rsn>
                <RjctgPtyRsn>
                    Erro no processamento do SPI
                </RjctgPtyRsn>
                <RjctnDtTm>
                    2020-07-10T18:08:13.739Z
                </RjctnDtTm>
                <RsnDesc>
                    O código ISPB contido no identificador da ordem de pagamento está diferente do ISPB do debitado
                </RsnDesc>
                <AddtlData>
                    EndToEndId=E243131022020071018060wXkti9xrUK
                </AddtlData>
            </Rsn>
        </admi.002.001.01>
    </Document>`

**Dados adicionais**

Fizemos um cenário passando o ISPB do direto no EndToEndId e o ISPB do indireto apenas na seção de dados do pagador. Nesse caso, a PACS.008 foi processada com sucesso. O correto seria seguir esse formato?

**PACS.008 com sucesso**

` <Document>
        <BkToCstmrDbtCdtNtfctn>
            <GrpHdr>
                <MsgId>M000381660KCGK4MZD10G2QK2RFLGIBK</MsgId>
                <CreDtTm>2020-07-10T18:32:17.497Z</CreDtTm>
            </GrpHdr>
            <Ntfctn>
                <Id>M1337083515944059365724RT3qhp38W</Id>
                <Acct>
                    <Id>
                        <Othr>
                            <Id>13370835</Id>
                        </Othr>
                    </Id>
                </Acct>
                <Ntry>
                    <Amt Ccy="BRL">99.00</Amt>
                    <CdtDbtInd>DBIT</CdtDbtInd>
                    <Sts>
                        <Cd>BOOK</Cd>
                    </Sts>
                    <BookgDt>
                        <Dt>2020-07-10</Dt>
                    </BookgDt>
                    <ValDt>
                        <DtTm>2020-07-10T18:23:34.393Z</DtTm>
                    </ValDt>
                    <BkTxCd>
                        <Domn>
                            <Cd>PMNT</Cd>
                            <Fmly>
                                <Cd>IRCT</Cd>
                                <SubFmlyCd>DMCT</SubFmlyCd>
                            </Fmly>
                        </Domn>
                    </BkTxCd>
                    <NtryDtls>
                        <TxDtls>
                            <Refs>
                                <EndToEndId>E133708352020071018224UHeBRvtM3q</EndToEndId>
                            </Refs>
                            <RltdAgts>
                                <DbtrAgt>
                                    <FinInstnId>
                                        <ClrSysMmbId>
                                            <MmbId>24313102</MmbId>
                                        </ClrSysMmbId>
                                    </FinInstnId>
                                </DbtrAgt>
                                <CdtrAgt>
                                    <FinInstnId>
                                        <ClrSysMmbId>
                                            <MmbId>00000000</MmbId>
                                        </ClrSysMmbId>
                                    </FinInstnId>
                                </CdtrAgt>
                            </RltdAgts>
                            <RmtInf>
                                <Ustrd>xcxzcxz</Ustrd>
                            </RmtInf>
                            <RltdDts>
                                <AccptncDtTm>2020-07-10T18:22:32.567Z</AccptncDtTm>
                            </RltdDts>
                            <AddtlTxInf>HIGH</AddtlTxInf>
                        </TxDtls>
                    </NtryDtls>
                </Ntry>
            </Ntfctn>
        </BkToCstmrDbtCdtNtfctn>
    </Document>`

**Comment by rafael-omello** [comment]
Dúvidas negociais devem ser encaminhadas para spi@bcb.gov.br
