### ISSUE TITLE
[Dúvida|Problema] no [SISTEMA] - Como devemos proceder a chamada de API para informar o DICT sobre a remoção da chave interna? 

### ISSUE THREAD

**Issue by gilbertogomesBS2** [bacen/pix-perguntas-e-respostas#65]
**Descreva sua dúvida ou problema**
Verificando o Manual de Especiações versão 6.2, página 104 onde consta o fluxo de reivindicação de posse no papel de PSP doador o item 11 Informa Remoção/Opção Cancelar.
Como devemos proceder a chamada de API para informar o DICT sobre a remoção da chave interna? 
Devemos chamar a API de "Remover Vínculo" do DICT, passando a razão: ENTRY_INACTIVITY? Ou deve-se chamar outra API?

**Sistema ou Área**
DICT

**Identificador do Problema**
Correlation-Id (no caso de erro do DICT), ou ResourceId (no caso do SPI/ICOM). Se possível, indique também o ISPB, e a data-hora em que identificou o problema.

**Mensagens Enviadas / Recebidas**
XML das mensagens enviadas e recebidas (sem assinatura fica melhor)

**URL de conexão**
URL para onde a mensagem foi enviada

**Dados adicionais**
Qualquer informação adicional que ajude a identificar o problema ou dúvida.

**Comment by judahreis** [comment]
@gilbertogomesBS2, a simples confirmação da reivindicação já realiza a remoção da chave no DICT. Não é necessário fazer a remoção posterior. Em outras palavras, ao chamar o /claims/{ClaimId}/confirm o dict muda o estado da reivindicação e também remove o vínculo da chave com o participante.
