### ISSUE TITLE
[Problema] no [DICT] - Erro Missing request header 'PI-CertSubjectDN' 

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#67]
**Descreva sua dúvida ou problema**
Olá! Começamos a receber o seguinte erro ao tentar cadastrar uma chave:

`Missing request header 'PI-CertSubjectDN' for method parameter of type AuthenticatedParticipant`

Houve alguma mudança na assinatura da API?

**Sistema ou Área**
DICT

**Comment by fCamargosRibeiro** [comment]
Também ocorreu com a gente hoje em várias chamadas do DICT além do cadastro, o mesmo erro.

**Comment by judahreis** [comment]
houve manutenção no ambiente após as 18h00 do dia 13/07, mas já está resolvido. Lembramos que o período "garantido" dos testes é das 9h00 às 17h00. Se o problema aconteceu (ou voltar a acontecer) dentro da janela, favor informar o CorrelationId pra que a gente possa investigar.
