### ISSUE TITLE
Problema no DICT - Erro chamadas

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#68]
**Descreva sua dúvida ou problema**
Desde a tarde de ontem 13/07/2020, começamos a receber o erro "Missing request header PI-CertSubjectDN for method parameter of type AuthenticatedParticipant", em todas operações Dict com Bacen. Realizamos pesquisa em todos documentos relacionados a Dict e não encontramos algo que possibilitasse esse erro, acredito que houve uma atualização no sistema Dict Bacen e não foi realizado atualização nas documentações. 
Fico no aguardo.
Obrigado.

**Sistema ou Área*
DICT

**Mensagens Enviadas / Recebidas**
<title>Bad Request</title><status>400</status><detail>Missing request header PI-CertSubjectDN for method parameter of type AuthenticatedParticipant</detail>

**Comment by judahreis** [comment]
@evertongodoi, tentamos reproduzir, mas não conseguimos... você tem o CorrelationId do erro?

**Comment by evertongodoi** [comment]
@judahreis segue FCBEE58486FA4F3684F5F5AF61A262EB

**Comment by judahreis** [comment]
@evertongodoi, houve manutenção no ambiente após as 18h00 do dia 13/07, mas já está resolvido. Lembramos que o período "garantido" dos testes é das 9h00 às 17h00. Se o problema aconteceu (ou voltar a acontecer) dentro da janela, favor informar o CorrelationId pra que a gente possa investigar.

**Comment by evertongodoi** [comment]
Obrigado!
