### ISSUE TITLE
Dúvida no DICT -  URL dinâmica

### ISSUE THREAD

**Issue by tnolasco** [bacen/pix-perguntas-e-respostas#69]
Bom dia,

Em relação ao documento referência[1] com o título **"Consultar Arquivo de CIDs"** é citado um body de resposta onde uma das tag's é o endereço de download do arquivo do CID's como listado abaixo:
_<Url>https://some_download_url/apath/12345678/dict_file_name.cids</Url>_
Tenho um dúvida em relação a parte do host **some_donwload_url** , este endereço do host será dinâmico?
Isso surgiu por que estamos utilizando um proxy para que seja feito a conexão com o Bacen, se as contexto e recursos das URL's do PIX forem alteradas funcionaram perfeitamente. No entanto, se os endereços FQDN alterar teremos problemas. Podem nos tirar esta dúvida?

Obrigado!

[1] https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/AnexoV-APIdoDiretoriodeIdentificadoresdeContasTransacionais-versao1.0.0-RC4.html#operation/getCidSetFile

**Sistema ou Área**
INFRA

**Comment by judahreis** [comment]
@tnolasco, atualmente o nome do serviço que disponibiliza os arquivos é "arq-h.pi.rsfn.net.br". Em produção, o serviço deverá se chamar arq.pi.rsfn.net.br. Não há previsão de mudança. Caso aconteça, haverá comunicação prévia.
