### ISSUE TITLE
[Dúvida|] no [SPI] - CAMT.052 - Download do arquivo de lançamentos

### ISSUE THREAD

**Issue by gilbertogomesBS2** [bacen/pix-perguntas-e-respostas#7]
**Descreva sua dúvida ou problema**
Conforme o item 3.4.2 do documento de especificações do PIX 6.1, a forma de download do arquivo seria divulgada oportunamente. Já teríamos disponível essa documentação?

**Sistema ou Área**
DICT, SPI, Iniciação de Pagamentos, QR Code, INFRA

**Identificador do Problema**
Correlation-Id (no caso de erro do DICT), ou ResourceId (no caso do SPI/ICOM). Se possível, indique também o ISPB, e a data-hora em que identificou o problema.

**Mensagens Enviadas / Recebidas**
XML das mensagens enviadas e recebidas (sem assinatura fica melhor)

**URL de conexão**
URL para onde a mensagem foi enviada

**Dados adicionais**
Qualquer informação adicional que ajude a identificar o problema ou dúvida.

**Comment by cristianokbc** [comment]
@gilbertogomesBS2, as instruções estão no Informe SPI - 018/2020. O trecho que trata do acesso ao arquivo é o seguinte:

> A consulta relação de lançamentos é solicitada via mensagem Camt.060 e respondida via mensagem Camt.052, cujas especificações estão contidas no arquivo Anexo II – Catálogo de Mensagens do SPI - versão 1.7. O nome do arquivo contido na mensagem Camt.052 deve ser utilizado para realizar o download do mesmo, seguindo as mesmas diretivas de segurança e autenticação das interfaces ICOM e DICT, mas no endereço https://arq-h.pi.rsfn.net.br e no caminho “/api/v1/download/[ISPB]/extrato/[nome do arquivo informado na mensagem camt.052].zip”.


É necessário, portanto, usar o mesmo esquema de autenticação mútua utilizado no acesso ao DICT e ICOM, com o certificado de cliente enviado anteriormente via arquivo CERTPIC no STA.
