### ISSUE TITLE
[Dúvida] no [DICT] - Path dos serviços versão RC5

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#70]
**Descreva sua dúvida ou problema**

Gostaria de tirar uma dúvida referente ao comunicado, de que a partir de sexta as 17h, no ambiente de homologação estará rodando a versão **v1.0.0-RC5**.

Para chamar os serviços do DICT, será necessário mudar o path das chamadas para apontar para a versão RC5?

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
Sim! 
A versão v1.0.0-RC5 estará no path base `/api/v1-rc5` . 
A v1.0.0-RC4 em `/api/v1-rc4` .
O path `api/v1`, que hoje aponta para v1.0.0-RC3, deixará de funcionar com publicação da RC6.

Sempre que há quebra de compatibilidade, geramos nova versão no path da API. 
A tendência é que após a release final da V1 (path `/api/v1`), tenhamos estabilidade, sem quebras de compatibilidade.
