### ISSUE TITLE
Problema no SISTEMA - retorno Invalid Reason em reivindicação por indireto

### ISSUE THREAD

**Issue by kertony** [bacen/pix-perguntas-e-respostas#71]
Reivindicação de uma chave onde o reivindicador é o PSP Direto (92894922) e o doador é o PSP Indireto (92894923), a reivindicação está no estado "WAITING_RESOLUTION" mas quando tentamos fazer a confirmação como PSP Indireto com reason "USER_REQUESTED" recebemos erro de "Invaid Reason". Na sequência temos as mensagens XML envolvidas:
1) Mensagem XML enviada anexo "Claim_Request.xml" 
2) Mensagem XML recebida anexo "Claim_Response.xml"
CorrelationId da mensagem retornada: 95A05339055B4B64BCF72361F0B258DA

DICT

Reivindicação - Invalid Reason

Aparentemente o endpoint https://dict-h.pi.rsfn.net.br/api/v1/claims/{ClaimId}/confirm está ignorando o PSP Indireto informado no payload e está realizando a operação usando o ISPB do PSP Direto (da conexão). Como forma de demonstrar essa hipótese fizemos uma operação de confirmação de uma reivindicação que de um PSP Direto parceiro usando o ISPB do nosso PSP Direto (92894922) em que a resposta foi "Participant is not allowed to access this resource"  diferente do que recebemos na operação interna.
3) Mensagem XML enviada, anexo "Claim_Request2.xml"
4) Mensagem XML recebida, anexo "Claim_Response2.xml"

[Claim_Request.xml.txt](https://github.com/bacen/pix-perguntas-e-respostas/files/4922521/Claim_Request.xml.txt)
[Claim_Request2.xml.txt](https://github.com/bacen/pix-perguntas-e-respostas/files/4922522/Claim_Request2.xml.txt)
[Claim_Response.xml.txt](https://github.com/bacen/pix-perguntas-e-respostas/files/4922523/Claim_Response.xml.txt)
[Claim_Response2.xml.txt](https://github.com/bacen/pix-perguntas-e-respostas/files/4922524/Claim_Response2.xml.txt)

**Comment by luizlaydner** [comment]
@kertony 
Você precisa apontar para o endpoint /api/v1-rc4/ , onde está a versão da API em que esse problema foi corrigido.

Os endpoints /api/v1 e /api/v1-rc3 apontam para a versão anterior (incompatível com atual), em que o ConfirmClaimRequest não tem o campo <Participant>, necessário para fazer a lógica de autorização corretamente.
