### ISSUE TITLE
[PIX Link] - Contribuições técnicas

### ISSUE THREAD

**Issue by felipecn** [bacen/pix-perguntas-e-respostas#72]
**Descreva sua dúvida ou problema**
Pelo que li nas especificações de iniciação do PIX, entendi que o Banco Central irá registrar o aplicativo de cada PSP para ativar App Links (para Android) e Universal Links (para iOS).
A documentação sempre trabalha com a premissa de que o sistema operacional irá permitir ao usuário escolher a aplicação que irá abrir aquele link (ou definir um padrão) dentre as que tem instalado. O que é válido para o Android.
Porém, no iOS, não é possível escolher o aplicativo aberto por um universal link.
Meu entendimento é que o primeiro aplicativo listado no _https://pix.bcb.gov.br/.well-known/apple-app-site-association_ que o usuário tiver instalado será aberto.

Isso dito, tenho duas dúvidas:

1. Qual será a ordem usada no _https://pix.bcb.gov.br/.well-known/apple-app-site-association_ para listar os aplicativos de cada PSP? Tinha a impressão de ser na ordem alfabética pelo nome de cada instituição mas não achei a especificação.
2. Existe alguma intenção de mitigar esse caso? Creio um usuário ter mais um aplicativo compatível com PIX Links será um cenário bastante comum.

**Sistema ou Área**
PIX Link

**Comment by ninrod** [comment]
"Meu entendimento é que o primeiro aplicativo listado no https://pix.bcb.gov.br/.well-known/apple-app-site-association que o usuário tiver instalado será aberto."

@felipecn, estamos interessados nesse elemento que você pontuou. Você poderia citar documentação, se possível, oficial da Apple, que confirme esse entendimento?

**Comment by felipecn** [comment]
Há pouca documentação oficial sobre esse ponto, mas em [Support Universal Links](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html), há esse trecho

> The value of the details key is an array of dictionaries, one dictionary per app that your website supports. The order of the dictionaries in the array determines the order the system follows when looking for a match, so you can specify an app to handle a particular part of your website.

Assim, como o path de todo PIX Link será o mesmo para cada PSP, acho que o iOS usará a ordem no apple-app-site-association para definir qual aplicativo abrir.

**Comment by ninrod** [comment]
Caro @felipecn , apenas para ficar mais claro.

Se o Bacen servir um `AASA` file assim:

```json
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appID": "APP1.com.example",
                "paths": [ "qr/"]
            },
            {
                "appID": "APP2.com.example",
                "paths": [ "qr/" ]
            }
        ]
    }
}
```
Seu entendimento é que o iOS vai abrir a APP1 diretamente, sem permitir que o usuário escolha o APP (assim como acontece com um PDF, por exemplo?)

**Comment by felipecn** [comment]
Exato. Na maioria dos casos o app é aberto automaticamente. Em alguns casos, especialmente quando há um redirect, é exibido um prompt apenas para confirmar se deve direcionar para outro app.

![BB9C9C73-981F-41CB-9B15-2BD6DC2EA2ED](https://user-images.githubusercontent.com/1370796/87580001-317ae180-c6ad-11ea-87a0-70407b4a2c89.png)

**Comment by ninrod** [comment]
Certo, e você acredita que o android apresenta um comportamento diferente, que seria o de oferecer ao usuário a possibilidade de escolher o aplicativo?

**Comment by felipecn** [comment]
Eu tinha praticamente certeza que sim, mas estava pensando na experiência de deep links.
Lendo a documentação dos App Links, aparentemente o dialogo de desambiguação que eu estava lembrando de ver no Android não é exibido para App Links. ([The difference between deep links and app links](https://developer.android.com/training/app-links/verify-site-associations#the-difference))

É falado sobre múltiplos apps associados à paths diferentes, mas não o comportamento de múltiplos apps no mesmo path.

**Comment by ninrod** [comment]
> É falado sobre múltiplos apps associados à paths diferentes, mas não o comportamento de múltiplos apps no mesmo path.

Sim, é bem difícil obter informações claras sobre esse caso de uso específico nas documentações oficiais.

**Comment by ninrod** [comment]
> Eu tinha praticamente certeza que sim, mas estava pensando na experiência de deep links.

[Esse trecho](https://developer.android.com/training/app-links/verify-site-associations#multiple-apps) indica que o Android trabalharia da maneira como pensávamos, mas de maneira nenhuma deixa clara a experiência do usuário no sentido de poder escolher o app.

**Comment by ninrod** [comment]
@oximer, @felipecn e demais devs que eventualmente cheguem nessa issue, gostaríamos de entender exatamente qual é o comportamento do iOS ao se utilizar universal links. Como exemplo, suponha que o BCB sirva o seguinte arquivo AASA (apple-app-site-association) file em pix.bcb.gov.br/.well-known/apple-app-site-association:

```json
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appID": "APP1.com.example",
                "paths": [ "qr/"]
            },
            {
                "appID": "APP2.com.example",
                "paths": [ "qr/" ]
            },
           {
                "appID": "APP3.com.example",
                "paths": [ "qr/" ]
            }
        ]
    }
}
```

Temos as seguintes perguntas: 

1) A ordem de instalação tem algum efeito? Se o usuário instalar na sequência 3 -> 2 -> 1, o iOS adotaria o mesmo comportamento no caso em que o usuário instalasse na ordem 1 -> 2 -> 3? Ou seja, abriria  sempre o APP1? É sempre o primeiro elemento do array que "ganha" a precedência? Como funciona, exatamente, essa precedência? 

2) A associação do app ao domínio acontece somente no momento da instalação ou atualização do app, ou o arquivo AASA é checado de tempos em tempos pelo iOS?

3) Uma vez que o iOS escolha, baseado na ordem de precedência do AASA file, um app para abrir um link pertencente a determinado domínio, essa escolha permanece ou uma nova escolha pode ser feita decorrente de instalações de novos aplicativos e eventuais mudanças na ordem de precedência do arquivo AASA? 

4) Há alguma forma, de repente escondida nas configurações do iOS, que permita o usuário escolher qual dos 3 APPS ele quer utilizar para abrir links com domínio pix, de maneira que o usuário possa ignorar qualquer ordem de precedência estabelecida pelo AASA file? 

5) Conseguimos citar documentação oficial que comprove esse entendimento?

**Comment by oximer** [comment]
1. Não faz diferença a ordem de instalação
2. É checado de tempo em tempo, inclusive é razão de bugs constante. Se o usuário instala o a aplicativo e a ocorre um erro de conexão a internet, muitas vezes não ocorre a associação entre url e app. Não fica claro quando o OS checa novamente, mas eventualmente ele checa.
3.No iOS não existe essa escolha de preferencia. A preferencia é feita pela ordem do AASA. Acredito que se um novo aplicativo for instalado, a ordem do AASA passa a ser respeita. Entretanto, não fiz testes sobre o assunto apenas li a documentação  e forums.
4.Entendo que não. Uma alternativa seria o usuário cair no site do Bacen, escolher o app de preferencia no site do Bacen  e o usuário fazer um redict vira urlscheme para o app do banco escolhido. A experiência ficaria prejudicada, mas teríamos isonomia.
5.Restrita ao iOS
6.O @felipecn já colocou o trecho da documentação.

**Comment by tfalencar** [comment]
https://developer.apple.com/videos/play/wwdc2020/10146/ https://developer.apple.com/videos/play/wwdc2020/10098/ são relevantes para este tema.

**Comment by oximer** [comment]
@tfalencar assisti ao conteúdo. Ambos os vídeos são legais, mas não respondem a algumas das questões levantadas.
Continuamos com problemas para tratar links quando o cliente tiver mais de um banco/fintech instalado no celular.

@felipecn essa experiencia de redirect que você mostro no caso do submarino acontece em um muitos casos por causa de analytics. Muitas empresas contratam soluções de marketing e querem fazer tracking da conversão dos links para calcular CAC e ROI de campanhas.

Como eu disse redirect pode ser um caminho, prejudicaríamos a experiencia em troca de isonomia.
Mas exigiria uma implementação do BACEN, para guardar preferência por usuário (estrutura de cookie), criar database para relacionar banco a um urlscheme....

Alguma outra alternativa?

**Comment by oximer** [comment]
Pessoal estive pensando que o modelo atual de iniciação não permite o pagamento por link no mundo WEB.
Dado que o manual de iniciação por link diz que o link será no padrão:

> https://pix.bcb.gov.br/qr/MDAwMjAxMDEwMjEyMjY3MjAwMTRici5nb3Yu
> YmNiLnBpeDI1NTBieC5jb20uYnIvcGl4LzhiM2RhMmYzLTlhNDEtNDBkMS1h
> OTFhLWJkOTMxMTNiZDQ0MTUyMDQwMDAwNTMwMzk4NjU0MDYxMjMuNDU1ODAy
> QlI1OTEzRnVsYW5vIGRlIFRhbDYwMDhCUkFTSUxJQTYyMTkwNTE1UlAxMjM0
> NTY3OC0yMDE5NjMwNDQ1QzgK

Se eu enviar um link de cobrança por email para você, se você tiver no desktop trabalhando, você não consegue pagar sem utilizar um celular. Esse cenário é muito ruim principalmente para PJs.

Acredito que a alternativa para esse caso seja realmente o BACEN no site _pix.bcb.gov.br_ criar uma estrutura de redirecionando para o internet banking dos player cadastrados no sistema. O usuário salvaria sua preferência e o BACEN faria o redirect. O BACEN teria que manter um banco de dados com CHAVE/VALOR com o endereço/domínio de internet banking de cada banco/fintech no país.

Essa solução trataria até mesmo o problema do PIX link no iOS descrito nessa issue.
Dado que ao fazer o redirect, o usuário mobile poderia ser redirecionado via url-scheme para o app do banco.

Evidentemente a usabilidade no mundo iOS ficaria um levemente pior que a experiência no Android.
O usuário teria esse quebra molas de ao clicar no link, abrir o browser e do browser ser redirecionado app.

Nesse primeiro momento, o BACEN nem precisaria criar um sistema complexo de login ou identificação. 
A escolha do usuário poderia ficar salva no cache. 
Trocou a máquina ou usou aba anônima, ele tem que selecionar o banco do redirect novamente.

Me preocupa essa indefinição a poucos dias do lançamento dado que essa questão é bastante estrutural.
Estou a disposição para discussão de outros possíveis soluções.

**Comment by ninrod** [comment]
@oximer , essa situação no desktop está sendo endereçada. Devem sair definições sobre essa questão nas próximas versões do manual de UX. 

A respeito da questão de isonomia envolvendo links, também está sendo endereçada. Por isso estou deixando a issue em aberto.

**Comment by oximer** [comment]
Tem previsão de data para essa nova versão?

**Comment by ninrod** [comment]
Não posso relatar nada oficial quanto a isso, mas posso adiantar que deve sair em breve. Já se encontra em estágio de revisão.

**Comment by oximer** [comment]
@ninrod não seria legal já trazer para discutir na comunidade? 
Talvez possamos já antecipar eventuais problemas.

**Comment by ninrod** [comment]
@oximer , nesse sentido que você pontuou, será exposta uma versão para consulta aos participantes em que o mercado terá tempo para apontar problemas e enviar feedbacks, como de praxe.

**Comment by oximer** [comment]
@ninrod a especifição final do PIX sai no dia 14 de agosto né?
Vamos ter interações sobre o assunto depois da versão final?
Estamos preocupados com o impacto no desenvolvimento para entrega com prazo estipulado  pelo BACEN.

**Comment by ninrod** [comment]
Pessoal, eu gostaria de agradecer por vocês terem levantado essa issue. Ela chegou até os mais altos níveis no BCB e foi seriamente discutida. Entendemos a preocupação com o prazo e isso será levado em consideração. 

Muito em breve o mercado será informado quanto a providências nesse contexto.

**Comment by oximer** [comment]
Depois do [relatório final ](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II_ManualdePadroesparaIniciacaodoPix-versao1.pdf) ficamos sem a opção de pagamento por link até sentarmos e pensar em uma maneira de tratar esse bug apresentado. É isso?

Me coloco a disposição para pensarmos uma solução para o problema.

**Comment by ninrod** [comment]
@oximer , exatamente, o Banco central optou por não apresentar essa funcionalidade no momento devido, em parte, aos problemas apresentados na presente issue. Obrigado a todos que contribuiram aqui.

**Comment by objectivecosta** [comment]
Pessoal, li essa discussão a partir de um tweet. Uma alternativa possível seriam file-types, dado que ambos os OSs oferecem seletores de apps para abertura de arquivos de um mimetype específico e mais de um app pode se registrar para fazer isso. Assim, arquivos .pixtransaction ou qualquer extensão que quiserem podem ser utilizados para esse fim.

**Comment by miguelslemos** [comment]
@objectivecosta um extensão nova poderia gerar varios problemas, pois não é comum, servidores e-mails poderia considerar como virus e a visualização desse arquivo no whatsapp também não teria thumbnail.

**Comment by objectivecosta** [comment]
> @objectivecosta um extensão nova poderia gerar varios problemas, pois não é comum, servidores e-mails poderia considerar como virus e a visualização desse arquivo no whatsapp também não teria thumbnail.

Servidores de e-mail já fazem filtros por URLs, então o mesmo poderia ser dito de URLs. Quanto a thumbnail no WhatsApp, acho que isso é um problema que o WhatsApp deveria/não deveria consertar de acordo com eles...

**Comment by miguelslemos** [comment]
Um solução poderia ser o SDK feito pelo bacen onde todos os PSP implementariam e nele teria a listagem de todos bancos e os respectivos schemas para abertura de deeplink. Então seria um tela comum em todos os Apps que apenas faria routing para o App escolhido, outro ponto é que possivel fazer caching das listas de PSP ficando uma experiencia melhor que abrir uma pagina web.

**Comment by oximer** [comment]
SDK esbarraria na tecnologia Webapp e na experiência.
Apesar que o modelo anterior já esbarrava.
Acredito que a melhor alternativa seja algo agnóstico que permita que qualquer empresa se plugar na solução.
Nessa aspecto a web se destaca.

A idéia de redirect para url-schemes específicos por banco com caching da opção salva com é uma opção.
Entretanto, a parte de segurança ficaria comprometida, dado que um ataque de DNS poisoning poderia comprometer a percepção de segurança do usuário.

Na live ontem falaram em compartilhar o QRCode como arquivo PDF para ser aberto pelos aplicativos.
Pode funcionar também apesar de onerar a rede e ter uma usabilidade bem pior que link com redirect.
Exige uma maturidade digital maior.

Temos um problema complexo dado a limitação das plataformas.

**Comment by ninrod** [comment]
@objectivecosta 

> @ninrod Uma alternativa possível seriam file-types, dado que ambos os OSs oferecem seletores de apps para abertura de arquivos de um mimetype específico e mais de um app pode se registrar para fazer isso. Assim, arquivos .pixtransaction ou qualquer extensão que quiserem podem ser utilizados para esse fim.

O problema como os file-types (tipo uma extension .pix) é que o link não é "renderizado" por padrão. depende do app. Outro problema é que qualquer app pode dizer que abre um arquivo do tipo .pix. 

@miguelslemos: 

> Um solução poderia ser o SDK feito pelo bacen onde todos os PSP implementariam e nele teria a listagem de todos bancos e os respectivos schemas para abertura de deeplink. Então seria um tela comum em todos os Apps que apenas faria routing para o App escolhido, outro ponto é que possivel fazer caching das listas de PSP ficando uma experiencia melhor que abrir uma pagina web.

 ideia interessante ,mas penso que seria complicado de operacionalizar considerando todas as diferentes arquiteturas utilizadas pelos diferentes PSPs do mercado brasileiro. Além disso, o BCB teria que criar uma equipe para manter esse produto. Além disso, esse SDK limitaria de alguma forma a evolução dos apps dos PSPs. 

Enfim, essa funcionalidade foi removida em um primeiro memomento, mas está em nosso radar. Alguns caminhos estão sendo pensados. 

Vou manter a issue aberta para que a comunidade não pense que essa é uma questão fechada e para encorajar contribuições.

**Comment by rubenskuhl** [comment]
E se o pix fosse um URL-Scheme, da forma pix://psp.example ? Os problemas apontados para domínios no tópico se aplicariam também ?

**Comment by objectivecosta** [comment]
> E se o pix fosse um URL-Scheme, da forma pix://psp.example ? Os problemas apontados para domínios no tópico se aplicariam também ?

Sim, até onde sei. Infelizmente.

**Comment by ninrod** [comment]
@rubenskuhl , 

> E se o pix fosse um URL-Scheme, da forma pix://psp.example ? Os problemas apontados para domínios no tópico se aplicariam também ?

O problema do URL-scheme é semelhante: você não tem uma garantia de que o link é "renderizado". Pode testar nos seus aplicativos de mensagem. Outro problema também é que qualquer app pode dizer que abre um URI do tipo `pix://o_payload_vai_todo_aqui`.

**Comment by rubenskuhl** [comment]
A possibilidade que vejo então seria um app do BACEN que abriria os links de https://pix.example, e só ele estaria autorizado a fazer isso; o app identificaria quais dos apps autorizados estão instalados e daria opção de escolha entre esses apps para conclusão da transação.

**Comment by ninrod** [comment]
Uma solução incluindo um "aplicativo centralizado redirecionador", também foi pensada. Funciona, mas obrigaria o usuário a instalar mais um aplicativo. Também tem um custo de implementação e manutenção.

**Comment by rubenskuhl** [comment]
Eu acho o aplicativo redirecionador uma melhor UX do que PDF...

**Comment by ninrod** [comment]
@rubenskuhl, 

> Eu acho o aplicativo redirecionador uma melhor UX do que PDF...

Eu concordo com você, mas tem que ser considerados outros elementos, além de UX, que envolvem é timing, custo e risco. 

Além disso, mesmo na esfera de UX, tem que ser considerado que o usuário será obrigado a instalar um app PIX. 

Adicionalmente, há uma questão de segurança envolvendo app links, falando especificamente de Android.  É mais flexível e menos seguro do que Universal Links. 

No app links, qualquer app consegue dizer que gerencia um pix link e funciona. Não adianta o BCB estabelecer uma lista restrita em um arquivo https://pix.bcb.gov.br/.well-known/assetlinks.json

**Comment by rubenskuhl** [comment]
Eu tenho a sensação de que ter o pix.br/well-known/assetlinks.json e o pix.br/well-known/apple-app-site-association só com o app do BACEN tem os mesmos riscos que o PDF, mas com UX melhor. A mesma possibilidade de interceptar um Pix se aplica ao PDF. 
(e sim, o domínio poderia ser pix.br ao invés de pix.bcb.gov.br...)

**Comment by rubenskuhl** [comment]
Eu estava lendo a apresentação do último fórum Pix, que cita geolocalização para localizar estabelecimentos que tenham Saque Pix. Isso provavelmente ficaria melhor com um app; esse mesmo app poderia ser responsável por tratar o Pix Link (como única aplicação autorizada) e então acionar as aplicações autorizadas pelos PSPs pagadores.

**Comment by ninrod** [comment]
Caros tendo em vista a consulta realizada pelo BCB trazendo alternativas ao link para pagamento, vou tomar a liberdade de fechar essa issue. Obrigado a todos pelas contribuições.

**Comment by rubenskuhl** [comment]
https://tools.ietf.org/html/rfc8905 tem formas padronizadas de construção de link de pagamento com o método payto. Há inclusive um utilizado no primo indiano do Pix, o UPI. 

O do Pix poderia ser algo
payto://pix/chave?amount=BRL:200&TxID=TxID
(Estático)
ou
payto://pix/?link=https://{fdqnPSPRecebedor}/{pixEndpoint}/v2/{pixUrlAcessToken}
(Dinâmico)

**Comment by ninrod** [comment]
@rubenskuhl 

> https://tools.ietf.org/html/rfc8905 tem formas padronizadas de construção de link de pagamento com o método payto. Há inclusive um utilizado no primo indiano do Pix, o UPI.

Também já tínha sido mapeado. O problema é que qualquer aplicativo pode dizer que abre links do tipo `payto`. Além disso, esse link não é "renderizado" por padrão nos apps.

**Comment by renatofrota** [comment]
> @rubenskuhl
> 
> > https://tools.ietf.org/html/rfc8905 tem formas padronizadas de construção de link de pagamento com o método payto. Há inclusive um utilizado no primo indiano do Pix, o UPI.
> 
> Também já tínha sido mapeado. O problema é que qualquer aplicativo pode dizer que abre links do tipo `payto`. Além disso, esse link não é "renderizado" por padrão nos apps.

@ninrod 

Está prevista a obrigatoriedade (ou autorizada a disponibilização pelos PSPs) de suporte à leitura de QR Codes a partir de uma imagem salva no dispositivo ou da área de transferência? Assim os usuários poderiam copiar a imagem do QR Code ou mesmo "tirar um print da tela" e depois abrir essa imagem (ou colar a imagem QR) com o app para enviar um Pix (adicionalmente à possibilidade já prevista de copiar a string do QR Code)?

Pensei nisso hoje ao fazer um pagamento de boleto. Copiei a linha digitável e o app do banco reconheceu automaticamente que o conteúdo da área de transferência era uma LD de boleto, sugerindo o pagamento do mesmo.

**Comment by ninrod** [comment]
bom dia @renatofrota , 

> Pensei nisso hoje ao fazer um pagamento de boleto. Copiei a linha digitável e o app do banco reconheceu automaticamente que o conteúdo da área de transferência era uma LD de boleto, sugerindo o pagamento do mesmo.

Está prevista sim a obrigatoriedade de implementação, por parte dos PSPs pagadores, da funcionalidade "Pix Copia e Cola". Que seria justamente algo como "a linha digitável". O que é copiado é a string do BR Code.

**Comment by renatofrota** [comment]
> bom dia @renatofrota ,
> 
> > Pensei nisso hoje ao fazer um pagamento de boleto. Copiei a linha digitável e o app do banco reconheceu automaticamente que o conteúdo da área de transferência era uma LD de boleto, sugerindo o pagamento do mesmo.
> 
> Está prevista sim a obrigatoriedade de implementação, por parte dos PSPs pagadores, da funcionalidade "Pix Copia e Cola". Que seria justamente algo como "a linha digitável". O que é copiado é a string do BR Code.

bom dia, @ninrod 

Pois então, na mensagem acima eu citei isso:

> adicionalmente à possibilidade já prevista de copiar a string do QR Code

Uma __imagem__ do QR Code, poderia ser lida em formato de arquivo (ou da área de transferência) pela mesma lib que avalia a imagem capturada pela câmera do dispositivo.

É até relativamente simples fazer com que a string do QR Code seja copiada para a área de transferência com um mero clique, em se tratando dos navegadores mobile (só um comandinho JS e pronto).

Mas poder ler diretamente uma imagem em formato de QR Code facilitaria, por exemplo, o pagamento de QR Codes enviados por aplicativos de mensagem ou por e-mail ("mídias" onde a string do QR Code em formato texto vão, muito provavelmente, se quebrar, especialmente quando esta contiver os `***` previstos para reserva de campo txid sem conteúdo).
