### ISSUE TITLE
[Problema] no [DICT] - Problema ao Listar Reivindicações

### ISSUE THREAD

**Issue by fCamargosRibeiro** [bacen/pix-perguntas-e-respostas#74]
Prezados,
Temos uma dúvida em relação a Listar Reinvindicações e Consultar Reinvindicação, conforme a divergência de dados apresentada abaixo em ambas.

Ao listar as reivindicações em que somos doador ou reivindicador [GET Listar Reivindicações] estamos recebendo na lista as seguintes informações para o “id: f2aa2f09-111d-4de7-92ed-95ce957a5eae” e sem vínculo ao nosso ISPB.

{

      "type": "OWNERSHIP",

      "key": "renato.santos@grupopan.com",

      "keyType": "EMAIL",

      "claimerAccount": {

        "participant": "59588112",

        "branch": "0001",

        "number": "0001",

        "type": "CACC"

      },

      "claimer": {

        "type": "NATURAL_PERSON",

        "taxIdNumber": "03658978090",

        "name": "leo"

      },

      "donorParticipant": "59285411",

      "id": "f2aa2f09-111d-4de7-92ed-95ce957a5eae",

      "claimStatus": "OPEN",

      "resolutionPeriodEnd": "2020-07-15T18:24:00Z",

      "completionPeriodEnd": "2020-07-22T18:24:00Z",

      "lastModified": "2020-07-08T18:24:07.784Z"

    },

 

 

Entretanto, quando excutamos a consulta de reivindicação [GET Consultar Reivindicações] para o mesmo “id: f2aa2f09-111d-4de7-92ed-95ce957a5eae”, recebemos informações divergentes no <claimerAccount> e <claimer> para a Reivindicação aberta e no <claimerAccount> com o nosso ISPB.

 

{

  "claim": {

    "type": "OWNERSHIP",

    "key": "renato.santos@grupopan.com",

    "keyType": "EMAIL",

    "claimerAccount": {

      "participant": "01181521",

      "branch": "0101",

      "number": "000240",

      "type": "CACC"

    },

    "claimer": {

      "type": "NATURAL_PERSON",

      "taxIdNumber": "36918323857",

      "name": "CARTAO TESTE AQN"

    },

    "donorParticipant": "59285411",

    "id": "f2aa2f09-111d-4de7-92ed-95ce957a5eae",

    "claimStatus": "OPEN",

    "resolutionPeriodEnd": "2020-07-15T18:24:00Z",

    "completionPeriodEnd": "2020-07-22T18:24:00Z",

    "lastModified": "2020-07-08T18:24:07.784Z"

  }
}

**Comment by Leonardo34** [comment]
Vou contribuir para essa thread do que aparenta ser um bug. Os dados de claimer e owner que estão sendo listados aqui são meus: 

```
{
  "type": "OWNERSHIP",

  "key": "renato.santos@grupopan.com",

  "keyType": "EMAIL",

  "claimerAccount": {

    "participant": "59588112",

    "branch": "0001",

    "number": "0001",

    "type": "CACC"

  },

  "claimer": {

    "type": "NATURAL_PERSON",

    "taxIdNumber": "03658978090",

    "name": "leo"

  },

  "donorParticipant": "59285411",

  "id": "f2aa2f09-111d-4de7-92ed-95ce957a5eae",

  "claimStatus": "OPEN",

  "resolutionPeriodEnd": "2020-07-15T18:24:00Z",

  "completionPeriodEnd": "2020-07-22T18:24:00Z",

  "lastModified": "2020-07-08T18:24:07.784Z"

}
```

É justamente o ISPB da instituição em que trabalho, e os dados de account e claimer que estão ali são meus. @fCamargosRibeiro  se puderes detalhar melhor a requisição que originou o problema, para que a equipe do Bacen possa simular seria interessante, pois este problema me preocupa. São dados meus em uma reivindicação de posse da qual eu nunca fiz.

**Comment by fCamargosRibeiro** [comment]
Então @Leonardo34 a gente usou o serviço de Listar Reivindicações passando o ISPB do Sicredi, sem usar os outros filtros, sobre ser seus dados, talvez sua if tenha usado para fazer essa operação de teste, como algumas instituições estão fazendo teste em conjunto.

**Comment by luizlaydner** [comment]
@fCamargosRibeiro  Não conseguimos reproduzir a situação que você relatou. Se você conseguir reproduzir, por favor nos informe! 
Além disso, como não guardamos no DICT os xmls das respostas enviadas, apenas os recebido dos PSPs, ajudaria também ter o xml da resposta incoerente.
