### ISSUE TITLE
[Problema] no [DICT] - Listar Eventos de CIDs - Retorno de erro inválido

### ISSUE THREAD

**Issue by gabrielmendesbb** [bacen/pix-perguntas-e-respostas#75]
Na transação **Listar Eventos de CIDs**
Quando retorna um erro (tag Problem), não está vindo a tag "type"
De acordo com o manual a tag type deveria ser obrigatória.

Segue um exemplo de retorno:
&lt;problem xmlns=\"urn:ietf:rfc:7807\"&gt;
&lt;ds:Signature&gt;&lt;/ds:Signature&gt;
&lt;title&gt;Bad Request&lt;/title&gt;
&lt;status&gt;400&lt;/status&gt;
&lt;detail&gt;Invalid parameters&lt;/detail&gt;
&lt;correlationId&gt;eb54f147a3b7e5c16959733243602e5a&lt;/correlationId&gt;
&lt;violations&gt;
   &lt;violation&gt;
     &lt;reason&gt;Failed to convert property value of type java.lang.String to required type br.gov.bcb.dict.api.v1.model.KeyType for property KeyType; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@javax.validation.constraints.NotNull @javax.validation.Valid br.gov.bcb.dict.api.v1.model.KeyType] for value XXX; nested exception is java.lang.IllegalArgumentException: No enum constant br.gov.bcb.dict.api.v1.model.KeyType.XXX&lt;/reason&gt;
	 &lt;value&gt;XXX&lt;/value&gt;
	 &lt;property&gt;KeyType&lt;/property&gt;
  &lt;/violation&gt;
  &lt;violation&gt;
    &lt;reason&gt;must not be null&lt;/reason&gt;
    &lt;property&gt;keyType&lt;/property&gt;
  &lt;/violation&gt;
&lt;/violations&gt;
&lt;/problem&gt;

**Comment by luizlaydner** [comment]
Obrigado por reportar! Correção estará disponível em breve.
Nesse caso a tag `<type>` será `https://dict.pi.rsfn.net.br/api/v1/error/BadRequest`
