### ISSUE TITLE
Problema no DICT - Erro Verificar Sincronismo (reason: must not be null)

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-perguntas-e-respostas#76]
**Descreva sua dúvida ou problema**
Estamos com problemas na realização do Verificar sincronismo, estamos recebemos o seguinte erro, reason: must not be null, mas na documentação v1-rc4 não existe a especificação da tag reason para envio na chamada.

**Sistema ou Área**
DICT

**Identificador do Problema**
Correlation-Id: 46E891E0FD0D49C8B426C082A6F33D3B

**Mensagens Enviadas / Recebidas**
XML Enviado
<CreateSyncVerificationRequest>
	<SyncVerification>
		<Participant>21332862</Participant>
		<KeyType>EVP</KeyType>
		<SyncVerifier>75142cef4e3addd1a81c15d24dd46885d14c2bca8453efc2c7a0aa09725150f4</SyncVerifier>
	</SyncVerification>
</CreateSyncVerificationRequest>

XML Recebido
<problem>
	<title>Bad Request</title>
	<status>400</status>
	<detail>Invalid parameters</detail>
	<correlationId>46E891E0FD0D49C8B426C082A6F33D3B</correlationId>
	<violations>
		<violation>
			<reason>must not be null</reason>
			<property>syncVerification.participantSyncVerifier</property>
		</violation>
	</violations>
</problem>

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1-rc4/sync-verifications/

**Comment by judahreis** [comment]
@evertongodoi, o campo SyncVerifier da versão RC3 mudou para ParticipantSyncVerifier na RC4, para deixar claro que o campo é o valor informado pelo participante. O exemplo na API ainda está errado (ainda usa SyncVerifier), mas na estrutura já está mapeado o ParticipantSyncVerifier. Vamos corrigir o exemplo na API, mas vc já pode renomear o parâmetro.
