### ISSUE TITLE
Problema no SPI - Documentação XLSX divergente com o XSD

### ISSUE THREAD

**Issue by alexandredsimoes** [bacen/pix-perguntas-e-respostas#77]
Na mensagem CAMT054, o campo **AddtlTxInf** é especificado como PioridadePagamento
![image](https://user-images.githubusercontent.com/5480346/87709357-88022180-c77a-11ea-9221-84f9b2d7adec.png)

já no XSD ele é definido como exibido na imagem abaixo: 
![image](https://user-images.githubusercontent.com/5480346/87709256-5ee19100-c77a-11ea-95c8-9e15dcf35a63.png)

Já a tag **AddtlNtryInf** que no XLSX está como CodigoErro, tem a seguinte especificação no XSD
![image](https://user-images.githubusercontent.com/5480346/87709590-df07f680-c77a-11ea-9e7b-671b9a0070f6.png)
![image](https://user-images.githubusercontent.com/5480346/87709694-019a0f80-c77b-11ea-9032-cad75e31ac35.png)

**Sistema ou Área**
SPI

**Identificador do Problema**
Acho que existe um erro na documentação pois no XSD a tag **AddtlNtryInf** está apontando o tipo para a enumeração de prioridade e não o código de erro conforme  a documentação XLSX.

**Comment by LeoGonCha** [comment]
@alexandredsimoes Realmente houve uma alteração nesses campos na versão 1.6 do catalogo, gerando a versão 1.2 da camt.054.

A correção deverá ser disponiblizada na próxima versão do catálogo de mensagens.

**Comment by ninrod** [comment]
resolvido com a publicação do catálogo v1.11
