### ISSUE TITLE
[Problema] no [DICT] -  Listar Reivindicações não aceita um array de Status no Query Parameters.

### ISSUE THREAD

**Issue by lucasjmatias** [bacen/pix-perguntas-e-respostas#78]
**Descreva sua dúvida ou problema**
Listar Reivindicações não aceita um array de Status no query Parameters.

No passo 5 do Fluxo de portabilidade no documento de especificações é descrito que:
_PSP reivindicador deve esperar a atualização de status. Para isso, deve, uma vez por minuto, consultar o DICT sobre o status dos pedidos em que é reivindicador, atualizando-se dos pedidos **"Cancelados" ou "Confirmados"(não é necessário consultar individualmente)**._

Porém, ao tentar consultar ambos os status em uma só solicitação, só recebemos o retorno do primeiro status.
Dado nosso limite de requisições, a listagem por ambos status é mais fácil de se gerenciar. 

**Sistema ou Área**
DICT

**Identificador do Problema**
O resultado retornado é somente para o primeiro parâmetro de Status passado, quando o esperado seria para todos os status passados. Visto que o parâmetro Status é opcional, não vejo motivo para não aceitar mais de um.

Com a requisição abaixo:
**?Participant=00000208&IsDonor=false&IsClaimer=true&Status=CONFIRMED&Status=CANCELLED&Limit=100**

**URL de conexão**
https://dict-h.pi.rsfn.net.br/api/v1/claims/?Participant=00000208&IsDonor=false&IsClaimer=true&Status=CONFIRMED&Status=CANCELLED&Limit=100

**Comment by luizlaydner** [comment]
A especificação da API hoje limita a somente um status. Vamos avaliar sua sugestão de permitir vários.

**Comment by judahreis** [comment]
@lucasjmatias, sua sugestão foi atendida na RC6, já disponível no ambiente de homologação.
