### ISSUE TITLE
[Problema] no [DICT] - Chave cadastrada como LEGAL_PERSON e DICT retorna NATURAL_PERSON

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#79]
Olá! Percebemos que quando cadastramos uma chave onde o tipo de pessoa é pessoa jurídica (LEGAL_PERSON), o DICT está gravando como pessoa física (NATURAL_PERSON).

Poderiam, por favor, verificar?

Abaixo segue o request enviado e o response recebido.

**Sistema ou Área**
DICT

**Identificador do Problema**

Request Id: 1ec6064b-69ed-40d8-b999-6c0e94663828

**Request**

`<CreateEntryRequest><Entry><Account><AccountNumber>67642</AccountNumber><AccountType>CACC</AccountType><Branch>9914</Branch><Participant>13370835</Participant></Account><Key>+5531984978132</Key><KeyType>PHONE</KeyType><Owner><Name>Giovanni e Geraldo Construcoes Ltda</Name><TaxIdNumber>67642543000183</TaxIdNumber><TradeName/><Type>LEGAL_PERSON</Type></Owner></Entry><Reason>USER_REQUESTED</Reason><RequestId>1ec6064b-69ed-40d8-b999-6c0e94663828</RequestId>`

**Response**

`<ds:X509Data><ds:X509IssuerSerial><ds:X509IssuerName>CN=Autoridade Certificadora do SERPRO Final SSL, OU=Servico Federal de Processamento de Dados - SERPRO, OU=CSPB-1, O=ICP-Brasil, C=BR</ds:X509IssuerName><ds:X509SerialNumber>66906355272994040667436154809</ds:X509SerialNumber></ds:X509IssuerSerial></ds:X509Data></ds:KeyInfo></ds:Signature><Entry><Key>+5531984978132</Key><KeyType>PHONE</KeyType><Account><Participant>13370835</Participant><Branch>9914</Branch><AccountNumber>67642</AccountNumber><AccountType>CACC</AccountType></Account><Owner><Type>NATURAL_PERSON</Type><TaxIdNumber>67642543000183</TaxIdNumber><Name>Giovanni e Geraldo Construcoes Ltda</Name></Owner><CreationDate>2020-07-17</CreationDate><KeyOwnershipDate>2020-07-17</KeyOwnershipDate></Entry></CreateEntryResponse>" 
`

**Comment by luizlaydner** [comment]
Há de fato bug na geração da resposta. Vamos corrigir.
Muito obrigado @monise !

**Comment by HenriqueSimoes82** [comment]
@monise 
Problema corrigido. Pode testar novamente. Obrigado pelo reporte detalhado.

**Comment by monise** [comment]
@HenriqueSimoes82 obrigada pelo retorno!! Para realizarmos esse teste, precisamos da correção da issue #96.
