### ISSUE TITLE
Problema no DICT - "Bad Request - Claim type inconsistent" ao tentar realizar reivindicação de posse

### ISSUE THREAD

**Issue by Leonardo34** [bacen/pix-perguntas-e-respostas#8]
**Descreva sua dúvida ou problema**
Estou com problema ao realizar uma reivindicação de posse de uma chave do tipo EMAIL. 

**Sistema ou Área**
DICT

**Identificador do Problema**
Correlation-Id: **21EBC3800A204F249C0C3CE1B2F40029**. 
Solicitação feita pelo ISPB: 59588111 (o claimer da reivindicação que tentei criar foi o ISPB virtual, 59588112)
Data requisição: 2020-06-22 20:35

**Mensagens Enviadas / Recebidas**

```
<?xml version="1.0" encoding="UTF-8"?>
<CreateClaimRequest xmlns:ns2="http://www.w3.org/2000/09/xmldsig#">
   <Claim>
      <Type>OWNERSHIP</Type>
      <Key>teste_happy@gmail.com</Key>
      <KeyType>EMAIL</KeyType>
      <ClaimerAccount>
         <Participant>59588112</Participant>
         <Branch>0001</Branch>
         <AccountNumber>543210</AccountNumber>
         <AccountType>CACC</AccountType>
      </ClaimerAccount>
      <Claimer>
         <Type>NATURAL_PERSON</Type>
         <TaxIdNumber>03658978090</TaxIdNumber>
         <Name>Leonardo  Morais</Name>
      </Claimer>
   </Claim>
</CreateClaimRequest>
```

**URL de conexão**
POST -> https://dict-h.pi.rsfn.net.br/api/v1/claims/

**Dados adicionais**
Na sequência deste teste consegui cadastrar uma reivindicação de portabilidade para a mesma chave.

**Comment by judahreis** [comment]
Leonardo,

* Troca de chave entre owners diferentes (com ou sem troca de participante) --> Reivindicação de Posse. 
* Troca de chave entre participantes diferentes (sempre para um mesmo owner) --> Portabilidade.

No seu caso, a chave estava cadastrada para o TaxIdNumber 03658978090, e foi reivindicada pelo mesmo owner.

**Comment by Leonardo34** [comment]
Perfeito, não tinha me atentado para este cenário. Acredito que talvez a mensagem não tenha ficado tão clara.

`"Bad Request - Claim type inconsistent"`

Talvez explicitar o porque a operação é inválida, enfim, apenas uma sugestão. Obrigado pelo rápido retorno.
