### ISSUE TITLE
[Dúvida] no [DICT] - Exclusão de chave em portabilidade/reivindicação

### ISSUE THREAD

**Issue by PamelaFabiao** [bacen/pix-perguntas-e-respostas#80]
Se uma chave estiver em processo de portabilidade ou reivindicação e o usuário dono da chave resolver efetuar a exclusão da chave na IF que inicialmente estiver cadastrada, qual retorno receberemos do processo de portabilidade/reivindicação?

**Comment by farito** [comment]
@PamelaFabiao 

Na api do DICT tem un ERRO que e:

**EntryLockedByClaim**

`Existe uma reivindicação com status diferente de concluída ou cancelada para a chave do vínculo. Enquanto estiver nessa situação, o vínculo não pode ser excluído.`

Nao vai poder excluí a chave ate finalize o proceso de portabilidade ou reivindicação

**Comment by luizlaydner** [comment]
Obrigado @farito !
