### ISSUE TITLE
[Dúvida] no [DICT] - Exclusão por inatividade de chave

### ISSUE THREAD

**Issue by PamelaFabiao** [bacen/pix-perguntas-e-respostas#82]
Nos manuais temos o direcionamento de realizar a exclusão de chave por inatividade de uso após 12 meses, porém não é de obrigatoriedade a informação do tipo de chave que está sendo meio de realização de transação no PIX.
Com isso, como poderemos proceder com a exclusão sem saber por qual chave o usuário está recebendo créditos no PIX?

**Comment by luizlaydner** [comment]
Peço que encaminhe esse questionamento ao email pix@bcb.gov.br

**Comment by douglasjunior** [comment]
@PamelaFabiao vc obteve uma resposta para essa dúvida?
