### ISSUE TITLE
[Dúvida] no [DICT] - Chave EVP

### ISSUE THREAD

**Issue by PamelaFabiao** [bacen/pix-perguntas-e-respostas#83]
Sobre a chave EVP:
- Qual a quantidade máxima de chave EVP que posso gerar por conta?
- A chave EVP terá validade? 
- Se a chave EVP não for usada pelo período de 12 meses teremos que excluir ela do DICT?
- Devemos considerar a chave EVP dentro da quantidade de 5 chaves para PF e 20 chaves para PJ?
- Quando utilizada uma chave EVP para transação no PIX, qual informação de retorno o DICT dará sobre os dados dos usuários?

**Comment by luizlaydner** [comment]
> Qual a quantidade máxima de chave EVP que posso gerar por conta?

Há um limite máximo de chaves, independente do tipo, que podem ser associadas a uma conta+titular.
No caso de chaves do tipo EVP, não há limite de geração de novos EVPs, contanto que o limite máximo de vínculos seja respeitado. Significa que sempre é possível excluir EVPs para incluir EVPs novos.

> A chave EVP terá validade?

Atualmente, nenhum tipo de chave tem validade.

> Se a chave EVP não for usada pelo período de 12 meses teremos que excluir ela do DICT?

Peço que consulte o regulamento do DICT para essa pergunta, ou envie para pix@bcb.gov.br

> Devemos considerar a chave EVP dentro da quantidade de 5 chaves para PF e 20 chaves para PJ?

Sim.

> Quando utilizada uma chave EVP para transação no PIX, qual informação de retorno o DICT dará sobre os dados dos usuários?

Retornará as mesmas informações de outros tipos de chave.
