### ISSUE TITLE
[Dúvida] no [DICT] - Portabilidades Intra PSP

### ISSUE THREAD

**Issue by farito** [bacen/pix-perguntas-e-respostas#84]
**Descreva sua dúvida ou problema**
Portabilidad INTRA PSP, deberia ir por el mismo flujo que una portabilidad INTER psp? es decir llegar hasta DICT?

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
Para portabilidade intra-psp, é possível usar o _endpoint_ de [atualizar vínculo](https://github.com/bacen/pix-dict-api/blob/f85f14f40e1d4df0040b0769de729f5ebfc704af/openapi/openapi.yaml#L484) com razão `USER_REQUESTED`. Não há, no entanto, impedimento para uso do fluxo normal de portabilidade nesse cenário. 
Como é necessário manter os dados de vínculos do PSP e do DICT sincronizados, toda portabilidade intra-psp deverá ser refletida no DICT antes, de alguma forma.
