### ISSUE TITLE
[Dúvida] no [DICT] - Data antifraude asociada a chave

### ISSUE THREAD

**Issue by farito** [bacen/pix-perguntas-e-respostas#85]
**Descreva sua dúvida ou problema**
A informação associada a uma chave consultada ao DICT respeito de antifraude, vai estar disponible de alguma forma para as chaves locales ao PSP?

**Sistema ou Área**
DICT

**Comment by judahreis** [comment]
@farito , essa é uma melhoria possível, mas não estará disponível nas primeiras versões do serviço. Todas as informações de antifraude da chave são geradas a partir de Disputas nas quais o Participante é destinatário. Portanto, a melhoria será colocada no backlog, mas tem baixa prioridade.
