### ISSUE TITLE
[Dúvida] no [Iniciação de pagamento] - Universal Links e Iniciação da Pagamento por Link

### ISSUE THREAD

**Issue by oximer** [bacen/pix-perguntas-e-respostas#86]
**Descreva sua dúvida ou problema**
A iniciação da pagamento por Link prevê que usuário fará a escolha que qual app será utilizado para realizar o pagamento.
Entretanto, tal comportamento não existe no mundo iOS.
A atribuição dos apps compatíveis com um padrão de link se dá por meio de um cadastro no servidor do detentor do DNS.
Exemplo: https://www.bcb.gov.br/.well-known/apple-app-site-association

Nesse mesmo arquivo é escolhido a ordem de prioridade do app que abrirá o link.
Cliente que sejam multi-bancarizados ou possuam várias carteiras de pagamentos terão problemas para escolha do app que irá pagar.

Qual o tratamento será dado pelo BACEN para garantir isonomia?
Qual será o critério de ordem cadastrado no site `apple-app-site-association`

**Sistema ou Área**
Iniciação de Pagamentos

**Identificador do Problema**
Como garantir a isonomia

**Comment by ninrod** [comment]
@oximer, obrigado. Já existe uma issue aberta sobre o problema: #72. Vou te marcar lá para que você possa contribuir com as informações que estamos pedindo.
