### ISSUE TITLE
[Dúvida] no [DICT] - Confirmar Reivindicação

### ISSUE THREAD

**Issue by idutra** [bacen/pix-perguntas-e-respostas#87]
**Descreva sua dúvida ou problema**
De acordo com a documentação da DICT API versão  (1.0.0-RC4), no que diz respeito a confirmar uma reivindicação se a razão informada for `USER_REQUESTED,` o prazo de encerramento (`CompletionPeriodEnd`) será adiantado para permitir o encerramento imediato pelo reivindicador. A data referente ao prazo de encerramento deverá ser informado por quem estiver comandando a confirmação?

**Sistema ou Área**
DICT

**Comment by luizlaydner** [comment]
O DICT é quem define o novo prazo. Ao confirmar uma reivindicação de posse com razão `USER_REQUESTED` , CompletionPeriodEnd será colocado com a data-hora em que a confirmação foi feita. Com isso, reivindicador poderá concluir a reivindicação logo em seguida.

**Comment by luizlaydner** [comment]
Complementando: Existe também um tempo máximo (estará no "manual de tempos" a ser liberado ainda no site do BC) entre o usuário comandar confirmação e o participante fazer a ação no DICT.
