### ISSUE TITLE
[Dúvida] no [SPI] - Dúvida timeout Long Polling

### ISSUE THREAD

**Issue by adrianbp** [bacen/pix-perguntas-e-respostas#88]
**Descreva sua dúvida ou problema**
Bom dia!

No manual de interfaces de comunicação 1.2 na seção 2.2.2.7 está dizendo que a chamada da API GET aguarda por alguns segundos caso não haja mensagem disponível para o PSP antes de retornar um 204(No Content). Gostaria de saber quantos segundos o PSP  deveria aguardar o retorno da API no método GET neste cenário. 

**Sistema ou Área**
SPI

**URL de conexão**
GET  /api/v1/out/{ispb}/stream/start

**Comment by gstabel** [comment]
Olá, bom dia.
Realmente também não identificamos essa informação na documentação. Precisamos esse informação para definir o nossos _timeout_.
Nos testes em _homologação_ vimos que esse tempo está de 5 segundos.

Grato.
Gabriel

**Comment by cristianokbc** [comment]
O _timeout_ está configurado em 5 segundos atualmente. Há a possibilidade de aumento do valor no futuro, mas isso poderá ser melhor avaliado durante os testes de capacidade.

Não deve ser necessário ao participante controlar esse tempo. Entendemos que se demorar muito mais do que o normal, pode significar algum problema, e que deve ser útil avaliar isso.

O ideal é que o PSP, se desejar controlar o tempo, que o faça de forma configurável.
