### ISSUE TITLE
[Dúvida] DICT - Reconciliação

### ISSUE THREAD

**Issue by asflorencio** [bacen/pix-perguntas-e-respostas#89]
A partir do processo de reconciliação completa, temos uma dúvida no seguinte cenário, onde: 

A partir do batimento do arquivo com a base local do PSP, poderá haver divergências de dois tipos: (i) CIDs que existem somente no arquivo (e não na base do PSP); e (ii) CIDs que existem somente no PSP (e não no arquivo). 

Para o tipo (ii), podemos utilizar-se da operação de registro de vinculo para incluir no DICT (Bacen), entretanto, se essa chave não existente no arquivo e existente na base local do PSP for do tipo EVP, como fazer o processo de inclusão desta no DICT (Bacen)?

**Comment by judahreis** [comment]
@asflorencio, no cenário (ii) com EVP, a única opção é pedir a remoção da chave. O EVP é uma chave que tem mais restrições, para garantir a sua segurança. Somente o DICT gera o EVP. Se o DICT não possui um EVP (e o participante tem), significa que, em algum momento, o participante solicitou a remoção ou portabilidade do EVP.
