### ISSUE TITLE
[Dúvida] no [DICT] - Valida  posse da chave

### ISSUE THREAD

**Issue by simonevirgilio** [bacen/pix-perguntas-e-respostas#90]
No Manual de Especificações, o fluxo de reivindicação de posse demonstra no item 6-Valida posse da chave, onde após a reivindicação ser confirmada, o PSP reivindicador deverá fazer a validação ativa de posse da chave com o usuário final. Essa validação da posse da chave deverá ser efetuada novamente? Visto que no início do fluxo o usuário já é comunicado pelo PSP reivindicador.

**Sistema ou Área
DICT

**Comment by judahreis** [comment]
@simonevirgilio, seu entendimento está correto: é necessária uma segunda validação de posse. O intuito é prevenir "roubo" de chaves por um fraudador que conseguiu fazer a primeira validação por posse temporária da chave. A segunda validação garante que o usuário reivindicante tem posse da chave por, pelo menos, duas semanas. 
Essa modificação foi um pedido do GT de Segurança, formado pelos próprios participantes do arranjo, e foi acatado pelo Banco Central.

**Comment by esantanapr** [comment]
Relacionado a este tema, o manual Operacional do DICT apresenta que do ponto de vista do usuário doador, se quiser Cancelar o pedido de portabilidade ou reivindicação de posse da chave, deve previamente fazer a validação da chave.

No caso da portabilidade, visto que a chave pertence ao mesmo dono, é realmente necessário realizar a validação ativa de posse antes de o cliente doador solicitar o cancelamento?
