### ISSUE TITLE
[Dúvida] na [API Recebimento] - Obrigatoriedade do campo "pagador" na criação do Pagamento

### ISSUE THREAD

**Issue by dgnunes** [bacen/pix-perguntas-e-respostas#91]
**Descreva sua dúvida ou problema**
Olá,

Lendo o Swagger com a definição da API de Recebimento, ficamos com uma dúvida:

O campo pagador na rota "POST /document/" é mandatório ou não? A definição indica que caso o campo seja preenchido, os campos dos objetos PessoaFisica ou PessoaJuridica devem estar presentes. Porém não fica explícito se a presença em si desses objetos é obrigatória.
Obrigado.

**Sistema ou Área**
API Recebimento

**Comment by ninrod** [comment]
@dgnunes , vou fechar aqui por que já temos a mesma issue aberta [aqui](https://github.com/bacen/pix-api-recebimentos/issues/1).
