### ISSUE TITLE
Dúvida no Teste Homologatório - Mecanismo de proteção varredura DICT

### ISSUE THREAD

**Issue by kertony** [bacen/pix-perguntas-e-respostas#92]
O item:
3. Mecanismos de proteção à varredura do DICT e da base de dados interna dos participantes
   I – enviar declaração, para o e-mail dict@bcb.gov.br, com afirmação de que a realização de duas consultas sucessivas de uma mesma chave para endereçamento está gerando como resultado o mesmo “PI-EndUser” para ambas as consultas; e
Referencia o atributo "PI-EndUser”, contudo, não encontramos este nas documentações disponibilizadas. Pode orientar qual atributo da mensageria devemos usar? 

DICT

PI-EndUser

**Comment by judahreis** [comment]
@kertony, o nome do header foi corrigida na [carta circular 4070](https://www.bcb.gov.br/pre/normativos/busca/downloadNormativo.asp?arquivo=/Lists/Normativos/Attachments/51098/C_Circ_4070_v1_O.pdf). O nome correto é PI-EndUser.
