### ISSUE TITLE
[Problema] no [DICT] - Erro "Version not available"

### ISSUE THREAD

**Issue by gabrielmendesbb** [bacen/pix-perguntas-e-respostas#93]
Vi q hj foi publicada uma nova versão do DICT. Porem a anterior parou de funcionar.
Estou usando a penúltima versão (1.0.0-RC4). A ultima versão não é retro-compatíveis com a penúltima ?

Segue o erro:

`<type>https://dict.pi.rsfn.net.br/api/v1/error/BadRequest</type><title>Bad Request</title><status>400</status><detail>Version not available</detail><correlationId>33c794b4e4894f2c60d5b8947bc96a32</correlationId></problem>`

**Comment by judahreis** [comment]
@gabrielmendesbb, ela é retrocompatível. A versão 1.0.0-RC4 está disponível em /api/v1-rc4/ e a versão 1.0.0-RC5 em /api/v1-rc5/ . O caminho /api/v1/ deixou de estar disponível em homologação. Este será o caminho da versão 1.0.0 da API, quando ela estiver na versão que irá para produção.

**Comment by gabrielmendesbb** [comment]
Ok. mas na API da versao rc4 nao tem essa url (/api/v1-rc4). La ta /api/v1

**Comment by luizlaydner** [comment]
@gabrielmendesbb  Na especificação da RC4 o endereço ficou incorreto de fato.
