### ISSUE TITLE
[Dúvida] no [REDA.014] - Cadastro de Participante Indireto não está concluíndo

### ISSUE THREAD

**Issue by julianemelo1104** [bacen/pix-perguntas-e-respostas#94]
**Descreva sua dúvida ou problema**
Ao enviar uma REDA.014 o sistema retorna a REDA.016 sempre com a mensagem : CAI4 | Cadastro   Inexistente de participante indireto

**Sistema ou Área**
 SPI

**Identificador do Problema**
Mensagem enviada: M0118152120200723122828ohP6jSJU9

**Mensagens Enviadas / Recebidas**
"<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Envelope xmlns="https://www.bcb.gov.br/pi/reda.014/1.1">
	<AppHdr>
		<Fr>
			<FIId>
				<FinInstnId>
					<Othr>
						<Id>01181521</Id>
					</Othr>
				</FinInstnId>
			</FIId>
		</Fr>
		<To>
			<FIId>
				<FinInstnId>
					<Othr>
						<Id>00038166</Id>
					</Othr>
				</FinInstnId>
			</FIId>
		</To>
		<BizMsgIdr>M0118152120200723122828ohP6jSJU9</BizMsgIdr>
		<MsgDefIdr>reda.014.spi.1.1</MsgDefIdr>
		<CreDt>2020-07-23T12:28:28.566Z</CreDt>
	</AppHdr>
	<Document>
		<PtyCreReq>
			<MsgHdr>
				<MsgId>M0118152120200723122828ohP6jSJU9</MsgId>
				<CreDtTm>2020-07-23T12:28:28.566Z</CreDtTm>
			</MsgHdr>
			<Pty>
				<PtyId>
					<Id>
						<Id>
							<PrtryId>
								<Id>01181521</Id>
								<Issr>BCB</Issr>
							</PrtryId>
						</Id>
					</Id>
				</PtyId>
				<Tp>
					<Prtry>IDRT</Prtry>
				</Tp>
				<MktSpcfcAttr>
					<Nm>CNPJIDRT</Nm>
					<Val>33920559000199</Val>
				</MktSpcfcAttr>
			</Pty>
		</PtyCreReq>
	</Document>
</Envelope>"

**Comment by rodalvarenga** [comment]
Prezada, a mensagem REDA.014 é utilizada para cadastrar um participante indireto no SPI. 
Porém, esse participante já deve estar previamente cadastrado no arranjo PIX. 
De acordo com a descrição do código de erro CAI4, o CNPJ do Participante Indireto **33920559000199** não está cadastrado no arranjo do PIX.

**Comment by julianemelo1104** [comment]
> Prezada, a mensagem REDA.014 é utilizada para cadastrar um participante indireto no SPI.
> Porém, esse participante já deve estar previamente cadastrado no arranjo PIX.
> De acordo com a descrição do código de erro CAI4, o CNPJ do Participante Indireto **33920559000199** não está cadastrado no arranjo do PIX.


Fiz a tentativa de cadastro com outros CPFs que estão na lista de cadatsro, e continuo recebendo o mesmo erro (CAI4 | Cadastro Inexistente de participante indireto):
874 -- 03.428.338/0001-37 Em andamento INDIRETA
875 -- 03.128.973/0001-07 Em andamento INDIRETA

**Comment by rodalvarenga** [comment]
Prezada, favor encaminhar sua dúvida para a equipe de negócios responsável pela mensagem REDA.014 => spi@bcb.gov.br
