### ISSUE TITLE
[Problema] no [INFRA] - Http Status 429 - Too many Requests

### ISSUE THREAD

**Issue by rsabin** [bacen/pix-perguntas-e-respostas#95]
**Descreva sua dúvida ou problema**
Endpoint da api de pagamentos está retornando 429 - Too many requests.

**Sistema ou Área**
INFRA

**URL de conexão**
https://icom-h.pi.rsfn.net.br/api/v1/out/92702067/stream/start

**Dados adicionais**
Já faz quase 1h. A API está fora?
Tem previsão de existir um serviço / canal / etc onde os PSP poderão ver o status de cada API?

**Comment by rsabin** [comment]
Voltou a funcionar...

**Comment by adyjunior** [comment]
Primeiramente a API estava retornando o status 429 - Too many requests. Voltou a funcionar temporariamente, mas agora estamos tomando **Connection reset**.

A API está fora?
