### ISSUE TITLE
[Problema] no [DICT] - Erro ao cadastrar chave - mudança formato de data na RC4

### ISSUE THREAD

**Issue by monise** [bacen/pix-perguntas-e-respostas#96]
**Descreva sua dúvida ou problema**

Olá! Estamos tendo problema ao cadastrar uma chave. É retornado o seguinte erro:

`Caused by: java.time.format.DateTimeParseException: Text '2020-07-23T12:49:33.431Z' could not be parsed, unparsed text found at index 10  `

Foi divulgado que na RC5 será alterado o formato da data, conforme imagem do changlog:
![image](https://user-images.githubusercontent.com/5355541/88291641-effebd80-ccce-11ea-951e-d8eb48bc6b6d.png)

Porém, nos nossos testes estamos apontando para o ambiente RC4.

A alteração da RC5 já está sendo refletida na RC4?

O formato de retornar data-time será aplicado para todos os campos de data?

**Sistema ou Área**
DICT

**Identificador do Problema**

*Request*

POST dict-h.pi.rsfn.net.br/api/v1-rc4/entries/

`<CreateEntryRequest>
    <Entry>
        <Account>
            <AccountNumber>45969</AccountNumber>
            <AccountType>CACC</AccountType>
            <Branch>9914</Branch>
            <Participant>13370835</Participant>
        </Account>
        <Key>+5561991672768</Key>
        <KeyType>PHONE</KeyType>
        <Owner>
            <Name>Joao Alves Castro</Name>
            <TaxIdNumber>13668945969</TaxIdNumber>
            <Type>NATURAL_PERSON</Type>
        </Owner>
    </Entry>
    <Reason>USER_REQUESTED</Reason>
    <RequestId>c11b8ece-83cb-4f23-8636-965ba0cc2f75</RequestId>
</CreateEntryRequest>`

*Response*
`<CreateEntryResponse>
    <Entry>
        <Key>+5561991672768</Key>
        <KeyType>PHONE</KeyType>
        <Account>
            <Participant>13370835</Participant>
            <Branch>9914</Branch>
            <AccountNumber>45969</AccountNumber>
            <AccountType>CACC</AccountType>
        </Account>
        <Owner>
            <Type>NATURAL_PERSON</Type>
            <TaxIdNumber>13668945969</TaxIdNumber>
            <Name>Joao Alves Castro</Name>
        </Owner>
        <CreationDate>2020-07-23T12:49:33.431Z</CreationDate>
        <KeyOwnershipDate>2020-07-23T12:49:33.427Z</KeyOwnershipDate>
    </Entry>
</CreateEntryResponse>`

Campos retornados no novo formato:
`<CreationDate>2020-07-23T12:49:33.431Z</CreationDate>
<KeyOwnershipDate>2020-07-23T12:49:33.427Z</KeyOwnershipDate>`

**Comment by luizlaydner** [comment]
@monise v1.0.0-RC4 Não deveria estar com novo formato. Falha nossa. Vamos corrigir o mais rápido possível.

**Comment by monise** [comment]
@luizlaydner muito obrigada pelo retorno! Vocês tem a previsão de quando essa correção será liberada? Assim conseguimos nos planejar para dar continuidade em outros testes.

**Comment by HenriqueSimoes82** [comment]
@monise 
Problema corrigido. Agradeço o reporte.
