### ISSUE TITLE
[Dúvida] no [SPI] - Quantidade máxima de transações por mensagem

### ISSUE THREAD

**Issue by douglasrs89** [bacen/pix-perguntas-e-respostas#97]
**Descreva sua dúvida ou problema**
Gostaria de saber se vocês já tem algum número aproximado para a quantidade de transações máxima por mensagem.
Em uma **PACS008**, quantas transações eu posso ter dentro de uma?

Na documentação está muito vago, fala que tem que ser maior ou igual a 1, porém, precisamos de um número máximo aproximado, para podermos ter uma base.

`Campo obrigatório deve ser preenchido com o valor maior ou igual a "1"  (NbOfTxs >=1). A definição do número máximo de transações por mensagem será definido a posteriori.`

**Sistema ou Área**
SPI

**Comment by cristianokbc** [comment]
@douglasrs89, não implementamos a limitação, mas para pagamentos prioritários, começamos a trabalhar com a ideia de limitar em 10 operações.
