### ISSUE TITLE
[Dúvida] no [SPI] - Agendamento de Devolução

### ISSUE THREAD

**Issue by WagnerLau** [bacen/pix-perguntas-e-respostas#98]
**Pode ser ofertado o agendamento da Devolução?**
No fluxo de efetivação de pagamento, está claro que o PSP pode ofertar o agendamento da ordem de pagamento (pacs.008), onde ele deverá reter em seu sistema e enviá-las ao SPI somente na data indicada pelo usuário pagador.
Conforme "Documento de especificações - versão 6.2.pdf", item "1.1", página "12".

Esse mesmo fluxo pode ser adotado para a devolução (pacs.004)?
No item "1.4" do documento citado, não identifiquei citação sobre agendamento.

**Sistema ou Área**
SPI

**Comment by rafael-omello** [comment]
Dúvidas negociais devem ser encaminhadas para spi@bcb.gov.br.
